### ISSUE TITLE
why can't @foreign_key_type be deprecated and determined by @primary_key of foreign model?

### ISSUE THREAD

**Issue by troyk** [elixir-lang/ecto#1000]
I know nothing of elixir macro programming, but thought I'd ask.  Referencing the below schema, If I do not include the "type: :string" option on the belongs_to :product then the model dies a horrible death at query time trying to cast product_id to a Ecto.UUID.

```elixir
defmodule AH.SearchReq do
  use AH.Web, :model

  @primary_key {:id, Ecto.UUID, read_after_writes: true}
  @foreign_key_type Ecto.UUID

  schema "search_reqs" do
    belongs_to :product, AH.Product, type: :string
    timestamps inserted_at: :created_at
    field :completed_at, Ecto.DateTime
    field :turnaround, :integer
    field :status, :string
    field :score, :string
    field :cost, :decimal
    field :access_fee, :decimal
    field :price, :decimal
    field :request, :map
    field :result, :map
  end
end
```

I'm fairly sure the code below is the code I should be looking at from `schema.ex`  foreign_key_type is retrieved from mod, but would the @primary_key attribute be available on queryable?
```elixir
  @doc false
  def __belongs_to__(mod, name, queryable, opts) do
    check_options!(opts, [:foreign_key, :references, :define_field, :type], "belongs_to/3")

    opts = Keyword.put_new(opts, :foreign_key, :"#{name}_id")
    foreign_key_type = opts[:type] || Module.get_attribute(mod, :foreign_key_type)

    if Keyword.get(opts, :define_field, true) do
      __field__(mod, opts[:foreign_key], foreign_key_type, false, opts)
    end

    association(mod, :one, name, Ecto.Association.BelongsTo, [queryable: queryable] ++ opts)
  end
```

**Comment by josevalim** [comment]
Because otherwise we would be coupling things that should not be coupled. You may as well have a single table that uses UUID. Therefore, can you please expand on the actual error happening here:

>  If I do not include the "type: :string" option on the belongs_to :product then the model dies a horrible death at query time trying to cast product_id to a Ecto.UUID.

Also include Ecto and Elixir versions.

**Comment by troyk** [comment]
Hi @josevalim , thanks for your consideration

Elixir 1.1.1
Ecto 1.0.4

actual error:
```
** (exit) an exception was raised:
    ** (ArgumentError) cannot load `"CRCT"` as type Ecto.UUID
        (ecto) lib/ecto/schema.ex:968: Ecto.Schema.load!/3
        (ecto) lib/ecto/schema.ex:960: anonymous fn/3 in Ecto.Schema.do_load/4
        (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/schema.ex:958: Ecto.Schema.do_load/4
        (ecto) lib/ecto/schema.ex:943: Ecto.Schema.__load__/6
        (ecto) lib/ecto/adapters/sql.ex:503: anonymous fn/3 in Ecto.Adapters.SQL.process_row/3
        (elixir) lib/enum.ex:1102: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (ecto) lib/ecto/adapters/sql.ex:497: Ecto.Adapters.SQL.process_row/3
        (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
        (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1043: Enum.map/2
        (ecto) lib/ecto/adapters/sql.ex:267: Ecto.Adapters.SQL.decode/2
        (stdlib) timer.erl:166: :timer.tc/1
        (ecto) lib/ecto/adapters/sql.ex:262: Ecto.Adapters.SQL.decode/3
        (ecto) lib/ecto/adapters/sql.ex:209: Ecto.Adapters.SQL.query/5
        (ecto) lib/ecto/adapters/sql.ex:170: Ecto.Adapters.SQL.query!/5
        (ecto) lib/ecto/adapters/sql.ex:465: Ecto.Adapters.SQL.execute/6
        (ecto) lib/ecto/repo/queryable.ex:95: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
```

Here is AH.Product model:
```elixir
defmodule AH.Product do
  use AH.Web, :model
  @primary_key {:id, :string, autogenerate: false}

  schema "products" do
    field :description, :string
    field :report_order, :integer
    field :price, :decimal
  end

  @required_fields ~w(description, report_order, price)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    params = Dict.put(params, :display_name, "Troy")
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end
```

As you can see, the pkey on AH.Product is a string, while the pkey on AH.SearchReq is an Ecto.UUID.  Thus, when loading SearchReq's, `product_id` (whose value is "CRCT") is being cast to a Ecto.UUID.  But just because SearchReq uses a uuid as a pkey, it's not right to assume all foreign keys will also be uuid's.  So if possible, it seems the best case would be for the macro to consult the foreign model (in this case AH.Product) and consult it's pkey type because that is going to be the foreign key type on the AH.SearchReq model.  Does that make sense?  RDBMS do not require primary keys to be of a single type across the database, but they do require the fkey and pkey types to match.  

Just to be clear,  `belongs_to :product, AH.Product, type: :string` works but `belongs_to :product, AH.Product` errors trying to cast the foreign key value "CRCT" to a uuid.

Thanks,
Troy

**Comment by josevalim** [comment]
> As you can see, the pkey on AH.Product is a string, while the pkey on AH.SearchReq is an Ecto.UUID. Thus, when loading SearchReq's, product_id (whose value is "CRCT") is being cast to a Ecto.UUID. 

So you shouldn't set `@foreign_key_type` to `Ecto.UUID`. That's exactly what you are changing. So you have two options: you don't change `@foreign_key_type` or you pass the `:type` option. Am I missing something?

**Comment by troyk** [comment]
@josevalim not setting `@foreign_key_type` would require setting the `:type` options on all your foreign keys  --I just tried it and for some reason won't even load the pkeys correctly  error:
```
** (exit) an exception was raised:
    ** (ArgumentError) cannot load `<<4, 3, 10, 242, 16, 107, 70, 12, 159, 199, 106, 5, 110, 110, 180, 116>>` as type :id
        (ecto) lib/ecto/schema.ex:968: Ecto.Schema.load!/3
        (ecto) lib/ecto/schema.ex:960: anonymous fn/3 in Ecto.Schema.do_load/4
        (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/schema.ex:958: Ecto.Schema.do_load/4
        (ecto) lib/ecto/schema.ex:943: Ecto.Schema.__load__/6
        (ecto) lib/ecto/adapters/sql.ex:503: anonymous fn/3 in Ecto.Adapters.SQL.process_row/3
        (elixir) lib/enum.ex:1102: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (ecto) lib/ecto/adapters/sql.ex:497: Ecto.Adapters.SQL.process_row/3
        (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
        (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1043: Enum.map/2
        (ecto) lib/ecto/adapters/sql.ex:267: Ecto.Adapters.SQL.decode/2
        (stdlib) timer.erl:166: :timer.tc/1
        (ecto) lib/ecto/adapters/sql.ex:262: Ecto.Adapters.SQL.decode/3
        (ecto) lib/ecto/adapters/sql.ex:209: Ecto.Adapters.SQL.query/5
        (ecto) lib/ecto/adapters/sql.ex:170: Ecto.Adapters.SQL.query!/5
        (ecto) lib/ecto/adapters/sql.ex:465: Ecto.Adapters.SQL.execute/6
        (ecto) lib/ecto/repo/queryable.ex:95: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
        (ecto) lib/ecto/repo/queryable.ex:55: Ecto.Repo.Queryable.one!/4
```

If a model has a `belongs_to :product, AH.Product` then it should lookup the pkey type for `AH.Product` not itself because by RDMBS rule, the fkey has to match the type of the pkey of the other model... not the pkey of it's own model.

**Comment by josevalim** [comment]
@troyk If most of your primary keys are UUID, then you have everything correctly set up. You need to use UUIDs for everything and explicitly specify the type for the other cases. We cannot lookup the key in AH.Product because that would cause a circular dependency in the compiler, so you need to be explicit about it.

**Comment by troyk** [comment]
@josevalim got it, thanks for your time.  Hopefully I can repay your kindness and efforts with some elixir advocacy as it looks like we are going to get some big wins bringing an app over from rails-land.

**Comment by josevalim** [comment]
you are welcome @troyk . have a great weekend!
