### ISSUE TITLE
Provide Ecto.Repo.prepare/2

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1003]
It will be called with query + options, allowing developers to customize queries before they are sent to the repository. For example, one can use this for setting up a query prefix based on some configuration, before reaching the database.

@Dania02525 and @reset would this be useful in your experience with prefixes? /cc @Tica2

**Comment by reset** [comment]
@josevalim yes, this is something that I've implemented myself as a nice way to interact with setting prefixes

**Comment by Dania02525** [comment]
Anything we can do to make prefixing easier I'm all for.  The current incarnation works but is a bit clunky IMO. Are you thinking this would replace something like this:
```elixir
results = Model 
      |> Ecto.Queryable.to_query
      |> Map.put(:prefix, "foo")
      |> Repo.all
```
With something like this:
```elixir
results = Repo.prepare(Model, prefix: :foo) |> Repo.all
```
?

**Comment by josevalim** [comment]
@Dania02525 There are a couple ways we could leverage it.

1. The first one is by passing it as an option:

    ```elixir
    defmodule MyRepo do
      use Ecto.Repo

      def prepare(query, opts) do
        %{prefix: prefix} = query = Ecto.Queryable.to_query(query)
        %{query | prefix: prefix || opts[:prefix]}
      end
    end
    ```

    And use it as:

    ```elixir
    Repo.all query, prefix: "foo"
    ```

2. We could automatically load it behind the scenes:


    ```elixir
    defmodule MyRepo do
      use Ecto.Repo

      def prepare(query, opts) do
        %{prefix: prefix} = query = Ecto.Queryable.to_query(query)
        %{query | prefix: prefix || Apartmentex.prefix_or_raise!}
      end
    end
    ```

    And use it as:

    ```elixir
    Repo.all query
    ```

If we think `1.` is enough then we don't even need `prepare/2`. We can support the option directly in Ecto.

**Comment by Dania02525** [comment]
I kinda prefer the first one as its a little more explicit, even if a little repetitive in some use cases.  What do you think @reset @Tica2 ?

**Comment by Tica2** [comment]
If in Model we have prefix: then we need a way to change.

If we replace "tentant" prefix with "tentant_999" this is valabil for all models that use "tentant" prefix.
This mean I need a way to say on global to do that. In repo module or conf:
```elixir
tentant: &Multitenancy.current/0
``` 
Second problem to solve is a way to add dinamic repo (add dinamic database).
If new client create account+domain, app create new database and client is ready to 
use the app, no need to define new Repo.

Look like a pool of repos.
Thinking ...

Easy here,  I will come back with code examples ...

**Comment by josevalim** [comment]
@Tica2 `prepare/2` would allow you to use something global. I don't want to have something global with Ecto out of the box because it is somehow a bad practice. But I want developers that know what they are doing to be able to achieve it. The question is: is global really necessary?

**Comment by Tica2** [comment]
@josevalim In your next example what is `opts` ? 

we have a lot of functions: Repo.all/2 Repo.one/2 ...

I think, with example with process state we don't need opts. 

```elixir
# Based on domain/prefix/user find tenant
Multitenancy.set_current(tenant)

defmodule MyRepo do
  use Ecto.Repo

  def prepare(query, opts) do
    query 
     |> Ecto.Queryable.to_query
     |> build_prefix(Multitenancy.get_current)
  end
end
```

@josevalim for me **PERFECT**

**Comment by josevalim** [comment]
The options is for other things people may want to extend the query with. :)

**Comment by Tica2** [comment]
I can start working on it ?

**Comment by josevalim** [comment]
Yes, please!
