### ISSUE TITLE
Support prefixes in migrations

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1004]
For @elixir-lang/ecto-adapters 

* [x] MySQL
* [x] PostgreSQL
* [x] SQLite3
* [x] MSSQL
* [x] MongoDB

See #998.

**Comment by josevalim** [comment]
I removed support for prefix in references and cleaned up the tests here: 73e1d691a25f5bd81ef894a5c7ec21ed1ea3f9da

**Comment by michalmuskala** [comment]
MongoDB adapter does not support prefixes for the time being, so I think this can be ticked as done.

**Comment by jazzyb** [comment]
I apologize for it taking me so long to get around to this.

SQLite:  https://github.com/jazzyb/sqlite_ecto/commit/20d7da37c6ab65bc20a8f42589f1ef60a95a6ecf

**Comment by josevalim** [comment]
No problem, there is still quite some time for a new Ecto release anyway. :)

**Comment by mobileoverlord** [comment]
MSSQL: livehelpnow/tds_ecto@59956cdf48dca3337d4dd2fc7f9f03f91a908a88
