### ISSUE TITLE
Support prefixes in migration runner

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1005]
See #978.

**Comment by josevalim** [comment]
Here is what I have in mind for this:

1. A prefix option can now be given to the migrator

2. The prefix will be stored in the agent and be accessible in migrations via the `prefix()` function (defaults to nil). The schema migrations will be bound to the prefix

3. If someone sets `create table("foo", prefix: "bar")` and we have defined a `prefix` in the migrator, we should error unless the prefixes are the same. People can fix this by wrapping those chunks in a `unless prefix do` check

4. Support `--prefix` option in the mix tasks

@Dania02525 @Tica2 what do you think?

**Comment by Dania02525** [comment]
@josevalim 
I like it, but I was thinking about this yesterday, specifically with regards to making a mix task later to migrate a whole set of tenants at once.  

My previous implementation puts the prefix in the runner agent, and this will cause a problem if more than one migration happens at the same time (To do lots of them, I'd probably want to max out the connection pool and do 10 at a time concurrently).  I think this would cause a problem since there is only one runner agent, and I suspect it would be the same problem with a prefix agent.  

If we could pass the name of a unique agent into the migration module as we were parsing it, we could use that agent to run migrations (and get the right prefix) when running concurrently. Am my off track with this?

**Comment by josevalim** [comment]
@Dania02525 You are right. The current migrations were designed to not run concurrently, because we use a globally named agent, but that should be fixable. I can think of two options:

1. Inject the name or the pid of the agent in the module as we parse it. I don't enjoy this a lot because it would force all of the migration code to be defined inside the migration module.

2. We define an Ecto.MigrationManager that would spawn a process and associated the migrator process pid to the agent pid. The manager would be responsible for shutting things off. This approach is easier to manage.

**Comment by Dania02525** [comment]
@josevalim 
So you are thinking like a genserver for the migration manager that receives migration requests, then spawns migrator and runner as it gets migration requests? In the current migrations module, how would we be able to get the pid or agent name of the spawned runner? I think its hardcoded now directly to the runner agent.

**Comment by josevalim** [comment]
The migratory calls the manager giving its own pid. The manager spawns the
agent and every time the migrator needs the agent it asks the manager for
the migrator pid. Does it make sense?



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Dania02525** [comment]
I'll play around with this to see what I can come up with :-)

**Comment by Tica2** [comment]
@josevalim Is not clear to me. I came with clear cases:

##  Case 1 - current usage, all prefixes nil
`mix ecto.migrate` will create all objects with public/default prefix (schema_migrations included)
`mix ecto.migrate --prefix foo` will create all objects with foo prefix (schema_migrations included)

##  Case 2 - simple app that use default + 1 second prefix. 

```elixir
create table(:tbl1)
create table(:tbl2)
create table(:tbl_a, prefix: :web)
create table(:tbl_b, prefix: :web)
```

We have 2 prefixes [nil, :web]

```bash
mix ecto.migrate
```
Expect to create:

public.schema_migrations
public.tbl1
public.tbl2
web.tbl_a
web.tbl_b

What mean now?

```bash
mix ecto.migrate --prefix foo
```

???
If we have one prefix [nil] or [pub] problem is simple see **CASE 1**

If we have 2: [nil, :web] we can do:
```bash
mix ecto.migrate --prefix foo --prefix web:bar
```
Rezult is:
foo.schema_migrations
foo.tbl1
foo.tbl2
bar.tbl_a
bar.tbl_b

If we have 3: [nil, :web, :crm] we can do:
```bash
mix ecto.migrate --prefix foo --prefix web:bar --prefix crm:xxx
```

`--prefix foo` Affect nil schema and where is created schema_migrations
`--prefix web:bar` Affect objects defined with :web prefix and will be created with :bar prefix

 These are my cases.

**Comment by Tica2** [comment]
Better:
If we do not have `--prefix` we know what to do with `mix ecto.migrate` in all cases
with [nil] [nil, :web] [:web, :crm] ....

if we add --prefix then **best** is to specify full map for all defined prefixes:

`mix ecto.migrate --prefix for_nil --prefix web:web --prefix crm:crmXXX`

**Comment by josevalim** [comment]
No, there is no need for a mapping. if you have  `--prefix foo` and `table(:bar, prefix: "baz")`, we are going to error. You can fix this by doing one of:

```elixir
# Use the command line prefix if there is one
table(:bar, prefix: prefix() || "baz")
```

Or:

```elixir
unless prefix() do
  create table(:bar, prefix: "baz")
end
```

This way you can programatically solve the conflict.

**Comment by Tica2** [comment]
@josevalim Now it's more clear what you said.
Ok, look good.

That mean:
- All objects will have same prefix `prefix()`
- Also `table(:bar)` will have same prefix `prefix()` 
- We can't have in same folder 2 objects with two explicit prefixes.
- prefix() will return atom (To transform 1 string in atom per generation is fine)
- schema_migrations is created with prefix `prefix()` 
- Finaly we don't have any difference between
 
`table(:bar, prefix: prefix())`
and
`table(:bar)`

for me is fine, 
in one folder we can have all objects with static prefixes and nil
in new folder we can have all objects related to tenant with prefix nil, prefix will be provided on migration: `mix ecto.migrate --prefix tenant_099`

Is more restrictive and clear.
a) Who use static prefixes (2, 3,..) is fine to put explicit
b) Who need tenants use new Repo+directory not explicit prefix (default nil) and is up to user to provide on migration script: 

`mix ecto.migrate --prefix tenant_091`
`mix ecto.migrate --prefix tenant_092`
`mix ecto.migrate --prefix tenant_093`

**Comment by josevalim** [comment]
> prefix() will return atom (To transform 1 string in atom per generation is fine)

I am torn about making it an atom. Because while atoms are ok in migrations, atoms are not fine for models and queries. I think we should push everyone to use string prefixes.

**Comment by Dania02525** [comment]
@josevalim 
Ok, I've created a Manager module which starts an agent named Ecto.Migration.Manager.  In Ecto.Migration.Runner.run, I start the runner agent without a name, and send its PID along with the PID of the current process and the prefix option to the manager, so migrations in the manager agent look like this: {migrator_pid, runner_agent_pid, prefix}.  

Within Ecto.Migration.Runner, I can call functions like Manager.get_runner(self()) and Manager.get_prefix(self()) to get the prefix string or the runner agent for this migration.  However, I'm unable to call these in connection.ex to retrieve the prefix string, getting a no process error.  It looks like for some reason I can ony use the Migration agent inside the function I called it in am I calling it incorrectly maybe?

BTW, I expected to be able to call it in connection, as self() there returns the same pid as self() in the runner. Aside from this problem, I can run concurrent migrations with the manager.

**Comment by josevalim** [comment]
@Dania02525 From your description, it seems everything should be working fine. if you send a PR, I will gladly take a look!

**Comment by Dania02525** [comment]
@josevalim 
Its was actually a noob mistake, the schema migrations were trying to run before the manager agent was started :-0.  Its actually fully functional now, and you are right that its a much cleaner way to do it.  It makes all the ecto tests fail however, so that will need some work.  I have implemented it in my apartmentex library here: https://github.com/Dania02525/apartmentex

I will work on the bugs making 137 tests fail in ecto, then do a commit.  Here's how I'm test running it 
```elixir
["priv/repo/migrations", "priv/repo/tenant_migrations"]
|> Enum.map(fn(dir) -> Task.async(fn->
    case dir do
      "priv/repo/migrations" -> Apartmentex.Migrator.run(Test.Repo, dir, :up,  [all: true])
      "priv/repo/tenant_migrations" -> Apartmentex.Migrator.run(Test.Repo, dir, :up,  [all: true, prefix: :tenant_1])
    end
  end) 
end)
|> Enum.map(&Task.await/1)
```

and here's the implementation of the migration manager:

```elixir
def start_link do
    Agent.start_link(fn -> HashDict.new end, name: __MODULE__)
  end

  def put_migration(migrator, prefix) do
    Agent.update(__MODULE__,fn migrations -> Dict.put_new(migrations, migrator, {nil, prefix}) end)
  end

  def put_runner(migrator, runner) do
    Agent.update(__MODULE__,fn migrations -> 
      Dict.update!(migrations, migrator, fn({nil, prefix}) -> {runner, prefix} end)
    end)
  end

  def get_runner(migrator) do
    {runner, _prefix} = Agent.get(__MODULE__, fn migrations -> Dict.fetch!(migrations, migrator) end)
    runner
  end

  def get_prefix(migrator) do
    {_runner, prefix} = Agent.get(__MODULE__, fn migrations -> Dict.fetch!(migrations, migrator) end)
    prefix
  end

  def stop() do
    Agent.stop(__MODULE__)
  end 
```
I start the manager (ensure it is started) in the migrator passing it the current pid and the prefix opt) Instead of calling Ecto.Migration.Runner within the runner module, I get the runner pid from the manager using the current pid.  In connection, I get the prefix from the manager also using the current pid.  If the table, index, or reference prefix is set and is different than the option prefix, I raise. 

right now, there is no call to stop the manager, however I think we can drop migrations from the Hashdict when they finish, and when we end up with an empty Hashdict in the manager agent, we can stop it.

**Comment by josevalim** [comment]
Great to hear @Dania02525! If you need any help with figuring out the tests, please let me know.

**Comment by Dania02525** [comment]
@josevalim 

I've got this working, but had to change the adapter, migrator, and migration tests to async: false, since each operation was running concurrently in the same process causing the manager's references to get messed up.  Since each process in normal use will call migrator separately instead of directly calling execute_ddl or importing migrator, I think this is just a test artifact.  

I wrote a couple of tests for this, testing both the raise on non-matching prefixes and concurrent migrations.  It could probably use more if anyone thinks of more ways to test this.  

I did run into an issue with calling Manager.remove_migration(self()) at the end of the migrator.up, down, and run functions.  My function returns :ok, which messes up the expected return for the tests- open to suggestions on how to prevent this happening.  It is commented out in the commit, but once we get this working, it should kill the manager agent when the last migration is removed.  

diff here: https://github.com/elixir-lang/ecto/compare/master...Dania02525:master

**Comment by josevalim** [comment]
That looks great @Dania02525!

Concurrency should definitely work, so we are missing something. In particular, we should not call the Manager from MySQL and Postgrex connection. Instead, the prefix should be stored in the runner and we would call it here:

https://github.com/elixir-lang/ecto/blob/master/lib/ecto/migration.ex#L364

Notice this may break postgres_test and mysql_test though, because they don't have a runner, but you can change them to use `%Table{name: :foo}` instead of `table(:foo)`. This should also help clean up the code because you won't need to repeat the get_prefix code in three different places (runner, postgres and mysql).

If you don't like changing the `table` function directly, you can change `create`, `drop`, `alter` and `rename`  every time they receive a table (this may actually be better).

Thoughts?

**Comment by Dania02525** [comment]
@josevalim 
I think its definitely a good idea to consolidate how the prefix is applied, by putting it into the existing structs.  

If we get the prefix from the manager when not set in table(:foo), and set the prefix in manager when table(:foo, prefix: :bar), and raise when they don't match, we could actually set the prefix on reference() and index() to the same prefix as the table if they aren't set (since if they are blank, it would pull prefix from manager)- I think thats the behavior @Tica2 wanted.  

I still don't like how schema migrations ends up in the public schema with this method though, since runner is called after that.  This was my primary motivation for putting the get_prefix call in the connection, but either method won't make a difference for prefixes set in the migration module since we don't know the prefix until its parsed and already in the runner.    To remove the call from the connections, I could just call get_prefix in the schema_migrations module to apply to the create table command, but it will only return a prefix given as an option in the run, and not one given in the migration module.  Any ideas on how to fix this?

**Comment by josevalim** [comment]
@Dania02525 we can pass the prefix as option to `migrated_versions` and pass it explicitly to the underlying `Ecto.Migration.SchemaMigration` functions. No need to rely on the agents in this case.

@Tica2 what is the issue with the references? If I do "create table PREFIX.FOO ... references BAR" in postgres, shouldn't bar automatically belong to that prefix?

**Comment by josevalim** [comment]
I have removed support for prefix on references on this commit: 73e1d691a25f5bd81ef894a5c7ec21ed1ea3f9da

@Dania02525 I also realized that check we do for tables should also be done for indexes. :) So we should really just change `create`, `drop`, `rename`, `alter` to check if the prefixes match instead of modifying `table` and `index`.

**Comment by Tica2** [comment]
> @Tica2 what is the issue with the references? If I do "create table PREFIX.FOO ... references BAR" in postgres, shouldn't bar automatically belong to that prefix?

For Postgresql is working in schema.
For MySql is working perfect see example [1].
If is removed then we make logic restriction that make sens. 

I think the best is to have also prefix for Reference. 
First version from @Dania02525. Is up to @josevalim to decide. 
**AND Adapter** to decide what to do. If is not supported Adapter can show warning message and ignore. Is exact what do databases until implemented. (See sqlite) 

In one DB instance I can have:

share.<public tables here> like countries, cities
share.countries
share.cities

```sql
tenant_001.company  field county_id **reference** share.countries 
```

```sql
tenant_091.company  field county_id **reference** share.countries 
```

With @Dania02525 version I can do that:

ShareRepo (all objects has share prefix)
TenantRepo (all objects do not have prefix, will be provided by --prefix on migration)

mix ecto.migrate --prefix tenant_001
mix ecto.migrate --prefix tenant_091
  

Table, Index are stored objects, 
Reference is like Logical object and belongs to table.
 
### MySql example, cross reference is woring   

```sql
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| a_db               |
| b_db               |
| ecto_test          |
| mysql              |
| performance_schema |
| tenant_001         |
| test               |
+--------------------+
8 rows in set (0.00 sec)

mysql> create table a_db.parent (id INT NOT NULL, PRIMARY KEY (id)) ENGINE=INNODB;
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE b_db.child (id INT, parent_id INT, INDEX par_ind (parent_id), FOREIGN KEY (parent_id)  REFERENCES a_db.parent (id)) ENGINE=INNODB;
Query OK, 0 rows affected (0.01 sec)

mysql> insert into a_db.parent values (1);
Query OK, 1 row affected (0.00 sec)

mysql> insert into a_db.parent values (1);
ERROR 1062 (23000): Duplicate entry '1' for key 'PRIMARY'
mysql> insert into a_db.parent values (2);
Query OK, 1 row affected (0.00 sec)

mysql> select * from a_db.parent;
+----+
| id |
+----+
|  1 |
|  2 |
+----+
2 rows in set (0.00 sec)

mysql> insert into b_db.child values (1, 1);
Query OK, 1 row affected (0.00 sec)

mysql> insert into b_db.child values (1, 10);
ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`b_db`.`child`, CONSTRAINT `child_ibfk_1` FOREIGN KEY (`parent_id`) REFERENCES `a_db`.`parent` (`id`))
mysql>

petrica@mac ~ >

```

**Comment by Tica2** [comment]
> I still don't like how schema migrations ends up in the public schema 
Is require schema_migrations to be with prefix provided by Mix task:
```elixir
mix ecto.migrate --prefix tenant_091
```

**Comment by josevalim** [comment]
> I still don't like how schema migrations ends up in the public schema  Is require schema_migrations to be with prefix provided by Mix task

Yes, we don't like it either. This is what we are trying to solve next. :D

**Comment by Tica2** [comment]
%References with or without prefix ?

**Comment by josevalim** [comment]
References no longer support prefix because we cannot make it work across databases. They always always point to something in the same prefix by default.

**Comment by Tica2** [comment]
This is fine. Just remind is working fine for MySQL and Postgresql.

**Comment by Dania02525** [comment]
@josevalim 
I'm sorry, I just read your very first comment on the issue where you described exactly what you wanted this to look like.  I'll read more carefully next time :-).  So, just to be clear, you want schema migrations to look something like this:
```elixir
def ensure_schema_migrations_table!(repo, opts) do
    adapter = repo.__adapter__
    create_migrations_table(adapter, repo, opts)
  end

  def migrated_versions(repo, opts) do
    repo.all from(p in __MODULE__, select: p.version) |> Map.put(:prefix, Keyword.get(opts, :prefix, nil)), @opts
  end

  def up(repo, version) do
    repo.insert! %__MODULE__{version: version} |> put_meta(prefix: Keyword.get(opts, :prefix, nil)), @opts
  end

  def down(repo, version) do
    repo.delete_all from(p in __MODULE__, where: p.version == ^version) |> Map.put(:prefix, Keyword.get(opts, :prefix, nil)), @opts
  end

  defp create_migrations_table(adapter, repo, opts) do
    # DDL queries do not log, so we do not need
    # to pass log: false here.
    adapter.execute_ddl(repo,
      {:create_if_not_exists, %Ecto.Migration.Table{name: :schema_migrations, prefix:  Keyword.get(opts, :prefix, nil)}, [
        {:add, :version, :bigint, primary_key: true},
        {:add, :inserted_at, :datetime, []}]}, @opts)
  end
```
with something like this for each command in migrations.ex:
```elixir
def create(%Index{} = index) do
    Runner.execute {:create, %{index | prefix: prefix(index.prefix)}}
  end

  def create(%Table{} = table) do
    do_create %{table | prefix: prefix(table.prefix)}, :create
    %{table | prefix: prefix(table.prefix)}
  end

def prefix(opts_prefix) do
  case {Manager.get_prefix(self), Manager.get_prefix(self) == opts_prefix} do
    {nil, _) -> opts_prefix
    {prefix, true} -> prefix
    {_, false} -> raise Ecto.MigrationError, 
      message: "prefixes given as migration options must match global migrator prefix"
  end
end
```

Then,  only alias and use the manager in runner.ex and migrations.ex.  If this all looks acceptable, I'll work on it.

**Comment by josevalim** [comment]
@Dania02525 For the first snippet, I am not sure we need options, I think we can just pass the prefix directly. For the second one, it looks good.

Also, it is not about what I want, I am just proposing solutions. :) If we all agree it is the best way to go, then let's go with it :D

Thank you for all the work!

**Comment by Dania02525** [comment]
@josevsalim
Allright, I will work on this.  Your suggestions seem to always work out to be the right and clean way to do it :-).  

This might be a larger discussion, but I actually think it would be interesting to hold *all* prefixes in an agent, sort of a prefix manager which would be called for both queries and migrations, then apply them at the connector level.  This would make it possible to do something like, set the prefix in a controller plug, then have all repo queries and in-controller migrations directed to that prefix without having any of the put_prefix() stuff for each query.  Sort of a unified way to apply prefixes for all things happening in a given process.  The agent would be supervised and start with repo.  I'm not sure its something right for the main ecto library, but it might make an interesting branch for those building SaaS apps.

**Comment by josevalim** [comment]
> This might be a larger discussion, but I actually think it would be interesting to hold all prefixes in an agent, sort of a prefix manager which would be called for both queries and migrations, then apply them at the connector level. 

I agree.  But as you said, I don't want to do that in Ecto itself. :)

If you remember, there was another issue were I proposed `Repo.prepare/2`. With `Repo.prepare/2` you would be able to implement this by reading from the agent before sending to the Repo and changing the query. This way, the adapters do not need to worry about this stuff and you can still cleanly implement it. So maybe we should build something like `Repo.prepare/2`. :)

**Comment by Dania02525** [comment]
True, if we had Repo.prepare/2 working it would be pretty easy to get the prefix from an agent, I'm just thinking of those moving over from those poor languages lacking things like agents having to implement this on their own ;-)

**Comment by josevalim** [comment]
Great! I really want Ecto to have all the building blocks to make your life easier with apartmentex. Also, I don't even think you need an agent, you can store this particular stuff in the process dictionary. You could retrieve the prefix with something like this:

```elixir
defmodule MyApp.Repo do
  use Ecto.Repo, otp_app: :my_app
  use Apartmentex.Repo
end
```

And Apartmentex.Repo would generate functions like this:

```elixir
def put_prefix(prefix) do
  Process.put({:apartment, repo}, prefix)
end

def get_prefix do
  Process.get({:apartment, repo})
end

@default_prefix @config[:default_prefix]

def prepare(query, opts) do
  query = Ecto.Queryable.to_query(query)
  %{query | prefix: query.prefix || get_prefix() || @default_prefix || raise "no prefix was set. do this or that to fix it"}
end
```

**Comment by Tica2** [comment]
Look clean!
 
Who call def prepare(query, opts)?
If is call automatically by Repo before process %Query to SQL is perfect.

**Comment by josevalim** [comment]
> If is call automatically by Repo before process %Query to SQL is perfect.

Yes, exactly. Check #1003. :)

The only issue is that it won't prepare models but I am thinking model callbacks would be enough for inserts.

**Comment by Tica2** [comment]
What about to call 
`def prepare(changeset, opts) do:`

or similar

Idea is:

the only difference between 1 client (static prefix) and more clients (SaaS) is new prefixes.
I mean one map; {nil => "cli_099", "work" => "work_099"}
I just need to set on prepare/2 and all to work by magic.

**Comment by Dania02525** [comment]
@josevalim 
Appreciate the changes you made to connection to allow for easier testing with the migration manager.  The PR has it fully tested, including raising on non matching prefixes, allowing both prefixes to be set if they are the same, and shutting down the manager when it runs out of ongoing migrations.  

Thank you for your guidance!

**Comment by Dania02525** [comment]
@josevalim 
I think this issue is resolved as of my last commit to the PR.  The agent is now supervised, tested and just holds the k-v reference from caller process to runner process, with the prefix stored in agent process.  https://github.com/elixir-lang/ecto/pull/1047

**Comment by josevalim** [comment]
Perfect! I am on holidays now so I am a bit slower on the reviews, I will try to get to this soon though. :)

**Comment by Dania02525** [comment]
Oops! Sorry, I just wanted to make sure I wasn't supposed to be doing anything :-) enjoy!

-----Original Message-----

**Comment by josevalim** [comment]
Good news! I am back to work on Ecto and I will tackle this soon. When the time comes, I will just go ahead and merge this since I have already made you wait long enough. :) Thank you so much!

**Comment by bokay** [comment]
Hi everyone,

It was discussed [above in](https://github.com/elixir-lang/ecto/issues/1005#issuecomment-146946973) this thread to have the possibility to use ` unless prefix do` to handle errors when running the migrations while having the `--prefix tenant_x`. 
However, this function is only available in the  runner and I can't write this for instance : 

```
def change do
  unless prefix do
    create_table(:tenants, prefix: :public) do
      add :identifier, :string
    end
  end
end
```
The following returns : `undefined function prefix/0`
Is there a way to get the prefix within the migrations ? Or is there another way to deal with non prefixed tables so they don't get created on tenants?

Tested with `2.0.0-rc.5` along postgresql

**Comment by josevalim** [comment]
Could you please send a PR that adds a `prefix()` function to Ecto.Migration that simply delegates to the runner one? Thank you!
