### ISSUE TITLE
Support prefixes in schema definition

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1006]
See #978.

**Comment by Tica2** [comment]
Possible examples:
```elixir
schema "table", prefix: "nondefaultschema" do
```
or
```elixir
schema {"nondefaultschema", "table"}  do
```

This solve static reference for non default schema. This is perfect fine when one app works with 2-3 static prefixes.

Some more about SAAS/Multitenancy.

But in SAAS/Multitenancy when same app will handle more clients with different data, then we need a way to say "tenant" prefix is dinamic. Is calculated on each request based on  SAAS/Multitenancy strategy: domain, url prefix, username, ...

```elixir
defmodule User do
  use Ecto.Schema

  schema "users", tenant_prefix: &Multitenancy.current  do
    field :name, :string
    field :age, :integer, default: 0
    has_many :posts, Post
  end
end
```
or `prefix:` to support "string" or function/0

Here I expose main idea.

I prefer to say on global level, in config what prefix is dinamic.
```elixir 
schema "users", prefix: "tenant" do
```

```elixir
config :my_app, Sample.Repo,
  adapter: Ecto.Adapters.Postgres,
  multitenancy: ["tentant": Multitenancy.current]
```

Here we need more check how we do connection new databases dinamicaly.

**Comment by josevalim** [comment]
Right now let's start with prefix: "string" only. Baby steps. We can make
it dynamic if necessary in the future, otherwise it is very easy to over
architect the wrong solution. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Tica2** [comment]
:+1: 
```schema "table", prefix: "nondefaultschema" do```

**Comment by hubertlepicki** [comment]
@josevalim what's the reasoning behind this prefix thingy? I think you can simply do:

    schema "myprefix_users" do
    ...
    end

and have the same result... I had a look at the code, it would be quite easy to add this prefix functionality but I am uncertain how it is any better than specifying custom table name.

**Comment by Tica2** [comment]
Is not about "prefix" in same database/schema.
On SQL level look like:
user1.products
user2.products
user3.products

**Comment by Tica2** [comment]
@josevalim I did more changes and tests to support new format:
```elixir
schema "table", prefix: "nondefaultschema" do
```
I change https://github.com/elixir-lang/ecto/blob/master/lib/ecto/schema.ex#L310

```elixir
defmacro schema(source, [do: block]) do
```

to schema/2 and schema/3

```elixir
  @doc """
  Defines a schema with a source name and field definitions.
  """
  defmacro schema(source, [do: block]) do
    quote do
      Ecto.Schema.schema unquote(source), [], unquote([do: block])
    end
  end
  @doc """
  Defines a schema with a source name, optional `prefix: "my_prefix"` and field definitions.
  """
  defmacro schema(source, schema_opts, [do: block]) do
    prefix = Keyword.get(schema_opts, :prefix)
```

One problem here was to avoid broke some possible existing imports. 
If you know better way, please help.

__using__ import schema/2, schema/3

```elixir
 @doc false
  defmacro __using__(_) do
    quote do
      import Ecto.Schema, only: [schema: 2, schema: 3, embedded_schema: 1]
```

On runtime prefix: can be query with:
model.__schema__(:prefix)

Now I working to alter Query to use this prefix.

Not sure but, but look prefix is set on all query is not related to table.
I work here to have more details.

**Comment by Tica2** [comment]
PR in next days

**Comment by josevalim** [comment]
It looks perfect. Just remember to also store the prefix when we build `Ecto.Schema.Metadata`.

**Comment by Tica2** [comment]
This is solved ...

Problem is here:
a.table1
b.table2

and one query join
a.table1 join b.table2

In this case 
If I alter prefix on this query we have confusion.

I think this will working only if all tables from query do not have static prefixes.

Come back with PR

**Comment by Tica2** [comment]
@josevalim Please check https://github.com/Tica2/ecto/commit/ef4fe26cb9432e1069e863a08affc66df9a486c7

`__meta__` is correct now.

Now we need to decide when we can alter prefix:
Here https://github.com/Tica2/ecto/commit/ef4fe26cb9432e1069e863a08affc66df9a486c7#diff-08587a116d45885d97f1e77faf88f539R125
`Map.to_list q` return

```elixir
[__struct__: Ecto.Query, assocs: [], distinct: nil,
 from: {"model_with_prefix", Ecto.SchemaTest.PrefixModel}, group_bys: [],
 havings: [], joins: [], limit: nil, lock: nil, offset: nil, order_bys: [],
 prefix: nil, preloads: [], select: nil, sources: nil, updates: [], wheres: []]
```

One join example is here:
https://github.com/elixir-lang/ecto/blob/master/test/ecto/adapters/mysql_test.exs#L369-L373
`Map.to_list query` return
 
```elixir
__struct__: Ecto.Query, assocs: [], distinct: nil,
 from: {"model", Ecto.Adapters.MySQLTest.Model}, group_bys: [], havings: [],
 joins: [%Ecto.Query.JoinExpr{assoc: nil,
   file: "/Users/petrica/github/Tica2/ecto/test/ecto/adapters/mysql_test.exs",
   ix: 1, line: 370,
   on: %Ecto.Query.QueryExpr{expr: {:==, [],
     [{{:., [], [{:&, [], [0]}, :x]}, [ecto_type: :integer], []},
      {{:., [], [{:&, [], [1]}, :z]}, [ecto_type: :id], []}]},
    file: "/Users/petrica/github/Tica2/ecto/test/ecto/adapters/mysql_test.exs",
    line: 370, params: nil}, params: nil, qual: :inner,
   source: {"model2", Ecto.Adapters.MySQLTest.Model2}}], limit: nil, lock: nil,
 offset: nil, order_bys: [], prefix: nil, preloads: [],
 select: %Ecto.Query.SelectExpr{expr: 0, fields: [0],
  file: "/Users/petrica/github/Tica2/ecto/test/ecto/adapters/mysql_test.exs",
  line: 370, params: nil},
 sources: {{"model", Ecto.Adapters.MySQLTest.Model},
  {"model2", Ecto.Adapters.MySQLTest.Model2}}, updates: [], wheres: []]
```

Current prefix is on query level.
That mean if one source has prefix we use that prefix.

If global prefix (on query) is used then all prefix sources need to be nil.
If source prefix is not the same with query prefix we rise error.

I am right ?

**Comment by josevalim** [comment]
> If global prefix (on query) is used then all prefix sources need to be nil. If source prefix is not the same with query prefix we rise error.

Ah, this is tricky. :( It may be easier to say that only the prefix from "from" is respected. Prefix for associations are ignored.

**Comment by Tica2** [comment]
Static prefixes and query prefix is solved in this way:
https://github.com/Tica2/ecto/commit/7c94a87f45a9ec83f40f111d60e32fac4ee8d4db

If is fine, I will add CRUD tests with all operations, 
I can prepare final PR.

**Comment by josevalim** [comment]
This is a step in the good direction but we want the validation to happen in `Ecto.Query.Planner`. We should also make it as cheap and fast as possible. Finally, what do you think about simply ignoring the schema prefix in queries? Let's always ask for a explicit prefix there... the schema one should only affect new models... maybe we should even call it ":build_prefix", to be clear it only affects the model when we build it. I believe this would solve all of those problems and be much simpler.

**Comment by josevalim** [comment]
If that is not an option, then I don't think we should fix this, because it would mean queries basically do not compose.

**Comment by josevalim** [comment]
Ok, after some thought, I decided we shouldn't really do this because it does not compose. I believe we should explicitly set the prefix for both queries and models and maybe provide hooks to make this easier. For queries, it would be `Repo.prepare/2`. For models, we can in the worst scenario use callbacks. 

Thank you @Tica2 for leading the work on this! Unfortunately we won't merge any code but your work was the one who pointed that we should not do this, and Ecto will be better for it. :heart:

**Comment by Tica2** [comment]
`:build_prefix` is good ideea!

We have `query.prefix` that change `prefix` for all tables in query.
We can't query and work with more prefixes on same time/query.   

This is what, I think, you don't like 

```elixir
  test "alter prefix new value" do
    query = PrefixModel |> select([r], r.x) |> normalize
    query = %{query | prefix: "prefix1"}

    assert_raise ArgumentError, "Model Ecto.Adapters.MySQLTest.PrefixModel " <>
      ~s{has static prefix: "prefix" that can't be altered by global query prefix: "prefix1"}, fn ->
      SQL.all(query)
    end
  end
```
We can fix with your ideea:

1) To have static prefixes on model is good. A lot of legacy apps work with more static prefixes by default. 
2) Compose queries help:
  * To have dynamic prefixes (what we have now for {nil, "table"})
  * To replace possible static prefix with new-one dynamically
       
What about function in query:

def build_prefix(%Query{}, static_prefix, dinamic_prefix)
   # update build_prefix: key in query %{static_prefix, dinamic_prefix} 
   # if static_prefix is nil is updated prefix: key
end

If I have 3 categories of models:
main: do not define prefix (is nil)
hr: Human resources
inv: Inventory

```elixir
query
  |> build_prefix(nil, "tenant_main_008")
  |> build_prefix("hr", "tenant_hr_008")
  |> build_prefix("inv", "tenant_inv_008")
  |> select(...)
  |> Repo.all 
```

**Comment by Tica2** [comment]
A, ... to have a call build_prefix/2 in Repo.prepare/2
build_prefix(%Query{}, map)

All tenant setting is in one map:
```elixir
%{nil => "tenant_main_008", "hr" => "tenant_hr_008", "inv" => "tenant_inv_008"}
```
Now to see how to mix all together.

**Comment by green-arrow** [comment]
This will be a welcome addition to the library and I really appreciate the thought / work going into it. Especially for PostgreSQL, the use of different static schemas is very common. 

For example, in out database we have a `config` schema that houses a large amount of "reference" data that is used throughout the `public` schema. Currently we have no way to join `public` tables to the reference data tables located in the `config` schema. It seems that these changes will resolve that issue for us.

To echo what I think @josevalim said earlier, I think providing support for static prefixes is a very important first step.

**Comment by Tica2** [comment]
@josevalim How we can continue here?

See last my comment with `build_prefix`
```elixir
query
  |> build_prefix(nil, "tenant_main_008")
  |> build_prefix("hr", "tenant_hr_008")
  |> build_prefix("inv", "tenant_inv_008")
  |> select(...)
  |> Repo.all  
```

**Comment by josevalim** [comment]
Another option here, so we don't change the `schema` API, is to support `@ecto_prefix "my_prefix"`. A lot of the schema configuration is already done via module attributes.

**Comment by Tica2** [comment]
`@schema_prefix "my_prefix"` is good
but to alter schema on runtime we still need build_prefix/2

Is fine this solution?
```elixir
query
  |> build_prefix(nil, "tenant_main_008")
  |> build_prefix("hr", "tenant_hr_008")
  |> build_prefix("inv", "tenant_inv_008")
  |> select(...)
  |> Repo.all 
```

I will prepare new PR to see options

**Comment by josevalim** [comment]
The `query` one is another discussion. Let's solve the schema one, then worry about `query`. :)

**Comment by josevalim** [comment]
Specially because we can do `%{query | prefix: "foo"}` today. :)

**Comment by Tica2** [comment]
ok, set prefix first!

I will continue to work here :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
