### ISSUE TITLE
key :password not found

### ISSUE THREAD

**Issue by radar** [elixir-lang/ecto#1011]
I have an application at https://github.com/radar/logs.ex which I'm compiling with:

```
MIX_ENV=prod mix release
```

When I try to run this application on my server using a `prod.secret.exs` with:

```
use Mix.Config

# In this file, we keep production configuration that
# you likely want to automate and keep it away from
# your version control system.
config :logs, Logs.Endpoint,
  secret_key_base: "TkLFBLaJCC0gw5zRCE8E3qHL2N8qwcHlUDmN+DVAGdIiSHJd/5QmI4xqmOY+sr1t"

# Configure your database
config :logs, Logs.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "railsbot",
  pool_size: 20

```

(Not the real secret, of course)

Then I run this command:

```
rel/logs/bin/logs foreground
```

The server is then accessible on port 8001. When I make a request though, it attempts to make a query and fails:

```
** (exit) exited in: GenServer.call(#PID<0.1295.0>, {:query, "SELECT c0.\"id\", c0.\"name\", c0.\"hidden\" FROM \"channels\" AS c0 WHERE (c0.\"name\" = $1) AND (c0.\"hidden\" = $2)", ["favicon.ico", false]}, 5000)
    ** (EXIT) an exception was raised:
        ** (KeyError) key :password not found in: [hostname: "localhost", username: "ryanbigg", timeout: 5000, otp_app: :logs, repo: Logs.Repo, adapter: Ecto.Adapters.Postgres, database: "railsbot", extensions: [{Ecto.Adapters.Postgres.DateTime, []}, {Postgrex.Extensions.JSON, [library: Poison]}], port: 5432]
            (elixir) lib/keyword.ex:235: Keyword.fetch!/2
            (postgrex) lib/postgrex/protocol.ex:82: Postgrex.Protocol.message/3
            (postgrex) lib/postgrex/connection.ex:417: Postgrex.Connection.new_data/2
            (postgrex) lib/postgrex/connection.ex:292: Postgrex.Connection.handle_info/2
            (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
            (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

I don't need to specify `password` here, because it _should_ be using ident auth. Running the same set of commands locally on my MBP does not make it require the `password` key. In fact, I can make whatever requests I like.

I _think_ this is an Ecto issue, since it's Ecto that is making the query to PostgreSQL. I'm sorry if this is not the right repo to file the issue under.

If you need any other info, I'll be around to provide it to you. Thanks.

**Comment by ericmj** [comment]
Which postgrex version are you using? Hard to debug with the stacktrace without knowing it.

**Comment by radar** [comment]
My apologies. I'm using 0.9.1. Here's the line from my `mix.lock` showing that:

```
"postgrex": {:hex, :postgrex, "0.9.1"},
```

**Comment by ericmj** [comment]
The server is telling the client to use md5 authentication. I think you have a bug in your hba conf.

**Comment by radar** [comment]
The Rails app configuration on the same server works without specifying a password. Why is Ecto/Postgrex not doing that?

**Comment by ericmj** [comment]
I don't know how rails work in this regard, so I couldn't say, sorry.

On Mon, Oct 12, 2015 at 6:06 PM, Ryan Bigg <notifications@github.com> wrote:

> The Rails app configuration on the same server works without specifying a
> password. Why is Ecto/Postgrex not doing that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1011#issuecomment-147545084>.
>



-- 
Eric Meadows-Jönsson

**Comment by josevalim** [comment]
It may be because Active Record uses socket connection via the C API. Ecto uses TCP.

**Comment by radar** [comment]
Ah, that could well be it. I will check my hba_conf.

**Comment by ericmj** [comment]
I can't find any documentation for it, but from googling around it seems to be that you need unix-domain sockets for ident auth. Unfortunately we cannot use unix-domain sockets until OTP supports it.

**Comment by radar** [comment]
That's perfectly alright. I'll just set a username/password for my app and call it done. Thanks for your time @ericmj and @josevalim :)

**Comment by Arthur-Kamau** [comment]
Am deploying a sample application, i have the same error.From the comments above i do not understand how to fix the error.
What should be altered to fix the above error.
