### ISSUE TITLE
--no-deps-check flag doesn't work with ecto mix tasks

### ISSUE THREAD

**Issue by lachie** [elixir-lang/ecto#1013]
As I understand it, for a built elixir project with `git` dependencies I should be able to do things like
```sh
mix ecto.create --no-deps-check
```
to create the database on machine with no `git` installed.

This doesn't work for me. The easiest way to verify is:
1. have a project with a git dependency.
2. `sudo chmod 0644 $(which git)` # temporarily of course
3. 
```
mix ecto.create --no-deps-check
** (Mix) Error fetching/updating Git repository: the "git" executable is not available in your PATH. Please install Git on this machine or pass --no-deps-check if you want to run a previously built application on a system without Git.
```
(don't forget to `sudo chmod 0755 $(which git)`)

I've also used `execsnoop` to verify that `git` is being invoked.

I'm new to elixir, so I have no idea what's happening in the code, or how to debug this.

The workaround was to install `git` (I'm working in a docker container), but this isn't really a fix, and isn't feasible in the long term.

**Comment by josevalim** [comment]
Which Ecto version?

**Comment by josevalim** [comment]
Actually, I just noticed it won't ever work because the task is in a dependency itself. So we need to ensure the dependency is correct, I don't think there is much we can do. Maybe try this project? https://github.com/reset/migrator

**Comment by josevalim** [comment]
Also, this will be fixed on Elixir 1.2 because we will allow Mix to run without the source files. :) So we are getting there, please hold on tight. :)

**Comment by madkinder** [comment]
Hi. I'm facing exactly the same problem. Since you closed the ticket could you please explain how did you fix it?

**Comment by josevalim** [comment]
Currently there is no solution. We are tackling other issues that will solve this but using something like migrator or ensuring that the tasks are loaded before executing the command is enough:

    mix do deps.loadpaths, ecto.create --no-deps-check

**Comment by DavidRawk-Blake** [comment]
Still a problem.  "there is no solution".  Can we re-open this :)

**Comment by josevalim** [comment]
It is closed here because it is not an Ecto issue. Mix will always load and check dependencies, before Ecto does anything, because Ecto itself is a dependency. It is a chicken and egg issue.
