### ISSUE TITLE
Increase timeout value in Ecto

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1022]
`5000`, the default, is way too low. I am thinking about `15_000`. Thoughts? @michalmuskala @fishcakez @ericmj?

**Comment by ericmj** [comment]
:+1:

**Comment by fishcakez** [comment]
I am not entirely on board with this.

When using `poolboy`, the query timeout and queue timeout is the same length, `:timeout`. We do not want to queue for `15_000` with `poolboy`. `poolboy` has an unbounded queue length which means requests can really build up in the queue. With an excessive timeout this can lead to horrible buffer bloat situations where everything takes 15 seconds whether it succeeds or fails.

If we want to change the default we need to add a `queue_timeout` configuration to the `poolboy` pool. There was a recent thread on the mailing list where the timeout was increased to `10_000` and ecto became completely unresponsive.

**Comment by josevalim** [comment]
Agreed. Let's increase timeout and introduce queue_timeout.

**Comment by fishcakez** [comment]
Shall I pick this up? Do we need to define `queue_timeout` in __pool__? Perhaps we should call it `pool_timeout` as it will be the timeout passed to the `Ecto.Pool`. It wont always be a queue timeout and never is for the sbroker pools.

**Comment by josevalim** [comment]
`pool_timeout` sounds great and yes, let's store it in `__pool__`.

**Comment by josevalim** [comment]
And yes, please go ahead! :D
