### ISSUE TITLE
(FunctionClauseError) no function clause matching in Postgrex.Extensions.Binary.encode_interval/1

### ISSUE THREAD

**Issue by troyk** [elixir-lang/ecto#1023]
version 1.0.4
elixir 1.1.1

I think this might be a postgrex bug, but wanted to post here first since I'm using Ecto (and btw, the SSN in the example is invalid and ok to publish)

stack:
```
** (FunctionClauseError) no function clause matching in Postgrex.Extensions.Binary.encode_interval/1
    (postgrex) lib/postgrex/extensions/binary.ex:248: Postgrex.Extensions.Binary.encode_interval("12 months")
    (postgrex) lib/postgrex/protocol.ex:299: anonymous fn/2 in Postgrex.Protocol.encode_params/1
      (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
      (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
      (elixir) lib/enum.ex:1043: Enum.map/2
    (postgrex) lib/postgrex/protocol.ex:294: Postgrex.Protocol.encode_params/1
    (postgrex) lib/postgrex/protocol.ex:264: Postgrex.Protocol.send_params/2
    (postgrex) lib/postgrex/protocol.ex:136: Postgrex.Protocol.message/3
    (postgrex) lib/postgrex/connection.ex:417: Postgrex.Connection.new_data/2
    (postgrex) lib/postgrex/connection.ex:292: Postgrex.Connection.handle_info/2
      (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
      (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
      (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

```elixir
  def for_ssn(ssn, limit \\ 69) do
    q = from h in Ah.AddressHistory,
    where: h.ssn == ^ssn,
    order_by: fragment("? DESC NULLS LAST",h.to_date)
    cond do
      is_integer(limit) -> q |> Ecto.Query.limit([q], ^limit)
      is_binary(limit) and Regex.match?(~r/max/i, limit) -> q |> Ecto.Query.limit([q], fragment("regexp_replace(?,'[^0-9]','','g')::int", ^limit))
      is_binary(limit) -> q |> Ecto.Query.where([q], fragment("? >= (now()-(?)::interval)::date", q.to_date, ^limit))
      #is_binary(limit) -> q |> Ecto.Query.where([q], fragment("? >= (now()-to_interval(?))::date", q.to_date, ^limit))
    end
  end

 # calling the above fn results in the following Ecto.Query
#Ecto.Query<from a in Ah.AddressHistory, where: a.ssn == ^"078051120",
 where: fragment("? >= (now()-(?)::interval)::date", a.to_date, ^"12 months"),
 order_by: [asc: fragment("? DESC NULLS LAST", a.to_date)]>

```

the commented line `#is_binary(limit) -> q |> Ecto.Query.where([q], fragment("? >= (now()-to_interval(?))::date", q.to_date, ^limit))` works because I subverted the ::interval cast by creating as postgres function called to_interval

```sql
CREATE OR REPLACE FUNCTION to_interval(i text) returns interval
AS $$ select i::interval $$ LANGUAGE SQL IMMUTABLE RETURNS NULL ON NULL INPUT;
```

So it seems the text `interval` is somehow triggering a call to ` Postgrex.Extensions.Binary.encode_interval/1` as I also tried `is_binary(limit) -> q |> Ecto.Query.where([q], fragment("? >= (now()-(case (? as interval))::date", q.to_date, ^limit))` and got the same error, but 'to_interval' passes to the db with success

**Comment by josevalim** [comment]
I don't think there is anything wrong here. Postgrex does not now how to cast a binary to an interval. Btw, Ecto supports intervals: https://github.com/elixir-lang/ecto/blob/master/lib/ecto/query/api.ex#L137-L162

**Comment by troyk** [comment]
But on a cast operation (casting on the server with the `::` operator or `CAST AS`) it's not Postgrex job to cast, it should just send the underlying type.  if `^limit` is a binary, I'm saying send this binary to postgresql and let it cast it to an interval.

**Comment by josevalim** [comment]
Yes, Postgrex is not trying to cast. That's exactly the issue, Postgrex is going to the database, sending the query, and Postgres is telling Postgrex it must send an interval back. And Postgrex doesn't know how to cast. The one giving the instructions, anyway, is the database. :)
