### ISSUE TITLE
Support count distinct

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1027]
For @elixir-lang/ecto-adapters 

* [x] MySQL
* [x] PostgreSQL
* [x] SQLite3
* [x] MSSQL
* [x] MongoDB

See #1024.

**Comment by michalmuskala** [comment]
MongoDB: https://github.com/michalmuskala/mongodb_ecto/commit/995f2e4173194a2d1de9fcafe5b19e536cff1688

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/5af7ff7c03402a29d86cc7b2474056f4f5f193d2

**Comment by mobileoverlord** [comment]
Wow I let this one slip by: livehelpnow/tds_ecto@6cb70bdc63bd4e4650d8da197b8369851512c9f7

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
