### ISSUE TITLE
Remove changeset.valid?

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1030]
A lot of folks are relying on this information, which is wrong, since it does not consider constraints. We need to remove `valid?` and use something that would indicate more cleanly what is the changeset state.

**Comment by michalmuskala** [comment]
I agree that it can be misused, but knowing if any of the "normal" validations failed can also be useful. 
If you have multiple models you need to save/update inside a transaction this can save you from even starting a transaction and persisting couple of those models, if you know one of them is not valid anyway. You can skip the entire trip to the database in that case.
