### ISSUE TITLE
String interpolation will grow cached unboundedly

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ecto#1031]
Ecto should not allow for string interpolation for string literals in queries, instead it should force the user to use query interpolation if dynamic strings are needed. Ecto will treat changes in the interpolated string as unique new query entries in the cache and it will grow unboundedly.

Also, I couldn't find an upper limit on the number of entries in the cache which we should have because queries can be generated dynamically in other ways.

**Comment by Havvy** [comment]
Motivating example:

elixir```
defmodule Messages do
  @choke %{
    id: 0,
    len: 1
  }
 
  def decode_type(<<@choke.len::size(32), @choke.id, rest::bytes>>) do
    {:choke, rest}
  end
end
```

**Comment by michalmuskala** [comment]
I agree that we need to bound the cache, on the other hand I disagree that we should ban non-literal fragments completely. There are valid use cases for them, that can't be expressed otherwise - i.e. dynamic `or` queries. Maybe we should mark non-literal fragments as non-cacheable?

Also with MongoDB we have keyword fragments, so we can't only consider strings (although MongoDB does not use caching at all currently).

**Comment by josevalim** [comment]
> Ecto should not allow for string interpolation for string literals in queries

Agreed.

> Also, I couldn't find an upper limit on the number of entries in the cache which we should have because queries can be generated dynamically in other ways.

Yes, given people were using eval to build queries on the mailing list, a limit here wouldn't hurt. Ideally we would like to implement something like LRU but I am unsure if we can implement that efficiently with ETS.

**Comment by ericmj** [comment]
We don't allow string interpolation in fragments because it would allow for
SQL injection (1). This issue is about string interpolation in literals.

(1) Maybe we should allow dynamic fragments in mongo or maybe we already do but
that's another issue.

On Sunday, 18 October 2015, Michał Muskała <notifications@github.com> wrote:

> I agree that we need to bound the cache, on the other hand I disagree that
> we should ban non-literal fragments completely. There are valid use cases
> for them, that can't be expressed otherwise - i.e. dynamic or queries.
> Maybe we should mark non-literal fragments as non-cacheable?
>
> Also with MongoDB we have keyword fragments, so we can't only consider
> strings (although MongoDB does not use caching at all currently).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1031#issuecomment-149001981>.
>


-- 
Eric Meadows-Jönsson
