### ISSUE TITLE
Poolboy worker blocks poolboy to start connection if lazy: false

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/ecto#1034]
Starting connection in worker's `init/1` blocks poolboy while the connection is started. If the connection attempts to connect during start this will block poolboy.

The following adapters always block:
* mysql
* tds

The following adapters don't block by default but can be configured to block with `sync_connect: true`:
* postgresql

The following adapters never block:
* mongo

This issue will probably only have an impact if `max_overflow > 0`  and the adapter blocks in connect. However it will also slow startup time or restart time in the event of a crash.

A potential fix is in the sbroker worker, which casts to self() to connect.

**Comment by josevalim** [comment]
Should we push this to adapters? Just ask them to not block on connection by default?

**Comment by fishcakez** [comment]
When using poolboy to checkout the following occurs:
* call to poolboy with timeout
* call to worker with timeout
* call to connection with timeout

If the connection blocks when started then the call to worker will block if it needs to start a connection. This means on a bad day the client can wait for nearly 3 * timeout.

If the connection doesn't block when started then the call to worker should be very fast as it just needs to spawn a process. However the call to the connection will have to wait for the socket to connect and do any handshaking before its query is handled. This may mean that the call to connection times out because connect/handshake is much more expensive than the query but the longest a client will wait is 2 * timeout.

Importantly if the call to the connection does timeout the worker will shutdown the connection so that the on going query does not effect the next client. Of course the next client may face the same problem as it has to wait for the connection to connect/handshake.

I am unsure which of those behaviours people will prefer.

Poolboy uses a LIFO worker queue (by default) so the most recent worker to be checked in will be the first worker to be checked out. This means if a connection crashes, a query times out or a client exits mid transaction its likely the next checkout will be for a worker without a connection. Therefore blocking to connect can occur a disproportionately number of times.

This issue can solved by using the sbroker pool with an adapter that blocks on start as workers/connections are only queued when ready, the client gets the connection directly from the broker so doesn't call the worker and the worker never blocks the broker process.

**Comment by fishcakez** [comment]
Now that `lazy: false` doesn't block shall we encourage adapters to always sync connect or add a configuration like postgrex (with a default determined by the pool)?

**Comment by josevalim** [comment]
That sounds good. I think most adapters sync connect though?

**Comment by fishcakez** [comment]
> That sounds good. I think most adapters sync connect though?

postgrex `sync_connect` option has a bug in the latest tag where a failed connection returns an exception instead of {:error, exception}. It was fixed in master long ago.

mongodb does not provide a `sync_connect` option.

**Comment by michalmuskala** [comment]
I think it's important to have in mind that the MongoDB's adapter does not use currently Ecto pools, but has it's own pooling.

**Comment by fishcakez** [comment]
Ah thanks @michalmuskala. Looking at the code MongoDB's connection process is smarter than its SQL counterparts and does not need a middleman process. Its started by poolboy directly and does not block on start. It also handles network errors in an elegant manner. @michalmuskala, @ericmj and others have done really great work there.

Now we are just waiting on`:postgrex` to tag a release and then we can add `sync_connect: true` as a default option in the postgrex adapter.

**Comment by josevalim** [comment]
@fishcakez we can add the option now anyway and we will be safe whenever it is out (unless we need it for tests).

**Comment by fishcakez** [comment]
@josevalim I think we should wait because postgrex supports it now but there is a bug in the current release where `Postgrex.Connection.start_link` returns `%Postgrex.Error{}` instead of `{:error, %Postgrex.Error{}}`.

**Comment by ericmj** [comment]
What do we want? sync_connect! when do now! we want it?

**Comment by ericmj** [comment]
the lazy option also does not compose with sync_connect. Should we just drop lazy?

**Comment by fishcakez** [comment]
> the lazy option also does not compose with sync_connect. Should we just drop lazy?

I don't think we can drop lazy because of migrations? I remember wanting to drop it when introducing `Ecto.Pools` and could not.

Can you explain why it doesn't compose? Above I think I mention `sync_connect` was a good approach for lazy connections because it prevents the case where connecting time is included in the "query timeout", which can lead to a timeout on a query. The timeout causes the worker to stop the connection and the cycle begins again. Perhaps this is a needless worry.

Are you saying that including the connecting time in the "query timeout" is desired when `lazy: true`? In that situation the timeout max is `pool_timeout` + `timeout` rather than `pool_timeout` + `pool_timeout` + `timeout`?

**Comment by ericmj** [comment]
Sorry, I was confusing things. You are right that sync_connect is preferable with lazy.

> I don't think we can drop lazy because of migrations? I remember wanting to drop it when introducing Ecto.Pools and could not.

Migrations manually start and stop the repo now, are there other issues with migrations or did that fix the issue?

**Comment by josevalim** [comment]
Closing this because I believe it has been fixed. Please reopen otherwise.
