### ISSUE TITLE
Add another example app?

### ISSUE THREAD

**Issue by parkerl** [elixir-lang/ecto#1038]
A few folks on the #ecto slack channel suggested I ask about contributing the project I have been maintaining with query examples to Ecto as an example. I have been compiling example queries from bog posts and issues that come up in slack here:

https://github.com/parkerl/ecto_query_library

I would be happy to clean up this project and move any or all of it into Ecto. 

Thanks for all the hard work on this great project!

//cc @josevalim

**Comment by josevalim** [comment]
I feel those examples would be really nice to have. I don't think they would be hard to maintain either. I would just move them to code, to make it easier for folks to run and for us to check they are up to date. Thoughts @ericmj/@michalmuskala?

**Comment by st23am** [comment]
It would be nice to include something like these in the Phoenix Guides as advanced usage or at least link to them. Just a :thought_balloon: cc: @lancehalvorsen

**Comment by wicliff** [comment]
@st23am - Adding this to https://github.com/phoenix-examples/ecto_query_library Basically refers to different examples and implementations

**Comment by st23am** [comment]
@wicliff  cool :+1:

**Comment by ericmj** [comment]
Maybe we can link to it from ecto instead of including it in ecto itself. Including it in ecto would require some clean up, adding tests and making sure it's part of CI and the regular suite so it is kept up to date. I am afraid that will be too much work for ecto itself.

**Comment by parkerl** [comment]
@wicliff thanks! That's great. 

@ericmj I would be more than willing to clean it up and test. I plan to do that regardless. However, I understand you concerns about CI and the main suite. I certainly wouldn't want it to burden the project.

**Comment by josevalim** [comment]
I am closing this for now because we have way too many things on our plate. Thank you @parkerl!
