### ISSUE TITLE
No way to specify MySQL connection for integration tests

### ISSUE THREAD

**Issue by maxim** [elixir-lang/ecto#1041]
I have MySQL running in a docker container, since I run multiple versions of it. Trying to run integration tests against it always fails as follows.

```
dev/ecto git:(master) MIX_ENV=mysql MDBUSER=root MDBPASSWORD=secret MDBHOST="192.168.99.100" MYSQL_TCP_PORT=32769 mix test                                1 ↵
** (MatchError) no match of right hand side value: {:error, "ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)\n"}
    integration_test/mysql/test_helper.exs:73: (file)
    (elixir) lib/code.ex:363: Code.require_file/2
    (elixir) lib/enum.ex:579: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:579: Enum.each/2
    (mix) lib/mix/tasks/test.ex:183: Mix.Tasks.Test.run/1
```

These credentials work fine in my phoenix app, so the problem is with ENV vars being ignored I believe.

**Comment by maxim** [comment]
It worked after manually editing these hardcoded lines:

https://github.com/elixir-lang/ecto/blob/master/integration_test/mysql/test_helper.exs#L28
https://github.com/elixir-lang/ecto/blob/master/integration_test/mysql/test_helper.exs#L49

Except 2 tests in https://github.com/elixir-lang/ecto/blob/master/integration_test/mysql/storage_test.exs which provide their own hardcoded params for "correct_params".

**Comment by josevalim** [comment]
Closing in favor of the PR. :D
