### ISSUE TITLE
Create fails when using sqlite3 on Windows

### ISSUE THREAD

**Issue by Shemeikka** [elixir-lang/ecto#1050]
I'm having trouble getting sqlite3 to work with ecto and phoenix.

I created a new phoenix project using
    
    mix phoenix.new webend --database sqlite

Then I tried to run

    mix ecto.create

but that failed since compiling esqlite failed. Compiler cl.exe was not found in path but luckily I had Visual Studio installed on my computer so I just added the bin-folder to path. After trying again to compile esqlite using

    mix deps.compile esqlite

it failed again. This time it couldn't find some files if I remember right. I installed proper rebar and added that to my path. Again tried to compile and it still failed. Then I started developer command prompt for visual studio and tried to compile esqlite again. This time it worked.

But after all this ecto.create fails with following error message:

```
15:43:10.010 [error] Process #PID<0.148.0> raised an exception
** (MatchError) no match of right hand side value: {:error, {:load_failed, 'Failed to load NIF library c:/Stuff/Programming/Repos/webend/_build/dev/lib/esqlite/priv/esqlite3_nif: \'Unspecified error\''}}
    src/esqlite3_nif.erl:47: :esqlite3_nif.init/0
    (kernel) code_server.erl:1674: anonymous fn/1 in :code_server.handle_on_load/4
** (UndefinedFunctionError) undefined function: :esqlite3_nif.start/0 (module :esqlite3_nif is not available)
    :esqlite3_nif.start()
    src/esqlite3.erl:59: :esqlite3.open/2
    lib/sqlite_ecto.ex:57: Sqlite.Ecto.storage_up/1
    lib/mix/tasks/ecto.create.ex:32: Mix.Tasks.Ecto.Create.run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (elixir) lib/code.ex:168: Code.eval_string/3


15:43:10.012 [warn]  The on_load function for module esqlite3_nif returned {{:badmatch,
  {:error,
   {:load_failed,
    'Failed to load NIF library c:/Users/Spitz/Dropbox/Programming/Repos/webend/_build/dev/lib/esqlite/priv/esqlite3_nif: \'Unspecified error\''}}},
 [{:esqlite3_nif, :init, 0, [file: 'src/esqlite3_nif.erl', line: 47]},
  {:code_server, :"-handle_on_load/4-fun-0-", 1,
   [file: 'code_server.erl', line: 1674]}]}
```

Don't even know if this is a problem with ecto or esqlite.

I'm using
Elixir 1.1.1
Ecto 1.0.6
esqlite 0.2.1
sqlite_ecto 1.0.2
sqlitex 0.8.2
Windows 10 64bit ENG
Visual Studio 2015

**Comment by ericmj** [comment]
Can you try using esqlite directly without ecto? I don't think this is an ecto issue.

**Comment by Shemeikka** [comment]
You were right. Tried to load esqlite module using erl-shell and it gave the same error message.
So it's not an ecto issue after all.

**Comment by ericmj** [comment]
Thank you for investigating. I would recommend opening an issue on the driver library's repository if you haven't already.

**Comment by aruprakshit** [comment]
@Shemeikka How did you fix it?
