### ISSUE TITLE
Remove bindings from most operations in Ecto.Query

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1055]
Quoting @paulcsmith:

> To make this work well across the Query API, I think that making the binding optional for order_by, limit, where, and whatever other query functions are needed would make writing queries so much simpler.

This issue is currently assigned to him. :)

**Comment by paulcsmith** [comment]
To clarify, do we want to support something like `Post |> where(views > 100)` or just a keyword list for where `Post |> where(title: "My title")`. I am leaning toward only allowing a keyword list

**Comment by josevalim** [comment]
It should be a keyword list, which we already support. We just need to make
the binding an optional argument. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by paulcsmith** [comment]
Perfect. That's what I thinking too :)
