### ISSUE TITLE
Fragment with array parameter

### ISSUE THREAD

**Issue by strokovnjaka** [elixir-lang/ecto#1058]
I'm not sure if this is a bug, but when I try to create a query with a fragment containing 'in' with an array to be interpolated, the thing does not work (in my case the fragment contains a bit more sql, but the sample below fails with the same error).

```elixir
pos = [1,2,4]
MyModel |> Ecto.Query.where([e], fragment("position not in (?)",^pos)) |> Repo.all
```

The error is 
```
** (FunctionClauseError) no function clause matching in Postgrex.Extensions.Binary.encode/4
    (postgrex) lib/postgrex/extensions/binary.ex:59: Postgrex.Extensions.Binary.encode(%Postgrex.TypeInfo{array_elem: 0, base_type: 0, comp_elems: [], input: "int4in", oid: 23, output: "int4out", receive: "int4recv", send: "int4send", type: "int4"}, "position not in (1,2,4)", 213042, {9, 3, 6})
    (postgrex) lib/postgrex/protocol.ex:299: anonymous fn/2 in Postgrex.Protocol.encode_params/1
      (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
      (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
      (elixir) lib/enum.ex:1043: Enum.map/2
    (postgrex) lib/postgrex/protocol.ex:294: Postgrex.Protocol.encode_params/1
    (postgrex) lib/postgrex/protocol.ex:264: Postgrex.Protocol.send_params/2
    (postgrex) lib/postgrex/protocol.ex:136: Postgrex.Protocol.message/3
```

It seems the interpolation only works when the parameter is an integer.

Versions:
Elixir 1.1.1
Ecto 1.0.3
Postgres server 9.3.6
Postgrex adapter 0.9.1

**Comment by josevalim** [comment]
We are not going to automatically expand `in`.  You can write this using regular query syntax:

    Ecto.Query.where([e], not e.position in ^pos)

or use Postgres arrays directly:

    Ecto.Query.where([e], fragment("NOT position = ALL(?)", ^pos))

**Comment by strokovnjaka** [comment]
@josevalim Thank you for guidance, and of course for the great work with elixir!
The second suggestion is the one I use as I do a subquery in fragment.
