### ISSUE TITLE
Consider getting rid of Ecto.Models

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1059]
We should be able to move callbacks to the repository (but not calling them callbacks) and that's pretty much what models have to offer.

**Comment by josevalim** [comment]
The only other topic of discussion is where the functions Ecto.Model should exist (maybe Ecto?).

**Comment by michalmuskala** [comment]
Those concerning associations could be moved to `Ecto.Association`, `primary_key/1` could be moved to schema. I'm not sure where we could move `put_meta/2`.
