### ISSUE TITLE
After inserting a changeset with embeds, the embedded document's state is still `built`

### ISSUE THREAD

**Issue by paulcsmith** [elixir-lang/ecto#1065]
You can see a failing test here: https://github.com/paulcsmith/ecto/commit/11945063d7bf830dbd1473bb3dc480cfe099620a

Maybe this is expected behavior, but it seems like a bug because the returned record from `Repo.insert!` has the embedded document's state as `:built` , but when I load the record from the repo after I have inserted the changeset, the embedded document's state is `:loaded` (which is what I expect).

If this is a bug I'd be happy to help fix it, but I could use some pointers about which function/modules to look at.

**Comment by michalmuskala** [comment]
This definitely looks like a bug. The call chain starts with `Ecto.Repo.Model.insert` and continues to `Ecto.Repo.Model.process_embeds`, this follows to `Ecto.Changeset.Relation.on_repo_action` and finishes in `Ecto.Embedded.on_repo_action`. I think this [last place](https://github.com/elixir-lang/ecto/blob/master/lib/ecto/embedded.ex#L157) would be the best one, it should probably be changed to mimic what we do for [normal models](https://github.com/elixir-lang/ecto/blob/master/lib/ecto/repo/model.ex#L318-L331)

**Comment by josevalim** [comment]
Great, I am assigning it to you @michalmuskala!

**Comment by paulcsmith** [comment]
Thanks @michalmuskala!
