### ISSUE TITLE
Add from_now() or ago() for querying date times

### ISSUE THREAD

**Issue by paulcsmith** [elixir-lang/ecto#1071]
Original discussion: https://groups.google.com/forum/#!topic/elixir-ecto/ghbMz30f4QY

Me:
> Rather than requiring `datetime_add(^Ecto.DateTime.utc, -5, "minutes")` I think it would make sense to use the current time by default `datetime_add(-5, "minutes")`

> Thoughts on this? I think it's still pretty intuitive and saves a lot of space, and time looking up what to call to get the current date :) I'd be happy to submit a PR if we want it as part of Ecto

Jose:
> I would rather add a from_now() or even ago() to the API. The question is if we **should get the current time from Elixir land or the database**. We should ping @lau, he will have good ideas on the topic. Could you please get in touch with him and sync?

@lau do you have any thoughts on this? My thought would be that we get it from Elixir, but I'm not really sure.

Also, I think I prefer `from_now` as the function name: `inserted_at > from_now(-5, :minutes)`, but I don't have a strong preference

**Comment by lau** [comment]
It can be dangerous to add default values. So I would recommend not doing that.

To get the time right now, it would make sense to get it in UTC from Elixir. `inserted_at` timestamps are also UTC "now" from Elixir.

`from_now` and `ago` is OK-ish, but now where? This also touches on an issue with Ecto.DateTime: "Naive datetimes" and UTC datetimes are treated the same. There is no differentiating between the two. So you might compare an UTC datetime to something that is not UTC. In order to be more explicit I would prefer `from_now_utc` (and optionally `ago_utc`). That way it the function name tells you it is UTC, so you have that mental cue when comparing it to another datetime.

**Comment by josevalim** [comment]
@lau so to be clear, you are ok with: `from_now_in_utc` and `ago_in_utc`? I am honestly thinking it is better to use Ecto.DateTime.utc, from Ecto itself.

**Comment by josevalim** [comment]
Thanks a lot for your input @lau  :)

**Comment by lau** [comment]
@josevalim I'm happy to help. 

> I am honestly thinking it is better to use Ecto.DateTime.utc, from Ecto itself.

I'm not sure I understand. Better than what?

**Comment by josevalim** [comment]
@lau better than using `NOW()` from the database.

**Comment by lau** [comment]
Yes, I was assuming that `Ecto.DateTime.from_now_in_utc` would be a shortcut for `Ecto.DateTime.utc` that was then advanced by an argument. Eg. `Ecto.DateTime.from_now_in_utc(60)` would get the time now from Elixir and add 60 seconds to and return this new Ecto.DateTime struct.

**Comment by lau** [comment]
I should have checked the docs. datetime_add is in the query API, not in Ecto.DateTime...

**Comment by josevalim** [comment]
@lau sorry, not quite. We would send do the database: `? + 60 SECONDS`, where `?` is `Ecto.DateTime.utc`. So the datetime is calculated in Elixir but the interval is calculated at the database.

**Comment by lau** [comment]
Yeah I had misunderstood where this would be used. But I just checked the docs again.

So I guess that this

```elixir
# Get all items published since the last month
from p in Post, where: p.published_at >
                       from_now_in_utc(-1, "month")
```
would be a shortcut for

```elixir
# Get all items published since the last month
from p in Post, where: p.published_at >
                       datetime_add(^Ecto.DateTime.utc, -1, "month")
```
Is that what we are talking about? And `NOW()` from the db would not be used, right? In that case it seems OK to me.

**Comment by lau** [comment]
I'm not sure if I like how the database does the calculations. From the MySQL docs http://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_date-add
```
If you add MONTH, YEAR_MONTH, or YEAR and the resulting date has a day that
is larger than the maximum day for the new month, the day is adjusted to the
maximum days in the new month:
```
But that is another issue.

As I see it the proposed new function above is just a shortcut for whatever is there already.

**Comment by paulcsmith** [comment]
This is probably quite ignorant, but I would rather use a plain `from_now` or `ago` function without `in_utc` in the name. As long as whatever it's using under the hood is documented (which I assume it would be), it should be ok. If you need to be specific about what time it's using, you could use `datetime_add` instead.

**Comment by lau** [comment]
It could be `from_now_utc` without `_in`. I think it is important to have it in the name. With all the date/time bugs around everywhere, developers can benefit from that kind of help IMHO. Personally I will gladly have to write 4 extra chars for the function name to tell that extra information.

If the function was always used to compare with a datetime with sufficient timezone information, it wouldn't be necessary to specify, but in this case you can compare with "naive datetimes" and this is why `_utc` is helpful.

**Comment by michalmuskala** [comment]
I like the idea of `from_now`, but I wonder if we should be adding this to the query API, given it's a one line macro to implement it:

```elixir
defmacro from_now(count, unit) do
  quote do
    datetime_add(^Ecto.DateTime.utc, unquote(count), unquote(unit))
  end
end

**Comment by paulcsmith** [comment]
I think it's used enough that it would be nice to not have to create the macro, require the module, etc. I'm not sure about the Ecto philosophy of what to include/not include though so if it doesn't fit in, that's fine

**Comment by josevalim** [comment]
> I'm not sure about the Ecto philosophy of what to include/not include though so if it doesn't fit in, that's fine

I see no problem adding functions to the query api after we added `Ecto.Query.API`.

**Comment by paulohp** [comment]
Hey! I see the Level:Starter on the issue and I really want to start contributing with Elixir and Ecto.
Do you folks have some advices on starter contributing with this one? Looks easy but I don't know the code of ecto yet. some insights will be a good start tom me.

Thanks!

**Comment by tony612** [comment]
@paulohp I think you can refer to the code in Ecto.Query.Api
