### ISSUE TITLE
Support nils in arrays

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/ecto#1082]
It turns out both PostgreSQL and MongoDB support `nil` values in arrays of other types (it's quite obvious with Mongo not having rigid structure).

For PostgreSQL this is discussed in the documentation here: http://www.postgresql.org/docs/current/static/arrays.html#ARRAYS-INPUT

We should allow arrays of type `{:array, subtype}` to contain both values of type `subtype` as well as `nil`.

Thanks to @amokan for initial report in MongoDB adapter: https://github.com/michalmuskala/mongodb_ecto/issues/51

**Comment by tony612** [comment]
But it seems work on master branch. I wrote two test cases(https://github.com/tony612/ecto/commit/a1d056a5e3c5f5a146eac16351c626cec415d2c1) for this, both them passed(https://travis-ci.org/tony612/ecto/builds/97240242).

Is there something wrong in my test cases? Or this problem has been fixed?
@amokan Can you provide your ecto version and error log?

**Comment by josevalim** [comment]
@tony612 can you please send a PR? Let's keep the first test (in type.exs) but let's make sure we also read the inserted record from the database and it works.  Thank you!
