### ISSUE TITLE
Possible discrepancy in documentation regarding the map type and Poison

### ISSUE THREAD

**Issue by mfilej** [elixir-lang/ecto#1085]
I’m trying to figure out if there is a discrepancy in the docs or if I’m reading things wrong. According to ecto docs on the `:map` type (https://hexdocs.pm/ecto/Ecto.Schema.html):

> For maps to work in such databases, Ecto will need a JSON library. By default Ecto will use Poison which needs to be added your deps in mix.exs:

I found that having poison in `deps` was not enough - I had to explicitly set
`config :ecto, :json_library, Poison`

If I understand correctly, the docs also hint that this config applies to mysql/mssql while I'm using postgres.

If someone can confirm that the problem is in the docs I'm happy to provide a patch. If needed I can send a sample app demonstrating this.

**Comment by josevalim** [comment]
This value is set by default as long as you have added `:ecto` to your list of applications as the README says here: https://github.com/elixir-lang/ecto/blame/master/README.md#L88

**Comment by mfilej** [comment]
That is indeed what was missing, thanks for the quick response. 

![](http://i.imgur.com/7O2FM6I.gif)
