### ISSUE TITLE
`Repo.insert!` doesn't respect NOT NULL columns with fallback

### ISSUE THREAD

**Issue by henrik** [elixir-lang/ecto#1091]
I see this was discussed before in #591.

I'm on Ecto 1.0.6 though, and I was bitten by this issue, so maybe it recurred?

I added a column like:

``` elixir
alter table(:packages) do
  add :testcol, :string, null: false, default: "somedefault"
end
```

And I get this unexpected behaviour:

``` elixir
iex(1)> %Toolbox.Package{} |> Toolbox.Package.changeset(%{name: "a", hex_updated_at: "2015-01-01T00:00:00Z"}) |> Toolbox.Repo.insert!
[debug] BEGIN [] OK query=122.0ms queue=4.1ms
[debug] INSERT INTO "packages" ("description", "hex_updated_at", "inserted_at", "name", "testcol", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id" [nil, {{2015, 1, 1}, {0, 0, 0, 0}}, {{2015, 11, 17}, {22, 9, 9, 0}}, "a", nil, {{2015, 11, 17}, {22, 9, 9, 0}}] ERROR query=4.9ms
[debug] ROLLBACK [] OK query=0.3ms
** (Postgrex.Error) ERROR (not_null_violation): null value in column "testcol" violates not-null constraint
```

I would not expect the generated query to attempt to set any unspecified columns (so not "description" nor "testcol").

The changeset indeed ignores these unspecified columns:

``` elixir
%Ecto.Changeset{action: nil,
 changes: %{hex_updated_at: #Ecto.DateTime<2015-01-01T00:00:00Z>, name: "a"},
 …
```

But they do become part of the INSERT query for whatever reason.

**Comment by josevalim** [comment]
@henrik insert will always insert all fields known to the model exactly because it is the first insert.

**Comment by henrik** [comment]
@josevalim Thank you. I now see that this behaviour is documented fairly clearly – I should have checked that. I assumed it was a bug because it was not intuitive to me.

It still isn't intuitive to me – in what situations is it preferable for Ecto to attempt to insert nil values into every unspecified column, instead of respecting any column defaults? I don't doubt it's well-considered, I just can't think of a scenario for it myself.

**Comment by henrik** [comment]
Ah, you can set a `default: "something"` in the model schema (i.e. not in the migration), and that will apply in this situation. So maybe the recommendation is not to rely on DB-level defaults, but instead use model-level defaults?

**Comment by sorentwo** [comment]
I encountered this earlier today as well. The behavior I was aiming for and expecting was to use a `NOT NULL` constraint with a database default value.

@henrik Thanks for noting the use of `default: "something"`, that's the answer I was looking for. 

However, the `default:` solution doesn't work for timestamps, as noted in the documentation. Is that part of the current set of changes around removing callbacks?

**Comment by henrik** [comment]
@sorentwo Happy it helped. And sad that two people were bit by the same thing. I think I would like it if this behaviour was changed but I don't have the bigger picture here I guess.

Defaults in the model are a little trickier if you add a NOT NULL column to a table that already has data, as I'm noticing now. Then I suppose you either need to duplicate the default in the migration as well, or maybe add it as a NULL column, assign the model default value somehow, then make it NOT NULL.

**Comment by stevedomin** [comment]
@henrik I got bitten by it a while ago too. @josevalim gave a workaround in that thread in case you're interested: https://groups.google.com/forum/#!topic/elixir-ecto/QLiLzbWsUPE

I looked at how we could improve the docs but nothing obvious came up. I definitely think we should do something though.

**Comment by henrik** [comment]
@stevedomin Thank you. I guess that thread is a better place to continue the discussion – I might write something there.

**Comment by divmgl** [comment]
Is there any way we can use database defaults now that `before_insert` is deprecated? I'm having a rough time trying to perform a basic insert... I keep asking around but it seems like no one knows the solution. 

```
  @primary_key false
  schema "upvote" do
    field :account_id, Ecto.UUID, primary_key: true
    field :suggestion_id, Ecto.UUID, primary_key: true
    field :created_on, Ecto.DateTime
  end

  def insert_changeset(upvote) do
    %__MODULE__{}
    |> cast(Map.from_struct(upvote), [:account_id, :suggestion_id], [])
    |> delete_change(:created_on)
  end
```

In particular, I want to remove the `:created_on` change. This isn't working when I call `Repo.insert(changeset)`.

```
** (Postgrex.Error) ERROR (not_null_violation): null value in column "created_on" violates not-null constraint
``` 

Any help would be appreciated...

**Comment by divmgl** [comment]
I updated to Ecto `2.0.0-beta` and this issue is no longer occurring.

**Comment by michalmuskala** [comment]
With 1.1 the solution to this issue is callbacks, even though they are deprecated.
With 2.0 fields that are `nil` and that don't have a default value are not sent to the database, which solves the issue entirely.
