### ISSUE TITLE
Creating migration and models from existing tables

### ISSUE THREAD

**Issue by nathanjohnson320** [elixir-lang/ecto#1092]
Hi all, I made a project over on nathanjohnson320/Ecto-Generator and it pulls from existing MySQL tables to generate Ecto models. @olafura raised an issue (nathanjohnson320/Ecto-Generator#1) saying that it would make sense for this kind of functionality to be part of ecto itself and I was wondering if there was any plan to implement this functionality in ecto? I could work on it if needed though I'm still pretty new to elixir.

**Comment by josevalim** [comment]
Thank you for pinging @nathanjohnson320! We have other priorities for ecto in the short and mid-term so right now please keep rocking ecto-generator as a separate project!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
