### ISSUE TITLE
Handle socket and decode data on the client

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1094]
Hello @elixir-lang/ecto-adapters,

Ecto v1.1 will rely on clients being able to read the socket from the client (instead of inside the connection process) and to manually decode data. The implementation for Postgrex can be found here:

* https://github.com/ericmj/postgrex/pull/108
* https://github.com/ericmj/postgrex/pull/118 (this is optional and brings further improvements)

And here are the Ecto changes:

* https://github.com/elixir-lang/ecto/pull/1073

Our results measure that this is 25% faster than the current approach. Let us know if you have questions.

* [x] Postgres
* [ ] MySQL
* [ ] MSSQL
* [ ] SQLite3
* [ ] MongoDB

**Comment by fishcakez** [comment]
I've written a library for database connection processes at https://github.com/fishcakez/db_connection that handles sockets and decoding data on the client process. It provides an optional, more efficient version of Ecto pooling and transactions. Hopefully this will help moving the drivers to the new style and save reimplementing the same code. It will also allow all drivers to benefit from any improvements (such as idle timeouts and (re)connection backoff that have been added already).

I will look at using db_connection with postgrex next week. If you need any help getting your driver working or would like changes to the API please open an issue on db_connection tracker/your drivers issue tracker and mention me or contact me directly. It would be very good to release a stable API before Ecto 1.1.

**Comment by ericmj** [comment]
We should wait with implementing this on MongoDB until me and @michalmuskala have confirmed that it's an actual performance improvement. The mongo protocol allows us to have concurrent access to a single connection and the queries will be pipelined in the connection process unlike postgrex (and I think the other drivers) where queries are queued.

**Comment by fishcakez** [comment]
@ericmj sounds good, it is more important for the SQL adapters as they share the same pools/adapters and are more able to reap the benefits. I will try to find time next week to help out on a multi-checkout queue/pool (as we have discussed previously) on top of sbroker.

**Comment by josevalim** [comment]
Yes, let's hold on this for now while we continue experimenting with db_connection. Once we decide the role db_connection will play, we will reopen this and push adapters to use on it.
