### ISSUE TITLE
MySQL DDL transaction support?

### ISSUE THREAD

**Issue by bossyang** [elixir-lang/ecto#1097]
Ecto doesn't  persist data correctly when MySQL system variable __autocommit__ is OFF.

**Comment by josevalim** [comment]
We tried to provide this feature even with autocommit set to OFF and MySQL was still behaving unexpectedly under different versions when we wrapped DDL inside a transaction.

**Comment by bossyang** [comment]
2 years later, I found I had the wrong title. I have to set `autocommit=ON`. Ecto doesn't start a transaction automatically.
