### ISSUE TITLE
Support EXCLUDE constraint in changeset

### ISSUE THREAD

**Issue by bitgamma** [elixir-lang/ecto#1098]
I am using the EXCLUDE constraint in Postgres and currently there is no way to check for it using an Ecto Changeset. Adding this should be trivial (I do not know if other DB also support this) since Postgrex already maps this error with the error code :exclusion_violation.

I can tackle this issue myself, but I wanted to know if this is a desired addition. The function would have the following signature

```elixir
exclude_constraint(changeset, field, opts)
```

and behave just like the unique_constraint function.

Comments?

**Comment by josevalim** [comment]
While this is low in our list of priorities, if you implement it, we would definitely appreciate a pull request. :) So it is certainly welcome!
