### ISSUE TITLE
update_all combined with joins will update all rows

### ISSUE THREAD

**Issue by kimforsgren** [elixir-lang/ecto#1100]
I have been attempting to run an update_all on a fairly simple query with a single join.

The `Repo.all` gives me a result with the rows that I want (2 rows) to update on but if I run  `Repo.update_all` on the same query it updates all rows in the table (54 rows).

I have included the queries being generated.

```
query = from action_item in ActionItems,
join: action in assoc(action_item, :action),
where: action.parent_id == ^10

Repo.all(query)
Repo.update_all(query, set: [action_id: 11])

SELECT a0."id", a0."action_id", a0."item_id", a0."inserted_at", a0."updated_at" 
FROM "action_items" AS a0 
INNER JOIN "actions" AS a1 ON a1."id" = a0."action_id" 
WHERE (a1."parent_id" = $1) [10]

UPDATE "action_items" SET "action_id" = $1 
FROM "action_items" AS a0 
INNER JOIN "actions" AS a1 ON a1."id" = a0."action_id" 
WHERE (a1."parent_id" = $2) [11, 10]
```

**Comment by josevalim** [comment]
The generated queries look correct to me. What happens if you run them directly against the database?

**Comment by kimforsgren** [comment]
I got curious and tried to simulate the select and update query in a simpler environment to see if i made a misstake somewhere else in my code. I tried running the following snippet directly into postgres with version 9.4.4:
```
DROP TABLE IF EXISTS a;
DROP TABLE IF EXISTS b;

CREATE TABLE a (
    id serial primary key,
    value integer
);
CREATE TABLE b (
    id serial primary key,
    a_id integer NOT NULL,
    value BOOLEAN
);

INSERT INTO a (id, value) VALUES (1, 1);
INSERT INTO a (id, value) VALUES (2, 1);
INSERT INTO a (id, value) VALUES (3, 2);

INSERT INTO b (id, a_id, value) VALUES (1, 1, false);
INSERT INTO b (id, a_id, value) VALUES (2, 1, false);
INSERT INTO b (id, a_id, value) VALUES (3, 2, false);
INSERT INTO b (id, a_id, value) VALUES (4, 3, false);

SELECT table_b."id"
FROM "b" AS table_b 
INNER JOIN "a" AS table_a ON table_a."id" = table_b."a_id" 
WHERE (table_a."value" = 1);

UPDATE "b" SET "value" = true 
FROM "b" AS table_b 
INNER JOIN "a" AS table_a ON table_a."id" = table_b."a_id" 
WHERE (table_a."value" = 1);

SELECT COUNT(id) FROM b WHERE value = true;
```

The result for the first SELECT is:
![screen shot 2015-11-27 at 17 16 55](https://cloud.githubusercontent.com/assets/6968360/11445233/cca672a0-952a-11e5-83a4-9f6c4c6d72ce.png)

And for the second SELECT:
![screen shot 2015-11-27 at 17 19 47](https://cloud.githubusercontent.com/assets/6968360/11445267/222b38fa-952b-11e5-9ee8-0d83920789cb.png)

However, the value for id: 4 should still be false and I should get one row back from the second query.

**Comment by josevalim** [comment]
Ok, so the query we generate is definitely bogus. I think this is due to the from. Can you please try the following:

```sql
UPDATE "b" AS table_b SET "value" = true 
FROM "a" AS table_a
WHERE (table_a."id" = table_b."a_id") AND (table_a."value" = 1);
```

**Comment by kimforsgren** [comment]
Yes, that works for this example! Is it possible to nest more joins into this approach?

**Comment by josevalim** [comment]
Yes, it is. I will work on a fix for this, as it is a serious bug, and do a new release, thank you!

**Comment by josevalim** [comment]
Ecto v1.0.7 has been released. Thank you for the report and the help with debugging!
