### ISSUE TITLE
Allow belongs_to via changesets

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1102]
The main blocker for this feature in the past was how callbacks would work. Given callbacks are on the way out, this feature will be straight-forward to implement. It is pending on callbacks being effectively removed.

**Comment by josevalim** [comment]
We should also support `on_delete` for belongs_to once we add this.

**Comment by abitdodgy** [comment]
@josevalim if I understand you correctly, callbacks are getting deprecated? If so, why?

**Comment by josevalim** [comment]
This is now in master.

@paulcsmith, could you please check if, when using Ecto master, ExMachina no longer needs any of the Ecto code? For example, we support inserting the whole tree directly, like here:

https://github.com/elixir-lang/ecto/blob/6f1971f4120b84e1a441792feb77ba451c4fc783/integration_test/cases/repo.exs#L720-L743

**Comment by paulcsmith** [comment]
@josevalim This will be so awesome! I was able to remove all of the Ecto code and still have *almost* all the tests passing

It almost worked. These two tests failed when the association was `%Ecto.Association.NotLoaded{}`

https://github.com/thoughtbot/ex_machina/blob/4443b72b677387a09fbc6c1351b29c526a0ca061/test/ex_machina/ecto_has_many_test.exs#L120

https://github.com/thoughtbot/ex_machina/blob/4443b72b677387a09fbc6c1351b29c526a0ca061/test/ex_machina/ecto_test.exs#L142

Here's the stack trace:

```
** (FunctionClauseError) no function clause matching in Ecto.Changeset.Relation.do_empty/1
     stacktrace:
       (ecto) lib/ecto/changeset/relation.ex:24: Ecto.Changeset.Relation.do_empty(nil)
       (ecto) lib/ecto/repo/schema.ex:377: anonymous fn/4 in Ecto.Repo.Schema.surface_changes/4
       (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/repo/schema.ex:366: Ecto.Repo.Schema.surface_changes/4
       (ecto) lib/ecto/repo/schema.ex:128: Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:76: Ecto.Repo.Schema.insert!/4
       test/ex_machina/ecto_test.exs:141
```

I'll pull the latest Ecto and see if it's a problem in Ecto or in ExMachina and Ecto together. I'll open a PR if there's a problem in Ecto

**Comment by paulcsmith** [comment]
@josevalim So Ecto is fine, it fails if you explicitly set an `Ecto.Association.NotLoaded` without a cardinality. So Just need to update the tests in ExMachina. Ecto side looks great :+1:

**Comment by josevalim** [comment]
That's so awesome, I am so excited! :D
