### ISSUE TITLE
mix optional dep requirement clashing with only

### ISSUE THREAD

**Issue by bcardarella** [elixir-lang/ecto#1110]
In my library, ecto_fixtures I am setting `postgrex` to be a test env only dep: https://github.com/dockyard/ecto_fixtures/blob/e0cf50ed3fde682fb5e90f9ab480978b1ca6b325/mix.exs#L46

but with Elixir 1.1 I get the following error:

```
Unchecked dependencies for environment test:
* postgrex (Hex package)
  the dependency postgrex

  > In mix.exs:
    {:postgrex, "> 0.0.0", [hex: :postgrex, only: :test]}

  does not match the environments calculated for

  > In deps/ecto/mix.exs:
    {:postgrex, "~> 0.9.1", [optional: true, hex: :postgrex]}

  Remove the :only restriction from your dep
** (Mix) Can't continue due to errors on dependencies
```

I've confirmed that this does not exist on Elixir 1.0.x

**Comment by josevalim** [comment]
Moved to Elixir.

**Comment by bcardarella** [comment]
whoops, sorry long night :frowning:
