### ISSUE TITLE
Documentation for Ecto.Schema read_after_writes incorrect?

### ISSUE THREAD

**Issue by brightbits** [elixir-lang/ecto#1111]
The documentation on https://hexdocs.pm/ecto/Ecto.Schema.html states:

`:read_after_writes` - When true, the field only sent on insert if not nil and always read back from the repository during inserts and updates.

From our testing, it appears the first part of this explanation is not correct. It still sends the value `nil` along to the database when inserting. The second part (reading it back) works as described.

Thanks

**Comment by josevalim** [comment]
The docs are outdated. It means it will read the fields every time there is an insert or update. However, Ecto will always send all fields by default. The work around so far is to provide a before_insert/before_update callback that will call delete_change on the field you don't want to be sent. I will fix the docs on master, thank you! :)

**Comment by sorentwo** [comment]
@josevalim What is the proposed solution to this considering callbacks are being phased out?

**Comment by michalmuskala** [comment]
We will definitely address this issue, but the solution is not yet fully realized.

**Comment by divmgl** [comment]
+1, need a way to be able to insert models where default values are provided by the database but not by `Ecto.Schema`. `before_insert` macro is currently working for me. `:read_after_writes` and `:virtual` don't match my use case. maybe a `:omit_insert` keyword is needed?

**Comment by michalmuskala** [comment]
AFAIK Ecto 2.0 won't send default `nil` values to the database on insert - this should solve the issue.

**Comment by divmgl** [comment]
@michalmuskala thanks for the clarification
