### ISSUE TITLE
Virtual fields are dropped in changeset params

### ISSUE THREAD

**Issue by mgwidmann** [elixir-lang/ecto#1121]
See mailing list topic: https://groups.google.com/forum/#!topic/elixir-ecto/SlFSfkfB03k

**Comment by tony612** [comment]
Can you provide your `User.changeset` code? Did you forget to add `temp` to `required` or `optional` params?
Because there's a test for this case, I move the `temp` to `optional` params, it still works. But the field will be dropped if I remove `temp`

**Comment by mgwidmann** [comment]
:+1: my mistake, you're right. Thats exactly what I was doing wrong, thanks!
