### ISSUE TITLE
Add First and Last to Repo

### ISSUE THREAD

**Issue by victorlcampos** [elixir-lang/ecto#1124]
Hi,
On Rails we Have Model.first and Model.last methods to return first and last model object respectively.
It would be nice if I could do: Model |> Repo.first and Model |> Repo.last to the same thing.

I could implement that and send a pull request if you agree.

**Comment by victorlcampos** [comment]
I posted at mailing list, sry to create unnecessary issue

**Comment by syndbg** [comment]
@victorlcampos What was the answer?

**Comment by michalmuskala** [comment]
If you need them, you can add them in your repo module. They were considered before 2.0 was released, but ultimately deemed confusing and proving less features than what we have right now. 

There are `Ecto.Query.first/2` and `Ecto.Query.last/2` functions, though for building this kind of queries. When imported, they can be used as:
```elixir
Repo.one(first(Post))
```
