### ISSUE TITLE
Remove after_connect and log as repository "callbacks"

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1126]

**Comment by tony612** [comment]
It's a commit to remove after_connect https://github.com/tony612/ecto/commit/fdde818bc3028e2e82ee0fe96a41f2c05a98f6ec .
But I'm not clear about *log as repository "callbacks"*, does it mean keeping the after_connect but just use `IO.write :stderr` to show warning?

**Comment by josevalim** [comment]
Don't worry about `after_connect` for now because things will change once we adopt db_connection. Regarding log, it means we will no longer call a `log` function but we will allow folks to specify `loggers: [...]` in the repo configuration and we will call the ecto_query function on it passing the log entry.

**Comment by tony612** [comment]
@josevalim I'm trying to removing the log callback, then I met a strange error when I try to iterate loggers. I can reproduce the error with a simple snippet:
```elixir
defmodule Foo do
  require Logger

  def log(msg) do
    loggers = [Logger]
    Logger.debug(msg)
    for logger <- loggers do
      IO.inspect to_string(logger)
      logger.debug(msg)
    end
  end
end

iex(2)> Foo.log("bar")
"Elixir.Logger"

19:07:59.337 [debug] bar
** (UndefinedFunctionError) undefined function Logger.debug/1
    (logger) Logger.debug("bar")
             iex:9: anonymous fn/3 in Foo.log/1
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
             iex:7: Foo.log/1
```
I have no idea what's happening. Is it a bug in Elixir or my wrong usage ?

**Comment by josevalim** [comment]
`debug` is a macro, you can't call it dynamically. Please hold on though on this feature, I would like to move to db_connection before we start changing those callbacks (as after_connect relies on db_connection in the first place).

**Comment by tony612** [comment]
:ok_hand:

**Comment by fishcakez** [comment]
The db_connection changes for this are now in, I'm not sure what's required for this now though.

**Comment by josevalim** [comment]
We just need to stop exposing log I the repository in favor of MFAs, like
in after_connect.

On Saturday, January 9, 2016, James Fish <notifications@github.com> wrote:

> The db_connection changes for this are now in, I'm not sure what's
> required for this now though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1126#issuecomment-170252476>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
