### ISSUE TITLE
No response on mix ecto.migrate

### ISSUE THREAD

**Issue by sachinbhutani** [elixir-lang/ecto#1130]
Running mix task ecto.migrate gives no response 
ecto.create was executed successfully. 
OSX  El capitan 
Phoenix v1.0.0
Ecto v1.0.7
Elixir v1.1.1
MySQL v5.7.9

contents of the only migration file in priv/repo/migration folder
````
defmodule Rumbl.Repo.Migrations.CreateUser do
  use Ecto.Migration
  def change do
    create table(:users) do
      add :name, :string
      add :username, :string, null: false
      add :password_hash, :string
      timestamps
    end
    create unique_index(:users, [:username])
  end
end

**Comment by josevalim** [comment]
This is a MySQL bug. You can workaround it by adding the following to your mix.exs:

    {:mariaex, "~> 0.6.1", override: true}

**Comment by sachinbhutani** [comment]
thanks, it worked.
