### ISSUE TITLE
Improve error messages when Ecto.Query.from is not imported

### ISSUE THREAD

**Issue by stevedomin** [elixir-lang/ecto#1136]
I ran into the issue where I didn't import the `from/2` function from `Ecto.Query` and compilation was failing on queries with interpolated expressions as a result.

Here's was my initial query:

```
Repo.one(from u in User,
                 where: u.username == ^email_or_username or u.email == ^email_or_username,
                 limit: 1)
```

And the error I was getting:

```
== Compilation error on file web/plugs/auth.ex ==
** (CompileError) web/plugs/auth.ex:31: cannot use ^email_or_username outside of match clauses
    (elixir) expanding macro: Kernel.or/2
    web/plugs/auth.ex:31: Rumbl.login_with_password/4
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

Then I replaced my interpolated variable with a string and I got this error:

```
== Compilation error on file web/plugs/auth.ex ==
** (CompileError) web/plugs/auth.ex:30: function from/2 undefined
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

This obviously solved my initial problem. It didn't take me too long to figure it out but still I'm wondering if we can make the experience nicer I imagine this must happen quite frequently. If you think there is a way I'm happy to dig into it.

**Comment by josevalim** [comment]
There is nothing we can do. Because there is no macro, the compiler will try to expand everything as usual, running into invalid expressions.

**Comment by stevedomin** [comment]
It makes sense, thanks for the explanation @josevalim
