### ISSUE TITLE
Dynamically select/restrict fields in a query

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1145]
The issue we are trying to address is that it is impossible to restrict which fields are being returned in a query, both dynamically and statically. For example, imagine you have the following query:

```elixir
from p in Post, where: p.published, select: p
```

However we don't want to fetch all of `p`, only some specific fields. It is not possible to do so today. The aim of this issue is to discuss possible solutions that allows fields to be restricted both statically and dynamically.

## 1. Using {...} syntax

One possible solution is to allow the fields to be specified using `{...}`:

```elixir
from p in Post, where: p.published, select: p.{name, title, published_at}
```

Dynamically those fields could be interpolated as a list of atoms:

```elixir
only = [:name, :title, :published_at]
from p in Post, where: p.published, select: p.{^only}
```

The limitation of this approach is when we consider the preloads syntax. For example:

```elixir
from p in Post, join: c in assoc(p, :comments), preload: [comments: c]
```

If we want to limit the fields returned by `c`, how to achieve so both statically and dynamically? We have a couple options. One is to allow such directly inside preload, albeit it composes poorly as it requires the fields to be specified alongside the preload:

```elixir
from p in Post, join: c in assoc(p, :comments), preload: [comments: c.{body}]
```

Another option is to specify as a nesting from select, statically:

```elixir
from p in Post, join: c in assoc(p, :comments), preload: [comments: c], select: p.{name, title, published_at, comments.{body}}
```

Such syntax can be used also for filtering the fields from preloads. Dynamically, it looks more elegant:

```elixir
only = [:name, :title, :published_at, comments: :body]
from p in Post, join: c in assoc(p, :comments), preload: [comments: c], select: p.{^only}
```

## 2. Using a function

Instead of using `{}`, we could introduce a function called `take`. Statically:

```elixir
from p in Post, where: p.published, select: take(p, [:name, :title, :published_at])
```

Dynamically:

```elixir
only = [:name, :title, :published_at]
from p in Post, where: p.published, select: take(p, ^only)
```

Statically with joins:

```elixir
from p in Post, join: c in assoc(p, :comments), select: take(p, [:name, :title, :published_at, comments: :body])
```

Dynamically with joins:

```elixir
only = [:name, :title, :published_at, comments: :body]
from p in Post, join: c in assoc(p, :comments), select: take(p, ^only)
```

The benefit of `take` is that we can make the static and dynamic syntaxes much closer.

## 3. Using restrict

Another option is to introduce a new macro called restrict with the purpose of restricting fields. Statically:

```elixir
from p in Post, where: p.published, restrict: [p: [:name, :title, :published_at]]
```

Dynamically:

```elixir
only = [:name, :title, :published_at]
from p in Post, where: p.published, restrict: [p: ^only]
```

Statically with joins:

```elixir
from p in Post, join: c in assoc(p, :comments), restrict: [p: [:name, :title, :published_at, comments: :body]]
```

Dynamically with joins:

```elixir
only = [:name, :title, :published_at, comments: :body]
from p in Post, join: c in assoc(p, :comments), restrict: [p: ^only]
```

`restrict` is similar to the function approach, except it is orthogonal, allowing you to choose how fields are filtered apart from how they are structured.

Thoughts?

/cc @drewolson @jeregrine @chrismccord @ericmj @michalmuskala

**Comment by jeregrine** [comment]
I like option 1 probably the most because it uses select as you'd expect. 

Of the preload options I don't have a strong opinion. I don't often join and then preload, I more often find myself using it either as Repo.preload or as plain preload in the query like so.

```elixir
from(p in Posts, where: p.published_at) # Simple example, more often scoped and then passed to preload at the end before rendering. 
|> Repo.preload([comments: [:author], :images])
```

In this case I'm not sure I'd expect to be able to select specific fields based on the above suggestions. I would like to, but I'm not sure we can do it in this style without reference to a table. I know the JSONAPI query builder I'm working on would *love* to be able to do this though.

**Comment by drewolson** [comment]
I actually prefer 2 or 3, with my gut saying 2 is best. It seems simple at easy to understand. Perhaps `pluck` is a better name?

**Comment by jeregrine** [comment]
@drewolson yea option 2 isn't bad either.

**Comment by lexmag** [comment]
:+1: for __2__ and `take` as the function name.

**Comment by mitchellhenke** [comment]
I like 1 and 2 partly because it still feels like this functionality should be apart of a `select`

**Comment by parkerl** [comment]
:+1: for 2

It seems to have the cleanest syntax.

**Comment by sorentwo** [comment]
:+1: for 2, with 1 as the second vote, and not at all in favor of 3.

**Comment by michalmuskala** [comment]
What we should consider is not only preload. We could reuse the same syntax for restricting fields from maps or embedded models.

The syntax I like the most is 2, because it seems to me it's the least "magic" one.

**Comment by josevalim** [comment]
In master.

**Comment by turboladen** [comment]
Could someone be so kind as to point me in the direction as to how this got implemented? I'm coming from the Rails world, looking for something analogous to AR's `pluck`, ended up here... this looks like what I'm looking for, but I've tried the proposals and they didn't seem to work for me. I just updated to phoenix 1.2.0 & phoenix_ecto 3.0.0. Thanks!

**Comment by josevalim** [comment]
We have implemented 2 but we called it `map/2` and `struct/2`. See the docs here: https://hexdocs.pm/ecto/Ecto.Query.API.html#map/2

Let us know if you have more questions!

**Comment by turboladen** [comment]
Ahh, I think I may have come across some SO examples of that, @josevalim, but my brain thought they were using `Enum` functions instead of doing things in SQL. Thank you!

**Comment by josevalim** [comment]
If it helps, when you are inside the query, it is always the query DSL unless you call `^`.

**Comment by turboladen** [comment]
That is helpful, thanks @josevalim.

**Comment by rockwood** [comment]
With this solution, is there a way to omit specific fields instead of selecting? 

I have a schema with a `field :meta, :map` that's not necessary in most cases. Instead of selecting every field but `:meta`, I'd rather do something like `from t in Thing, omit: [:meta]`. Is something like that possible?

**Comment by josevalim** [comment]
@rockwood not right now, no.

**Comment by rockwood** [comment]
No worries @josevalim. I might take a crack at if you don't mind.

**Comment by josevalim** [comment]
@rockwood that would be great. We would need a proposal before the implementation though, I wouldn't like to introduce `:omit` because it is something very specific to `:select`. So we need an option in there, similar to how we have `struct(p, ....)`. Maybe `select: drop(p, [:meta])`.

**Comment by rockwood** [comment]
@josevalim Got it. I'll try to put a proposal together soon.

**Comment by skosch** [comment]
@rockwood any news on this front? :-)

**Comment by rockwood** [comment]
@skosch I opened a [discussion thread](https://groups.google.com/forum/#!topic/elixir-ecto/9lCaPISWebg). There's some potential confusion around returning maps vs structs, so I'm not sure it's worth implementing at this point. What's your opinion?

**Comment by skosch** [comment]
Oh, cool. I have no strong opinion on what to name things, I just keep running into situations where this functionality would be useful, so I was curious.

**Comment by rockwood** [comment]
Got it. I'll try restarting the discussion and see if it goes anywhere. Thanks!

**Comment by joaomdmoura** [comment]
I see this is live as a `map/2` in `Ecto.Query.API` but do we have a syntax sugar for drop specific fields already? Is this still wanted? I could help tackle it, currently in need on another open source project 😅  cc @rockwood @josevalim
