### ISSUE TITLE
Error when running a migration on ecto&phoenix 1.1

### ISSUE THREAD

**Issue by gabrielgatu** [elixir-lang/ecto#1147]
I ran into the issue after updating phoenix to 1.1 according to: [upgrade phoenix to 1.1](https://gist.github.com/chrismccord/557ef22e2a03a7992624).

Created a migration using `mix phoenix.gen.model`:

`(mix phoenix.gen.model Request requests path:string country:string browser:string os:string date:datetime duration:integer query:string method:string remote_ip:string api_key:string)`

```
defmodule Youremind.Repo.Migrations.CreateRequest do
  use Ecto.Migration

  def change do
    create table(:requests) do
      add :path, :string
      add :country, :string
      add :browser, :string
      add :os, :string
      add :date, :datetime
      add :duration, :integer
      add :query, :string
      add :method, :string
      add :remote_ip, :string
      add :api_key, :string
    end

  end
end
```

Only removed the timestamps from the migration. The running with: `mix ecto.migrate` gives me this error: 

```
youremind git:(master) ✗ mix ecto.migrate

12:49:22.175 [info]  == Running Youremind.Repo.Migrations.CreateRequest.change/0 forward

12:49:22.175 [info]  create table requests

12:49:22.184 [info]  == Migrated in 0.0s
** (FunctionClauseError) no function clause matching in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/repo/schema.ex:55: Ecto.Repo.Schema.do_insert(Youremind.Repo, Ecto.Adapters.Postgres, %{__struct__: Ecto.Changeset, action: nil, changes: %{}, constraints: [], errors: [], filters: %{}, model: %Ecto.Migration.SchemaMigration{__meta__: #Ecto.Schema.Metadata<:built>, inserted_at: nil, version: 20151217103137}, optional: [], opts: [], params: nil, repo: nil, required: [], types: %{inserted_at: Ecto.DateTime, version: :integer}, valid?: true, validations: []}, [timeout: :infinity, log: false])
    (ecto) lib/ecto/repo/schema.ex:14: Ecto.Repo.Schema.insert!/4
    (ecto) lib/ecto/pool.ex:292: Ecto.Pool.with_rollback/3
    (ecto) lib/ecto/adapters/sql.ex:582: Ecto.Adapters.SQL.transaction/8
    (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6
    (ecto) lib/ecto/adapters/sql.ex:551: Ecto.Adapters.SQL.transaction/3
    (ecto) lib/ecto/migrator.ex:226: anonymous fn/4 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:63: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:579: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:579: Enum.each/2
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

I've tried to recompile everything with `mix compile`, even tried: `mix deps.compile`, `mix deps.get`, `mix deps.update` but still nothing.
For more informations, here's the `mix.lock` file with all the versions:

```
%{"comeonin": {:hex, :comeonin, "1.6.0"},
  "connection": {:hex, :connection, "1.0.2"},
  "cowboy": {:hex, :cowboy, "1.0.4"},
  "cowlib": {:hex, :cowlib, "1.0.2"},
  "decimal": {:hex, :decimal, "1.1.0"},
  "ecto": {:hex, :ecto, "1.1.0"},
  "fs": {:hex, :fs, "0.9.2"},
  "phoenix": {:hex, :phoenix, "1.1.0"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "2.0.0"},
  "phoenix_html": {:hex, :phoenix_html, "2.3.0"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.0.1"},
  "plug": {:hex, :plug, "1.0.3"},
  "poison": {:hex, :poison, "1.5.0"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "postgrex": {:hex, :postgrex, "0.10.0"},
  "ranch": {:hex, :ranch, "1.2.0"}}
```

**Comment by josevalim** [comment]
Which Elixir version? Can you please try running "rm -rf _build" and let us
know if it fixes the problem?

On Thursday, December 17, 2015, Gabriel Gatu <notifications@github.com>
wrote:

> I ran into the issue after updating phoenix to 11 according to: upgrade
> phoenix to 11 <https://gistgithubcom/chrismccord/557ef22e2a03a7992624>
>
> Created a migration using mix phoenixgenmodel:
>
> (mix phoenixgenmodel Request requests path:string country:string
> browser:string os:string date:datetime duration:integer query:string
> method:string remote_ip:string api_key:string)
>
> defmodule YouremindRepoMigrationsCreateRequest do
>   use EctoMigration
>
>   def change do
>     create table(:requests) do
>       add :path, :string
>       add :country, :string
>       add :browser, :string
>       add :os, :string
>       add :date, :datetime
>       add :duration, :integer
>       add :query, :string
>       add :method, :string
>       add :remote_ip, :string
>       add :api_key, :string
>     end
>
>   end
> end
>
> Only removed the timestamps from the migration The running with: mix
> ectomigrate gives me this error:
>
> youremind git:(master) ✗ mix ectomigrate
>
> 12:49:22175 [info]  == Running YouremindRepoMigrationsCreateRequestchange/0 forward
>
> 12:49:22175 [info]  create table requests
>
> 12:49:22184 [info]  == Migrated in 00s
> ** (FunctionClauseError) no function clause matching in EctoRepoSchemado_insert/4
>     (ecto) lib/ecto/repo/schemaex:55: EctoRepoSchemado_insert(YouremindRepo, EctoAdaptersPostgres, %{__struct__: EctoChangeset, action: nil, changes: %{}, constraints: [], errors: [], filters: %{}, model: %EctoMigrationSchemaMigration{__meta__: #EctoSchemaMetadata<:built>, inserted_at: nil, version: 20151217103137}, optional: [], opts: [], params: nil, repo: nil, required: [], types: %{inserted_at: EctoDateTime, version: :integer}, valid?: true, validations: []}, [timeout: :infinity, log: false])
>     (ecto) lib/ecto/repo/schemaex:14: EctoRepoSchemainsert!/4
>     (ecto) lib/ecto/poolex:292: EctoPoolwith_rollback/3
>     (ecto) lib/ecto/adapters/sqlex:582: EctoAdaptersSQLtransaction/8
>     (ecto) lib/ecto/poolex:244: EctoPoolouter_transaction/6
>     (ecto) lib/ecto/adapters/sqlex:551: EctoAdaptersSQLtransaction/3
>     (ecto) lib/ecto/migratorex:226: anonymous fn/4 in EctoMigratormigrate/4
>     (elixir) lib/enumex:1043: anonymous fn/3 in Enummap/2
>     (elixir) lib/enumex:1387: Enum"-reduce/3-lists^foldl/2-0-"/3
>     (elixir) lib/enumex:1043: Enummap/2
>     (ecto) lib/mix/tasks/ectomigrateex:63: anonymous fn/4 in MixTasksEctoMigraterun/2
>     (elixir) lib/enumex:579: Enum"-each/2-lists^foreach/1-0-"/2
>     (elixir) lib/enumex:579: Enumeach/2
>     (mix) lib/mix/cliex:55: MixCLIrun_task/2
>     (elixir) lib/codeex:363: Coderequire_file/2
>
> I've tried to recompile everything with mix compile, even tried: mix
> depscompile, mix depsget, mix depsupdate but still nothing
> For more informations, here's the mixlock file with all the versions:
>
> %{"comeonin": {:hex, :comeonin, "160"},
>   "connection": {:hex, :connection, "102"},
>   "cowboy": {:hex, :cowboy, "104"},
>   "cowlib": {:hex, :cowlib, "102"},
>   "decimal": {:hex, :decimal, "110"},
>   "ecto": {:hex, :ecto, "110"},
>   "fs": {:hex, :fs, "092"},
>   "phoenix": {:hex, :phoenix, "110"},
>   "phoenix_ecto": {:hex, :phoenix_ecto, "200"},
>   "phoenix_html": {:hex, :phoenix_html, "230"},
>   "phoenix_live_reload": {:hex, :phoenix_live_reload, "101"},
>   "plug": {:hex, :plug, "103"},
>   "poison": {:hex, :poison, "150"},
>   "poolboy": {:hex, :poolboy, "151"},
>   "postgrex": {:hex, :postgrex, "0100"},
>   "ranch": {:hex, :ranch, "120"}}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1147>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by gabrielgatu** [comment]
Always the best! Indeed it fixes the problem.

**Comment by josevalim** [comment]
This was not supposed to happen though. Can you let us know your elixir
version? :) meanwhile, can you please close this too? :)

On Thursday, December 17, 2015, Gabriel Gatu <notifications@github.com>
wrote:

> Always the best! Indeed it fixes the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1147#issuecomment-165435630>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by gabrielgatu** [comment]
Currently using:

- Elixir 1.1.1
- Erlang/OTP 18 [erts-7.1] [source] [64-bit]

**Comment by josevalim** [comment]
Thank you, I will investigate.

On Thursday, December 17, 2015, Gabriel Gatu <notifications@github.com>
wrote:

> Currently using:
>
>    - Elixir 1.1.1
>    - Erlang/OTP 18 [erts-7.1] [source] [64-bit]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1147#issuecomment-165436960>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by gabrielgatu** [comment]
Glad to help! Cheers from Turin :)

**Comment by parkerl** [comment]
@gabrielgatu Glad @josevalim was able to help. I told you it was above my pay grade ;-) .

@josevalim I was helping troubleshoot this and ran across this comment: 

https://github.com/elixir-lang/ecto/blob/v1.1/lib/ecto/changeset.ex#L250

It does not look like everything there is handled here:

https://github.com/elixir-lang/ecto/blob/v1.1/lib/ecto/changeset.ex#L671

Is there a separate issue there?

**Comment by matthewlehner** [comment]
I also had the same issue with this, upgrading to Phoenix 1.1.

```
** (FunctionClauseError) no function clause matching in Ecto.Repo.Schema.do_insert/4
```

I'm running:
```
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.2.0
```

removing the `_build` directory solved it though I had recompiled prior to this.
```
** (FunctionClauseError) no function clause matching in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/repo/schema.ex:55: Ecto.Repo.Schema.do_insert(Matrimony.Repo, Ecto.Adapters.Postgres, %{__struct__: Ecto.Changeset, action: nil, changes: %{}, constraints: [], errors: [], filters: %{}
, model: %Ecto.Migration.SchemaMigration{__meta__: #Ecto.Schema.Metadata<:built>, inserted_at: nil, version: 20160103213522}, optional: [], opts: [], params: nil, repo: nil, required: [], types: %{inserte
d_at: Ecto.DateTime, version: :integer}, valid?: true, validations: []}, [timeout: :infinity, log: false])
    (ecto) lib/ecto/repo/schema.ex:14: Ecto.Repo.Schema.insert!/4
    (ecto) lib/ecto/pool.ex:292: Ecto.Pool.with_rollback/3
    (ecto) lib/ecto/adapters/sql.ex:582: Ecto.Adapters.SQL.transaction/8
    (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6
    (ecto) lib/ecto/adapters/sql.ex:551: Ecto.Adapters.SQL.transaction/3
    (ecto) lib/ecto/migrator.ex:226: anonymous fn/4 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:63: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

**Comment by hdcos** [comment]
same here, elixir 1.2, mariaex version 6.2
```
22:45:11.873 [info]  create table worships

22:45:11.943 [info]  == Migrated in 0.6s
** (FunctionClauseError) no function clause matching in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/repo/schema.ex:55: Ecto.Repo.Schema.do_insert(AdVitam.Repo, Ecto.Adapters.MySQL, %{__struct__: Ecto.Changeset, action: nil, changes: %{}, constraints: [], errors: [], filters: %{}, model: %Ecto.Migration.SchemaMigration{__meta__: #Ecto.Schema.Metadata<:built>, inserted_at: nil, version: 20160115212938}, optional: [], opts: [], params: nil, repo: nil, required: [], types: %{inserted_at: Ecto.DateTime, version: :integer}, valid?: true, validations: []}, [timeout: :infinity, log: false])
    (ecto) lib/ecto/repo/schema.ex:14: Ecto.Repo.Schema.insert!/4
    (ecto) lib/ecto/migrator.ex:226: anonymous fn/4 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:63: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```
