### ISSUE TITLE
mix ecto.migrate failed

### ISSUE THREAD

**Issue by dylancogini** [elixir-lang/ecto#1150]
I have updated ecto 1.1 which using postgrex 0.10,
postgrex 0.10 has problem with migration,

This is the message:
** (EXIT from #PID<0.48.0>) shutdown: failed to start child: Ecto.Adapters.Postgres
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:postgrex, {'no such file or directory', 'postgrex.app'}}}
            (ecto) lib/ecto/adapters/postgres.ex:56: Ecto.Adapters.Postgres.start_link/2
            (stdlib) supervisor.erl:343: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:326: :supervisor.start_children/3
            (stdlib) supervisor.erl:292: :supervisor.init_children/2
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

**Comment by simonh1000** [comment]
how did you solve this?

**Comment by kexoth** [comment]
@simonh1000 I encountered when migrating my app on Postgres.
My reason for this was that I haven't included `postgrex` both as a dependency & as an application in `mix.exs`.
