### ISSUE TITLE
Add an easy way to change validation errors

### ISSUE THREAD

**Issue by VladShcherbin** [elixir-lang/ecto#1158]
There are some closed issues, but we really need an easy way, how to change the errors. Traversing is not a good option. We definitely need something better, this is a very common task.

**Comment by josevalim** [comment]
I would like to know while traversing is not enough, as it works perfectly with gettext. Can you please give more information?

**Comment by VladShcherbin** [comment]
@josevalim actually, I just need to rewrite the error messages, I don't need to translate to any other languages.

Except traversing, the only option is gettext? Maybe there is a tutorial / repo / gist on how to do this?

**Comment by josevalim** [comment]
@VladShcherbin most of the helpers accept a `:message` thing. The only ones that can be configured are "is invalid" and "can't be blank" which you can easily match on traverse_errors.

    Ecto.Changeset.traverse_errors changeset, fn "can't be blank" -> "must not be blank"; x -> x end

**Comment by VladShcherbin** [comment]
@josevalim so, I still need to traverse the errors.. I'm using React and send validation errors via websocket. So, currently, I need to traverse all the errors with `string.replace` to insert values into the error message ([like this one](http://www.thisisnotajoke.com/blog/2015/09/serializing-ecto-changeset-errors-to-jsonapi-in-elixir.html)). Plus, I will need to change the message.

Don't you think, it is a bit hard to do this things (they are common for many apps)? I used Laravel and Meteor, handling errors is much easier there (via configs).

Maybe we can also have something more simple? Like an array of default errors and a way to change this array? Plus, a standard method to convert errors to json format so we don't need to reinvent and google the method for it?

**Comment by josevalim** [comment]
@VladShcherbin Right. We know it is a bit painful but that's because we decided to keep things simple in Ecto for others to build on top. The only way to build those things so it works in multiple languages is by keeping strings and parameters apart.

Phoenix v1.1 has finally closed this gap by providing I18n. You now do have a list of all error messages, you can simply change the `errors.po` for english. The performance cost is very low: http://sevenseacat.net/2015/12/20/i18n-in-phoenix-apps.html

**Comment by VladShcherbin** [comment]
@josevalim great, thank you! I'll switch to this solution then.

So, probably my issue is that it's little hard to find this solution, a line in the docs somewhere would be great ;)

**Comment by josevalim** [comment]
Thanks for the feedback, @VladShcherbin. To clarify, we were aware it was an issue and we are trying to improve it now, so we will keep an eye open to more complaints such as yours (which btw we love) and improve accordingly.

**Comment by VladShcherbin** [comment]
@josevalim yes, I've updated to 1.1, but skipped the gettext part as I thought it is only for internalisation. Now, you opened my eyes. I really hope, I am not too annoying with my questions and issues as I'm still a newcomer. 

Thank you for your awesome work, I really-really love it!
