### ISSUE TITLE
Get validation pluralization right by default?

### ISSUE THREAD

**Issue by henrik** [elixir-lang/ecto#1164]
I noticed in https://github.com/rrrene/elixirstatus-web/pull/31/files#diff-a7ff7e3b7047e2bbdc4c9c51a61f908aR40 that the default translations seem to say things like "should be %{count} character(s)".

To my eyes, "%{count} foo(s)" makes a site look a bit sloppy, so I'd love for us to pluralize it properly by default. But I wanted to request comments before I look into changing the code, since there could be good reasons to leave it.

cc @whatyouhide

**Comment by michalmuskala** [comment]
You can very easily plug in gettext to do the real translation and pluralization (like it's done in phoenix), so I'm not sure it's really worth it building some parallel solution in ecto itself.

**Comment by henrik** [comment]
My thinking was that it would be nice for the default gettext extraction to get it right, but I guess that could be difficult to achieve if Ecto owns the default strings but also doesn't know about pluralisation.

I do agree it doesn't seem worthwhile to implement parallel pluralisation.

I wonder if it could make sense for phoenix_ecto to provide pluralised default values for gettext. Haven't dug into the code.

It's not unreasonable to leave the "foo(s)" defaults, either if there's no good way around it. I just don't love the idea of everyone getting defaults that look bad (to me).

**Comment by josevalim** [comment]
Phoenix v1.1 already solves this. It ships with the proper pluralization tools out of the box. :)

**Comment by josevalim** [comment]
In fact, we should probably change Phoenix to translate those by default here: https://github.com/phoenixframework/phoenix/blob/master/installer/templates/new/priv/gettext/en/LC_MESSAGES/errors.po#L44-L73

**Comment by henrik** [comment]
Yes, that's what I was going for: default translation pluralisations for these so the default isn't the inelegant "foo(s)" :)

Not sure of the status of this since the ticket was closed.
