### ISSUE TITLE
Support many_to_many

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1169]
The main API will be:

    schema "posts" do
      many_to_many :tags, MyApp.Tag
    end

For many to many to work, we need to use a join table. We could inflect it by default (yes or no?) but we must support it being given as option. One option is to use the same option as `has_many :through`:

    many_to_many :tags, MyApp.Tag, through: "posts_tags"

There are a couple issues with using `through`:

  1. The `through` option in `has_many :through` sets the association to read-only mode (i.e. you can't do changes via changesets), which `many_to_many` won't be
  2. The `through` option in `many_to_many` expects a single value, for `has_many` it expects a list

Therefore, I would like to use another option besides `:through`. One of such option could be `:join_table`, which I personally don't like because in the future we will also allow schemas to be given, for example:

    many_to_many :tags, MyApp.Tag, through: MyApp.PostTag

Any candidate besides `:through`?

**Comment by tony612** [comment]
How about `:via` ? I'm not a native English speaker, but I just think of this word

**Comment by josevalim** [comment]
Thanks @tony612! I thought about `:via` but I thought it was too close to `:through` so it could be confusing. :(

**Comment by sorentwo** [comment]
In Latin `via` translates to `by way of`, so `via` seems like a very natural fit to me.

**Comment by NilsLattek** [comment]
I would still prefer using `:through` even with the two small issues. As a new user I think I would intentionally try to use `:through` for `many_to_many` if I already know it from `has_many`. If it is named differently it could be confusing and it can become one of these things you always have to look up.

**Comment by michalmuskala** [comment]
Maybe `:join_through` - this would be similar to `:through`, yet different because it accepts different format.

**Comment by josevalim** [comment]
:+1: for `:join_through`.

**Comment by cseeger** [comment]
Makes sense to me.

**Comment by abitdodgy** [comment]
I would probably try to use `:through` out of instinct. I think familiarity should trump those two minor issues. I vote for `:through`.

**Comment by jerodsanto** [comment]
:+1: for `:join_through`. Similar language, but distinct enough for people to realize the use may be (and indeed, is) different than `has_many`'s `:through` option.

**Comment by josevalim** [comment]
Closing in favor of the PR, #1177.
