### ISSUE TITLE
Issue with cast_assoc(:socials, required: true)

### ISSUE THREAD

**Issue by mrkaspa** [elixir-lang/ecto#1170]
I'm trying to validate a association as required

```elixir
defmodule CheersApi.User do
  use CheersApi.Web, :model
  use Arc.Ecto.Model

  schema "users" do
    field :email, :string
    field :name, :string
    field :bio, :string
    field :gender, :string
    field :friends_count, :integer
    field :avatar, CheersApi.Avatar.Type

    has_many :socials, CheersApi.Social

    timestamps
  end

  @required_fields ~w(name)
  @optional_fields ~w(email bio gender friends_count)
  @required_file_fields ~w()
  @optional_file_fields ~w(avatar)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> cast_assoc(:socials, required: true)
    |> cast_attachments(params, @required_file_fields, @optional_file_fields)
  end
end

```

**Comment by mrkaspa** [comment]
I think the problem is when the key is not present

**Comment by mrkaspa** [comment]
I've solved it in this PR https://github.com/elixir-lang/ecto/pull/1171

**Comment by josevalim** [comment]
The issue is that today we check for nil but we need to use this function to check for required: https://github.com/elixir-lang/ecto/blob/master/lib/ecto/changeset/relation.ex#L35-L38 (due to empty lists and not loaded entries). We also need a test. :)

**Comment by mrkaspa** [comment]
@josevalim How should I invoke that function? when the key is not present the code goes this way https://github.com/elixir-lang/ecto/blob/master/lib/ecto/changeset.ex#L510 , should I use the empty? method here https://github.com/elixir-lang/ecto/blob/master/lib/ecto/changeset.ex#L516 ?

**Comment by josevalim** [comment]
Yes, use empty? instead of is_nil.

**Comment by mrkaspa** [comment]
@josevalim This is the new PR for this https://github.com/elixir-lang/ecto/pull/1175

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
