### ISSUE TITLE
Error running migrations when using Mongo

### ISSUE THREAD

**Issue by danschultz** [elixir-lang/ecto#1172]
I'm not quite sure if this is the correct project to file this issue. If not, let me know where I should resubmit this.

I created a new Phoenix project with MongoDB support, and when running a migration I get the following error:

```
dan$ mix ecto.migrate

23:59:34.751 [info]  Already up
** (UndefinedFunctionError) undefined function: Mongo.Ecto.stop/3
    (mongodb_ecto) Mongo.Ecto.stop(HelloPhoenix.Repo, #PID<0.157.0>, 5000)
    (ecto) lib/mix/ecto.ex:94: Mix.Ecto.ensure_stopped/2
    (elixir) lib/enum.ex:579: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:579: Enum.each/2
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

Steps to repro:

1. `mix phoenix.new hello_phoenix --database mongodb`
2. `mix ecto.create`
3. `mix phoenix.gen.html User users name:string email:string bio:string number_of_pets:integer`
4. `mix ecto.migrate`

**Comment by josevalim** [comment]
It is a mongo_ecto issue: https://github.com/michalmuskala/mongodb_ecto. Can you please open it there? In fact, it has been already fixed in master, it is rather a matter of doing a new release (but they can't release from master due to other features). Thank you!
