### ISSUE TITLE
Consider removing stop from adapters

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1173]
Considering this:

https://github.com/elixir-lang/ecto/commit/69ae60d172ca5d46a0c45612765d302e2368fde3#diff-9157fa039deb54c4144866d7c134462aR42

@fishcakez do you think we can add this to the repository directly instead of requiring each adapter to implement it? Or maybe just use :gen.call now that we depend on Erlang 18? Or is it better to leave it up to each adapter?

**Comment by fishcakez** [comment]
Don't we start each adapter under a supervisor? If so we can just use
Supervisor.stop on that supervisor as we will have the pid.

**Comment by josevalim** [comment]
Thank you, fixing in master!
