### ISSUE TITLE
Support dynamic multiple database conn?

### ISSUE THREAD

**Issue by henryj** [elixir-lang/ecto#1183]
So we keep our clients' data in their own databases. When they visit the site, according to the domain, they are connected to their respective db, assuming there could be thousands of clients' dbs probably sit in diff db server. 

It seems in ecto you have to def a repo module for each db? Could there be a more feasible way to achieve this? Also notice that the clients' dbs could be automatically generated/deleted during run time. 

BTW, we use mongodb so prefix is not a solution here I guess.

**Comment by josevalim** [comment]
Please don't use the issues tracker for questions, use the mailing list.

Ecto does not support this so cleanly, maybe your best option is to use the mongo driver directly and start up connections as needed.
