### ISSUE TITLE
How to get model schema in adapter file?

### ISSUE THREAD

**Issue by OpakAlex** [elixir-lang/ecto#1188]
Hello!
I am working on oracle adapter and i need access to model schema in adapter. How i can do it?

**Comment by josevalim** [comment]
On which function? For insert/update/delete the second argument contains metadata.

**Comment by OpakAlex** [comment]
@josevalim 
```elixir
  def insert(prefix, table, header, rows, returning) do
```

`table` it's only table name...

**Comment by josevalim** [comment]
In Ecto v1.0 at least it includes a map instead of the table.

**Comment by OpakAlex** [comment]
But if i want use ecto from master? In master it's a table name. Yes in v1.0 it's a map. But how it will be in future?

**Comment by josevalim** [comment]
In master it is a map: https://github.com/elixir-lang/ecto/blob/v1.0/lib/ecto/adapter.ex#L155-L156

Maybe you are talking about the function that builds the SQL. That function will receive only the table but you can intercept and change it in the adapter. For example, we do it for MySQL: https://github.com/elixir-lang/ecto/blob/v1.0/lib/ecto/adapters/mysql.ex#L160-L181

**Comment by OpakAlex** [comment]
ok thanks @josevalim ! Happy new year! :)
