### ISSUE TITLE
Error running mix test on umbrella project with an ecto-enabled phoenix app (Elixir 1.2.0 only)

### ISSUE THREAD

**Issue by tjsousa** [elixir-lang/ecto#1190]
I have an umbrella project setup with two apps, one of them is an ecto-enabled phoenix app. The setup is pretty simple, bootstrapped the phoenix app using `mix phoenix.new`.

When running `mix test` on the umbrella project directory, an error is thrown:

```
~/g/t/auth-system ❯❯❯ mix test
==> auth_consumer
.

Finished in 0.07 seconds (0.07s on load, 0.00s on tests)
1 test, 0 failures

Randomized with seed 96905
==> auth_service
** (Mix) No repository available. Please pass a repo with the -r option.
```

This only happens with Elixir 1.2.0 (1.1.1 runs just fine). 

From my quick assessment it seems that this is raised from the following lines in the generated `test_helper.ex` file:

```elixir
ExUnit.start

Mix.Task.run "ecto.create", ["--quiet"]
Mix.Task.run "ecto.migrate", ["--quiet"]
```

Looking [at the source code](https://github.com/elixir-lang/ecto/blob/master/lib/mix/ecto.ex#L24-L36) it seems that `Mix.Project.config[:app]` is `nil` when running a `Mix.Task.run` on each sub app. Perhaps it is related to configuration sharing for umbrella projects in Elixir 1.2.0?

**Comment by josevalim** [comment]
You can remove the "ecto.create" and "ecto.migrate" calls from the app that does not have Ecto. For the app that has Ecto, you need to pass the repository. Here is what Phoenix is generating now:

https://github.com/phoenixframework/phoenix/blob/master/installer/templates/new/test/test_helper.exs#L3-L4

**Comment by tjsousa** [comment]
:+1: Great! Sorry for the noise.
