### ISSUE TITLE
Allow keyword lists and maps in put_assoc and put_embed

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1192]
When such are given, we will automatically build the changeset and call the on_change functions again.

**Comment by sorentwo** [comment]
Mind if I try to tackle this one?

**Comment by josevalim** [comment]
Sorry, I already have it almost done locally. :S

**Comment by josevalim** [comment]
Maybe #1193? :)

**Comment by sorentwo** [comment]
Sounds good, I was eyeing that one too.
