### ISSUE TITLE
Inconsistent api for strings/atoms in Relation.cast

### ISSUE THREAD

**Issue by stavro** [elixir-lang/ecto#1193]
> Below is accurate as of Ecto v1.1.1.
> I couldn't get v2.0.0-dev to compile, so I don't know if things have changed.

Following the **Nested associations and embeds** part of this example: http://blog.plataformatec.com.br/2015/08/working-with-ecto-associations-and-embeds/

Nearly all Changeset interfaces allow either a map of strings **or** atoms to be given as the parameters when manipulating models.

However, there appears to be an inconsistency when working with nested associations, which **requires** strings:

Given:

```elixir
todo_list =
  FormTest.TodoList
  |> FormTest.Repo.get(1)
  |> FormTest.Repo.preload([:todo_items])

params = @params

todo_list
|> FormTest.TodoList.changeset(params)
|> FormTest.Repo.update
```

For string parameters, the following is given:

```elixir
@params %{
  title: "Grocery List",
  todo_items: [%{
    "id" => 2,
    "body" => "Bananas"
  }]
}

{:ok,
 %FormTest.TodoList{__meta__: #Ecto.Schema.Metadata<:loaded>, id: 1,
  inserted_at: #Ecto.DateTime<2016-01-08T00:46:37Z>, title: "Grocery List",
  todo_items: [%FormTest.TodoItem{__meta__: #Ecto.Schema.Metadata<:loaded>,
    body: "Bananas", delete: nil, id: 2,
    inserted_at: #Ecto.DateTime<2016-01-08T00:46:37Z>,
    todo_list: #Ecto.Association.NotLoaded<association :todo_list is not loaded>,
    todo_list_id: 1, updated_at: #Ecto.DateTime<2016-01-08T17:37:38Z>}],
  updated_at: #Ecto.DateTime<2016-01-08T17:37:38Z>}}
```

For atom parameters, the following error is received:

```elixir
@params %{
  title: "Grocery List",
  todo_items: [%{
    id: 2,
    body: "Bananas"
  }]
}

** (RuntimeError) you are attempting to change relation :todo_items of
FormTest.TodoList, but there is missing data.

By default, if the parent model contains N children, at least the same
N children must be given on update. In other words, it is not possible
to orphan embed nor associated records, attempting to do so results
in this error message.

It is possible to change this behaviour by setting `:on_replace` when
defining the relation. See `Ecto.Changeset`'s section on related models
for more info.

    (ecto) lib/ecto/changeset/relation.ex:279: Ecto.Changeset.Relation.local_on_replace/2
    (ecto) lib/ecto/changeset/relation.ex:264: Ecto.Changeset.Relation.on_replace/2
    (ecto) lib/ecto/changeset/relation.ex:392: Ecto.Changeset.Relation.build_changeset!/4
    (ecto) lib/ecto/changeset/relation.ex:349: Ecto.Changeset.Relation.reduce_delete_changesets/5
    (ecto) lib/ecto/changeset.ex:585: Ecto.Changeset.cast_relation/4
```

Additionally, the documentation around this behavior is lacking a bit, it took me quite a while to track down the behavior to implement manually where Ecto sorts and groups by the primary key in nested associations, and that's all that is really required to get it working properly.

Can we update `Relation.cast` to accept atoms as well as strings for consistency, and perhaps add a note about requiring the primary key to be present?

**Comment by michalmuskala** [comment]
This is definitely a bug. 
I think the correct solution is to make [`Ecto.Changeset.convert_params/1`](https://github.com/elixir-lang/ecto/blob/master/lib/ecto/changeset.ex#L413-L426) recursive

**Comment by ptrckbrwn** [comment]
I have some free time right now so I'm going to see if I can get this fixed.

**Comment by stavro** [comment]
@michalmuskala Making `convert_params` recursive is not enough.  If a params map of **all** atom keys is given, it will still fail currently

**Comment by stavro** [comment]
Ah nevermind.  Misunderstood. That looks like it will do fine :+1:

**Comment by josevalim** [comment]
Actually, I don't think we should make it recursive. That's because we can pass a regular map inside the params that is going to be part of a field and not part of an association. We should probably change just Relation.cast on how it finds the related data.
