### ISSUE TITLE
Top pool process is always supervisor which is a bug

### ISSUE THREAD

**Issue by chvanikoff** [elixir-lang/ecto#1208]
As per IRC discussion with @fishcakez :
the top pool process may or may not be a supervisor. It should be pool dependent. Currently it is always listed as a supervisor in the children of the repo supervisor. Its a bug.
https://github.com/elixir-lang/ecto/blob/v1.1/lib/ecto/repo/supervisor.ex#L115

`fishcakez_`: chvanikoff: yeah, we need the pool to define the child spec to get it right.
`micmus`: fishcakez_: most probably we should go to the adapter level, not all adapters are using ecto's pools (at least now)
`fishcakez_` micmus: yeah it would be the adapter level, and the sql adapter would pass it to the pool
`fishcakez_` the repo suoervisor has no ideal about pooling

**Comment by fishcakez** [comment]
Should we fix this in 1.1?

**Comment by Psli** [comment]
Should we fix this in 1.1? +1

**Comment by josevalim** [comment]
This is tricky to fix in 1.1 beacuse it requires changing the adapter API and changing the adapter API is backwards incompatible. So I think it should stay close and we will try to get 2.0 out asap.

**Comment by fishcakez** [comment]
@josevalim we can always put a supervisor at the top of a pool.

**Comment by josevalim** [comment]
@fishcakez good idea.
