### ISSUE TITLE
Add inverse_of option to associations?

### ISSUE THREAD

**Issue by bcardarella** [elixir-lang/ecto#1214]
Thoughts on adding an `inverse_of` option to associations? The sole purpose would be to annotate the inverse relationship. This is useful for libraries that are working with these associations.

**Comment by bcardarella** [comment]
BTW, I can PR this if its :+1:

**Comment by Tica2** [comment]
Do you have one example of usage?

**Comment by bcardarella** [comment]
@Tica2 yes, in ecto_fixtures I might build a fixture as:

```
posts model: Post, repo: Repo do
  valid do
    tag fixtures(:tag).tags.foo
  end
end
```

ecto_fixtures will build a payload and setup all of the foreign keys. For `HasThrough` relationships it will setup the the `through` model data as well. The issue I'm having is when the inverse model's fixture references back the original model:

```
tags model: Tag, repo: Repo do
  foo do
    post fixtures(:post).posts.valid
  end
end
```

With the `posts` fixture I know I can just delete the `tag` key, but from the perspective of that fixture I don't have any clarity as to what the inverse relationship field is. I need to delete the `post` key from the `tags` fixture to ensure there is no infinite loop.

**Comment by josevalim** [comment]
Thanks for opening the issue!

My concern with adding the inverse_of is that folks may believe they inverse and the associated are the same and, changing one, will cause the other to change.

That said, the example above is not clear. I don't know what the DSL means, so I don't understand what it is supposed to do.

**Comment by bcardarella** [comment]
@josevalim is there a way with the current API to determine what the inverse relationship is via the `through` model? Perhaps I am just missing the already existing solution

**Comment by josevalim** [comment]
@bcardarella no, there isn't.

**Comment by josevalim** [comment]
Also, I don't think the fixtures solution should rely on it. Otherwise folks would add inverse_of for their fixtures during tests and it will affect how the code works in production.

**Comment by josevalim** [comment]
@bcardarella are you ok with closing this? :)

**Comment by bcardarella** [comment]
yes, I found a work around. Closing!
