### ISSUE TITLE
Cassandra Support

### ISSUE THREAD

**Issue by cjhowe** [elixir-lang/ecto#1220]
Is it reasonable to add Cassandra support to Ecto? I'd definitely be interested in contributing this support.

**Comment by josevalim** [comment]
I am not that familiar with Cassandra to have an answer for this question. I think some folks were working on a Cassandra driver and that would be the first step. I am copying @lexmag but you can ping him here or on IRC for more info. :) Once the driver is built, this will definitely be a discussion worth having and I will be glad to help.

**Comment by lexmag** [comment]
I believe it doesn't worth the efforts. Cassandra doest have SQL-like syntax but it lacks very much of existing features from SQL (e.g. no GROUP BY). Most importantly data model is different: partition and clustering keys, wide rows, etc.

**Comment by vegabook** [comment]
Personally exploring Phoenix for its streaming capability for financial data series into client fixed income analysis endpoint which I plan to write. Cassandra is a must-have in this domain. Its data model ensures contiguous data storage which, for time series, is crucial, considering the quantities of data involved in range queries.

**Comment by whatyouhide** [comment]
@vegabook Cassandra is definitely a great database and a life-saviour in many use cases. However, I agree with @lexmag, IMO an Ecto adapter would have a very hard time "mapping" to Cassandra concepts.

**Comment by vegabook** [comment]
Would I be able to bypass ecto via the Erlang Cassandra tools? Could I use a nominal Postgres installation alongside Cassandra and use Phoenix effectively? Apols the sill questions - exploring only here as want to get the tech stack right to avoid problems down the line.

**Comment by whatyouhide** [comment]
@vegabook you can certainly use Erlang drivers for Cassandra with Phoenix. Anyways, the issue tracker is not a place for discussing these things :smiley: You can try asking these questions in the [phoenix-talk](https://groups.google.com/forum/#!forum/phoenix-talk) mailing list, on IRC or on Elixir's Slack room.

**Comment by vintikzzz** [comment]
@vegabook maybe a little bit late, but... https://github.com/vintikzzz/cassandra_ecto

**Comment by vegabook** [comment]
oooh - not late at all. Many thanks! Will check it out.

**Comment by hisea** [comment]
@vintikzzz Glad to see more ppl are using Elixir/Ecto and Cassandra.

Have you saw https://github.com/cafebazaar/ecto-cassandra? Wondering what are your thoughts on what difference there are between the packages if any.

I think we have a very small community for Elixir/Cassandra users, may make faster progresses if we all joint forces.

**Comment by vintikzzz** [comment]
@hisea both projects were made just in the same time and have quite close functionality. When I've started `cassandra_ecto` there were no alternatives at all. Main difference between projects that `ecto-cassandra` stays on top of elixir library [elixir-cassandra](https://github.com/cafebazaar/elixir-cassandra) and `cassandra_ecto` stays on top of erlang library [cqerl](https://github.com/matehat/cqerl). Also I should notice that `ecto-cassandra` has very poor documentation.
If you want to help please feel free to contribute to `cassandra_ecto` or to `ecto-cassandra`.

**Comment by hisea** [comment]
Thanks @vintikzzz I will try it out.

**Comment by PDeveloper** [comment]
Any updates on this? :)

**Comment by codebyaryan** [comment]
what about this in 2021? all the mentioned repos had their last update in 2018 :/

**Comment by josevalim** [comment]
I know there is https://github.com/lexhide/xandra but, per the above, the Ecto adapter is likely not a good route to go.

**Comment by codebyaryan** [comment]
I could see that integrating with ecto is not a good option, but would really like to see/ maybe contribute to something like an orm specifically for cassandra. For example, there is this cassandra driver with python that also comes with an orm out of the box. https://github.com/datastax/python-driver
I wouldn't be keen to write raw cql queries to handle cassandra.
It suprises me that we don't have an equivalent in elixir, coming from Python.
I also understand that the elixir community is growing.
