### ISSUE TITLE
Remove changeset.model

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1222]
Should we rename the model field into what? source? data? struct? Thoughts?

/cc @michalmuskala

**Comment by josevalim** [comment]
I would go with either `source` or `data`. `struct` is restrictive if we want to support non-struct in the future. `data` is clearer I think.

**Comment by josevalim** [comment]
Note to self: change Phoenix.Ecto and Phoenix.HTML accordingly.

**Comment by paulcsmith** [comment]
FWIW `source` makes the most sense to me. I think `changeset.data` might be too vague

**Comment by doomspork** [comment]
What about `entity`, or is that too similar to `model`?

**Comment by josevalim** [comment]
I went with `data` because `source` already has other meaning in Ecto (it is an adapter meaning but I thought better to avoid anyway). Thanks everyone!

**Comment by michalmuskala** [comment]
I'm :+1: on `data`. `source` indeed already has a defined meaning in Ecto.
