### ISSUE TITLE
Aggregate functions lose type information

### ISSUE THREAD

**Issue by benwilson512** [elixir-lang/ecto#1224]
Hey!

Suppose I have a Reading schema with a field

```
field :recorded_at, Timex.Ecto.DateTime
```

If I run this query:
```
Reading
|> select([r], r.recorded_at)
|> Repo.all 
```
I get back the `Timex.Date`  structs I expect. If however I want to find the maximum recorded_at value and thus run
```
Reading
|> select([r], max(r.recorded_at))
|> Repo.all
```

Now I get back `{{2016, 2, 8}, {1, 10, 29, 0}}` style datetimes.

Is this intended behaviour?

Thanks!

**Comment by josevalim** [comment]
Nope, bug. Thank you!
