### ISSUE TITLE
Using Phoenix/Ecto with an Oracle Database as storage

### ISSUE THREAD

**Issue by fknoll** [elixir-lang/ecto#1226]
I am interested in using **Phoenix/Ecto** with an **Oracle Database 12c** as storage. Is it possible? How?

**Comment by josevalim** [comment]
Afaik there are currently no drivers for Oracle Databases, those would have to be implemented first. :)

**Comment by fknoll** [comment]
@josevalim Maybe, I could ask you to share your thoughts about what it would take to implement and maintain a driver for the **Oracle database**? Is it a problem for the Phoenix community that Oracle is a commercial product?

**Comment by josevalim** [comment]
@fknoll there are no problems, we just need someone to do the work, which could be you! For example, this is the driver implementation for MSSQL: https://github.com/livehelpnow/tds and this is the Ecto adapter: https://github.com/livehelpnow/tds_ecto

**Comment by fknoll** [comment]
@josevalim Thank you, I will take a look :smile:

**Comment by Tica2** [comment]
Main problem with Oracle is protocol that is not open.
MSSQL use protocol that is used also by Sybase.

**Comment by fknoll** [comment]
@Tica2 As far as I know MSSQL is based on (an early version of) Sybase that Microsoft brought from Sybase Inc. back in year 1989. The collaboration between Sybase and Microsoft ended in year 1993, and the Sybase database and SQL Server database continued as separate products. But, does those historical ties between Sybase and Microsoft make the MSSQL "protocol" open? And, what do you actually mean by "protocol"?

Installing Oracle's networking software SQL*Net, provides you with a multitude of ways to communicate with the Oracle database, including open standards as ODBC, JDBC and native support for various programming languages like Fortran, Cobol, C and C++ on various platforms.

Unfortunately, I have not seen any native Oracle support for Erlang/Elexsir. But maybe the the **Erlang ODBC interface** could be used?

**Comment by Tica2** [comment]
@fknoll MSSQL implement TDS (Tabular Data Stream) and is protocol to talk with database on raw socket.
I not sure what you intent to do but for ODBC erlang has http://erlang.org/doc/man/odbc.html
If you have local ODBC CLI + Oracle driver you can conect to Oracle database.

**Comment by kuon** [comment]
Oracle made a library that might help in the process of making an elixir/erlang driver. https://github.com/oracle/odpi

**Comment by zandao** [comment]
https://hex.pm/packages/jamdb_oracle is a good bet but not battle tested yet. There is also a limited solution: https://github.com/laurenz/oracle_fdw/tree/ORACLE_FDW_2_0_0 but needs PostgreSQL 9.6 and it has poor performance.
