### ISSUE TITLE
Callbacks, how to

### ISSUE THREAD

**Issue by VladShcherbin** [elixir-lang/ecto#1227]
Since Ecto callbacks are deprecated now, how do we handle after/before actions now?

Is there any example, how this has to be done? Can't find anything.

**Comment by josevalim** [comment]
Please use elixir-ecto for questions. But the idea is that all behaviour can be built with changesets, you don't need callbacks.

**Comment by VladShcherbin** [comment]
@josevalim Sure, I understand, how we can do before actions using changesets.

But what about after actions. As I can understand, changesets are used before database actions. Maybe I'm wrong somewhere.
