### ISSUE TITLE
Precision loss when inserting some decimals

### ISSUE THREAD

**Issue by nickveys** [elixir-lang/ecto#1232]
I have a `:decimal` column w/precision 15 and scale 10.  When I insert most values, they are stored properly, but some values are losing precision.  When I insert directly using SQL they are stored properly.

Failing test case here: https://github.com/code-lever/ecto/commit/ae7530e2bf86e1e86809f84abc2204398c33d37f

I insert `41.185705`, and get back `41.1857500000`, note the ending of `705` became `75`.  It seems like consistently when the issue happens a zero is being squeezed out near the end of the value.

The decimal struct appears to be correct all the way up to `Postgres.Connection.execute`, I'd gladly dig further to fix it with some direction as to where to look!

This happens on `1.1.3` and `master` currently.  PostgreSQL 9.4.5.

**Comment by josevalim** [comment]
I have added a comment. You shouldn't be using floats if you need precision. :)

**Comment by nickveys** [comment]
Using a string doesn't appear to help in the test case, updated: https://github.com/code-lever/ecto/commit/f400681a4f0788d8f554c8a627e88428b0b44e8b

Here's the insert:

    latitude = Decimal.new("41.185705")
    TestRepo.insert!(%Post{latitude: latitude})

Match fails with:

    rhs:  [#Decimal<41.1857500000>]

**Comment by nickveys** [comment]
It looks like this is an issue w/Postgrex.  `Postgrex.Extensions.Numeric.encode_numeric_float` will strip zeroes at the 4th, 8th, 12th etc locations in the decimal portion of the number.

Created: https://github.com/ericmj/postgrex/issues/157

Sorry for the misplaced issue!

**Comment by josevalim** [comment]
Ah, great find!
