### ISSUE TITLE
Repo.first is not working with composite pk

### ISSUE THREAD

**Issue by NilsLattek** [elixir-lang/ecto#1235]
Wanted to try out the new features of ecto 2 and ran into the following issue:
I have a follower mapping table:

    create table(:followers, primary_key: false) do
      add :user_id, references(:users, [on_delete: :delete_all]), primary_key: true
      add :follower_id, references(:users, [on_delete: :delete_all]), primary_key: true
    end

I can read from it with the deprecated method `one`:

    mapping = Repo.one(from(f in Follower, where: f.user_id == ^id and f.follower_id == ^follower_id))

When changing `Repo.one` to `Repo.first` I get an error:

    Repo.get/2 requires the schema Follower to have exactly one primary key, got: [:user_id, :follower_id]

**Comment by josevalim** [comment]
Thank you! I will work on it. :D

**Comment by NilsLattek** [comment]
Thank you Jose! :+1:
