### ISSUE TITLE
Provide integration tests with ownership with Hound

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1237]
This is mostly a reminder that we need to have a good story for this by the time 2.0.0 is effectively out.

**Comment by josevalim** [comment]
```elixir
# config/test.exs
config :my_app, sql_sandbox: true

# lib/my_app/endpoint.ex
if Application.get_env(:my_app, :sql_sandbox) do
  plug Phoenix.Ecto.SQL.Sandbox
end

# test/acceptance_case.ex
setup do
  :ok = Ecto.Adapters.SQL.Sandbox.checkout(...)
  hound_session()
  visit Phoenix.Ecto.SQL.Sandbox.path_for(self())
end
```

**Comment by tokafish** [comment]
@keathley, @alexwdaniel and I were working on a hound test with Ecto 2 today, and ran into this. We took a stab at implementing the plug that you've outlined. Here it is:

```
defmodule Phoenix.Ecto.SQL.Sandbox do
  import Plug.Conn

  def init(opts), do: opts

  @sandbox_owner_path "/phoenix/etc/sql/sandbox/"
  @sandbox_owner_cookie "phoenix_ecto_sandbox_owner_pid"

  def call(%{request_path: @sandbox_owner_path <> pid_string} = conn, _opts) do
    conn |> put_resp_cookie(@sandbox_owner_cookie, pid_string)
  end

  def call(conn, _opts) do
    pid = conn |> fetch_cookies |> get_owner_pid

    Ecto.Adapters.SQL.Sandbox.allow(MyRepo, pid, self)
    conn
  end

  def path_for(pid) when is_pid(pid) do
    "#{@sandbox_owner_path}#{:erlang.pid_to_list(pid)}"
  end

  defp get_owner_pid(%{req_cookies: %{@sandbox_owner_cookie => pid_string}} = conn) do
    pid_string |> URI.decode |> String.to_char_list |> :erlang.list_to_pid
  end
end

``` 

@josevalim, is this what you had in mind? 

1. We can't hardcode the repo in the plug - should it take it as an option?
2. Is it appropriate to store the owner pid in a cookie?

**Comment by josevalim** [comment]
@tokafish this is so awesome, **thank you!**

Yes, you are right, we need to encode the repo in the URL as well. Also, should we support multiple repositories? I think we can just do something like:

    def path_for(repo_or_repos, pid) do
      List.wrap(repo_or_repos) ....
    end

And always handle them as a list in the plug. Does it make sense?

**Comment by josevalim** [comment]
@tokafish another option is to specify the repos when mounting the plug but I think passing them in is more robust.

**Comment by tokafish** [comment]
For anyone who's interested, I wrote up a [blog post](http://blog.carbonfive.com/2016/03/01/concurrent-acceptance-testing-in-elixir/) on running acceptance tests concurrently with the new plug and hound.

**Comment by josevalim** [comment]
Beautiful, thank you so much!

On Tuesday, March 1, 2016, Thomas Fisher <notifications@github.com> wrote:

> For anyone who's interested, I wrote up a blog post
> <http://blog.carbonfive.com/2016/03/01/concurrent-acceptance-testing-in-elixir/>
> on running acceptance tests concurrently with the new plug and hound.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1237#issuecomment-190893129>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
