### ISSUE TITLE
Allow Changeset.validate_required to accept lists of strings

### ISSUE THREAD

**Issue by mattbreeden** [elixir-lang/ecto#1238]
Changeset.validate_required calls out to Changeset.missing? which only works for atoms.
Allowing it to work with strings would make it easy to keep a lot of existing structure. Everything that currently uses:
```elixir
@required_fields ~w(field field2 field3)
@optional_fields ~w(field4 field5)
```
Could just change to:
```elixir
data
|> cast(params, @required_fields ++ @optional_fields)
|> validate_required(@required_fields)
```
instead of having to pass in a new list of atoms

Alternatively, it would be nice if the wording of h(Ecto.Changeset.validate_required) specified that it needs to be a list of atoms, because when you call that function and get the error `no function clause matching in Ecto.Changeset.missing?/2`, it's unexpected (to me anyway).

**Comment by michalmuskala** [comment]
If you change your `@required_fields` to be a list of atoms, instead of strings it will work just fine. You can do this easily with `a` modifier to the `~w` sygil: `@required_fields ~w(field field2 field3)a`.

Personally I'm not exactly sure why we accept both string and atom keys in cast.

**Comment by mattbreeden** [comment]
Awesome, I didn't know about a. I agree it would just be nice if they were consistent, especially since things like validate_change also requires an atom. Going to close this since it should have been a post on the mailing list in the first place instead of an issue.
