### ISSUE TITLE
Map field has different keys depending on the last type of Repo operation.

### ISSUE THREAD

**Issue by michalwarda** [elixir-lang/ecto#1244]
Elixir version: 1.2.1
Ecto version: 1.1.3

I was wondering if I found a bug in ecto or is it the default behaviour.
When you have a resource with a `:map` type `field` and you retrieve a record from this type of resource the `:map` field returns a map with `string` keys, which is logical I guess.
So for example `Repo.get(Resource, id).map` is a `%{"field1": „value1"}`.
The problem occurs when you insert the field passing a map with atoms as keys for example:
```record = Repo.insert(%Resource{map: %{field1: „value1"}})```
and then when you invoke `record.map` you get an atom based map like so
`%{field1: „value1"}`. 
It brings a bit of incosistency and I think invoking `.map` on both of these structs should return the same map.

**Comment by josevalim** [comment]
You should always use string keys. Because we use JSON, the JSON encoder of choice (default is Poison) converts atoms to string but when decoded they are always strings. Just avoid passing atoms and you should be good (or pick an encoder that does not allow atoms).

**Comment by michalwarda** [comment]
Thanks for the quick response.

**Comment by josevalim** [comment]
Glad to help! :D
