### ISSUE TITLE
Dialyzer `Function rollback/1 has no local return`

### ISSUE THREAD

**Issue by hojgr** [elixir-lang/ecto#1248]
Hello,

I'm running Dialyzer on my project and I've found that some of my errors are caused by Phoenix ( https://github.com/phoenixframework/phoenix/issues/1508 ) and I think this error is caused by Ecto.

I'm getting
```
lib/hosting/repo.ex:2: Function rollback/1 has no local return
```

Second line of repo.ex is
`use Ecto.Repo, otp_app: :hosting`

I've searched around a little and I've found the rollback here
https://github.com/elixir-lang/ecto/blob/master/lib/ecto/repo.ex#L126

that should lead to postgres' adapter, where `rollback` is not defined so I suppose it falls back to sql's rollback here
https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/sql.ex#L110

I have no idea where to go from here. Am I supposed to fix this somehow? Am I running dialyze wrong?

Thanks
Michal Hojgr

**Comment by fishcakez** [comment]
Indeed `rollback/1` has no local return so the warning is valid. It is not a bug though, some spec like `-spec rollback(any()) :: no_return` would remove the warning. I thought this warning would only appear if dialyzer was run with extra warnings.

**Comment by josevalim** [comment]
We have already specified no_return in the callback so we should be fine. As @fishcakez said, it is not a problem, but you should not get this warning unless you are specifying extra configs.
