### ISSUE TITLE
psql in storage integration test does not obey PG_URL

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/ecto#1249]

**Comment by sorentwo** [comment]
@fishcakez Mind if I take this? This is likely my fault anyhow.

**Comment by fishcakez** [comment]
@sorentwo feel free. I pinged you about this on IRC at some point and you didnt reply :cry:

**Comment by sorentwo** [comment]
Woops. I never saw a message about it, sorry!

**Comment by fishcakez** [comment]
Hehe. Just to let you know its not your fault, just thought you might want to handle it.

**Comment by josevalim** [comment]
@sorentwo please go ahead :D

**Comment by sorentwo** [comment]
I took a quick look at this and it seems like I'm missing some context or details. The `PG_URL` is set as `:pg_test_url` by the integration test helper, and setting `PG_URL` to something invalid (`fake:fake@localhost`) fails as I would expect. What is the situation that I'm missing?

**Comment by fishcakez** [comment]
I meant that these lines don't use PG_URL: https://github.com/elixir-lang/ecto/blob/428126157b1970d10f9d5233397f07c35ce69cac/integration_test/pg/storage_test.exs#L20-L26

**Comment by josevalim** [comment]
We can probably rewrite those lines to use the commands, honestly.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by sorentwo** [comment]
@fishcakez Thanks for the clarification! I went with @josevalim's advice here and used the commands directly. It is simpler, with the notable caveat that if the adapter implementation breaks at all the database will be left in a dirty state. Of course that is probably true of most of the integration tests, so developer beware.
