### ISSUE TITLE
Repo module is not loaded when executing mix tasks using ecto 2.0.0-beta.0 

### ISSUE THREAD

**Issue by Sbfrr** [elixir-lang/ecto#1251]
Here is the stacktrace when doing ``` mix ecto.create -r EctoTest.Datastores.PG ``` :
``` elixir
** (UndefinedFunctionError) undefined function EctoTest.Datastores.PG.__adapter__/0 (module EctoTest.Datastores.PG is not available)
    EctoTest.Datastores.PG.__adapter__()
    anonymous fn/1 in Mix.Tasks.Ecto.Create.run/1
    (elixir) lib/enum.ex:2400: Enum.do_all?/2
    lib/mix/tasks/ecto.create.ex:27: Mix.Tasks.Ecto.Create.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

When starting the project with ```  iex -S mix ```   : 
``` elixir
iex(1)> EctoTest.Datastores.PG
EctoTest.Datastores.PG
iex(2)> EctoTest.Datastores.PG.__adapter__
Ecto.Adapters.Postgres
```

My config file:
``` elixir
use Mix.Config

config :ecto_test, EctoTest.Datastores.PG,
  adapter: Ecto.Adapters.Postgres,
  database: "ecto_test_dev",
  username: "Sebastien",
  hostname: "127.0.0.1",
  port: 5432
```

The problem is not happening when switching back to a the previous ecto version 1.1.3.
I guess it's related to a problem of loading modules before executing the task but I'm not sure on how you wanna handle this.

Here is a small mix project reproducing the issue, just clone the project, update the config with your local pg config and then:
``` 
mix deps.get
mix ecto.create
```

Let me know if I can help with this.

**Comment by Sbfrr** [comment]
the repo to reproduce the problem: https://github.com/Sbfrr/ecto-mix-issue

**Comment by sorentwo** [comment]
I ran into this last week while working on an article about Ecto 2.0. At the time I thought I may have misconfigured something just worked around it. To make up for that I cloned your sample repo and confirmed the same behavior.

The code in lib is not available when it attempts to call `ensure_implements` within `ecto.create.ex`. I've attempted to shim in a `ensure_loaded` and `ensure_compiled` beforehand, but that returns `{:error, :nofile}` consistently.

**Comment by sorentwo** [comment]
I've bisected this (lazily, there is only one commit that changes ecto.create in the past 4 months) and tracked it to https://github.com/elixir-lang/ecto/commit/42812615. Restoring `ensure_repo(repos, args)` to `Mix.Tasks.Ecto.Create.run/1` fixes the problem. PR forthcoming.

**Comment by Sbfrr** [comment]
Thanks for taking care of it!

**Comment by webzepter** [comment]
:+1:

**Comment by matrinox** [comment]
Thanks ! :+1:
