### ISSUE TITLE
Make DBConnection a proper dependency or extract it to drivers

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ecto#1253]

**Comment by josevalim** [comment]
Wait, what? We only depend on it inside Ecto.Adapters.SQL.

**Comment by ericmj** [comment]
Then it should be listed as a dependency in mix.exs.

**Comment by josevalim** [comment]
It is ok to list as an optional dependency. I will add that but we are assuming the adapter will bring it in anyway because it is required from their side too.
