### ISSUE TITLE
Issue when using `Repo.first` with aggregate query

### ISSUE THREAD

**Issue by parkerl** [elixir-lang/ecto#1254]
Ecto master
Elixir 1.2
Postgres

This query:
```
TestRepo.first(from p in Post, select: count(p.id))
```
gives an error like the following:

```
     ** (Postgrex.Error) ERROR (grouping_error): column "f0.id" must appear in the GROUP BY clause or be used in an aggregate function
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:367: Ecto.Adapters.SQL.execute_and_cache/7
       (ecto) lib/ecto/repo/queryable.ex:122: Ecto.Repo.Queryable.execute/5
       (ecto) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/4
       (ecto) lib/ecto/repo/queryable.ex:59: Ecto.Repo.Queryable.one/4
```

I have reproduced it on my fork here https://github.com/parkerl/ecto/commit/a84cb06bce79f2bf0d67adf6dd1464d0b0641618

I have not had time to dig into the cause myself, sorry.

Thanks for taking a look!

**Comment by Gazler** [comment]
Query for Repo.one:

    "SELECT count(u0.\"id\") FROM \"users\" AS u0"

Query for Repo.first:

    "SELECT count(u0.\"id\") FROM \"users\" AS u0 ORDER BY u0.\"id\" LIMIT 1"

Here's a work around I am using for now:

    assert Repo.first!(from u in User, select: count(u.id), order_by: nil) == 4

**Comment by michalmuskala** [comment]
I have to admit I liked `Repo.one` much more than `Repo.first` - it doesn't work with schemas without primary keys, custom aggregate functions or more advanced queries, where you expect one result.

Even though, the issue with count currently has an alternative solution using `Repo.aggregate`:
```
Repo.aggregate(User, :count, :id)
```

**Comment by Gazler** [comment]
@michalmuskala `Repo.aggregate` is a nice solution in this case. Thanks for the tip.

I guess this issue still exists when you don't select an id.

**Comment by ericmj** [comment]
The problem with Repo.aggregate is that it doesn't solve it for every query that is incompatible with the implicit order_by. I agree with @michalmuskala here, Repo.first is a good idea but it's incompatible with too many types queries.

**Comment by benwilson512** [comment]
Chiming in, I too like `Repo.first` but still want something like `Repo.one`. I've built a Repo.fetch! into my Repo module for now but I still think it's common enough to use `Repo.one` that it ought not to be deprecated without a drop in replacement.

**Comment by josevalim** [comment]
Repo.all |> List.first or [value] = Repo.all :)

The goal is to move towards functions that offer more than a single
function composition.

I am checking though if we can emit better warning in cases like the one
reported here. I think having both one and first would be confusing.

On Friday, February 19, 2016, Ben Wilson <notifications@github.com> wrote:

> Chiming in, I too like Repo.first but still want something like Repo.one.
> I've built a Repo.fetch! into my Repo module for now but I still think it's
> common enough to use Repo.one that it ought not to be deprecated without
> a drop in replacement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1254#issuecomment-186229092>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by ericmj** [comment]
> The goal is to move towards functions that offer more than a single function composition.

How does `first` offer that over `one`?

**Comment by benwilson512** [comment]
`Item |> Repo.first` works and is relatively handy. `item |> assoc(:things) |> Repo.first`. Previously if you wanted just one thing you had to `|> limit(1)` everywhere or Repo.one would freak out.

**Comment by sorentwo** [comment]
`Repo.all |> List.first` is great when you have relatively few records, but you'll still want to put a `limit(n)` in there for any table with a substantial number of rows. Honestly I'd expect a limit to be set automatically for something like `Repo.first`.

**Comment by benwilson512** [comment]
`Repo.first` does set a limit(1) automatically. `Repo.one` did not.

**Comment by sorentwo** [comment]
@benwilson512 Well then, ignore that =)

**Comment by ericmj** [comment]
We should probably just remove the order by and just keep the limit. The order by is a bit weird anyway, ordering by primary key seldom makes sense, especially since ecto supports uuid and mongo objectid.

**Comment by parkerl** [comment]
My main concern is that the deprecation warning encouraged me to do switch to `first` regardless of the fact that I was using an aggregate.

That said, I have to agree with you @ericmj that ordering by the pk seems potentially problematic. If I care about ordering, I should set it up myself before passing the query to `first`. :+1: for taking out the default ordering.

**Comment by josevalim** [comment]
We are not dropping the ordering from first, otherwise you get completely irrelevant results for Postgres (which has no ordering even for integer primary keys). Of course, first is useless if you are using UUIDs, but that's not our default and it should be clear.

We are also not adding Repo.one back because it could not distinguish between a nil or a missing result. If we look at this thread, it is really easy to see all of the use cases folks having in mind:

* Repo.first with ordering (my use case)
* Repo.fetch (that works like Repo.one but wrapped in a tuple)
* Repo.one (because taking the value out of the tuple every time is annoying)
* Repo.one that also adds a limit (so you don't need to explicitly add it every time)

And we obviously cannot solve them all without having a quite large surface API. That's why the goal in Ecto 2.0 is to tackle the *trickier* ones. Repo.first and Repo.aggregate are quite more complex than Repo.one, Repo.fetch or Repo.one with limit. All of those could be solved quite quickly by using Repo.all with basic Elixir constructs without worrying about Ecto features.

I will improve the error message to not point everyone towards Repo.first, that is definitely wrong. :) Thank you.

**Comment by michalmuskala** [comment]
I have to admit I have a hard time finding use case for `id` ordered result as well that wouldn't be better replaced by something else.

**Comment by stevedomin** [comment]
Going to pitch in here as well, I struggle to see when that would be useful and I'm wondering if we are not promoting a bad practice somehow (especially since using uuid as primary key is a first-class citizen in Ecto, ordering by id makes no sense in that case)
