### ISSUE TITLE
Encoding datetimes in composite types

### ISSUE THREAD

**Issue by lau** [elixir-lang/ecto#1255]
There is an issue in Calecto: https://github.com/lau/calecto/issues/18 when composite types are used. In the postgres composite type there is a datetime. When using `Calendar.DateTime` in a query, an error is raised, even though there is a protocol implemented for that datetime. When not "inside" a composite type it works as expected.

Adding the following after https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/postgres/datetime.ex#L47 fixes this problem:

```elixir
    defp encode_timestamp({{year, month, day}, {hour, min, sec, usec}})
        when year <= @timestamp_max_year and hour in 0..23 and min in 0..59 and sec in 0..59 and usec in 0..999_999 do
      datetime = {{year, month, day}, {hour, min, sec}}
      secs = :calendar.datetime_to_gregorian_seconds(datetime) - @gs_epoch
      <<secs * 1_000_000 + usec :: signed-64>>
    end
## this is the new additional code:
    defp encode_timestamp(arg) do
      {:ok, {{_,_,_},{_,_,_,_}} = dt} = Ecto.DataType.cast(arg, :datetime)
      dt |> encode_timestamp
    end
```

I could do a PR that does just that. This is quite simple and would work.

An alternative would be to somehow have custom types be able to specify Ecto types for the sub-elements of the composite types.

**Comment by josevalim** [comment]
Thank you @lau. My concern is that we could fix this for this case but it would be broken for all other types. The issue is that, when using the fragment syntax, Ecto doesn't know the type, so it cannot do the conversion. The best would be to explicitly tell in the query syntax. I have posted some comments in the original issue, let's see how it goes. I will improve the error message accordingly though.

**Comment by josevalim** [comment]
@lau so i have fixed this by introducing a new callback to `Ecto.DataType`. If someone never provides any type information to Ecto, Calecto types will never be cast to :date, :datetime or :time and custom types will pass through to the adapter, leading to the issue you have just opened. With the new callback, adapters can call `Ecto.DataType.dump` on any uncast type to get its "default" Ecto type.

**Comment by stevedomin** [comment]
This is great, thanks @josevalim!

**Comment by lau** [comment]
@josevalim thanks!
