### ISSUE TITLE
Mix.Task.run "ecto.migrate" in test_helper?

### ISSUE THREAD

**Issue by tmjoen** [elixir-lang/ecto#1259]
I might be way off here, but I'm having some issues with my test_helper.exs using Ecto 2.0 (master and beta)

I tried setting it up like this:

```elixir
  alias Ecto2Test.Repo

  defmodule Ecto2Test.Integration.Case do
    use ExUnit.CaseTemplate

    setup do
      :ok = Ecto.Adapters.SQL.Sandbox.checkout(Ecto2Test.Repo)
    end
  end

  {:ok, _} = Ecto2Test.Repo.start_link

  _   = Ecto.Storage.down(Ecto2Test.Repo)
  _   = Ecto.Storage.up(Ecto2Test.Repo)

  Mix.Task.run "ecto.create", ["-r", Ecto2Test.Repo, "--quiet"]
  Mix.Task.run "ecto.migrate", ["-r", Ecto2Test.Repo, "--quiet"]

  Ecto.Adapters.SQL.Sandbox.mode(Ecto2Test.Repo, :manual)

  ExUnit.start()
```

but then it errors out with:

```
** (exit) exited in: GenServer.call(Ecto2Test.Repo.Pool, {:mode, :manual}, 5000)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:564: GenServer.call/3
    test/test_helper.exs:23: (file)
    (elixir) lib/code.ex:363: Code.require_file/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2


16:34:40.753 [error] GenServer #PID<0.178.0> terminating
** (stop) exited in: GenServer.call(Ecto2Test.Repo.Pool, {:mode, :manual}, 5000)
    ** (EXIT) no process
Last message: {:EXIT, #PID<0.47.0>, {:noproc, {GenServer, :call, [Ecto2Test.Repo.Pool, {:mode, :manual}, 5000]}}}
State: {:state, {#PID<0.178.0>, Supervisor.Default}, :simple_one_for_one, [{:child, :undefined, Task.Supervised, {Task.Supervised, :start_link, []},
 :temporary, 5000, :worker, [Task.Supervised]}], {:set, 0, 16, 16, 8, 80, 48, {[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []}, {{[]
, [], [], [], [], [], [], [], [], [], [], [], [], [], [], []}}}, 3, 5, [], Supervisor.Default, {:ok, {{:simple_one_for_one, 3, 5}, [{Task.Supervised
, {Task.Supervised, :start_link, []}, :temporary, 5000, :worker, [Task.Supervised]}]}}}
```

If I change my test_helper.exs to this:

```diff
  alias Ecto2Test.Repo

+ Code.require_file "../priv/repo/migrations/1_create_users.exs", __DIR__

  defmodule Ecto2Test.Integration.Case do
    use ExUnit.CaseTemplate

    setup do
      :ok = Ecto.Adapters.SQL.Sandbox.checkout(Ecto2Test.Repo)
    end
  end

  {:ok, _} = Ecto2Test.Repo.start_link

  _   = Ecto.Storage.down(Ecto2Test.Repo)
  _   = Ecto.Storage.up(Ecto2Test.Repo)

  Mix.Task.run "ecto.create", ["-r", Ecto2Test.Repo, "--quiet"]
- Mix.Task.run "ecto.migrate", ["-r", Ecto2Test.Repo, "--quiet"]

+ Ecto.Migrator.up(Ecto2Test.Repo, 1, Ecto2Test.Repo.Migrations.CreateUsers)

  Ecto.Adapters.SQL.Sandbox.mode(Ecto2Test.Repo, :manual)

  ExUnit.start()
```

It works fine.

I've put up an example project here: https://github.com/tmjoen/ecto2_test

Just wondering if there are some gremlins in the machine here, or if I'm not really supposed to do `Mix.Task.run "ecto.migrate", ["-r", Ecto2Test.Repo, "--quiet"]` like Phoenix can?

**Comment by josevalim** [comment]
The issue is that the migrator shuts down the repo so it can reload. But
because you are starting it by hand instead of your supervision tree, it
never comes back. Try starting the repo just later on, after you run all
storage and migration commands. I will improve the docs.

On Friday, February 19, 2016, T. Mjoen <notifications@github.com> wrote:

> I might be way off here, but I'm having some issues with my
> test_helper.exs using Ecto 2.0 (master and beta)
>
> I tried setting it up like this:
>
>   alias Ecto2Test.Repo
>
>   defmodule Ecto2Test.Integration.Case do
>     use ExUnit.CaseTemplate
>
>     setup do
>       :ok = Ecto.Adapters.SQL.Sandbox.checkout(Ecto2Test.Repo)
>     end
>   end
>
>   {:ok, _} = Ecto2Test.Repo.start_link
>
>   _   = Ecto.Storage.down(Ecto2Test.Repo)
>   _   = Ecto.Storage.up(Ecto2Test.Repo)
>
>   Mix.Task.run "ecto.create", ["-r", Ecto2Test.Repo, "--quiet"]
>   Mix.Task.run "ecto.migrate", ["-r", Ecto2Test.Repo, "--quiet"]
>
>   Ecto.Adapters.SQL.Sandbox.mode(Ecto2Test.Repo, :manual)
>
>   ExUnit.start()
>
> but then it errors out with:
>
> ** (exit) exited in: GenServer.call(Ecto2Test.Repo.Pool, {:mode, :manual}, 5000)
>     ** (EXIT) no process
>     (elixir) lib/gen_server.ex:564: GenServer.call/3
>     test/test_helper.exs:23: (file)
>     (elixir) lib/code.ex:363: Code.require_file/2
>     (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
>     (elixir) lib/enum.ex:604: Enum.each/2
>
>
> 16:34:40.753 [error] GenServer #PID<0.178.0> terminating
> ** (stop) exited in: GenServer.call(Ecto2Test.Repo.Pool, {:mode, :manual}, 5000)
>     ** (EXIT) no process
> Last message: {:EXIT, #PID<0.47.0>, {:noproc, {GenServer, :call, [Ecto2Test.Repo.Pool, {:mode, :manual}, 5000]}}}
> State: {:state, {#PID<0.178.0>, Supervisor.Default}, :simple_one_for_one, [{:child, :undefined, Task.Supervised, {Task.Supervised, :start_link, []},
>  :temporary, 5000, :worker, [Task.Supervised]}], {:set, 0, 16, 16, 8, 80, 48, {[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []}, {{[]
> , [], [], [], [], [], [], [], [], [], [], [], [], [], [], []}}}, 3, 5, [], Supervisor.Default, {:ok, {{:simple_one_for_one, 3, 5}, [{Task.Supervised
> , {Task.Supervised, :start_link, []}, :temporary, 5000, :worker, [Task.Supervised]}]}}}
>
> If I change my test_helper.exs to this:
>
>   alias Ecto2Test.Repo
> + Code.require_file "../priv/repo/migrations/1_create_users.exs", __DIR__
>
>   defmodule Ecto2Test.Integration.Case do
>     use ExUnit.CaseTemplate
>
>     setup do
>       :ok = Ecto.Adapters.SQL.Sandbox.checkout(Ecto2Test.Repo)
>     end
>   end
>
>   {:ok, _} = Ecto2Test.Repo.start_link
>
>   _   = Ecto.Storage.down(Ecto2Test.Repo)
>   _   = Ecto.Storage.up(Ecto2Test.Repo)
>
>   Mix.Task.run "ecto.create", ["-r", Ecto2Test.Repo, "--quiet"]- Mix.Task.run "ecto.migrate", ["-r", Ecto2Test.Repo, "--quiet"]
> + Ecto.Migrator.up(Ecto2Test.Repo, 1, Ecto2Test.Repo.Migrations.CreateUsers)
>
>   Ecto.Adapters.SQL.Sandbox.mode(Ecto2Test.Repo, :manual)
>
>   ExUnit.start()
>
> It works fine.
>
> I've put up an example project here: https://github.com/tmjoen/ecto2_test
>
> Just wondering if there are some gremlins in the machine here, or if I'm
> not really supposed to do Mix.Task.run "ecto.migrate", ["-r",
> Ecto2Test.Repo, "--quiet"] like Phoenix can?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1259>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by tmjoen** [comment]
Yes, that was it. Thank you so much!

**Comment by tokafish** [comment]
@josevalim I'm getting what I believe to be a related issue when running `mix test`, when running off of Ecto master as of fcd8c30365e102b8d2cb5b5f70515a20f1250249

> mix test                                                            [2.2.2]
> 09:17:08.036 [error] Postgrex.Protocol (#PID<0.262.0>) failed to connect: ** (Postgrex.Error) FATAL (invalid_catalog_name): database "allocations_test" does not exist
> ** (DBConnection.Error) connection not available
>     (db_connection) lib/db_connection.ex:817: DBConnection.checkout/2
>     (db_connection) lib/db_connection.ex:717: DBConnection.run/3
>     (db_connection) lib/db_connection.ex:957: DBConnection.run_meter/3
>     (db_connection) lib/db_connection.ex:421: DBConnection.query/4
>     (ecto) lib/ecto/adapters/sql.ex:178: Ecto.Adapters.SQL.query!/5
>     (ecto) lib/ecto/adapters/postgres.ex:56: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
>     (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
>     (ecto) lib/ecto/adapters/postgres.ex:56: Ecto.Adapters.Postgres.execute_ddl/3

My test_helper.exs looks like this:

ExUnit.configure(exclude: [pending: true])
ExUnit.start

Mix.Task.run "ecto.create", ~w(-r Allocations.Repo --quiet)
Mix.Task.run "ecto.migrate", ~w(-r Allocations.Repo --quiet)
Ecto.Adapters.SQL.Sandbox.mode(Allocations.Repo, :manual)

**Comment by tokafish** [comment]
I've got a minimal reproduction of the issue here:

https://github.com/tokafish/example_app

1. git clone https://github.com/tokafish/example_app
2. cd example_app
3. mix deps.get
4. mix test

**Comment by tokafish** [comment]
Never mind! @ericmj assisted me in IRC with the necessary fixes, which are documented [here](https://github.com/phoenixframework/phoenix/issues/1564) if anyone else runs into this issue before the generators are updated.
