### ISSUE TITLE
many_to_many "not-null constraint" on timestamps

### ISSUE THREAD

**Issue by xn4v8h** [elixir-lang/ecto#1260]
Heads up - seems theres something up with the setting of timestamps on associations. Commenting out "timestamps" skips the error.

`Repo.insert!(%Person{ name: "test", messages: [ %Message{text: "test"} ] } )`

Is throwing:

> ** (Postgrex.Error) ERROR (not_null_violation): null value in column "inserted_at" violates not-null constraint
    table: person_messages
    column: inserted_at
    Failing row contains (1, 1, 1, null, null).

My PersonMessage migration looks like this:

    def change do
        create table(:person_messages) do
            add :person_id, :integer
            add :message_id, :integer

            timestamps
        end
    end

**Comment by josevalim** [comment]
How did you define your association please?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by xn4v8h** [comment]
@josevalim Ah yes:

      schema "person_messages" do
        field :message_id, :integer
        field :person_id, :integer
        timestamps
    end

      schema "messages" do
        field :name, :string
        many_to_many :people, AppName.Person, join_through: "person_messages"
        timestamps
    end

    schema "people" do
        field :name, :string
        many_to_many :messages, AppName.Message, join_through: "person_messages"
        timestamps
    end

**Comment by josevalim** [comment]
I believe You need to pass a schema to join_through instead of a string if
you want those fields to be set.

On Saturday, February 20, 2016, xn4v8h <notifications@github.com> wrote:

> @josevalim <https://github.com/josevalim> Ah yes:
>
>   schema "person_messages" do
>     field :message_id, :integer
>     field :person_id, :integer
>     timestamps
> end
>
>   schema "messages" do
>     field :name, :string
>     many_to_many :people, AppName.Person, join_through: "person_messages"
>     timestamps
> end
>
> schema "people" do
>     field :name, :string
>     many_to_many :messages, AppName.Message, join_through: "person_messages"
>     timestamps
> end
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1260#issuecomment-186635926>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by princemaple** [comment]
Something like https://github.com/elixir-lang/ecto/blob/master/integration_test/support/schemas.exs#L144 probably

**Comment by xn4v8h** [comment]
Ah yes, that's it! Thanks for your help :D

**Comment by codecakes** [comment]
@xn4v8h 

> ** (Postgrex.Error) ERROR (not_null_violation): null value in column "inserted_at" violates not-null 
were you preferring something like:
```
def change do
    create table(:person_messages) do
        add :person_id, :integer
        add :message_id, :integer

    end
end
```
instead of

```
def change do
    create table(:person_messages) do
        add :person_id, :integer
        add :message_id, :integer

        timestamps
    end
end
```

??
