### ISSUE TITLE
Deprecated warnings

### ISSUE THREAD

**Issue by VladShcherbin** [elixir-lang/ecto#1262]
Are there any warnings about deprecated / updated stuff ?

For example, `cast/4` is deprecated, but still can be used with no problems, errors or warnings.

**Comment by josevalim** [comment]
`cast/4` is soft deprecated, so we won't emit warnings for now but will in the next release. We have decided to not emit warning to all deprecations to avoid making the upgrade super verbose.

**Comment by VladShcherbin** [comment]
Thank you.
