### ISSUE TITLE
Changeset.cast_assoc and validate_required

### ISSUE THREAD

**Issue by VladShcherbin** [elixir-lang/ecto#1265]
We have Universities with Faculties. Each Faculty can have many Specialities. The models are:

**Faculty**
```elixir
schema "faculties" do
  field :title, :string

  belongs_to :university, Universities.University
  has_many :specialities, Universities.Speciality
end

def changeset(model, params, assoc, opts \\ :invalid) do
  model
  |> cast(params, [:university_id, :title])
  |> cast_assoc(assoc, opts)
end
```

**Speciality**
```elixir
schema "specialities" do
  field :title, :string

  belongs_to :faculty, Universities.Faculty
end

def changeset(model, params \\ :invalid) do
  model
  |> cast(params, [:faculty_id, :title])
  |> validate_required([:faculty_id, :title])
end
```

Specialities require **faculty_id** to be set. 

So, now we want to insert a new Faculty and some Specialities.

```elixir
changeset = Faculty.changeset(%Faculty{}, attrs["data"], :specialities)

case Repo.insert(changeset) do
  {:ok, _model} -> {:reply, :ok, socket}
  {:error, changeset} ->
    {:reply, {:error, %{errors: translate_errors(changeset)}}, socket}
end
```

This gives me the error - **faculty_id can't be blank**. So, if I'm not wrong, it checks for this id before the Faculty was added, so no *faculty_id* is passed to Speciality.

Am I doing something wrong?

**Comment by josevalim** [comment]
validate_required is meant to validate the user input. If factory_id is not a user input, but set as part of your association, you are not meant to validate it. For example, it wouldn't even make sense to show to the user that "factory_id can't be blank" because he can't act on it.

**Comment by VladShcherbin** [comment]
@josevalim wow, this was fast. Thank you a lot. Ecto 2.0 feels so good :+1:

**Comment by jamescmartinez** [comment]
@josevalim I don't feel I understand this. Using those same relationships shown above, if I were to do the following:

```elixir
faculty = Repo.insert!(Faculty.changeset(%Faculty{}, %{}) # valid, saves correctly
changeset = Specialty.changeset(%{Specialty{}, %{ faculty: faculty })
changeset.valid? # false
changeset.errors # [faculty_id: {"can't be blank", []}]
```

Because the Specialty's Faculty was set using `faculty: faculty`, the `faculty_id` validation will not work. The changeset data for Specialty will look something like this, which prevents the validation from working:

```elixir
%MyApp.Specialty{faculty: %MyApp.Follower{id: 1}, faculty_id: nil}
```

In this case faculty is a user input and validation should be appropriate. Thoughts?

**Comment by josevalim** [comment]
Then you should validate the `:faculty` field, not the `:faculty_id`, because `:faculty` is what you are receiving externally.

**Comment by jamescmartinez** [comment]
@josevalim When I go to validate the `:faculty` field in this case, it always passes. The value of the `changeset.data` looks something like this when the faculty has not been set:

```elixir
changeset = Specialty.changeset(%{Specialty{}, %{})
changeset.data # %MyApp.Specialty{faculty: #Ecto.Association.NotLoaded<association :faculty is not loaded>, 
faculty_id: nil}
```
Faculty should be `nil` in this case for the validation to work, but it's not.

**Comment by josevalim** [comment]
@jamescmartinez you should preload it. I will make sure to raise on this case though. :) You can also pass the required: true flag the `cast_assoc`.
