### ISSUE TITLE
Dates in months which don't have a 29th/30th/31st are not marked as invalid on invalid dates

### ISSUE THREAD

**Issue by Theemuts** [elixir-lang/ecto#1267]
Currently, when a field with the Ecto.Date type receives a date whose day falls in the 1..31-range, it is marked as valid (`Ecto.DateTime.Utils.is_time/4`). As a result, a second validation is required to guarantee a date really is valid to account for the different number of days in February in leap and common years, and months with only thirty days. 

Also, if a date has a day larger than 31 it will always be marked as invalid. However, this now leads to two error messages for the invalid field: both the "can't be blank" and "is invalid" messages are set. I think it makes more sense to only mark them as invalid, after all the user has entered a value.

Ecto version: 2.0.0-beta1
Elixir version: 1.2.0

**Comment by josevalim** [comment]
Erlang ships with this function: http://erlang.org/doc/man/calendar.html#valid_date-1

Maybe we should just call it after cast of date and datetime. Could you please send a PR? Thank you!

**Comment by Theemuts** [comment]
Sure, where would you like to see it? 

My plan is to move the `cast/1`-functions to private `do_cast/1`s, create the private function `valid_date?\1` which returns `{:ok, dt}` / `{:ok, d}` / `:error` depending on the argument it receives and the value `:calendar.valid_date` returns. That way, `cast\1` can be written as `d |> do_cast |> valid_date?`

**Comment by josevalim** [comment]
Sounds perfect.
