### ISSUE TITLE
Subqueries with assoc

### ISSUE THREAD

**Issue by xn4v8h** [elixir-lang/ecto#1268]
Getting the following error when attempting to use a subquery with `assoc`, reporting here in case this is of interest. In this case would we write out the `assoc` manually?

> can only perform association joins on sources with a schema in query

code:

```
community = from(c in Community, where: c.id == 2, limit: 1)
query = from(c in Ecto.Query.subquery(community), join: posts in assoc(c, :posts), join: person in assoc(posts, :person), preload: [posts: {posts, person: person}])
```

Without a subquery, `community` causes the entire query (due to `limit: 1`) to return only 1 of each: Community, Post, and Person

**Comment by josevalim** [comment]
We may be able to solve this. I will investigate, thank you.
