### ISSUE TITLE
Allow prefix to be given as an option on Repo.preload

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1270]

**Comment by Tica2** [comment]
This was also my point here: 
https://github.com/elixir-lang/ecto/pull/1185/files

As long as Schema for preload need to have new schema (alter schema) in this case is solved also my case.

Can I come with some work/ideeas here ?

**Comment by josevalim** [comment]
Please do. The code today is wrong anyway because we are always overriding the prefix in the query. It is actually tricky to solve because when we have this:

    Repo.preload(data, [:account])

I can see sometimes folks would be interested in using the same prefix as data. And some other times, the same prefix as the one in the schema. So I see no better option than allowing the prefix to be given.

**Comment by Tica2** [comment]
Sorry for missing my feedback,
if `:account` has static prefix, what is used when we do not provide `prefix` for `preload`?

We need some tests here.

**Comment by josevalim** [comment]
It has been documented in the new commit. Preload will always use the collection value if an option is not given.

**Comment by Tica2** [comment]
ok, this is good.
I will test this part.
