### ISSUE TITLE
Rediscuss validate_required

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1274]
Some folks are starting to use validate_required and issues are starting to pop-up. In particular, we have two main issues:

1. cast and validate_required requires duplicating field names:

        User |> cast(params, [:name, :age]) |> validate_required([:name, :age])

  This is causing some confusion and some folks are forgetting the field names in `cast/3`

2. validate_required is always adding warnings, even when cast is called like `cast(User, :invalid)`. This doesn't happen with other validations because they only validate if a change was given, which is not the case with validate_required.

We need to discuss how to solve those issues or even if we should rollback to `cast/4` as before, but this time adding the validate_required string checks (so folks do not need to call scrub_params) on the Phoenix side.

/cc @chrismccord @paulcsmith @ericmj @michalmuskala

**Comment by stevedomin** [comment]
I didn't really like the mix of casting + validating required fields with `cast/4` so I'm quite happy with the new `cast/3` + `validate_required/2` functions.

Having said that, I ran into the exact problem you described with a Phoenix project and had to resort to using `Ecto.Changeset.change/2` to get an empty changeset. 

`cast/4` + validated_required string check seems like a good (the only?) solution to that problem.

**Comment by michalmuskala** [comment]
1. can be solved by keeping fields as a constant and passing in to both functions

2. can be solved by introducing `Ecto.Changeset.erase_errors/1` function that would drop all the errors from changeset, so that they don't show up in form.
Alternatively we could make `:invalid` prevent any validation functions from adding errors to the changeset, but this would probably require adding yet another field to the changeset, that already has a lot of them.

**Comment by josevalim** [comment]
@michalmuskala good point. 2 could be solved on the Phoenix.Ecto side by not adding errors to the form structure if there is no action in the changeset. It would effectively solve the problem listed here.

**Comment by josevalim** [comment]
If we adopt the suggestion above, then `:invalid` doesn't even have much purpose. We could use an empty map since we will use `changeset.action` as the driving factor to decide if we should show errors or not. I am inclined to give this a go because we would get rid of some complexities from a couple places. Thoughts?

**Comment by stevedomin** [comment]
@josevalim @michalmuskala Wouldn't that mean that `validate_required/2` would behave differently than the other `validate_` functions?

**Comment by josevalim** [comment]
@stevedomin it would but I don't see any way of making `validate_required` behave the same, since its goal is to validate exactly when there is no change (and all others are about validating only when there is a change).

**Comment by stevedomin** [comment]
@josevalim yes, that makes sense. In that case I'm :+1: on replacing `:invalid` by an empty map and using the changeset.action as the driving factor to decide whether to show errors or not.

In my project I used `Ecto.Changeset.change/2` as a temporary fix for the second issue you mentioned. Isn't that a valid workaround?

**Comment by josevalim** [comment]
@stevedomin the whole idea behind running validations without data is so we can collect validation as metadata to provide smarter forms. So calling `Ecto.Changeset.change/2` would bypass all of that.

@stevedomin can you please give phoenix_ecto master a try and let me know if it solves the issues you were seeing?

**Comment by stevedomin** [comment]
@josevalim interesting, I didn't know that. 

Will try phoenix_ecto master

**Comment by paulcsmith** [comment]
I really like the idea of removing the `:invalid` option and using an empty map. I think that is more clear anyway, and if it fixes the issues people are having with `validate_required` then that sounds even better! I also agree with @michalmuskala That using @attributes or some other constant would fix the first issue

Is `changeset.required` still "required fields as a list of atoms" or is it the permitted fields that you pass to `cast/3`? If it's the latter then I wonder if it would also make sense to throw an error in `validate_required` if you pass an atom to `validate_required` that was not permitted in `cast`

**Comment by stevedomin** [comment]
@josevalim phoenix_ecto master works great
