### ISSUE TITLE
Repo default priv folder

### ISSUE THREAD

**Issue by matrinox** [elixir-lang/ecto#1277]
### Environment

* Elixir version (elixir -v): 1.2.2
* Database and version: PostgreSQL 9.4
* Ecto version (mix deps): Ecto 2.0.0-beta1
* Database adapter and version (mix deps): postgrex 0.11.1
* Operating system: OS X 10.11.3

### Current behavior

Default folder name for a repo named App.Repo is: "priv/repo". If you add another repo called Second.Repo, it also has the same folder name: "priv/repo". This is because the code here:
https://github.com/elixir-lang/ecto/blob/master/lib/mix/ecto.ex#L113
takes the last name as the folder's name

### Expected behavior

It should name the folder "priv/namespace/repo" for a given repo called Namespace.Repo. Another alternative is "priv/namespace_repo". If the convention is to name repo's AppName.Repo, then this makes the most sense. I know it's not common but when it does happen, it's particularly confusing to see migrations get run on the other database! :(

**Comment by ericmj** [comment]
It's just a heuristic, you should set the `:priv` config instead.

**Comment by josevalim** [comment]
Just set the `:priv` option in your repository configuration. :)

**Comment by matrinox** [comment]
It still would be nice to get an error, at the very least, that there is a name conflict

**Comment by ericmj** [comment]
We can't show an error because the compilation of the two repos is completely decoupled. One repo doesn't know that any other repos exist. Also it is perfectly for two repos to share the same directory, in fact I would guess that is the common case.

**Comment by matrinox** [comment]
If that is recommended, then how to run specific migration for it's respective repo? Example:
2016-03-03...FirstRepoMigration1, 2016-03-04...FirstRepoMigration2, 2016-03-05...SecondRepoMigration1

**Comment by ericmj** [comment]
Pass the `-r` / `--repo` option to `ecto.migrate`.

https://hexdocs.pm/ecto/Mix.Tasks.Ecto.Migrate.html

**Comment by matrinox** [comment]
Doesn't that just run all migrations in the `priv/repo/migrations` fodler for that repo, instead of running just the related ones?

**Comment by ericmj** [comment]
You need to move the migrations to migration folder of the respective repo.
