### ISSUE TITLE
DateTime in queries inconsistencies

### ISSUE THREAD

**Issue by matrinox** [elixir-lang/ecto#1278]
### Environment

* Elixir version (elixir -v): 1.2.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.4
* Ecto version (mix deps): 2.0.0-beta1
* Database adapter and version (mix deps): postgrex 0.11.1
* Operating system: Mac OS X 10.11.3

### Current behavior

```elixir
from(a in "accounts", where: a.updated_at > "2016-02-23T19:26:46Z", select: a.id) |> Repo.all
[debug] SELECT a0."id" FROM "accounts" AS a0 WHERE (a0."updated_at" > '2016-02-23T19:26:46Z') [] OK query=17.7ms queue=0.3ms
[]
from(a in "accounts", where: a.updated_at > ^date_time, select: a.id) |> Chevron.Repo.all
** (ArgumentError) could not encode datetime: "2016-02-23T19:26:46Z"

This error happens when you are by-passing Ecto's Query API by
using either Ecto.Adapters.SQL.query/4 or Ecto fragments. This
makes Ecto unable to properly cast the type. For example:

    now = Ecto.DateTime.utc |> Calecto.DateTimeUTC.cast
    from u in User, where: fragment("(?).wall_time > ?", u.start_datetime, ^now)

In the query above, Ecto is unable to know the variable "now" is
being compared to a datetime due to the fragment and is therefore
unable to cast it. You can fix this by explicitly telling Ecto
which type must be used:

    fragment("(?).wall_time > ?",
      u.start_datetime,
      type(^now, :datetime))

Or by implementing the Ecto.DataType protocol for the given value.
```

### Expected behavior

(It would be nice if) it matched against a date/time string variable just the same as the actual string. It's counter-intuitive that this works:
```elixir
from(a in "accounts", where: a.updated_at > "2016-02-23T19:26:46Z")
```
but not this:
```elixir
datetime = "2016-02-23T19:26:46Z"
from(a in "accounts", where: a.updated_at > ^datetime)
```

I think for consistency's sake, either force it to always use Ecto.DateTime or support both (recommended)

**Comment by ericmj** [comment]
This is because of how casting works in postgres.

Postgres will automatically cast `datetime_value > text_value`. But when you are interpolating values ecto generates the following query `datetime_value > $1`, postgres will guess that the parameter for `$1` should be of the datetime type and tells the postgres driver/ecto this. So ecto will raise when it receives a string and it expects a datetime.

This is just something we have to live with, the error message tells you how to fix it; explicitly cast with `type(^date_time, :datetime)`.

**Comment by josevalim** [comment]
Yes, not much we can do.

**Comment by matrinox** [comment]
thank you @ericmj 
I hope someone figures out a way to solve this, it seems like it's possible.

**Comment by ericmj** [comment]
It won't be possible unless postgresql changes how it infers the types of parameters or ecto changes how it handles types, both are unlikely to happen any time soon. Explicitly casting solves the issue so I don't see the problem.
