### ISSUE TITLE
Repo.preload/3 fails with with cannot find ownership process

### ISSUE THREAD

**Issue by tokafish** [elixir-lang/ecto#1280]
### Environment

* Elixir version: 1.2.3
* Database: PostgreSQL 9.5.1
* Ecto version: master
* Database adapter and version: postgrex 0.11.1
* Operating system: MacOS

### Current behavior

In experimenting with hound and Ecto 2, I ran into what I believe could be a problem with `Ecto.Adapters.SQL.Sandbox` and the `Repo.preload` function. Here's failing test that I added to `Ecto.Integration.SandboxTest`, which I ran with `mix test.all`.

```
  test "can preload two associations when allowed from another process" do
    Sandbox.checkout(TestRepo)
    assert TestRepo.insert(%Post{})
    parent = self()

    Task.start_link fn ->
      Sandbox.allow(TestRepo, parent, self())
      assert [_] = TestRepo.all(Post) |> TestRepo.preload([:author, :comments])
      send parent, :success
    end

    assert_receive :success
  end
```

This test fails with a runtime error of "cannot find ownership process". It's worth noting that preloading works correctly if I make a few changes.

1. If I don't insert a post, everything works fine (nothing to preload)
2. Using preload via a keyword list works properly: `TestRepo.all(Post, preload: [:author, :comments])`
3. Using preload via TestRepo.preload works when preloading only one association: `TestRepo.all(Post) |> TestRepo.preload(:author)`

### Expected behavior

Ownership should be allowed to the processes started by Repo.preload.

**Comment by josevalim** [comment]
Thank you. This is happening because because `allow` is not transitive. I think we should support it in a way that if we allow from an allowed process, it will transparently propagate. @fishcakez, thoughts?

**Comment by josevalim** [comment]
@tokafish can you please try `db_connection` master?

    {:db_connection, github: "fishcakez/db_connection", override: true}

I will do a new release as soon it is confirmed it works and write a test for Ecto itself.

**Comment by tokafish** [comment]
@josevalim My test is now passing with db_connection master. Thanks for quickly fixing this!
