### ISSUE TITLE
Request to keep Repo.one undeprecated

### ISSUE THREAD

**Issue by vanstee** [elixir-lang/ecto#1281]
The addition of `Repo.first` and `Repo.last` in 2.0 is great and seems really useful, but it does not seem like a perfect drop-in replacement for `Repo.one`. I've been using `Repo.one` to say "this query, whether or not there is an explicit limit set, should only ever return a single result" which makes for some great intention revealing code. Now instead I would have to run `Repo.all` with a case statement to match that only a single value (or none) was returned. There were a few cases where I could replace our `Repo.one` call with `Repo.get_by` or `Repo.first` but in most cases we were using it to say that the database should only have 1 record matching this query. Here's an example from our codebase.

In Ecto 1.1.4 we had the following query:

```
    Repo.one!(from c in Command,
              join: b in assoc(c, :bundle),
              where: b.name == ^bundle,
              where: c.name == ^command)
```

We could switch this to use `Repo.first` but because `Repo.first` always adds a limit to the query, we would lose out on extra meaning of `Repo.one` to say, "we only ever expect this query to return a single value, otherwise blow up".

So far we've added a helper method to our codebase to give us the same functionality we had with `Repo.one` but would love to be able to use the existing function in the future. **So, is there anyway we could keep `Repo.one` and `Repo.one!` in Ecto 2.0?**

Also, if I missed any pass discussion that explains the deprecation, let me know. I couldn't find any pull requests that discussed that specifically.

**Comment by josevalim** [comment]
Thank you. The plan is to bring Repo.one and Repo.one! back and make both first and last to be functions in Ecto.Query.

**Comment by vanstee** [comment]
@josevalim Oh, great! :heart:

Do you expect this change to make it into the final 2.0 release?

**Comment by josevalim** [comment]
Definitely. They should be in the next beta.

**Comment by vanstee** [comment]
:+1: Feel free to close this or reword and leave as a reminder.

**Comment by josevalim** [comment]
Your wish has been granted. A new beta should be out soon! Thank you!

**Comment by vanstee** [comment]
Thanks so much @josevalim. I'll try out the new beta as soon as it drops.
