### ISSUE TITLE
Seemingly Random Failures on Mass Import

### ISSUE THREAD

**Issue by ybur-yug** [elixir-lang/ecto#1282]
### Environment

* Elixir 1.2.3
* Postgresql 9.4
* Ecto 1.1.3
* Postgrex 0.11.0
* Ubuntu 14.04 64 bit
* 12 CPU / 32GB RAM

### Current behavior
I have a directory of ~70 CSVs ranging from a few megabytes to ~7-10gb.

They sadly are not RFC compliant, and due to a myriad of other issues I am having to treat them as text files, stream them in, and manipulate from there using string methods.

Our process is as follows:

```
[
  # list of aboslute paths to files
]
|> File.stream!
|> Stream.chunk(1000)
|> Enum.map(fn(row) -> row |> text_row_to_map end)
|> Enum.map(fn(map) -> App.Property.changeset(%App.Property{}, map) |> App.Repo.insert! end)
```

There are no validations or callbacks whatsoever. Every field is listed as optional.

Right now, there are two really strange things that happen.

The more common of the two is a total crash of the Erlang VM.
I have a few `erl_crash.dump` files I can provide if needed for examination of that.
The other failure that pops up is:

```
    (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6
    (ecto) lib/ecto/adapters/sql.ex:551: Ecto.Adapters.SQL.transaction/3
    (ecto) lib/ecto/repo/schema.ex:14: Ecto.Repo.Schema.insert!/4
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1092: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1478: anonymous fn/3 in Enum.reduce/3
    (elixir) lib/stream.ex:1227: anonymous fn/3 in Enumerable.Stream.reduce/3
    (elixir) lib/stream.ex:164: anonymous fn/6 in Stream.chunk/4
    (elixir) lib/stream.ex:1101: Stream.do_resource/5
    (elixir) lib/stream.ex:1247: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:1477: Enum.reduce/3
    (elixir) lib/enum.ex:1092: Enum.map/2
```

Without any real meaningful errors. Just that stack trace.

### Expected behavior

Well this is quite the massive load. But I thought by stream/chunking and using such a large machine it would be OK.

The most it has gone without one of these two things occurring is 5,000,000 records. The quickest failure was after around 200,000 records.

I'm quite perplexed. I'm not sure if this is enough to really file an issue but @michalmuskala recommended I do after conferring in the Ecto Slack.

Happy Hacking & thanks for all the amazing work,
Bobby

**Comment by josevalim** [comment]
Can you please include the actual error message? Thank you.

**Comment by josevalim** [comment]
also, do you know *why* the vm is crashing? can you investigate your operating system logs? Maybe it is being killed by the OS due to lack of memory?

**Comment by josevalim** [comment]
Btw, you are also chunking and then mapping, which means the whole data set **is** being loaded into memory.

**Comment by ybur-yug** [comment]
@josevalim 

That actually is all that printed out other than the logs from the Raw SQL, the history in my terminal wont let me scroll back up to it but if it happens again I will make sure I catch all the output in a logfile this time.

I do not actually know the *why*, but I can give these observations:
  - the CPU usage floats around 20% on all cores
  - the memory utilization sits around 21gb/32gb (I have been monitoring with htop)

I am new at using streams etc so there is a reasonable change I am improperly using this. If I want to operate piece by piece without getting it all into memory, what should I be doing? My apologies if this is  naive/simple question. My grasp of the concept is tenuous but I am trying to learn.

**Comment by josevalim** [comment]
As soon as you call `Enum`, you will load the whole data into memory. This is what you want:

```elixir
...
|> Stream.chunk(1000)
|> Stream.map(fn(row) -> row |> text_row_to_map end)
|> Stream.each(fn(map) -> App.Property.changeset(%App.Property{}, map) |> App.Repo.insert! end)
|> Stream.run
```

You should have a more consistent memory usage. If you feel the memory is still growing, please let me know.

**Comment by ybur-yug** [comment]
Will do, thank you. I'm facepalming at myself right now because that is quite by the docs. Apologies.

I will let you know if with that change we stop having this problem. Will start running it again now.

**Comment by josevalim** [comment]
Great. I will close this for now but ping back and we can follow up on it.
