### ISSUE TITLE
Increase ownership timeout

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1287]
See discussion: https://groups.google.com/forum/#!topic/elixir-ecto/1ntidVW_qro

We need to decide if we are increasing this on db_connection or ecto side.

**Comment by mitchellhenke** [comment]
is there a workaround in the mean time?

I think I'm seeing it with Ecto 1.1.4 and Postgrex 0.11.0

**Comment by josevalim** [comment]
This is specific to Ecto 2.0 so you are likely seeing something else. :)

**Comment by fishcakez** [comment]
I think it would be nice t have the same defaults in db_connection as ecto to keep things simple and a good decision in one is going to be a good decision in another. What would the timeout be increased to? `:infinity`? A non-infinity timeout is currently the default so that any leaks get caught.

**Comment by josevalim** [comment]
@fishcakez it depends. If we can improve the error message, I think we would be fine with a timeout of 15 or 30 seconds, because we can use the error to say "your timeout is low, please increase it". Otherwise, I would go for something closer to 120 seconds or possibly infinity.

**Comment by fishcakez** [comment]
Beyond 15 seconds leak may not get caught so I think we would be better to improve this error message and perhaps other DBConnection.Error messages.

**Comment by josevalim** [comment]
Done in DBConnection.
