### ISSUE TITLE
Add type {:map, type}

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ecto#1291]
I created this issue per discussion on https://github.com/hexpm/hex_web/issues/205. An example of how this could be used is the following (inspired by HexWeb use case, but simplified):

```elixir
defmodule Package do
  use Ecto.Schema

  schema "packages" do
    field :name, :string
    field :links, {:map, :string}
  end
end

%Package{name: "Ecto", links: %{"GitHub" => "https://github.com/elixir-lang/ecto"}}
```

**Comment by ericmj** [comment]
I don't think we should allow setting the key since both postgres json and mongo bson only allows setting string keys.

**Comment by wojtekmach** [comment]
@ericmj ah, that's what you meant with just {:map, TYPE}. That makes sense, I'll update the proposal.
