### ISSUE TITLE
has_many :through multiple levels, assoc/2 returns error

### ISSUE THREAD

**Issue by arashb31** [elixir-lang/ecto#1299]
* Elixir version (elixir -v): 1.1.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): pg 9.4
* Ecto version (mix deps): 1.1.4
* Database adapter and version (mix deps): postgresx 0.11.1
* Operating system: Mac OS X / Ubuntu

### Current behavior

schema: 
user has_many :rooms
user has_many :comments :through :rooms
user has_many :comment_users through :comments

I have a current_user object.

cs = Ecto.model.assoc(current_user, :comment_users)  |> Repo.all   **throws error: no function clause matching in Ecto.Association.HasThrough.assoc_to_join/2**

bs = Ecto.Model.assoc(current_user, :comments) works fine, as does
as = Ecto.Model.assoc(current_user, :rooms)

It appears Ecto.Model.assoc/2 doesn't work on has_many through through

**Comment by josevalim** [comment]
Can you please provide a proper schema? Your schema is not valid because through: always expects a list with two associations.
