### ISSUE TITLE
Insert with empty association

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ecto#1305]
### Environment

* Elixir version (elixir -v): 1.3.0-dev
* Database and version: PostgreSQL 9.4
* Ecto version (mix deps): master

### Current behavior

```elixir
defmodule Post do
  use Ecto.Schema
  import Ecto
  import Ecto.Changeset

  schema "posts" do
    field :title, :string
    field :body, :string

    has_many :comments, Comment
  end

  def changeset(post, params \\ %{}) do
    cast(post, params, ~w(title body))
    |> cast_assoc(:comments)
  end
end

defmodule Comment do
  use Ecto.Schema
  import Ecto.Changeset

  schema "comments" do
    field :body, :string

    belongs_to :post, Post
  end

  def changeset(comment, params \\ %{}) do
    cast(comment, params, ~w(body))
  end
end
```

When inserting with association data, everything is OK:

```elixir
post = Post.changeset(%Post{}, %{title: "Post 1", comments: [%{body: "Comment 1"}]}) |> Repo.insert!
[%{body: "Comment 1"}] = post.comments
```

When inserting with empty association data, the association is marked as not loaded even though it's gonna be almost always empty [1]

```elixir
post = Post.changeset(%Post{}, %{title: "Post 1", comments: []}) |> Repo.insert!
post.comments # => #Ecto.Association.NotLoaded<association :comments is not loaded>
```
### Expected behavior

When inserting a new record, empty assoc should be loaded and empty:

```elixir
post = Post.changeset(%Post{}, %{title: "Post 1", comments: []}) |> Repo.insert!
[] = post.comments

post = Post.changeset(%Post{}, %{title: "Post 1"}) |> Repo.insert!
[] = post.comments
```

[1] if there're no fk constraints, there could be a comment referencing newly created post, and having the association be `[]` could be considered incorrect, however the same could be said for 1st case I mentioned above when inserting new record with associations data.

**Comment by wojtekmach** [comment]
Could someone verify if the expected behavior I proposed makes sense? If so, I'm happy to take a stab at implementing it at some point. Thanks!

**Comment by josevalim** [comment]
Yes, it is.

**Comment by josevalim** [comment]
Actually, let me clarify. The association should be marked as an empty list or nil ONLY IF it is marked as an empty list or nil BEFORE insertion. If it is NotLoaded before insertion, it should still be NotLoaded after insertion.

**Comment by wojtekmach** [comment]
Thanks @josevalim. Sorry if it's a silly question, but what would be a concrete example where we want to keep NotLoaded after new record was just inserted?

Assuming FKs are correctly set (see footnote above, perhaps we can't make that assumption though? Or we would make it but also document it, perhaps?) when using has_one, has_many I think we can safely default to `nil` or `[]` even if the association wasn't explicitly specified when inserting - that's the 2nd code snippet in the expected behaviour.

For `belongs_to`, NotLoaded would make sense if user would e.g. cast `author_id` with a non-nil value. If the user would `cast_assoc(:author)` and **wouldn't** cast `author_id` we could sensibly load it as `nil` by default. If the user would allow to both cast author_id and cast_assoc then it would be a problem :)

I'm not sure what exactly needs to change to make this work and as you can probably see I was looking at this issue from the cast/cast_assoc perspective. Also, perhaps I'm making this unnecessarily complicated :) I'll start with proper handling for casting assoc with `nil` or `[]`.

**Comment by josevalim** [comment]
> see footnote above, perhaps we can't make that assumption though? Or we would make it but also document it, perhaps?

That's my biggest concern. I would prefer to not do this assumption at this moment.

**Comment by wojtekmach** [comment]
@josevalim :+1:

**Comment by wojtekmach** [comment]
@josevalim damn, I was almost there (https://github.com/wojtekmach/ecto/commit/bdc9f12a1c6ee433cf1bac12797acebd7ab6a230) but definitely were missing a few pieces. Thanks for fixing it!
