### ISSUE TITLE
Bad Gettext interpolation keys when validating numbers

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/ecto#1308]
### Environment

* Ecto version (mix deps): 2.0.0-beta.2

### Current behavior

In Phoenix, we translate Ecto errors using `Gettext.dngettext/6`. In the [relevant snippet of code](https://github.com/phoenixframework/phoenix/blob/f43f8a7fc4101bfe271dfadd6f378b3ed27df741/installer/templates/new/web/views/error_helpers.ex#L29):

```elixir
  def translate_error({msg, opts}) do
    # Because error messages were defined within Ecto, we must
    # call the Gettext module passing our Gettext backend. We
    # also use the "errors" domain as translations are placed
    # in the errors.po file. On your own code and templates,
    # this could be written simply as:
    #
    #     dngettext "errors", "1 file", "%{count} files", count
    #
    Gettext.dngettext(MyApp.Gettext, "errors", msg, msg, opts[:count], opts)
  end
```

So, we pass `opts[:count]` as the 5th argument to `Gettext.dngettext/6`: according to [the documentation for `Gettext.dngettext/6`](https://hexdocs.pm/gettext/Gettext.html#dngettext/6), that argument should be a `non_neg_integer` (as it's the number of items that will allow gettext to decide how to pluralize the translation).

In Ecto, we use the following error messages to validate numbers (code is [here](https://github.com/elixir-lang/ecto/blob/2d1a2eecdc691c86aa98f261e9eddb880a7c411c/lib/ecto/changeset.ex#L164-L170)):

```elixir
  @number_validators %{
    less_than:                {&</2,  "must be less than %{count}"},
    greater_than:             {&>/2,  "must be greater than %{count}"},
    less_than_or_equal_to:    {&<=/2, "must be less than or equal to %{count}"},
    greater_than_or_equal_to: {&>=/2, "must be greater than or equal to %{count}"},
    equal_to:                 {&==/2, "must be equal to %{count}"},
  }
```

Here, we use `count` as the interpolation key for the value of the number field we're validating. However, `validate_number/3` also supports `Decimal`s and floats, and if there's an error, they end up being passed in the bindings (i.e., `[count: #Decimal<1.2>]`).

All of this amounts to a `FunctionClauseError` when `translate_error/1` from the Phoenix error helper is called with `opts = [count: x, ...]` with `x` being a non-integer.

### Expected behavior

This should not fail, of course :smile_cat:.

### Proposed solution

My proposed solution is to change the error messages in Ecto to not use `count` as the interpolation key (which I also believe being misleading but that's another story :grin:), and replace it with something like `number` instead. Then, in the Phoenix error helper, we could do:

```elixir
Gettext.dngettext(MyApp.Gettext, "errors", msg, msg, opts[:count] | | 1, opts)
```

so that we're safe from when `:count` is not in the passed options; this makes sense to me as many times (and number validation is one of these cases) we use plural translations just as a workaround, but we never actually use the `msgid_plural`.

I'd be happy to work on this if you want :)

**Comment by michalmuskala** [comment]
I'm personally not sure if it makes sense to pluralize number validators at all. In general you pluralize when you have a quantity and a noun that is in such quantity, but here there's no noun, therefore there's nothing to pluralize.

**Comment by josevalim** [comment]
Exactly.

On Thursday, March 10, 2016, Michał Muskała <notifications@github.com>
wrote:

> I'm personally not sure if it makes sense to pluralize number validators
> at all. In general you pluralize when you have a quantity and a noun that
> is in such quantity, but here there's no noun, therefore there's nothing to
> pluralize.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1308#issuecomment-194837976>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by whatyouhide** [comment]
Oh, of course. I assumed you kept the messages plural to make things extensible in the future or who knows what else :stuck_out_tongue: If we can use `dgettext`, than that's better :) Should I still go and rename `count` in the Ecto error messages or do we leave it like this (at least for the time being)?

**Comment by amencarini** [comment]
Renaming `count` and using `dgettext` does not seem to help:

```
** (exit) an exception was raised:
    ** (Gettext.Error) missing interpolation keys: count
        (gettext) lib/gettext.ex:623: Gettext.handle_backend_result/1
        (ecto) lib/ecto/changeset.ex:1805: anonymous fn/3 in Ecto.Changeset.merge_error_keys/2
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/changeset.ex:1799: Ecto.Changeset.traverse_errors/2
```

But I'm surely doing something silly.

**Comment by whatyouhide** [comment]
@amencarini you'd have to change Ecto to pass something different than `count` in the bindings [here](https://github.com/elixir-lang/ecto/blob/master/lib/ecto/changeset.ex#L1265) (and a few lines below).

**Comment by amencarini** [comment]
@whatyouhide yes, that's exactly what I did, used `number` as you suggested.

**Comment by amencarini** [comment]
Ok, my bad, I forgot to amend the actual strings passed.
Changing the po files, `@number_validators`, and the `validate_number` functions work; there's also the need to accommodate singular errors with bindings in `ErrorsHelper` in Phoenix but that's outside the scope of this issue.

**Comment by josevalim** [comment]
I think we should always emit `{message, kw}`. Phoenix will call dngettext only if it has a :count key.
