### ISSUE TITLE
Unique constraints wrapped in Repo.Transaction lose the ability to access the changeset

### ISSUE THREAD

**Issue by Anujan** [elixir-lang/ecto#1314]
### Environment

* Elixir version (elixir -v): 1.2.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgresql 9.4
* Ecto version (mix deps): 1.1.4
* Database adapter and version (mix deps): Postgrex 0.11.1
* Operating system: Ubuntu

### Current behavior
User model has unique_constraint(:email)
````elixir
    Repo.transaction fn ->
        #add the user
        case Repo.insert change do
          {:ok, new_user} ->
            generate_logins(new_user, change.changes.password_hash)
            |> log_it("Registration", "New registration for #{new_user.email}", params["ip"])
            |> user_with_token

          {:error, changeset} -> {:error, changeset.errors}
        end
      end
````

This returns {:error, :rollback} when there's a duplicate email being inserted so the result of `Repo.insert` is lost. I'd expect it would return {:error, changeset.errors} instead, but since `Repo.transaction` returns the value of `rollback`, this is lost.

**Comment by josevalim** [comment]
Yes, you must call `Repo.rollback(changeset.errors)` if something goes wrong so the information is propagated upstream. If you believe the docs could be better on this matter, PRs are really welcome! Thank you!
