### ISSUE TITLE
Release a new Ecto 1.x that depends on latest mariaex

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1316]

**Comment by ericmj** [comment]
We already have the (somewhat redundant) requirement `~> 0.5 or ~> 0.6` that will match latest mariex.

**Comment by josevalim** [comment]
Yeah, the goal was to be ~> 0.5.0 or ~> 0.6.0. So we either need to update
the requirement or depend on latest mariaex.



*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Released 1.1.5 with a proper requirement for now.

**Comment by narkq** [comment]
Will there be an Ecto 1.x release that's compatible with mariaex 0.7.0?
