### ISSUE TITLE
Allow select into a map key (currently results in compilation error).

### ISSUE THREAD

**Issue by iguberman** [elixir-lang/ecto#1317]
Verified the validity of this request first at https://groups.google.com/forum/#!topic/elixir-ecto/NjNRZPj5YxA
and got @josevalim approval.  Thanks Jose!   Details/examples below copied from the forum topic just in case.

When I saw that I can Ecto-select into a map of arbitrary formatting I was overjoyed: 

Format I was using at first was
```
{"stages" : 
    [{ "stage" : "1000",
      "name" : "blah", 
      "parameters" : {}, 
      "enabled" : "true" }
    },
...
]
}
```

```
from t in Task,
where: t.type_id == ^type_id,
select: %{
           "stage" => [fragment("?->>?", t.definition, "stage")], 
           "name" => fragment("?->>?", t.definition, "task_name"),
           "parameters" => t.config,
           "enabled" => true
        }
```

Until it turned out that JSON I need to produce is slightly different and can not be changed because too much depends on its format already: 
```
{"stages":
  ["1000" : { 
     "name" : "blah",
    "parameters" : {}.
    "enabled" : "true"
  }
...
 ]
}
```

To support this format I changed my code, but it produced compilation error:

```
from t in Task,
where: t.type_id == ^type_id,
select: %{ fragment("?->>?", t.definition, "stage")=> %{
           "name" => fragment("?->>?", t.definition, "task_name"),
           "parameters" => t.config,
           "enabled" => true
          }
        }
```

```
== Compilation error on file web/controllers/execution_controller.ex ==

** (Ecto.Query.CompileError) keys can only be atoms/binaries/integers/floats

    expanding macro: Ecto.Query.select/3

    web/controllers/execution_controller.ex:176: PipelineOperations.ExecutionController.tasks/2

    expanding macro: Ecto.Query.from/2

    web/controllers/execution_controller.ex:176: PipelineOperations.ExecutionController.tasks/2

    (elixir) expanding macro: Kernel.|>/2

    web/controllers/execution_controller.ex:186: PipelineOperations.ExecutionController.tasks/2

    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

The problem is now `[fragment("?->>?", t.definition, "stage")]` becomes map key instead of value in the map.  It retrieves a string from the table, i.e. "1000", "1200", etc. -- after the first pass, but isn't itself a string during compile time which seems like unnecessary limitation. Ecto knows the ultimate result of selecting a specific column, it knows it results in either string, integer, etc. because it has the actual models at its disposal even during compile time, yet the compile error is there.   Either for my case above or for numerous other cases.  For instance when people store actual metadata in the db tables.  (I.e. this type of task has these fields, and that type of task has other fields, so immediately your "map" keys become the stuff retrieved from db rather than stuff that's determined somewhere in your elixir code).  So in these cases, second pass will be required).  
 Second pass is ok, but totally takes away all the awesomeness of this feature :( 

P.S.   Just realized, mine isn't the best example because in case of JSON Ecto actually has no guarantee we're not retrieving something unsuitable for a map key (i.e. value is a map itself), which justifiably isn't allowed, but still this should be up to the developer to make the call, and this should be run-time problem rather than compile-time problem. If at runtime we retrieve a value not suitable for map key, THEN it should raise runtime exception.

**Comment by josevalim** [comment]
Added in Ecto master. :)

**Comment by iguberman** [comment]
Sorry, upgraded and tested just now, but thank you so much!  Works like a charm and my code is so much more elegant! :)
