### ISSUE TITLE
Averages of integers yield a #Decimal

### ISSUE THREAD

**Issue by jfrolich** [elixir-lang/ecto#1318]
### Current behavior

Currently averages of an integer type yield a Decimal. This makes it hard to use as there does not seem to be a straightforward way to convert Decimals to a Float without converting the Decimal to a String and parsing that as a float. When calculating an average I do not really see the benefits of Decimal, are there benefits. (Perhaps it is more precise in some scenarios?). 

Is this expected behavior, or would it make more sense to return a native float? Otherwise I guess a lot of use cases have a need to convert it to a float for further processing or to put the resulting calculation back in the database (in a float field), so perhaps it would make sense to have a to_float function on Decimal.

**Comment by josevalim** [comment]
@jfrolich yes, please open up issues on Decimal to have to_integer and to_float, although Decimal is the best representation here.

**Comment by ericmj** [comment]
You can also cast the decimal to a float in your query.

**Comment by jfrolich** [comment]
@ericmj A short example how to do that in Ecto? (should be a frequent use case, but cannot find any examples). The Ecto.Type.cast does not convert Decimal to float.

@josevalim it might be very obvious to Ecto experts, but also for future reference, I am very curious why a decimal is the best representation in this case? (A few words, references would suffice for me for me :))

**Comment by ericmj** [comment]
> A short example how to do that in Ecto? (should be a frequent use case, but cannot find any examples). The Ecto.Type.cast does not convert Decimal to float.

`select: fragment("?::float", avg(x.value))`

> it might be very obvious to Ecto experts, but also for future reference, I am very curious why a decimal is the best representation in this case? (A few words, references would suffice for me for me :))

The database itself stores the numeric value in an arbitrary precision number. If ecto converts from that number to a float we are loosing data since float has limited precision.

**Comment by jfrolich** [comment]
@ericmj: Thanks so much!
