### ISSUE TITLE
Memory issues with 2.0.0-beta on Ubuntu/Debian?

### ISSUE THREAD

**Issue by tmjoen** [elixir-lang/ecto#1328]
### Environment

* Elixir version (elixir -v): 1.2.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.4
* Ecto version (mix deps): 2.0.0-beta.2
* Database adapter and version (mix deps): postgrex 0.11.1
* Operating system: Ubuntu 14.04LTS / Debian jessie / OSX 10.11.3 El Capitan

### Current behavior

I started with a brand new Phoenix installation on a Ubuntu 14.04 LTS image.

```
iex(exrm_tester@vagrant-ubuntu-trusty-64)1> :erlang.memory
[total: 15617320, processes: 4282024, processes_used: 4281984, system: 11335296,
 atom: 331249, atom_used: 304968, binary: 38424, code: 7984132, ets: 507904]
```

Looks great!

Now I changed the deps a bit -> upgrading phoenix_ecto to ~> 3.0.0.-beta.

```
iex(exrm_tester@vagrant-ubuntu-trusty-64)1> :erlang.memory
[total: 70477264, processes: 5548200, processes_used: 5548160, system: 64929064,
 atom: 331249, atom_used: 312315, binary: 52618896, code: 8680146, ets: 760360]
```

Binary memory is suddenly 1000x +.

So which deps change between these two versions?

```diff
  connection: 1.0.2
  cowboy: 1.0.4
  cowlib: 1.0.2
  db_connection: 0.2.4
  decimal: 1.1.1
- ecto: 1.1.5
+ ecto: 2.0.0-beta.2
- phoenix_ecto: 2.0.1
+ phoenix_ecto: 3.0.0-beta.2
  phoenix_html: 2.5.1
  plug: 1.1.2
- poison: 1.5.2
+ poison: 2.1.0
  poolboy: 1.5.1
  postgrex: 0.11.1
  ranch: 1.2.1
```

I roll back everything to scratch, clean the deps and application itself.

First I upgrade Poison to 2.1.0 - no change.
Then I upgrade Ecto to 2.0.0-beta - and the binary memory balloons to 50mb +.

Similar experiment on OSX:

Ecto 1.1.5

```
iex(1)> :erlang.memory
[total: 34034760, processes: 6385376, processes_used: 6369384, system: 27649384,
 atom: 463441, atom_used: 442944, binary: 485240, code: 12593562, ets: 5595968]
```

Ecto 2.0.0-beta.2

```
iex(1)> :erlang.memory
[total: 45809560, processes: 7287344, processes_used: 7286304, system: 38522216,
 atom: 463441, atom_used: 450216, binary: 10333128, code: 13284882,
 ets: 5855504]
```

So ~ 20x more binary memory used.

Using `recon` to poke around in the Ubuntu application (since that was where the biggest discrepancy was found):

```
iex(16)> :recon_alloc.memory(:allocated_types)
[binary_alloc: 52723752, driver_alloc: 1179688, eheap_alloc: 4874280,
 ets_alloc: 7471144, fix_alloc: 1179688, ll_alloc: 25165824, sl_alloc: 131112,
 std_alloc: 1179688, temp_alloc: 131112]
```

```
iex(1)> :recon_alloc.fragmentation(:current)
[{{:ll_alloc, 0},
  [sbcs_usage: 1.0, mbcs_usage: 0.7790339787801107, sbcs_block_size: 0,
   sbcs_carriers_size: 0, mbcs_block_size: 19605032,
   mbcs_carriers_size: 25165824]},
 {{:ets_alloc, 0},
  [sbcs_usage: 1.0, mbcs_usage: 0.7491650542406892, sbcs_block_size: 0,
   sbcs_carriers_size: 0, mbcs_block_size: 5597120,
   mbcs_carriers_size: 7471144]},
 {{:std_alloc, 0},
  [sbcs_usage: 1.0, mbcs_usage: 0.15621757617268295, sbcs_block_size: 0,
   sbcs_carriers_size: 0, mbcs_block_size: 184288,
   mbcs_carriers_size: 1179688]},
 {{:fix_alloc, 0},
  [sbcs_usage: 1.0, mbcs_usage: 0.1737476349678898, sbcs_block_size: 0,
   sbcs_carriers_size: 0, mbcs_block_size: 204968,
   mbcs_carriers_size: 1179688]},
 {{:binary_alloc, 0},
  [sbcs_usage: 0.9988469869548287, mbcs_usage: 0.4165915055506202,
   sbcs_block_size: 52532000, sbcs_carriers_size: 52592640,
   mbcs_block_size: 491448, mbcs_carriers_size: 1179688]},
 {{:eheap_alloc, 0},
  [sbcs_usage: 0.883777296686747, mbcs_usage: 0.8209444215565103,
   sbcs_block_size: 600912, sbcs_carriers_size: 679936,
   mbcs_block_size: 3012912, mbcs_carriers_size: 3670056]},
 {{:temp_alloc, 0},
  [sbcs_usage: 1.0, mbcs_usage: 0.0, sbcs_block_size: 0, sbcs_carriers_size: 0,
   mbcs_block_size: 0, mbcs_carriers_size: 131112]},
 {{:sl_alloc, 0},
  [sbcs_usage: 1.0, mbcs_usage: 0.0039660748062725, sbcs_block_size: 0,
   sbcs_carriers_size: 0, mbcs_block_size: 520, mbcs_carriers_size: 131112]},
 {{:driver_alloc, 0},
  [sbcs_usage: 1.0, mbcs_usage: 0.5465861248398316, sbcs_block_size: 0,
   sbcs_carriers_size: 0, mbcs_block_size: 71664, mbcs_carriers_size: 131112]}]
```

```
iex(3)> :recon_alloc.average_block_sizes(:current)
[binary_alloc: [mbcs: 2369.2549019607845, sbcs: 2.6266e6],
 driver_alloc: [mbcs: 404.8813559322034, sbcs: 0],
 eheap_alloc: [mbcs: 9395.913312693498, sbcs: 600912.0],
 ets_alloc: [mbcs: 512.226442658875, sbcs: 0],
 fix_alloc: [mbcs: 176.93264248704662, sbcs: 0],
 ll_alloc: [mbcs: 737.6230552674471, sbcs: 0], sl_alloc: [mbcs: 520.0, sbcs: 0],
 std_alloc: [mbcs: 836.2714932126697, sbcs: 0], temp_alloc: [mbcs: 0, sbcs: 0]]
```

I originally opened an issue with exrm, since I thought there was something wrong with release packaging on Ubuntu vs OSX, but the problem exists when running the application from `mix` as well.

The issue is here (has some background on the problem) -> https://github.com/bitwalker/exrm/issues/314

### Expected behavior

Less memory usage on Linux?

**Comment by josevalim** [comment]
So the memory growth happens only on Linux and not on OSX? Also, are you running any query or is this right after bootstraping? Finally, are both machines using the same PostgreSQL version?

**Comment by tmjoen** [comment]
The memory growth happens on OSX too, but not to the same extent.

Linux: 38kb ==> 52.62mb
OSX: 485.24kb ==> 10.3mb

Not running any queries, this is right after bootstrapping.

Postgres 9.4 on both OSX and Ubuntu. I also tried 9.5 on Ubuntu with same results.

**Comment by josevalim** [comment]
@tmjoen I am pretty sure this is related to the Postgrex type cache. It needs to reach the database and load all types. You can probably reproduce it with a single that app that has postgrex and starts a connection. Are you connecting to an existing server with possibly a lot of extensions on Linux? It is probably being caused by this issue: https://github.com/ericmj/postgrex/issues/167

/cc @ericmj

**Comment by tmjoen** [comment]
Thank you for investigating!

The server is a fresh Postgresql 9.4 on Ubuntu, with default configuration.

**Comment by tmjoen** [comment]
I tried a new mix project with only Postgrex on Ubuntu 14.04LTS + Postgres 9.4:

```
iex(1)> :erlang.memory
[total: 25056520, processes: 5038768, processes_used: 5038768, system: 20017752,
 atom: 388601, atom_used: 378770, binary: 388072, code: 11237647, ets: 5265432]
iex(2)> {:ok, pid} = Postgrex.start_link(hostname: "localhost", username: "postgres", password: "postgres", database: "exrm_tester_dev")
{:ok, #PID<0.144.0>}
iex(3)> :erlang.memory
[total: 29738480, processes: 5351208, processes_used: 5351208, system: 24387272,
 atom: 429569, atom_used: 398192, binary: 3039008, code: 12662918, ets: 5454480]
```

**Comment by josevalim** [comment]
A new server is growing only 3MB? Interesting.

**Comment by tmjoen** [comment]
Well, yes, with only Postgrex.

A new server with Ecto 2 grows ~ 50mb.

**Comment by josevalim** [comment]
Ok. So the issue seems to be definitely be in Ecto 2. Can you try changing the pool size and let us know if that increases or reduces this number? Btw, can you push the new server with Ecto 2 to GitHub?

**Comment by tmjoen** [comment]
I misspoke a little:

A new server with Ecto 2 grows ~ 27mb
With Phoenix + Ecto 2 ~ 50mb

Here is an example project with Ecto 2 which grows 27mb

https://github.com/tmjoen/ecto2_mem

**Comment by josevalim** [comment]
One last question: what is your Erlang version and how have you installed it?

**Comment by tmjoen** [comment]
Ubuntu: Elixir 1.2.3 and OTP 18.2.4. Installed through the erlang-solutions repo.
OSX: Elixir 1.2.3 and OTP 18.2.4. Installed through homebrew

**Comment by fishcakez** [comment]
> The memory growth happens on OSX too, but not to the same extent.
> 
> Linux: 38kb ==> 52.62mb
> OSX: 485.24kb ==> 10.3mb

can you try the config in your Repo?

```elixir
socket_options: [recbuf: 8192, sndbuf: 8192]
```

In Ecto 2.0 we have non-lazy connections and this could explain the difference between OS's as postgrex sets the erlang socket buffer size based on the default kernel recbuf/sndbuf.

**Comment by tmjoen** [comment]
My Ecto example without `socket_options`:

```
iex(1)> :erlang.memory
[total: 53781160, processes: 5485808, processes_used: 5485768, system: 48295352,
 atom: 429569, atom_used: 401880, binary: 26753176, code: 12780669,
 ets: 5505360]
```

.. and with `socket_options`

```
iex(1)> :erlang.memory
[total: 27731472, processes: 5534272, processes_used: 5534232, system: 22197200,
 atom: 429569, atom_used: 401880, binary: 654720, code: 12780789, ets: 5505552]
```

My production release without `socket_options`:

```
iex(exrm_test@diamond)1> :erlang.memory
[total: 106795432, processes: 10983040, processes_used: 10982968,
 system: 95812392, atom: 850857, atom_used: 829114, binary: 53216120,
 code: 34490144, ets: 1971952]
```

.. and with `socket_options`

```
iex(exrm_test@diamond)1> :erlang.memory
[total: 54625080, processes: 10987992, processes_used: 10979360,
 system: 43637088, atom: 850857, atom_used: 828956, binary: 1041528,
 code: 34490296, ets: 1972040]
```

Ding ding ding! Thanks! I was afraid I had lost my mind the last week!

**Comment by josevalim** [comment]
@fishcakez should we set defaults in Postgrex/Mariaex then?

**Comment by fishcakez** [comment]
I don't think we need because the OS should make reasonable decision but maybe we can improve documentation? When we set the `:buffer` (this is what is using the binary memory I think) we could limit it when we set it - if `:buffer` is not part of `socket_options`.
