### ISSUE TITLE
No Gettext entry for `unique_constraint/3` error message

### ISSUE THREAD

**Issue by hauleth** [elixir-lang/ecto#1332]
### Environment

* Elixir version (elixir -v):

  ```
  Erlang/OTP 18 [erts-7.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

  Elixir 1.2.3
  ```
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): `VERSION = PostgreSQL 9.4.6`
* Ecto version (mix deps):

  ```
  * ecto 1.1.5 (Hex package) (mix)
    locked at 1.1.5 (ecto)
  * phoenix_ecto 2.0.1 (Hex package) (mix)
    locked at 2.0.1 (phoenix_ecto)
  ```
* Database adapter and version (mix deps):

  ```
  * postgrex 0.11.1 (Hex package) (mix)
    locked at 0.11.1 (postgrex)
  ```
* Operating system: `Linux NiunioBook 4.2.0-34-generic #39-Ubuntu SMP Thu Mar 10 22:13:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

### Description

Currently `mix gettext.extract` is unable to generate translation for `unique_constraint/3` error message `has already been taken`.

**Comment by josevalim** [comment]
Can you please open the issue on Phoenix? Afaik, the message in both .po and .pot files: https://github.com/phoenixframework/phoenix/blob/master/installer/templates/new/priv/gettext/errors.pot#L16 and https://github.com/phoenixframework/phoenix/blob/master/installer/templates/new/priv/gettext/en/LC_MESSAGES/errors.po#L18
