### ISSUE TITLE
Passing 'loggers' to 'use Ecto.Repo' has no effect

### ISSUE THREAD

**Issue by alco** [elixir-lang/ecto#1342]
This is done in https://github.com/elixir-lang/ecto/commit/1076c178f4fad0fd9387473830c434d874f19386#diff-b6be78dbea00d8fa0483ccbc0f827b67R5, however that option is simply ignored [here](https://github.com/elixir-lang/ecto/blob/0c004ff91ddfd2fb5bc53a263ab38303339076d3/lib/ecto/repo.ex#L93).

**Comment by josevalim** [comment]
Yes, it was changed in latter commits and must be passed as part of Application.get_env.
