### ISSUE TITLE
Typo in Changeset 'optimistic locking' example code

### ISSUE THREAD

**Issue by JohanVanZyl** [elixir-lang/ecto#1344]
The example code for optimistic locking in Changesets assigns a changeset to a variable named 'stable_change': 
```iex> stable_change = Post.changeset(:update, post, %{title: "baz"})```
Three lines later, it attempts to update the Repo, but refers to a 'stale_change' variable, which does not exist:
```iex> Repo.update!(stale_change)```

The variable should probably be changed from 'stable_change' to 'stale_change'.

**Comment by josevalim** [comment]
@JohanVanZyl perfect. could you please send a pull request? THank you!

**Comment by JohanVanZyl** [comment]
Sorry about that, it seems to have been fixed already. I was looking at [hexdocs](https://hexdocs.pm/ecto/Ecto.Changeset.html#optimistic_lock/3) v1.1.5

**Comment by josevalim** [comment]
evenbetter, thank you!
