### ISSUE TITLE
mix ecto.drop dont't drop test db in phoenix

### ISSUE THREAD

**Issue by maxgronlund** [elixir-lang/ecto#1346]
* Elixir version: 1.2.2
* Database and version PostgreSQL 9.4.5
* Ecto version: 2.0
* Database adapter and version {:phoenix_ecto, "~> 2.0"},  {:postgrex, ">= 0.0.0"},
* Operating system: OS X 10.11.1

Love Ecto ++ this issu might be a phoenix issue so forgive me if I'm wrong

first $ mix ecto.rollback 
then did some changes in the migrations
then  $ mix ecto.migrate
then test_db was out of sync
then mix ecto.drop; mix ecto.create
then the test_db was still out of sync
then I look with psql 
then mix ecto.drop
I can see my test db is still there
then I delete my development and test db from the terminal
then mix  mix ecto.create
now my test db is in sync

Keep it up Ecto rocks

**Comment by josevalim** [comment]
Hey @maxgronlund! You need to pass the environment if you want to create/delete the database for other environments:

    MIX_ENV=test mix ecto.create
    MIX_ENV=test mix ecto.drop

**Comment by maxgronlund** [comment]
Got it, thnx
