### ISSUE TITLE
order_by doesn't work with has_many through association

### ISSUE THREAD

**Issue by YoussefKababe** [elixir-lang/ecto#1353]
### Environment

* Elixir version: 1.2.3
* Database and version: PostgreSQL 9.5.2
* Ecto version: 1.1.3
* Database adapter: postgrex 0.11.0
* Operating system: Ubuntu 14.04

### Current behavior

I have a many to many association between `User` and `Conversation`:

```elixir
# models/user.ex

has_many :users_conversations, Application.UserConversation
has_many :conversations, through: [:users_conversations, :conversation]
```

```elixir
# models/conversation.ex

has_many :users_conversations, Application.UserConversation
has_many :users, through: [:users_conversations, :user]
```

```elixir
# models/user_conversation.ex

belongs_to :user, Application.User
belongs_to :conversation, Application.Conversation
```
Now I'm trying to preload conversations for a user in a descending order by the updated_at field using:

```elixir
# controllers/conversation_controller.ex

Repo.preload(user, conversations: from(c in Conversation, order_by: [desc: c.updated_at]))
```

But it doesn't work, I keep getting conversations ordered by their IDs.

### Expected behavior

Get conversations ordered descendingly by the updated_at field.

**Comment by josevalim** [comment]
Thank you for the report! Could you give Ecto 2.0.0-beta a try and let us know if it is solved there?

**Comment by josevalim** [comment]
More info here: http://blog.plataformatec.com.br/2016/02/ecto-2-0-0-beta-0-is-out/

**Comment by YoussefKababe** [comment]
@josevalim Thanks for the quick response! I upgraded Ecto to `2.0.0-beta.2` but I'm still having the same issue as before.

**Comment by josevalim** [comment]
Excellent, thank you!

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by YoussefKababe** [comment]
@josevalim I just checked the changelog; I didn't know Ecto `2.0.0-beta.2` has a new `many_to_many` association! There's no issue with this one. I'm sorry about the confusion, my bad!
