### ISSUE TITLE
Cannot set the connection pool to Sandbox

### ISSUE THREAD

**Issue by jebbench** [elixir-lang/ecto#1355]
### Environment

* Elixir version (elixir -v): 1.2.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 9.5
* Ecto version (mix deps): ecto 2.0.0-beta.2
* Database adapter and version (mix deps): poolboy 1.5.1, postgrex 0.11.1, db_connection 0.2.5
* Operating system: Windows 10 64bit

##### config/test.exs
```elixir
use Mix.Config

config :myapp, Myapp.Repo,
  pool: Ecto.Adapters.SQL.Sandbox
```

##### config/config.exs
```elixir
use Mix.Config

config :myapp, Myapp.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "myapp",
  username: "postgres",
  password: "password"
```

##### test_helper.exs
```elixir
ExUnit.start()

# Set the pool mode to manual for explicitly checkouts
Ecto.Adapters.SQL.Sandbox.mode(Persistence.Repo, :manual)
```
##### myapp_test.exs
```elixir
defmodule Myapp.MyappTest do
  use ExUnit.Case
  import Logger

  setup do
      :ok = Ecto.Adapters.SQL.Sandbox.checkout(Repo)
    end

    test "create valid user", %{uapi: uapi} do
      user = %{username: "username", password: "password", email: "email@test.com"}
      Persistence.Repo.insert(User.changeset(%User{}, user))
    end

end
```

#### Result
```
$ mix test
** (RuntimeError) cannot configure sandbox with pool DBConnection.Poolboy.
To use the SQL Sandbox, configure your repository pool as:

      pool: Ecto.Adapters.SQL.Sandbox

    (ecto) lib/ecto/adapters/sql/sandbox.ex:269: Ecto.Adapters.SQL.Sandbox.mode/2
    (elixir) lib/code.ex:363: Code.require_file/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/tasks/test.ex:186: Mix.Tasks.Test.run/1
```

### Expected behavior
I'm expecting the pool to be set to Sandbox and for the test to run.

**Comment by josevalim** [comment]
You are using different names, afaik. In your config you use:

```elixir
config :myapp, Myapp.Repo,
  pool: Ecto.Adapters.SQL.Sandbox
```

But in your test helper you use:

```elixir
Ecto.Adapters.SQL.Sandbox.mode(Persistence.Repo, :manual)
```

which one is it? Persistence.Repo or Myapp.Repo? :)

**Comment by jebbench** [comment]
My bad - missed some references when renaming the app - I've updated the original post to all say Myapp.

**Comment by fishcakez** [comment]
Is that your complete config/config.exs file? You will need to import the `config/test.exs` to use it, e.g.
```elixir
import_config "#{Mix.env}.exs"
```

**Comment by jebbench** [comment]
I'll try and post a complete example project when I get home.

I've included the test.exs and even tried setting pool directly in the
config.exs.

**Comment by jebbench** [comment]
Tried to replicate this in a fresh project and failed.

I deleted the _build folder in my project and then re-ran the test and it passed :-S

So solved by rebuilding the project.

**Comment by potz** [comment]
I experienced I the same problem recently, and it turned out I had  `MIX_ENV` set to `prod` in the environment. So `MIX_ENV=test mix test` solved this issue for me in this particular instance.

**Comment by sebastialonso** [comment]
@jebbench's solution didn't work for me.

**Comment by cyanistes** [comment]
I was following along the Ecto guide on testing, and hit the same issue. @fishcakez's solution solved it for me. I hadn't imported the configuration for the test environment at the bottom of `config.exs`.
The following is copied from a default Phoenix `config.exs`:

    # Import environment specific config. This must remain at the bottom
    # of this file so it overrides the configuration defined above.
    import_config "#{Mix.env()}.exs"

**Comment by jovanialferez** [comment]
mine was because my `docker-compose.yml` file had explicitly set `MIX_ENV`  to `dev`. so when running test, i had to set that to `test` like this: `MIX_ENV=test mix test`
