### ISSUE TITLE
Impossible to customise referenced column

### ISSUE THREAD

**Issue by stevedomin** [elixir-lang/ecto#1356]
### Environment

* Elixir version (elixir -v): 1.2.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.4
* Ecto version (mix deps): ecto 2.0.0-beta.2
* Database adapter and version (mix deps): postgrex 0.11.1
* Operating system: OS X

### Current behavior

When adding a reference to a column it's impossible to customise that column except for its type. 

### Expected behavior

I'm using varchars as primary keys and I'd like to be able to specify the size for instance  (it's defaulting to 255 at the moment).

Something like this maybe?

```elixir
defmodule Repo.Migrations.AddUser do
  use Ecto.Migration

  def change do
    create table(:users) do
      add :authorization_id, references(:authorizations, type: :string, size: 16)
    end
  end
end
```

**Comment by josevalim** [comment]
Would this work?

    add :authorization_id, references(:authorizations, type: :string), size: 16

**Comment by stevedomin** [comment]
It does! I tried:

```elixir
add :authorization_id, size: 16, references(:authorizations, type: :string)
```

But not this. Thank you so much @josevalim!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
