### ISSUE TITLE
Error when trying to preload data on many_to_many with binary_id foreign keys

### ISSUE THREAD

**Issue by andrewtimberlake** [elixir-lang/ecto#1357]
### Precheck

I receive the following error:

    ** (ArgumentError) Postgrex expected a binary of 16 bytes that can be encoded/cast to type "uuid", got "710e27db-91dd-4c8f-8e8d-a520eec7a095". Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
        (postgrex) lib/postgrex/extensions/uuid.ex:9: Postgrex.Extensions.UUID.encode/4
        (postgrex) lib/postgrex/query.ex:100: DBConnection.Query.Postgrex.Query.do_encode/4
        (postgrex) lib/postgrex/query.ex:61: DBConnection.Query.Postgrex.Query.encode/3
        (db_connection) lib/db_connection.ex:885: DBConnection.describe_execute/5
        (db_connection) lib/db_connection.ex:966: anonymous fn/4 in DBConnection.run_meter/5
        (db_connection) lib/db_connection.ex:421: DBConnection.query/4
        (ecto) lib/ecto/adapters/sql.ex:379: Ecto.Adapters.SQL.sql_call!/6
        (ecto) lib/ecto/adapters/sql.ex:363: Ecto.Adapters.SQL.execute/6

### Environment

* Elixir version (elixir -v): 1.2.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 9.4
* Ecto version (mix deps): 2.0.0-beta2
* Database adapter and version (mix deps): postgrex 1.11.0
* Operating system: Mac OSX

### Current behavior

Error as above. I have created a sample application that reproduces the behaviour at https://github.com/andrewtimberlake/ecto_test

### Expected behavior

That I can preload the association.

**Comment by dmarinortega** [comment]
About to report the same issue

**Comment by rodrigoddalmeida** [comment]
As @dmarinortega and I were discussing this "bug", I got this minimum example:

This works:

```elixir
  from(s in Schema)
  |> where([s], s.id == ^some.id)
```

This will not work:
```elixir
  from(s in "schemas")
  |> where([s], s.id == ^some.id)
```

The problem could be that the association query don't really know which type to cast, since there's no defined/referenced schema. In the given example, the error is supressed by doing:

```elixir
  from(s in "schemas")
  |> where([s], s.id == type(^some.id, Ecto.UUID))
```

**Comment by josevalim** [comment]
Thank you for the app that reproduces the error, really helpful!

**Comment by andrewtimberlake** [comment]
It’s a pleasure, glad I could help
