### ISSUE TITLE
Should we store times in :native time in Ecto.LogEntry?

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1363]
I think this would be best so every layers gets the precision it cares about. @fishcakez thoughts?

**Comment by fishcakez** [comment]
@josevalim :+1:. The DBConnection.LogEntry is already in `:native` units.

**Comment by fishcakez** [comment]
As a side note the `System` docs on elixir master suggest using `:native` for calculations and then converting as the final step so we would be acting against that advise if we did not make the change.
