### ISSUE TITLE
many_to_many breaks has_many through:

### ISSUE THREAD

**Issue by timbuchwaldt** [elixir-lang/ecto#1373]
### Environment

* Elixir version (elixir -v): 1.2.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL
* Ecto version (mix deps): 2.0.0-beta.2
* Database adapter and version (mix deps): postgres 0.11.1
* Operating system: OS X

### Current behaviour
I have three models:
* User
* List
* Item

The user has a many_to_many relation with lists through a join table, an item belongs to a list, the user `has_many :items, through: [:lists, :items]`
I now try the following:
```
assoc(user, :lists)
    |> Hackathon.Repo.all
````

This leads to the following error:

```
    ** (FunctionClauseError) no function clause matching in Ecto.Association.HasThrough.assoc_to_join/2
        (ecto) lib/ecto/association.ex:591: Ecto.Association.HasThrough.assoc_to_join(#Ecto.Query<from l0 in Hackathon.List, join: l1 in "list_users", on: l1.list_id == l0.id, where: l1.user_id in ^[6]>, 1)
        (ecto) lib/ecto/association.ex:568: Ecto.Association.HasThrough.assoc_query/3
        (hackathon) web/models/item.ex:29: Hackathon.Item.user_filter/2
```

Looking at the code in the association module it seems like the call syntax to assoc_to_join is wrong. It passes in "where" instead of "wheres" and also not as a list.
### Expected behaviour
It should return a list of all items belonging to the user.

**Comment by josevalim** [comment]
Thank you @timbuchwaldt, that makes sense! Could you please write a test case for our integration test suite? Please check "integration_test/cases/assoc.exs" for other examples. A test case would really help with us fixing the issue.

**Comment by timbuchwaldt** [comment]
Hey @josevalim - I tried my best altough not being 100% awake. I will extend the testcase once my brain is capable of formulating valid SQL/Ecto queries that match the expected behaviour.

**Comment by josevalim** [comment]
Fixed, thank you!
