### ISSUE TITLE
Ecto.Multi enhancements

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/ecto#1374]
Ecto 2.0 is still in beta, yet we already got some feedback on the use of the newly introduced features.
This focuses on the feedback we got on `Ecto.Multi`.

The most requested feature is ability to introspect previeus changes with `insert/update/delete` to gain access to fields generated in the database, like ids. It's currently possible to do this with the generic `run` function, but it's not very convenient.

A possible solution is to allow `insert/update/delete` to accept a function taking `changes_so_far` as an argument (similar to `run`) and returning a changeset that is to be processed. This solves the above issue, but limits the visibility into the `Multi` and hinders the ability to introspect it without actually running the transaction. That is mainly to the fact that funs are opaque and can't be externally analyzed. It's not yet entirely clear for us how important the introspection is in terms of `Multi` especially with migration to `db_connection` that allowed concurrent tests hitting the database.

## Proposed usage

```elixir
Multi.new
|> Multi.insert(:user, User.changeset(%User{}, user_params))
|> Multi.insert(:auth, &Auth.changeset(assoc(&1.user, :auths), auth_params))
|> Multi.insert(:session, &Session.changeset(assoc(&1.auth, :sessions), session_params))
```

## To decide

* Should those new operations be encoded as a special type of `insert/update/delete`, get a new operation type or be translated to `run` calls?
* It is not yet clear if this will land in 2.0 or will be deferred until 2.1.

**Comment by josevalim** [comment]
:+1 for these proposals.

> Should those new operations be encoded as a special type of insert/update/delete, get a new operation type or be translated to run calls?

Both seem fine. Write the code, document them, see which one works better. I am have a hunch the `run` version will be simpler.

> It is not yet clear if this will land in 2.0 or will be deferred until 2.1.

It depends on how fast you are. :)

**Comment by stevedomin** [comment]
This would be very neat!

Since people will use `Ecto.Multi.run/2` anyway to circumvent that limitation I don't think loosing the introspectability is too bad.
