### ISSUE TITLE
Possible docs preload example error

### ISSUE THREAD

**Issue by VladShcherbin** [elixir-lang/ecto#1377]
- Ecto 2.0.0-rc.0

The example is in the [docs preload](https://hexdocs.pm/ecto/2.0.0-rc.0/Ecto.Query.html#preload/3). The last examples group is **Expressions examples**. The example is:

```elixir
Post |> preload([p, c], [:user, comments: c]) |> select([p], p)
```

Tried the following, but got an error:

```elixir
University |> preload([u, f], [:city, faculties: f]) |> select([u], u) |> Repo.all
```

Error:
```console
** (ArgumentError) argument error
    (ecto) lib/ecto/repo/queryable.ex:119: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
```

Maybe I don't understand the example, but it looks similar to me.

**Comment by josevalim** [comment]
University |> preload([u, f], [:city, faculties: f]) |> select([u], u) |> Repo.all

@VladShcherbin is this your whole pipeline? If so, you are missing the place where you join on the association: "faculties". In any case, the error message should be better. :)

**Comment by VladShcherbin** [comment]
@josevalim oh, now I see. Yes, it works with join, I thought - maybe I can drop join if there is an example without it in the docs. Maybe, we also need to update this example? :)
