### ISSUE TITLE
Support Elixir v1.3 calendar types

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#1386]
Hi @elixir-lang/ecto-adapters,

This is a very ahead of time warning for adapter developers.

Once Elixir v1.3 lands, we will eventually release a new Ecto version that expects adapters to return the new calendar types for date, times and timestamps: https://github.com/elixir-lang/elixir/commit/258ffd4eea10b8480933245f1710432579f4ef34

There is nothing to be done for now but I thought it would be fair to let adapters developers know of plans that may cause backwards incompatible changes at the adapter level.

**Comment by michalmuskala** [comment]
How would it work if we'd like to keep backwards compatibility? Today adapters return datetime tuples, would we need to change that? And if so how do we decide which one to return? Or will there be a new version of Ecto requiring Elixir 1.3?

**Comment by josevalim** [comment]
Adapters will change that. Adapter can support an option when starting the connection that choses the proper data type.

**Comment by bcardarella** [comment]
@josevalim is this targeted for the 2.x cycle? If so, should we expect 3.x to drop `Ecto.{Date,DateTime}` entirely?

**Comment by josevalim** [comment]
Actually, we have changed plans. We will continue sending/receiving tuples at the adapter level for now for backwards compatibility although we will introduce the calendar types into Ecto v2.0 .
