### ISSUE TITLE
Tests deadlock for 2.0.0-rc.1, phoenix and postgres

### ISSUE THREAD

**Issue by tony612** [elixir-lang/ecto#1389]
### Environment

* Elixir version (elixir -v):

Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.2.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): postgres (PostgreSQL) 9.5.1
* Ecto version (mix deps): 2.0.0-rc.1
* Database adapter and version (mix deps): postgrex(0.11.1)
* Phoenix version: 1.1.4 (phoenix_ecto: 3.0.0-rc.0)
* Operating system: OS X 10.11.4 MacBook Pro (Retina, 13-inch, Late 2013)

### Current behavior

I updated ecto to 2.0.0-rc.1 from 2.0.0-rc.0 and change all tests to async based on this blog http://blog.plataformatec.com.br/2016/04/ecto-2-0-0-rc-is-out/ . Then the tests failed.(Sometimes it passed) The commit is here: https://github.com/tony612/exchat/commit/0097479d792b413c38468de01ec96f1fc06c812d

The error is like this:

```
     test/controllers/channel_controller_test.exs:35
     ** (Postgrex.Error) ERROR (deadlock_detected): deadlock detected

     Process 67939 waits for ShareLock on transaction 11786; blocked by process 67935.
     Process 67935 waits for ShareLock on transaction 11782; blocked by process 67939.
```

And I put the logs of three random failed tests in three gists:

https://gist.github.com/tony612/d8c713cef3c409d3a5b2ff38927d7b64
https://gist.github.com/tony612/dce4541d2e7ee6a36372bb801fe23c29
https://gist.github.com/tony612/88ada2da7f18ca36185d214013fc4640

Someting I found: The tests pass if I change [Exchat.ChannelControllerTest](https://github.com/tony612/exchat/blob/0097479d792b413c38468de01ec96f1fc06c812d/test/controllers/channel_controller_test.exs) to sync.

**Comment by josevalim** [comment]
That's a very cool example, you can check you server log and try to understand more about it. I got this:

```
ERROR:  deadlock detected
DETAIL:  Process 18673 waits for ShareLock on transaction 42018; blocked by process 18679.
	Process 18679 waits for ShareLock on transaction 42023; blocked by process 18673.
	Process 18673: INSERT INTO "users" ("inserted_at","updated_at","email","password_hash") VALUES ($1,$2,$3,$4) RETURNING "id"
	Process 18679: INSERT INTO "channels" ("inserted_at","updated_at","name") VALUES ($1,$2,$3) RETURNING "id"
HINT:  See server log for query details.
CONTEXT:  while inserting index tuple (0,33) in relation "users_email_index"
STATEMENT:  INSERT INTO "users" ("inserted_at","updated_at","email","password_hash") VALUES ($1,$2,$3,$4) RETURNING "id"
```

The issue seems to be on the unique indexes. You have two or more transactions waiting for different indexes. One possible solution is to make sure you are using different e-mails per test. All of them seem to use the same e-mail, I would make sure to use a counter. Something like `System.unique_integer([:positive])` is enough.

**Comment by tony612** [comment]
@josevalim I think so. And I write two simple cases to reproduce this error:

```
  # in one test file
  @tag :lock
  test "case1" do
    insert_channel
    insert_user
  end

  # in another test file
  @tag :lock
  test "case2" do
    insert_user
    insert_channel
  end
```

I change the log level to debug then I got the log:

```
15:42:46.076 [debug] begin [] OK query=0.2ms
15:42:46.077 [debug] begin [] OK query=18.4ms
15:42:46.103 [debug] INSERT INTO "channels" ("inserted_at","updated_at","name") VALUES ($1,$2,$3) RETURNING "id" [{{2016, 4, 23}, {7, 42, 46, 84957}}, {{2016, 4, 23}, {7, 42, 46, 84951}}, "general"] OK query=1.6ms
15:42:46.103 [debug] INSERT INTO "users" ("inserted_at","updated_at","email","password_hash") VALUES ($1,$2,$3,$4) RETURNING "id" [{{2016, 4, 23}, {7, 42, 46, 0}}, {{2016, 4, 23}, {7, 42, 46, 0}}, "tony@ex.chat", "$2b$04$fnobMTs1pnVaPeWka7wHTOKANvfURzHiqH85QUQYeOS3kiSQWmPtG"] OK query=1.8ms
# ------> These two commits are not real commits, right? <-----
15:42:46.103 [debug] commit [] OK query=0.2ms
15:42:46.103 [debug] commit [] OK query=0.3ms
15:42:46.104 [debug] begin [] OK query=0.1ms
15:42:46.106 [debug] begin [] OK query=0.1ms
15:42:47.106 [debug] INSERT INTO "channels" ("inserted_at","updated_at","name") VALUES ($1,$2,$3) RETURNING "id" [{{2016, 4, 23}, {7, 42, 46, 104332}}, {{2016, 4, 23}, {7, 42, 46, 104330}}, "general"] ERROR query=1002.2ms
15:42:47.107 [debug] rollback [] OK query=0.4ms
15:42:47.108 [debug] INSERT INTO "users" ("inserted_at","updated_at","email","password_hash") VALUES ($1,$2,$3,$4) RETURNING "id" [{{2016, 4, 23}, {7, 42, 46, 0}}, {{2016, 4, 23}, {7, 42, 46, 0}}, "tony@ex.chat", "$2b$04$grtD.b7FdQipDyZ8mSkOrevzrMkVDr.k8pfpANKzLCoT0bt9snSc6"] OK query=1001.8ms
15:42:47.108 [debug] commit [] OK query=0.3ms


  1) test user channel (Exchat.ChannelUserServiceTest)
     test/services/channel_user_service_test.exs:7
     ** (Postgrex.Error) ERROR (deadlock_detected): deadlock detected

     Process 49970 waits for ShareLock on transaction 12425; blocked by process 49969.
     Process 49969 waits for ShareLock on transaction 12424; blocked by process 49970.
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:405: Ecto.Adapters.SQL.struct/6
       (ecto) lib/ecto/repo/schema.ex:373: Ecto.Repo.Schema.apply/5
```

I have only one question left for this problem: Though there're two `commit` log above but it's not real commits, right? It's still in a transaction and the lock is not released, so I got the deadlock, isn't it?

**Comment by josevalim** [comment]
No, they are not real commits but rather savepoints (and savepoint rollbacks). Did you try using different e-mails?

**Comment by tony612** [comment]
@josevalim Got it. Yeah, it works. Thank you!
