### ISSUE TITLE
[Proposal] Add select output configuration option

### ISSUE THREAD

**Issue by VladShcherbin** [elixir-lang/ecto#1391]
Since now we have an awesome way to take a map or a struct using Ecto, maybe we can have an option, specifying, what to take by default with this syntax:

```elixir
from p in Post, select: [:title, :body]
```

When we execute the query, we will get a struct. It would be great to have an option to set the output format to map, since some of devs don't use structs and always need a map.

By default, it can be set to struct so existing apps won't be broken, some kind of:

```elixir
config :facebook, 
  ecto_repos: [Facebook.Repo],
  select_format: :map
```

**Comment by michalmuskala** [comment]
When you query a struct you get a struct back. You can query the table to get an unstructured result. This was always possible.

```elixir
from p in "posts", select: [:title, :body]
```

**Comment by ericmj** [comment]
Why do you use a schema if you are not going to use structs?

I think it's a bad idea to globally configure something that completely changes the behaviour of queries. If you ever pass your repo to some dependency or other code that doesn't know about this global configuration things are going to break.

**Comment by VladShcherbin** [comment]
Oh, I mean not for all queries, only for this:

```elixir
City |> select([:title]) |> Repo.all
```

This is same as:
```elixir
City |> select([c], struct(c, [:title])) |> Repo.all
```

This one will give you a map:
```elixir
City |> select([c], map(c, [:title])) |> Repo.all
```

So, the proposal was to have an option to set `City |> select([:title]) |> Repo.all` return a map instead of a struct.

**Comment by ericmj** [comment]
@VladShcherbin Right, so dependencies that use that `select` syntax may get unexpected results. They may expect a struct back and instead get a map back and it all depends on a global configuration they don't know about.

**Comment by VladShcherbin** [comment]
Oh, yes, probably there are many use cases, where this can give unexpected results.

@michalmuskala , @ericmj Thank you, guys!

**Comment by michalmuskala** [comment]
And you can already do this today by using table names instead of schemas as the source:

```elixir
City |> select([:title]) |> Repo.all
# vs
"cities" |> select([:title]) |> Repo.all
```

The first one returns a struct and the second one raw map.

**Comment by VladShcherbin** [comment]
@michalmuskala this one I didn't know before you showed me. So many possibilities. Thank you again!
