### ISSUE TITLE
Preloading with belongs_to association results in wrong preloaded record (incorrect commit referenced)

### ISSUE THREAD

**Issue by sbrink** [elixir-lang/ecto#1393]
### Environment

* Elixir version (1.2.4):
* Database and version (PostgreSQL 9.4):
* Ecto version (2.0.0.rc.0..2):
* Database adapter and version (postgrex 0.11.1):
* Operating system: OS X 10.11.4 

### Current behavior

I'm loading a simple list of posts with an associated user

`    posts =
      Post
      |> Repo.all
      |> Repo.preload(:user)
`

If I compare `post.user_id == post.user.id`, I get different results which is wrong.

This happend after an upgrade from 2.0.0.beta.2 to 2.0.0.rc.0.

I tracked the error down to this commit: #1353 

`fetch_ids = Enum.sort(fetch_ids) |> Enum.reverse()` in the commit seems to break a normal associations.

### Expected behavior

I should get the correct associated user. `post.user_id == post.user.id`

**Comment by VladShcherbin** [comment]
Hey, I don't know, if it can help you, but I had my keys messed up [today](https://github.com/elixir-lang/ecto/issues/1394), solved it by updating PostgreSQL to 9.5.2.

Maybe it can help you too.

**Comment by josevalim** [comment]
@sbrink thank you, I will investigate. Meanwhile, could you please try to add a test to our suite? They would be in `integration_test/cases/preload.exs`. You can run them as `MIX_ENV=pg mix test`. Thank you!

**Comment by josevalim** [comment]
I can confirm the bug.

@VladShcherbin PG does not guarantee an order to return results if there is no order by, many times, it is by ID, but sometimes it isn't. Upgrading PG may temporarily solve it but the bug is still there. :)

**Comment by sbrink** [comment]
@josevalim: I'll try again. I already found the test file earlier. But it's really some weired behaviour. If I limit the number of posts, I get the correct users again.

@VladShcherbin I'll try that, too

**Comment by VladShcherbin** [comment]
@josevalim thank you! :)
