### ISSUE TITLE
lib/ecto/adapters/mysql.ex compilation error on Heroku

### ISSUE THREAD

**Issue by Antiarchitect** [elixir-lang/ecto#1396]
Hi, Elixir guys!

Just upgraded my project with help of this guide:  http://blog.plataformatec.com.br/2016/04/ecto-2-0-0-rc-is-out/ and now having:

* Elixir version (elixir -v): 1.2.3
* Phoenix version: 1.1.4
* Ecto version (mix deps): 2.0.0-rc.3
* Heroku environment.

Locally on my Fedora Linux all seems fine, but when I try to push the changes on Heroku:

    remote: == Compilation error on file lib/ecto/adapters/mysql.ex ==
    remote: ** (CompileError) lib/ecto/adapters/mysql.ex:204: no super defined for insert/5 in module Ecto.Adapters.MySQL. Overridable functions available are: delete/5, dump/2, embed_id/1, execute/6, execute_ddl/3, insert/6, load/2, prepare/2, update/7
    remote:     lib/ecto/adapters/mysql.ex:203: (module)
    remote: 
    remote: could not compile dependency :ecto, "mix compile" failed. You can recompile this dependency with "mix deps.compile ecto", update it with "mix deps.update ecto" or clean it with "mix deps.clean ecto"
    remote: 
    remote:  !     Push rejected, failed to compile elixir app

**Comment by josevalim** [comment]
It seems to be a cache issue. Try setting the always_rebuild option in your buildpack configuration here: https://github.com/HashNuke/heroku-buildpack-elixir

**Comment by Gazler** [comment]
You can use https://github.com/heroku/heroku-repo to purge your cache as a one off.

**Comment by Antiarchitect** [comment]
@josevalim @Gazler thanks, worked like a charm!
P.S. Used @Gazler advice.

**Comment by josevalim** [comment]
> P.S. Used @Gazler advice.

✌️
