### ISSUE TITLE
Inconsistencies with Ecto.Adapters.SQL.query!/3

### ISSUE THREAD

**Issue by stavro** [elixir-lang/ecto#1405]
### Environment

* Elixir version: 1.2.0
* Database and version: Postgres 9.5
* Ecto version: 2.0.0-rc.3
* Database adapter and version: 0.11.1
* Operating system: OS X

### Current behavior

Manual querying through `Ecto.Adapters.SQL.query!` has some quirks with certain datatypes, as well as quirks casting between singular values vs arrays.

In particular, timestamps and uuids are treated inconsistently when using a single value vs arrays.

### Single Value Querying
```elixir
# DATES
now = Ecto.DateTime.utc()
Ecto.Adapters.SQL.query!(Sched.Repo, "SELECT $1::timestamp", [now]) #OK!

# UUIDS
uuid = Ecto.UUID.generate()
Ecto.Adapters.SQL.query!(Sched.Repo, "SELECT $1::uuid", [uuid]) # FAILS

{:ok, dumped_uuid} = uuid |> Ecto.UUID.dump()
Ecto.Adapters.SQL.query!(Sched.Repo, "SELECT $1::uuid", [dumped_uuid]) # OK!
```

### Array value querying

```elixir
# DATES
now = Ecto.DateTime.utc()
Ecto.Adapters.SQL.query!(Sched.Repo, "SELECT $1::timestamp[]", [[now]]) # FAILS

{:ok, dumped_date} = now |> Ecto.DateTime.dump()
Ecto.Adapters.SQL.query!(Sched.Repo, "SELECT $1::timestamp[]", [[dumped_date]]) #OK!

# UUID
uuid = Ecto.UUID.generate()
{:ok, dumped_uuid} = uuid |> Ecto.UUID.dump()
Ecto.Adapters.SQL.query!(Sched.Repo, "SELECT $1::uuid[]", [[dumped_uuid]]) # FAILS
Ecto.Adapters.SQL.query!(Sched.Repo, "SELECT $1::uuid[]", [[dumped_uuid.value]]) # OK!
```

Ideally this should be tightened up a bit to be more consistent.  If a particular input is accepted to be casted to a single value, that same input wrapped in an array should be castable to that array input.

### Specific Failures
None of these should fail in my opinion:

Querying a single UUID without manually dumping it:
```elixir
uuid = Ecto.UUID.generate()
Ecto.Adapters.SQL.query!(Sched.Repo, "SELECT $1::uuid", [uuid]) # FAILS
** (ArgumentError) Postgrex expected a binary of 16 bytes that can be encoded/cast to type "uuid", got "3f11a8a1-9736-4a03-988f-52deeb9cebb2". Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
         (postgrex) lib/postgrex/extensions/uuid.ex:9: Postgrex.Extensions.UUID.encode/4
```

Querying a timestamp array without manually dumping it first:
```elixir
now = Ecto.DateTime.utc()
Ecto.Adapters.SQL.query!(Sched.Repo, "SELECT $1::timestamp[]", [[now]]) # FAILS

** (ArgumentError) could not encode datetime: #Ecto.DateTime<2016-04-28 23:29:31>

This error happens when you are by-passing Ecto's Query API by
using either Ecto.Adapters.SQL.query/4 or Ecto fragments. This
makes Ecto unable to properly cast the type. For example:

    now = Ecto.DateTime.utc |> Calecto.DateTimeUTC.cast
    from u in User, where: fragment("(?).wall_time > ?", u.start_datetime, ^now)
```

Querying a UUID array without dumping it AND mapping to `value` first:

```elixir
uuid = Ecto.UUID.generate()
{:ok, dumped_uuid} = uuid |> Ecto.UUID.dump()
Ecto.Adapters.SQL.query!(Sched.Repo, "SELECT $1::uuid[]", [[dumped_uuid]]) # FAILS

** (ArgumentError) Postgrex expected a binary of 16 bytes that can be encoded/cast to type "uuid", got %Ecto.Query.Tagged{tag: nil, type: :uuid, value: <<190, 202, 15, 164, 44, 86, 78, 174, 147, 35, 213, 199, 34, 124, 44, 120>>}. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.


Ecto.Adapters.SQL.query!(Sched.Repo, "SELECT $1::uuid[]", [[dumped_uuid.value]]) # OK!
```

**Comment by ericmj** [comment]
Can you show the errors when the queries fail?

**Comment by stavro** [comment]
@ericmj Updated with error messages.

**Comment by ericmj** [comment]
The issue you seem to be hitting with UUIDs is that `Ecto.Adapters.SQL.query!` needs parameters in the format the underlying driver expects. When you dump a value you will get an "ecto native" typed value - not the type the driver expects.

**Comment by stavro** [comment]
But that shouldn't account for differences between singular and array types then, right?  If it can understand a type in order to cast it to a single value, it should be able to do the same for an array of those values.

```elixir
{:ok, dumped_uuid} = uuid |> Ecto.UUID.dump()
Ecto.Adapters.SQL.query!(Sched.Repo, "SELECT $1::uuid", [dumped_uuid]) # OK!
```

```elixir
{:ok, dumped_uuid} = uuid |> Ecto.UUID.dump()
Ecto.Adapters.SQL.query!(Sched.Repo, "SELECT $1::uuid[]", [[dumped_uuid]]) # FAILS!
```

**Comment by ericmj** [comment]
The UUID issue seems to be fixed on master. Looking into why the datetimes fail.

**Comment by ericmj** [comment]
The datetime issue is that this function https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/postgres/connection.ex#L88-L96 doesn't traverse nested data structures such as lists.
