### ISSUE TITLE
ecto.dump does not preserve the contents of schema_migrations

### ISSUE THREAD

**Issue by alco** [elixir-lang/ecto#1410]
I'm on Ecto v2.0.0-rc.3.

`mix ecto.dump` does not dump the contents of the `schema_migrations` table. This makes the dump/load workflow completely incompatible with migrations.

My use case is to do `mix ecto.dump` after each new migration is added, commit the resulting `structure.sql` into Git and use that to set up the schema in an empty DB. Whenever a new migration is added, I should be able to do `mix do ecto.migrate, ecto.dump` to save the latest schema version. That way, when deploying the app from scratch, I would be able to run `mix ecto.load` to quickly set up the DB and during release upgrades I'd like to be able to run `mix ecto.migrate` to upgrade to the latest schema version while preserving user data.

As a reference, ActiveRecord in Rails does just that (https://github.com/rails/rails/blob/e0a9baa044022eea52b8c4b36689396dac165944/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L987-L1005):

```ruby
      def dump_schema_information #:nodoc:
        versions = ActiveRecord::SchemaMigration.order('version').pluck(:version)
        insert_versions_sql(versions)
      end

      def insert_versions_sql(versions) # :nodoc:
        sm_table = ActiveRecord::Migrator.schema_migrations_table_name

        if supports_multi_insert?
          sql = "INSERT INTO #{sm_table} (version) VALUES "
          sql << versions.map {|v| "('#{v}')" }.join(', ')
          sql << ";\n\n"
          sql
        else
          versions.map { |version|
            "INSERT INTO #{sm_table} (version) VALUES ('#{version}');"
          }.join "\n\n"
        end
      end
```

**Comment by josevalim** [comment]
Yes, definitely.
