### ISSUE TITLE
Consider keeping Repo.transaction/2 argument as-is

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ecto#1414]
I think the previous argument order looks much better:

```elixir
Repo.transaction([option: :something], fn ->
  do_stuff
  do_something_else
end)
```

than the new one:
```elixir
Repo.transaction(fn ->
  do_stuff
  do_something_else
end, [option: :something])
```

It reads better and looks more natural to have the options before the anonymous function. I also realize that `Repo.transaction/2` now takes an `Ecto.Multi` struct which looks more natural with the struct before the options, that functionality can be moved to another function such as `Repo.run_multi/2`.

Since this is an opinionated change and there doesn't seem to be a conclusive existing convention I think we should hear some opinions before introducing a breaking change to 2.0.

**Comment by josevalim** [comment]
There is no evidence one approach is more readable than the other and I personally prefer to follow the conventions that options come last. I can see multiple reasons to keep the argument order as in master:

1. Your implementation would require the argument order to change (sometimes the function is the first arg, sometimes it is the second, etc)

2. Your implementation would require adding yet another function to the Repo API

The transaction/2 API is being kept as is. :)

**Comment by paulcsmith** [comment]
What do you think about the second part of ericmj's issue, about adding `Repo.run_multi/1` (or some other name)? It might be more clear than passing it to `Repo.transaction` What do you think?

`Service.register_user |> Repo.run_multi`
