### ISSUE TITLE
module with ecto schema silently fails to compile in some circumstances

### ISSUE THREAD

**Issue by adamkittelson** [elixir-lang/ecto#1418]
### Environment

* Elixir version (elixir -v): 1.2.5
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.5
* Ecto version (mix deps): 2.0.0-rc.4
* Database adapter and version (mix deps): postgrex 0.11.1
* Operating system: OSX 10.11.4

### Current behavior

I'm upgrading from Ecto 1.1.x to Ecto 2.0.0-rc.4 and ran into an issue where some modules would fail to compile with no error or output apart from the errors caused by their absence when compiling other modules (undefined structs etc).

I was able to narrow it down to the presence of virtual fields with the `:any` type and a default value of an integer or a map. Changing their type to the appropriate type or removing the default value both fix the issue and allow the module to compile.

bad:
```elixir
field :some_field, :any, virtual: true, default: 0
field :other_field, :any, virtual: true, default: %{}
```

good:
```elixir
field :some_field, :integer, virtual: true, default: 0
field :other_field, :map, virtual: true, default: %{}
field :yet_another_field, :any, virtual: true
``` 

### Expected behavior
I would expect these modules to either compile, compile with a warning, or fail to compile with an error. Basically anything other than silently failing to compile.

I'm not blocked on this or anything since I've just switched to the appropriate field types (in my case the values never changed types at runtime, although I suppose that would be legitimate with the :any field type).

Unfortunately while I am able to reproduce this with 100% consistency in three modules in my application by switching any `:integer` or `:map` virtual field with a default value to the `:any` type, I've thus far been unable to reproduce it in a more minimal example in a fresh application, so it seems that `:any` + `virtual: true` + an integer/map default value is not enough to cause the issue on their own but also require the presence of some other factor I haven't nailed down yet. I won't have time to take another stab at a more minimal reproduction until the weekend so I thought I'd go ahead and submit in an issue on the off chance that this rings any bells regarding any changes made between 1.1.x and 2.0.0-rc.4, if this isn't enough to go on let me know and I'll try to come back with something smaller that is reproducible.

Thanks!
Adam

**Comment by josevalim** [comment]
Thank you @adamkittelson! It doesn't ring any bell, so we are looking forward to more information. :)

**Comment by adamkittelson** [comment]
I dug in a bit more, and while I still don't have a minimal working example I do have a working theory about what is happening and why it's hard to reproduce minimally.

Where things seem to be going off the rails are when checking that the default argument is valid for the supplied type at https://github.com/elixir-lang/ecto/blob/529de0531c571d330d2141cf9968b3a1aade194a/lib/ecto/schema.ex#L1108

This leads to a call to `Ecto.Type.dump` at https://github.com/elixir-lang/ecto/blob/529de0531c571d330d2141cf9968b3a1aade194a/lib/ecto/schema.ex#L1395

Which if the type is `:any` leads us to this clause
https://github.com/elixir-lang/ecto/blob/529de0531c571d330d2141cf9968b3a1aade194a/lib/ecto/type.ex#L304
which results in a call to `Ecto.DataType.dump/1` which is a protocol. At this point of the compilation process we're pre-consolidation which if memory serves means these go through the code_server or some other kind of dynamic dispatch. I believe the issue is caused by that lookup taking too long in my large-ish project and that the reason I'm having trouble with a minimal reproduction is that by reducing the scope i'm reducing the load on the code_server (or whatever the pre-consolidation protocol dispatch mechanism is) to the point that it's quick enough to not be a problem.

If I replace the call to `Ecto.DataType.dump/1` there with a simple `{:ok, value}` tuple the issue goes away. I noticed that this line is new as of rc.4 so I tried compiling my project with rc.3 and that also worked.

Hope that helps, let me know if you need any more info or clarification.

Thanks!
Adam

**Comment by josevalim** [comment]
Thank you for such a great write up. Everything you said makes sense. It
seems that, because an implementation for maps has never been defined for
the Ectp.DataType protocol, Elixir is simply dropping the module and not
finishing compilation.

Could you please try Elixir master and see if the problem is gone? We have
improved how the compiler works in areas such as this and I think it may
have solved the issue. Meanwhile, I will make sure to avoid the protocol
dispatch for now.


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by adamkittelson** [comment]
Thanks Jose. I tried Elixir master and can confirm that it does solve the issue.
