### ISSUE TITLE
Ecto constructs parameters in wrong order while using in and fragment

### ISSUE THREAD

**Issue by mspanc** [elixir-lang/ecto#1427]
### Environment

* Elixir version (elixir -v): Elixir 1.2.1 Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.4.5
* Ecto version (mix deps): 1.1.6
* Database adapter and version (mix deps): postgrex 0.11.1
* Operating system: Mac OS X 10.11.4

### Current behavior

When I run the following code:

```elixir
field = "references" # hstore field
values = ["owner"] # hstore key
values_for_dict = ["a", "b", "c", "d"]

query = from p in query, where: fragment("?->?", field(p, ^field), ^Enum.at(values, 0)) in ^values_for_dict
```

The SQL generated SQL has reversed parameter names

```
[debug] SELECT r0."id", r0."name", r0."direction", r0."driver", r0."os_name", r0."os_uid", r0."transmission_enabled", r0."references", r0."extra", r0."inserted_at", r0."updated_at" FROM "resource_architecture_audio_interface" AS r0 WHERE (r0."references"->$5 IN ($1,$2,$3,$4)) ORDER BY r0."name" ["owner", "a", "b", "c", "d"] OK query=2.8ms
```

Which results in wrong values being passed to references->`key` and `in` clause.

### Expected behavior

It should generate `WHERE (r0."references"->$1 IN ($2,$3,$4,$5))` instead of `WHERE (r0."references"->$5 IN ($1,$2,$3,$4))`

**Comment by josevalim** [comment]
That's a great catch, thank you!

**Comment by mspanc** [comment]
No problem. I am seriously blocked by this, any chance for quick resolution? (I don't know Ecto internals well enough to do this quickly by myself).

**Comment by josevalim** [comment]
Yup, I can start investigating this now. :)

**Comment by josevalim** [comment]
There is a commit in the v1.1 branch that solves this issue.

**Comment by mspanc** [comment]
Thank you!

**Comment by josevalim** [comment]
v1.1.7 is out (since it was an important bug fix).
