### ISSUE TITLE
cast_assoc(..., required: true) should have more options

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ecto#1433]
It should both allow checking the existence of a field and if there are at least one item in the list.

**Comment by josevalim** [comment]
The plan is for required: true to simply check for non-nil and validate_length to check for a number of entries. Btw @ericmj, can't you use validate_required and validate_length today to get the behaviour that you want?

**Comment by josevalim** [comment]
You will need to call the validation functions AFTER you cast. Make sure to
not pass :required to cast and let me know how it goes. :)



-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by ericmj** [comment]
Thanks, I will try that out.

**Comment by ericmj** [comment]
```elixir
release_changeset
|> cast_assoc(:requirements)
|> validate_required(:requirements)
```

The `validate_required/2` above does not seem to have any effect in my tests.

**Comment by josevalim** [comment]
Oh... it does not work because it is always an empty list in the struct (or the NotLoaded struct). Now I remember why we need required: true in cast_assoc!

**Comment by josevalim** [comment]
To solve this, we should raise if validate_required receives a NotLoaded struct.
