### ISSUE TITLE
Add a `mix ecto` help task

### ISSUE THREAD

**Issue by joshprice** [elixir-lang/ecto#1440]
Currently the only way to know the available `mix ecto` tasks is to run `mix help`.

Running `mix ecto` or `mix help ecto` doesn't really help much.

```sh
✪ mix help ecto
** (Mix) The task "ecto" could not be found. Did you mean "ecto.dump"?

✪ mix ecto    
** (Mix) The task "ecto" could not be found. Did you mean "ecto.dump"?
```

Ideally a task like `mix hex` which provides all the hex specific tasks would be helpful.

```sh
✪ mix hex
Hex v0.12.0
Hex is a package manager for the Erlang ecosystem.

Available tasks:

mix hex.build       # Builds a new package version locally
mix hex.config      # Reads or updates Hex config
mix hex.docs        # Publishes docs for package
...

Further information can be found here: https://hex.pm/docs/tasks
```

**Comment by josevalim** [comment]
Yup. And it should be straight-forward to implement:

    mix help --search "ecto."

If someone would like to send a PR, please do.
