### ISSUE TITLE
Preload fails w/ Custom Primary Key fields

### ISSUE THREAD

**Issue by CrshOverride** [elixir-lang/ecto#1443]
### Environment

* Elixir version (elixir -v): **1.2.5**
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): **PostgreSQL 9.4.4**
* Ecto version (mix deps): **2.0.0-rc.5**
* Database adapter and version (mix deps): **Postgrex 0.11.1**
* Operating system: **OSX 10.10.5**

### Current behavior

With the following schemas defined:

```elixir
defmodule Magellanql.Country do
  use Magellanql.Web, :model

  @primary_key {:digital_element_id, :id, []}
  @derive {Phoenix.Param, key: :digital_element_id}
  schema "countries" do
    field :name, :string
  end
end
```

```elixir
defmodule Magellanql.Region do
  use Magellanql.Web, :model

  @primary_key {:digital_element_id, :id, []}
  @derive {Phoenix.Param, key: :digital_element_id}
  schema "regions" do
    field :name, :string

    belongs_to :country, Magellanql.Country, foreign_key: :country_digital_element_id
  end
end
```

The following query:

```elixir
Magellanql.Region
|> preload(:country)
|> Magellanql.Repo.all
```

Results in the following error:

```
[debug] QUERY OK db=5.3ms decode=39.9ms
SELECT r0."digital_element_id", r0."eid", r0."name", r0."name_localized", r0."ad_roll_id", r0."facebook_id", r0."created_at", r0."updated_at", r0."deleted_on", r0."country_digital_element_id" FROM "regions" AS r0 []
[info] Sent 500 in 50ms
[error] #PID<0.1391.0> running Magellanql.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /graphql?query=query+{regions{name}}
** (exit) an exception was raised:
    ** (Ecto.QueryError) deps/ecto/lib/ecto/association.ex:726: field `Magellanql.Country.id` in `where` does not exist in the schema in query:

from c in Magellanql.Country,
  where: c.id in ^[887, 882, 704, 862, 860, 858, 804, 834, 792, 788, 776, 795, 762, 764, 148, 760, 690, 752, 705, 703, 706, 222, 686, 736, 682, 643, 642, 634, 600, 620, 408, 616, 598, 608, 604, 591, 586, 512, 554, 524, 578, 558, 566, 480, 496, 499, 466, 807, 484, 498, 504, 428, 442, 440, 426, 434, 422, 418, 414, 410, 116, 417, 398, 392, 400, 380, 376, 352, 368, 364, 372, 356, 360, 348, 332, 191, 340, 320, 300, 624, 324, 268, 266, 250, 246, 231, 233, 724, 818, 218, 12, 214, 262, 276, 203, 196, 192, 170, 178, 180, 156, 152, 756, 124, 140, 64, 76, 68, 112, 70, 100, 50, 204, 56, 31, 51, 32, 784, 20, 8, 4, 716, 670, 840, 800, 520, 562, 516, 458, 308, 826, 72, 158, 688, 470, 104, 584, 462, 144, 583, 242, 208, 212, 40, 36, 28, 626, 275, 48, 44, 232, 894, 710, 548, 780, 748, 740, 674, 528, 508, 450, 492, 438, 662, 430, 296, 404, 388, 328, 270, 288, 120, 96, 52, 84, 108, 24, 581, 798, 768, 678, 728, 694, 90, 654, 702, 646, 585, 478, 454, 659, 304, 226, 188, 174, 132, 384, 854, 535],
  select: {c.id, c}

        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/repo/queryable.ex:119: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
        (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
```

### Expected behavior

The query successfully preloads the parent entities.

**Comment by josevalim** [comment]
You also need to pass the primary_key to belongs to so we know how to find
it in the other schema. We cannot fetch this information because it would
lead do deadlocks.

On Thursday, May 19, 2016, Justin Niessner <notifications@github.com> wrote:

> Environment
>
>    - Elixir version (elixir -v): *1.2.5*
>    - Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): *PostgreSQL
>    9.4.4*
>    - Ecto version (mix deps): *2.0.0-rc.5*
>    - Database adapter and version (mix deps): *Postgrex 0.11.1*
>    - Operating system: *OSX 10.10.5*
>
> Current behavior
>
> With the following schemas defined:
>
> defmodule Magellanql.Country do
>   use Magellanql.Web, :model
>
>   @primary_key {:digital_element_id, :id, []}
>   @derive {Phoenix.Param, key: :digital_element_id}
>   schema "countries" do
>     field :name, :string
>   endend
>
> defmodule Magellanql.Region do
>   use Magellanql.Web, :model
>
>   @primary_key {:digital_element_id, :id, []}
>   @derive {Phoenix.Param, key: :digital_element_id}
>   schema "regions" do
>     field :name, :string
>
>     belongs_to :country, Magellanql.Country, foreign_key: :country_digital_element_id
>   endend
>
> The following query:
>
> Magellanql.Region|> preload(:country)|> Magellanql.Repo.all
>
> Results in the following error:
>
> [debug] QUERY OK db=5.3ms decode=39.9ms
> SELECT r0."digital_element_id", r0."eid", r0."name", r0."name_localized", r0."ad_roll_id", r0."facebook_id", r0."created_at", r0."updated_at", r0."deleted_on", r0."country_digital_element_id" FROM "regions" AS r0 []
> [info] Sent 500 in 50ms
> [error] #PID<0.1391.0> running Magellanql.Endpoint terminated
> Server: localhost:4000 (http)
> Request: GET /graphql?query=query+{regions{name}}
> ** (exit) an exception was raised:
>     ** (Ecto.QueryError) deps/ecto/lib/ecto/association.ex:726: field `Magellanql.Country.id` in `where` does not exist in the schema in query:
>
> from c in Magellanql.Country,
>   where: c.id in ^[887, 882, 704, 862, 860, 858, 804, 834, 792, 788, 776, 795, 762, 764, 148, 760, 690, 752, 705, 703, 706, 222, 686, 736, 682, 643, 642, 634, 600, 620, 408, 616, 598, 608, 604, 591, 586, 512, 554, 524, 578, 558, 566, 480, 496, 499, 466, 807, 484, 498, 504, 428, 442, 440, 426, 434, 422, 418, 414, 410, 116, 417, 398, 392, 400, 380, 376, 352, 368, 364, 372, 356, 360, 348, 332, 191, 340, 320, 300, 624, 324, 268, 266, 250, 246, 231, 233, 724, 818, 218, 12, 214, 262, 276, 203, 196, 192, 170, 178, 180, 156, 152, 756, 124, 140, 64, 76, 68, 112, 70, 100, 50, 204, 56, 31, 51, 32, 784, 20, 8, 4, 716, 670, 840, 800, 520, 562, 516, 458, 308, 826, 72, 158, 688, 470, 104, 584, 462, 144, 583, 242, 208, 212, 40, 36, 28, 626, 275, 48, 44, 232, 894, 710, 548, 780, 748, 740, 674, 528, 508, 450, 492, 438, 662, 430, 296, 404, 388, 328, 270, 288, 120, 96, 52, 84, 108, 24, 581, 798, 768, 678, 728, 694, 90, 654, 702, 646, 585, 478, 454, 659, 304, 226, 188, 174, 132, 384, 854, 535],
>   select: {c.id, c}
>
>         (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
>         (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
>         (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
>         (ecto) lib/ecto/repo/queryable.ex:119: Ecto.Repo.Queryable.execute/5
>         (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
>         (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
>
> Expected behavior
>
> The query successfully preloads the parent entities.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1443>
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by CrshOverride** [comment]
@josevalim Passing the `references` option get the query working again. This wasn't necessary on the 1.x release of Ecto though.

**Comment by josevalim** [comment]
Nice! @CrshOverride yup, it is a change to 2.0. :)
