### ISSUE TITLE
Maybe `validate_confirmation/3` should require the confirmation field

### ISSUE THREAD

**Issue by asonge** [elixir-lang/ecto#1450]
The docs say that

> Note that this does not add a validation error if the confirmation field is nil. Note “email_confirmation” does not need to be added as a virtual field in your schema.

The problem is that if I do not add it as a virtual field in my schema, I cannot use `validate_required/3` to make sure the changeset contains the parameter. Virtual fields seem very model-like compared to the schema/representation model we are after in Ecto 2.

It seems that we should either provide a way to validate the existence of a parameter *or* `validate_confirmation/3` should have an option to require the confirmation to exist. This seems particularly important as these confirmations are important for security. I can imagine someone using a confirmation to verify the name of a resource that the user has to type in to delete. It might be easy to accidentally forget to include this parameter and enable delete without confirmation.

**Comment by josevalim** [comment]
A `required: true` option is fine then. The default should be false.

**Comment by michalmuskala** [comment]
I think it should be the default to check the confirmation field even exists on the schema.

A possible way to not enforce a virtual field on a schema is to have a `with` option:
```elixir
|> validate_confirmation(:password, with: &get_field(&1, :password_confirmation))
|> validate_confirmation(:foo, with: &(&1.params["foo_confirmation"]))
```

**Comment by josevalim** [comment]
@michalmuskala then it is better to just write your own confirmation code. :P

**Comment by michalmuskala** [comment]
That's probably good point.

But I still think we should error if the confirmation field does not exist. This can lead to subtle bugs.

**Comment by asonge** [comment]
Just to make a short case for making it true by default:

- For those making normal UI apps, it might be a surprise that they have to pass an extra option to enable requiring it to exist
- For those making API's without UI, they won't include the confirmation validator at all
- For those making normal UI apps that also have API functionality, and they turn to the manual when the API request fails, they know that if they turn off the confirmation requirement, and that they need to add extra code somewhere UI-specific to enforce that the parameter exists.

**Comment by josevalim** [comment]
> For those making normal UI apps, it might be a surprise that they have to pass an extra option to enable requiring it to exist

They mostly don't care because the UI will be passing the confirmation field anyway. If the UI doesn't, that's where the bug is.

> For those making normal UI apps that also have API functionality, and they turn to the manual when the API request fails, they know that if they turn off the confirmation requirement, and that they need to add extra code somewhere UI-specific to enforce that the parameter exists.

Opposite to a default that works for both today? :)

Let's also not forget that forcing confirmation by default means every Mix task, test and code that you write that uses the changeset needs to pass a needless confirmation value because UI concerns are creeping in. If that's what you want, fine, but I don't think it should be the default.

**Comment by josevalim** [comment]
If someone would like to contribute `required: true`, please send a PR.

**Comment by alexauritt** [comment]
@josevalim -- is this up for grabs? I'd like to take a pass.

**Comment by josevalim** [comment]
If @asonge and @micmus still find this useful, then surely!

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by michalmuskala** [comment]
Closed via https://github.com/elixir-lang/ecto/pull/1467
