### ISSUE TITLE
Multiple joins of one table when using `has_many :through` or `many_to_many`

### ISSUE THREAD

**Issue by gaynetdinov** [elixir-lang/ecto#1456]
### Environment

* Elixir version (elixir -v): 1.2.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 9.5.2
* Ecto version (mix deps): ecto 2.0.0-rc.5
* Database adapter and version (mix deps): postgrex 0.11.1
* Operating system: OSX

### Current behavior

I have a table which is kind of many-to-many, but between 3 tables. So this table has 3 tablename_id columns. For example, I have `User`, `Role` and `Resource`. Then there is `roles_users_resources` table which has `user_id`, `resource_id` and `role_id`. Many-to-many `roles_users_resources` table has `belongs_to` for `user` and `role`.

These are my associations in `User`:
```elixir
schema "users" do
  has_many :roles_users_resources, MyApp.RolesUsersResource
  has_many :resources, through: [:roles_users_resources, :resource]
  has_many :roles, through: [:roles_users_resources, :role]
end
```

The problem is that if I join `resources` and `roles` in my query, `roles_users_resources` table will be joined *twice*.

This query
```elixir
from u in User,
  join: role in assoc(u, :roles),
  join: resource in assoc(u, :resources),
```
results in
```sql
SELECT <...> FROM "users" AS u0 INNER JOIN "roles_users_resources" AS r3 ON r3."user_id" = u0."id" INNER JOIN "roles" AS r1 ON r1."id" = r3."role_id" INNER JOIN "roles_users_resources" AS r4 ON r4."user_id" = u0."id" INNER JOIN "roles_resources" AS r2 ON r2."id" = r4."resource_id" WHERE <.....>
```

To avoid that, I have to join more verbose:

`User.ex`
```elixir
schema "users" do
  has_many :roles_users_resources, MyApp.RolesUsersResource
end
```

And this query:
```elixir
from u in User,
  join: roles_users_resources in assoc(u, :roles_users_resources),
  join: role in assoc(roles_users_resources, :role),
  join: resource in assoc(roles_users_resources, :resource),
```

result in the following sql:
```sql
SELECT <...> FROM "users" AS u0 INNER JOIN "roles_users_resources" AS r1 ON r1."user_id" = u0."id" INNER JOIN "roles" AS r2 ON r2."id" = r1."role_id" INNER JOIN "roles_resources" AS r3 ON r3."id" = r1."resource_id" WHERE 
```

Another option would be to use `many_to_many` like this:
```elixir
schema "users" do
  many_to_many :resources, MyApp.Resource, join_through: "roles_users_resources"
  many_to_many :roles, MyApp.Role, join_through: "roles_users_resources"
end
```
and query in that case would look like this:
```elixir
from u in User,
  join: role in assoc(u, :roles),
  join: resource in assoc(u, :resources),
```
but again, such query leads to `roles_users_resources` being joined *twice*.

### Expected behavior

I'd expect that ecto can detect multiple joins through one table and join that table only once.

Thanks.

**Comment by josevalim** [comment]
@gaynetdinov yes, you will need to go with the more verbose approach. While we could attempt to fix this, it is definitely a non-trivial fix and it seems to a corner scenario that can be solved with a more explicit approach, so that's the way to go. :)
