### ISSUE TITLE
Add support for conditional operations in Multi functions

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ecto#1461]
If `nil` is returned from a multi function that operation would be skipped:

```elixir
Ecto.Multi.delete(:delete, fn %{data: data} ->
  if data do changeset end
end)
```

Another alternative would be to use lists, that way multiple records could operated on also:

```elixir
Ecto.Multi.delete(:delete, fn %{data: data} ->
  if data, do: [changeset], else: []
end)
```

**Comment by michalmuskala** [comment]
I wonder, maybe such complex logic is a good indication to migrate to a regular `Repo.transaction/2`?

I don't have strong feelings about this to be honest, but I'm not a big fan of complicating `Multi`. I think it's useful, because it's relatively simple and corresponds to direct operations on `Repo` that everybody understands.

**Comment by michalmuskala** [comment]
Just now someone asked for the version with lists on slack, so the use cases are there. I like this much more than returning nil.

Should this be with the same `insert` call, or maybe there should be a different function like `insert_many`? The case for a different function is that `Repo.insert` does not accept lists or nils. The case against is that `insert_many` or `insert_each` is very similar to `insert_all`.

/cc @josevalim

**Comment by josevalim** [comment]
To me that indicates another problem: that our function support is not as generic than we would like it to be. Maybe we would rather like to provide prepend and append with a function so users can generate multi inside multi and have those prepended/appended?

**Comment by ericmj** [comment]
> Maybe we would rather like to provide prepend and append with a function so users can generate multi inside multi and have those prepended/appended?

I think this is the right approach because otherwise we run the risk of adding more and more complexity to multi until they are as powerful as calling Repo functions directly. If we can generate multi inside multi we should be able to do anything with multi that we can with the Repo functions.

But this raises the question that @michalmuskala had with "I wonder, maybe such complex logic is a good indication to migrate to a regular Repo.transaction/2?". What would be the benefit of multi over a function that does the same thing by calling Repo functions?

**Comment by josevalim** [comment]
> I think this is the right approach because otherwise we run the risk of adding more and more complexity to multi until they are as powerful as calling Repo functions directly.

If we all agree this is the way to go, we should probably remove function support from insert/update/delete and add it to prepend/append only.

**Comment by michalmuskala** [comment]
@josevalim I'm not clear on how the `append` with functions would work, could you expand on that idea a little bit more?

**Comment by josevalim** [comment]
Closing in favor of #1464.
