### ISSUE TITLE
Add support for functions in Multi.insert_all

### ISSUE THREAD

**Issue by swennemans** [elixir-lang/ecto#1463]
As requested by @michalmuskala in Slack channel. 

Currently `Multi.insert_all` doesn't accept functions as a parameter. 
```
Multi.new
    |> Multi.insert(:foo, changeset)
    |> Multi.insert_all(:bar, Bars, &Enum.map([1,2], fn x -> %Bars{foo_id: &1.foo.id, something: x} end))
```

**Comment by josevalim** [comment]
Thank you! We are closing this because it can be supported by the prepend/append proposal currently at #1461.
