### ISSUE TITLE
Error using a pinned binary variable in where/3?

### ISSUE THREAD

**Issue by jordan0day** [elixir-lang/ecto#1465]
If I use the `where/3` macro with a binary literal, my query succeeds:
```elixir
Order
|> where([o], o.id == <<205, 84, 204, 152, 29, 245, 17, 230, 164, 245, 8, 0, 39, 126, 110, 113>>)
|> Repo.all

13:37:24.718 [debug] QUERY OK db=1.6ms decode=0.1ms
SELECT o0.`id`, o0.`sequence`, ... FROM `order` AS o0 WHERE (o0.`id` = x'cd54cc981df511e6a4f50800277e6e71') []
[%TestApp.Schemas.Order{__meta__: #Ecto.Schema.Metadata<:loaded> ...}]
```

But if I bind that value to a variable and try to use it, I get an `Ecto.Query.CastError`:
```elixir
id = <<205, 84, 204, 152, 29, 245, 17, 230, 164, 245, 8, 0, 39, 126, 110, 113>>

Order
|> where([o], o.id == ^id)
|> Repo.all

** (Ecto.Query.CastError) iex:52: value `<<205, 84, 204, 152, 29, 245, 17, 230, 164, 245, 8, 0, 39, 126, 110, 113>>` cannot be dumped to type :binary_id in query:

from o in TestApp.Schemas.Order,
  where: o.id == ^<<205, 84, 204, 152, 29, 245, 17, 230, 164, 245, 8, 0, 39, 126, 110, 113>>,
  select: o

    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
```

### Environment

* Elixir version (elixir -v): 1.2.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): mysql 5.5
* Ecto version (mix deps): 2.0.0-rc.5
* Database adapter and version (mix deps): mariaex 0.7.5
* Operating system: OS X

**Comment by josevalim** [comment]
@jordan0day the first one is sent directly to the database which will then compare binary to binary. The second one, however, will check the Ecto type and the value you are giving is not a binary id. Ecto is expecting something that looks like a UUID. We could likely make the first one also fail but the second and third ones should definitely raise.

**Comment by jordan0day** [comment]
Thanks @josevalim. That makes sense.
