### ISSUE TITLE
Improve error when trying to name an association the same as its foreign_key

### ISSUE THREAD

**Issue by narrowtux** [elixir-lang/ecto#1468]
When trying to do `belongs_to` with a custom `:foreign_key` that is the same as the name of the association, ecto crashes with 

```
** (exit) an exception was raised:
    ** (Ecto.QueryError) /path/to/project/deps/ecto/lib/ecto/association.ex:392: field `AppsrvWeb.Organization.parent` in `where` does not exist in the schema in query:
from o in AppsrvWeb.Organization,
  where: o.parent in ^[2],
  select: {o.parent, o}
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/repo/queryable.ex:119: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
        (ecto) lib/ecto/repo/preloader.ex:171: Ecto.Repo.Preloader.fetch_query/8
        (ecto) lib/ecto/repo/preloader.ex:111: Ecto.Repo.Preloader.preload_assoc/10
        (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
```

This error message should be fixed to tell that the association name has to be different from the `foreign_key`. The documentation should also state that

**Comment by alexauritt** [comment]
@michalmuskala -- possibly above my pay grade, but happy to take a look

**Comment by michalmuskala** [comment]
Sure, go ahead.

**Comment by alexauritt** [comment]
@narrowtux -- to clarify, you're getting that error when you execute a query on the child table (while preloading the parent), and you're saying we should have a clearer error when we compile the association/fk in the child schema, correct?

Could you post some example schemas and a query? I'm not able to reproduce this as I am in fact getting a compilation error when I use the same name for the association and fk.

e.g. if I define:

```
defmodule Demo.Author do
  use Ecto.Schema

  schema "authors" do
    field :name, :string
    field :email, :string
  end
end

defmodule Demo.Post do
  use Ecto.Schema

  schema "posts" do
    field :title, :string
    belongs_to :email, Demo.Author, foreign_key: :email
  end
end
```

... then I'll get the following compilation error:

```
== Compilation error on file web/models/post.ex ==
** (ArgumentError) field/association :email is already set on schema
    lib/ecto/schema.ex:1346: Ecto.Schema.put_struct_field/3
    lib/ecto/schema.ex:1326: Ecto.Schema.association/5
    lib/ecto/schema.ex:1180: Ecto.Schema.__belongs_to__/4
    web/models/post.ex:6: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

That's more or less the warning you desire, no?
Or, more likley, let me know what I'm missing.

Thanks!

**Comment by narrowtux** [comment]
Hm yes that was the error that would appear but as a noob in all things elixir, it wasn't clear to me that it would mean that.

**Comment by alexauritt** [comment]
@narrowtux ok thanks for clarification

**Comment by narrowtux** [comment]
Basically my train of thought when I saw this error
 
 * already defined? I'll check other fields in the schema
 * No, I didn't manually define this
 * Must be some bug

After clarification with michal it was clear to me though :)

**Comment by alexauritt** [comment]
close? see #1471
