### ISSUE TITLE
Updated_at date is earlier than the inserted_at date on insert 

### ISSUE THREAD

**Issue by twinfire** [elixir-lang/ecto#1486]
Elixir 1.2.2
Ecto 1.1.8
PostgreSQL 9.5.1.0 and Sql Server
Adapter: Ecto.Adapters.Postgres and Tds.Ecto
OS: OSX, 10.11.5 and CentOS 6.x

We have noticed that when we persist an model that uses the "timestamps" macro, the updated_at date in the table is before the inserted_at date in the table.  For example, here is a record from our persist:

inserted_at
timestamp without time zone
"2016-06-13 17:41:12.960207"        

updated_at
timestamp without time zone
"2016-06-13 17:41:12.960195"

The updated_at date should probably either be null or the exact same as the inserted_at date at creation.

**Comment by michalmuskala** [comment]
It would be fairly easy to reverse them and have the `updated_at` time after the `inserted_at`, but looking at how it currently works - where both are generated independently, it's hard to make them the same. At least I don't have any ideas how this could be achieved other than coupling the two together.

**Comment by josevalim** [comment]
I have fixed this for v2.0 by reversing the order. It will guarantee updated_at > inserted_at but they won't be the same.

**Comment by josevalim** [comment]
Backported to v1.1 as well, thank you!
