### ISSUE TITLE
MatchError exception when binding variable in Repo.transaction/1

### ISSUE THREAD

**Issue by almightycouch** [elixir-lang/ecto#1488]
### Environment

* Elixir version 1.2.6
* PostgreSQL 9.5.3
* Ecto version 2.0.0-rc5
* Mac OS
* [Source code](https://github.com/elixir-lang/ecto/files/315119/audiopia.zip)

### Issue

I'm having some troubles to understand why the code below:

```elixir
  if false do
    user = true
  else
    Repo.transaction(fn ->
      user = false # raises error
    end)
  end
```

raises following error:

```
(MatchError) no match of right hand side value: false
```

Basically, i'm wondering why the `user` variable from the `if` statement leaks to the `Repo.transaction` closure function. Are both branches sharing the same context?

* When renaming `user` to something else in one of the if/else branch the problem doesn't occur.
* This only happens in combination with `Repo.transaction`:

```elixir
  if false do
    user = true
  else
    cb = fn ->
      user = false # doesn't raise error
    end
    cb.()
  end
```

I've attached a working Phoenix example (see environment section).

Here's how my real-world code looks like this:

```elixir
query = from user in User,
       join: auth in assoc(user, :authorizations),
      where: user.email == ^info.email,
    preload: [authorizations: auth]

if user = Repo.one(query) do
  auth =
    if auth = Enum.find(user.authorizations, &(&1.uid == uid && &1.provider == provider)) do
      Repo.update!(change(auth, token: token))
    else
      Repo.insert!(build_assoc(user, :authorizations, uid: uid, provider: provider, token: token))
    end
  user = put_in(user.authorizations, [auth])
  {:ok, user}
else
  Repo.transaction(fn ->
    user = Repo.insert!(struct(User, Map.take(info, [:name, :email])))
    auth = Repo.insert!(build_assoc(user, :authorizations, uid: uid, provider: provider, token: token))
    put_in(user.authorizations, [auth])
  end)
end
```

**Comment by josevalim** [comment]
Can you post the full stacktrace? You are not getting a match error there but likely because a transaction expects you to return `{:ok, value}` or something of sorts.

**Comment by almightycouch** [comment]
Hi @josevalim,

The `transaction/1` function (when successful) wraps the return value from it's closure to `{:ok, value}`:

> A successful transaction returns the value returned by the function wrapped in a tuple as {:ok, value}.

Here's a small unit test which should allow you to reproduce the error:

```elixir
defmodule MyTest.TransactionTest do
  use MyTest.ModelCase

  test "successfull transaction" do
    result =
      Repo.transaction(fn ->
        _user = 21
      end)
    assert {:ok, 21} = result
  end

  test "transaction raises match error" do
    if false do
      user = 21
    else
      assert_raise(MatchError, fn ->
        Repo.transaction(fn ->
          user = 42
        end)
      end)
    end
  end
end
```

Also note that the compile has following warnings when executing the tests:
```
test/models/transaction_test.exs:18: warning: no clause will ever match
test/models/transaction_test.exs:18: warning: this check/guard will always yield the same result
```

Line 18 being:

```elixir
user = 42
```

**Comment by fishcakez** [comment]
Thanks @almightycouch, this is a compiler bug: https://github.com/elixir-lang/elixir/issues/4815
