### ISSUE TITLE
Migrations failing: DBConnection.query/4 undefined

### ISSUE THREAD

**Issue by nickarora** [elixir-lang/ecto#1490]
### Environment

* Elixir version (elixir -v): 1.2.6
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MYSQL
* Ecto version (mix deps): phoenix-ecto 3.0.0-rc / ecto 2.0.0-rc
* Database adapter and version (mix deps): mariax 0.7.1
* Operating system: OSX El Capitan 10.11.13

### Current behavior
On my system, `mix ecto.migrate` currently fails with the following error:

```
** (UndefinedFunctionError) undefined function DBConnection.query/4
    (db_connection) DBConnection.query(Admin.Repo.Pool, %Mariaex.Query{connection_ref: nil, name: "", parameter_types: [], reserved?: false, statement: "CREATE TABLE IF NOT EXISTS `schema_migrations` (`version` bigint, `inserted_at` datetime, PRIMARY KEY (`version`)) ENGINE = INNODB", statement_id: nil, type: nil, types: []}, [], [decode_mapper: #Function<1.124042512/1 in Ecto.Adapters.SQL.query!/4>, timeout: :infinity, pool_timeout: 5000, timeout: 15000, adapter: Ecto.Adapters.MySQL, username: "root", password: "", database: "admin_dev", hostname: "localhost", pool_size: 10, pool: DBConnection.Poolboy])
    (ecto) lib/ecto/adapters/sql.ex:174: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/mysql.ex:99: Ecto.Adapters.MySQL.execute_ddl/3
    (ecto) lib/ecto/migrator.ex:43: Ecto.Migrator.migrated_versions/2
    (ecto) lib/ecto/migrator.ex:142: Ecto.Migrator.run/4
    (ecto) lib/mix/tasks/ecto.migrate.ex:70: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

I believe this is because db_connection recently removed the DBConnection.query/4 method

see this commit: https://github.com/fishcakez/db_connection/commit/cca87d11d09c963b106ee6a0a460b3f603810d6a

### Expected behavior

The migrations to update the DB successfully

**Comment by josevalim** [comment]
Please add {:db_connection,  "~> 0.2.5"} to your deps in your `mix.exs` for now.

**Comment by stormpat** [comment]
If you have `phoenix_ecto 3-beta` you must override `{:db_connection, "~> 0.2.5", override: true}`

**Comment by josevalim** [comment]
I have just released a new ecto version that fixes this issue. So upgrading Ecto should work too.

**Comment by nickarora** [comment]
@josevalim thanks for the fast response! the upgrade has fixed the issue
