### ISSUE TITLE
assigns method for mass updates of models

### ISSUE THREAD

**Issue by jeregrine** [elixir-lang/ecto#246]
> 12:51 <josevalim> assign(Ecto.Model.t, params_with_keys_as_binaries_or_atoms)
> 12:51 <josevalim> assign would also perform type casting on values
> 12:52 <josevalim> and it should also support only: for parameter filtering

To help fix:
https://gist.github.com/jarednorman/6d509d96685c3fa98b07

**Comment by josevalim** [comment]
Now available in changesets!
