### ISSUE TITLE
Have Query return a map

### ISSUE THREAD

**Issue by chadbean** [elixir-lang/ecto#305]
When selecting multiple values, is it possible to have Query return a map like {:col1 => val1, :col2 => val2} ?

edit: specifically with the `all` function.

**Comment by josevalim** [comment]
1. Allow maps in [select builder](https://github.com/elixir-lang/ecto/blob/master/lib/ecto/query/builder/select.ex#L33). We will require keys to be atoms, binaries or numbers.

2. [Extract fields from map in the planner](https://github.com/elixir-lang/ecto/blob/master/lib/ecto/query/planner.ex#L420)

3. [Generate the map after we got results](https://github.com/elixir-lang/ecto/blob/master/lib/ecto/repo/queryable.ex#L128)

**Comment by whatyouhide** [comment]
@josevalim I'm working on it :)
