### ISSUE TITLE
`update_all` with dates in Ecto 0.5.0

### ISSUE THREAD

**Issue by drewolson** [elixir-lang/ecto#349]
If I attempt to update all records with a date in Ecto 0.5.0, I see a big stack trace. I'm doing something like this:

```elixir
new_date = Ecto.DateTime.utc |> Ecto.DateTime.to_date
MyApp.Model |> MyApp.Repo.update_all(date_field: ^new_date)
```

The error looks something like this:

```bash
** (exit) exited in: GenServer.call(#PID<0.167.0>, {:query, "UPDATE \"models\" AS m0 SET \"date_field\" = $1", [%Ecto.Date{day: 13, month: 1, year: 2015}], [timeout: 5000]}, 5000)
    ** (EXIT) exited in: :gen_server.call(#PID<0.173.0>, {:query, "UPDATE \"models\" AS m0 SET \"date_field\" = $1", [%Ecto.Date{day: 13, month: 1, year: 2015}], [timeout: 5000]}, 5000)
        ** (EXIT) an exception was raised:
            ** (FunctionClauseError) no function clause matching in :calendar.date_to_gregorian_days/1
```

**Comment by josevalim** [comment]
Fixed on master. On master I have already removed the old validations and old-style configuration, therefore, if you want to see this backported to v0.5.0, please let me know!

**Comment by drewolson** [comment]
If it's not too much of a hassle I'd love it backported so I can gradually introduce changesets.

**Comment by josevalim** [comment]
Ok, v0.5.1 released with this fix and a couple other improvements.

**Comment by drewolson** [comment]
Thanks :+1:
