### ISSUE TITLE
Store state (built, loaded, deleted) in model

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#353]
The idea here is to have a virtual field named `__state__` always generated with default value of `:built`. Loading data from the database (be it on Repo.all, Repo.insert or Repo.update) should set its status to `:loaded` while Repo.delete sets it to `:deleted`.

**Comment by briksoftware** [comment]
if nobody is working on this, I can do it.

**Comment by josevalim** [comment]
Please go ahead! :D
