### ISSUE TITLE
Support timestamps

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#354]
The goal of this task is to provide automatic management of created_at and updated_at for models. it consists of three changes.

## Schemas

Schemas will automatically generate `inserted_at` and `updated_at` fields. `@timestamps false` can be set before the `schema/2` to avoid generating timestamps and `@timestamps Type` can be used to give the generated timestamps a custom time.

## Migrations

Migrations will automatically generate `inserted_at` and `updated_at` fields. `timestamps: false` can be given to `table/2` to not generate a timestamp or customize its type.

## Ecto.Model.Timestamps

Ecto.Model.Timestamps will include a before_insert and a before_update callback into the model that automatically sets the `inserted_at` and `updated_at` values if such fields exist in the model and are not set in the changeset.

**Comment by joshnuss** [comment]
@josevalim A `Repo.touch/1` function could be useful too

**Comment by MSch** [comment]
Might be nice to make `Ecto.Model.Timestamps` not only check `inserted_at` and `updated_at` but also `created_at`, `created_on` and `updated_on`, to match [Rails behavior](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/timestamp.rb#L89-L95). Or just make the field names customizable.

**Comment by briksoftware** [comment]
I also vote for created_at/updated_at couple. These are quite common names and using them would make it easier to port existing applications without having to disable timestamp support, or worse rename fields.

Making them configurable would of course be best, but maybe unnecessary.

**Comment by josevalim** [comment]
So we should make it configurable given that I don't think it makes sense to use `created_at` as nothing in Ecto uses the `create` terminology. :(

**Comment by kotedo** [comment]
Yay!

**Comment by drewolson** [comment]
I like this, seems like a no brainer to do it.

**Comment by paulcsmith** [comment]
I prefer `inserted_at` to `created_at`, but an option to change that might be useful.

**Comment by tilo** [comment]
@josevalim so how can you configure Ecto to use :created_at and :updated_at to be backwards compatible with an existing Rails DB?

**Comment by michalmuskala** [comment]
@tilo you can pass options to the `Ecto.Schema.timestamps/1` macro or use the `@timestamp_opts` attribute  - you can find more information in the documentation https://hexdocs.pm/ecto/Ecto.Schema.html#timestamps/1
