### ISSUE TITLE
Support optimistic locking

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#355]
The idea here is to provide an `Ecto.Model.OptimisticLocking` module that introduces the macro `optimistic_lock :field_name`.  To implement this feature we will need:

1. Introduce the idea of filters into changesets. Filters will be passed to the underlying insert/update/delete operation and filtering the resource to be modified

2. Those filters will now be handled as part of those operations in the repository [alongside the pkfilter](https://github.com/elixir-lang/ecto/blob/master/lib/ecto/repo/model.ex#L60)

3. Because queries can now return [`{:error, :stale}`](https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/sql.ex#L381), we should match them in the Repo and raise `Ecto.StaleModelError`

4. Now with everything in hand, we can implement the `Ecto.Model.OptimisticLocking`. Once `optimistic_lock :field_name` is called, it will define before_update and before_delete callbacks that will read the value of the field in the changeset model and add it as a filter to the changeset and add a change that increments the lock field by one

5. Docs, tests and profit! $$$

**Comment by whatyouhide** [comment]
Pong, I'd like to give this a shot!

On Friday, February 20, 2015, José Valim <notifications@github.com> wrote:

> /cc @briksoftware <https://github.com/briksoftware> @whatyouhide
> <https://github.com/whatyouhide> If any of you want to tackle it, please
> ping here! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/355#issuecomment-75210101>.
>


-- 

Andrea Leopardi
an.leopardi@gmail.com

**Comment by josevalim** [comment]
Merged, thank you @whatyouhide!
