### ISSUE TITLE
Support associations in changesets

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#357]

**Comment by tony612** [comment]
Do you mean something like `Changeset.cast(post.author, params, [], [])` and `Changeset.cast(post.comments, params, [], [])` ?

**Comment by josevalim** [comment]
No, the idea here is a bit fuzzy yet. This is mostly a reminder to write a proper plan eventually.

**Comment by tony612** [comment]
@josevalim Got it.

**Comment by josevalim** [comment]
Sorry for the conciseness earlier. Basically the idea is to support updating the associations from post, so given your earlier example, something like `cast(post, %{comments: ...}, ..., ...)` would update them. But my earlier comment still applies, it is still a bit fuzzy, I need to do a bit more tinkering on this. :)

**Comment by tony612** [comment]
@josevalim Maybe we can let `post_changeset` has a associated `comments_changeset`. So about how to get right changeset of `comments`, one solution I think of is to specify one function of association module to call in `has_one/has_many`, e.g. `has_many comments, Comment, changeset: :comment_changeset`. Any idea?

**Comment by josevalim** [comment]
I don't want to specify it at the module level though because it is not very flexible. Maybe we would have a function that we would call on the changeset after being cast. That would be ok because we need to explicit allow the values into the changeset anyway. The other part of the issue is that we would need to change the repository to save associations too which is a much bigger task. I need to put more thoughts into this.

**Comment by tony612** [comment]
@josevalim More thoughts about this issue?

**Comment by josevalim** [comment]
Not yet. :)

**Comment by josevalim** [comment]
In master.
