### ISSUE TITLE
Type conversion issue in 0.5.x

### ISSUE THREAD

**Issue by herenowcoder** [elixir-lang/ecto#364]
Hi,

I have a many-to-many relation done classically by one-to-many + many-to-one, like this:
```Elixir
defmodule Subscription do
  schema "subscriptions" do
    has_many   :payment_matches, PayMatch
  end
end

defmodule PayMatch do
  @primary_key false
  schema "payment_match" do
    belongs_to :subscription, Subscription, references: :id
    belongs_to :payment,      Payment,      references: :id
  end
end

defmodule Payment do
  schema "payments" do
    has_many   :sub_matches, PayMatch
  end
end
```
(fields irrelevant to the case omitted)

Now this query - which does nested preload - was working in 0.2.x, 0.4.0,
but errors on 0.5.1:

```Elixir
iex(34)> (from s in Subscription, where: s.id==1, preload: [payment_matches: :payment])\
 |> Repo.one
** (MatchError) no match of right hand side value: :error
      (ecto) lib/ecto/schema.ex:394: anonymous fn/3 in Ecto.Schema.__load__/4
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
      (ecto) lib/ecto/schema.ex:392: Ecto.Schema.__load__/4
      (ecto) lib/ecto/adapters/postgres.ex:201: anonymous fn/3 in Ecto.Adapters.Postgres.process_row/2
    (elixir) lib/enum.ex:1036: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
      (ecto) lib/ecto/adapters/postgres.ex:194: Ecto.Adapters.Postgres.process_row/2
    (elixir) lib/enum.ex:977: Enum."-map/2-lc$^0/1-0-"/2
      (ecto) lib/ecto/repo/queryable.ex:20: Ecto.Repo.Queryable.all/4
```
Note that query itself is compiled without a problem,
```Elixir
iex(34)> (from s in Subscription, where: s.id==1, preload: [payment_matches: :payment])            
#Ecto.Query<from s in Subscription, where: s.id == 1,
 preload: [payment_matches: [:payment]]>
```

**Comment by josevalim** [comment]
Good catch. Can you please do me one quick favor?

Go to deps/ecto/lib/ecto/schema.rb and before this line:

https://github.com/elixir-lang/ecto/blob/v0.5.1/lib/ecto/schema.ex#L394

Add:

    IO.inspect {type, elem(values, idx)}

Once you change, `mix deps.compile ecto` must be enough to recompile it.

Something is reading the wrong type to the database, we need to figure out what. :) If you have custom types, that may be the reason too.

Thanks for reporting, I will improve those in upcoming releases regardless. :)

**Comment by herenowcoder** [comment]
@josevalim you got a good intuition.
It actually has nothing to do with nested relationships, it's rather a type conversion.

from psql:
```sql
# \d payments
                                         Table "public.payments"
       Column       |            Type             |                       Modifiers                       
--------------------+-----------------------------+-------------------------------------------------------
 id                 | integer                     | not null default nextval('payments_id_seq'::regclass)
 exec_date          | date                        | not null
 order_date         | date                        | not null
 amount             | numeric(8,2)                | not null
[...]
```

from iex:
```Elixir
iex(2)> (from p in Payment)|>Repo.one
SELECT p0."id", p0."exec_date", p0."order_date", p0."amount", p0."currency", p0."ending_balance", p0."giver_account", p0."giver_address", p0."created_at", p0."updated_at" FROM "payments" AS p0 [43632 us]
{:integer, 1}
{:date, {2010, 5, 10}}
{:date, {2010, 5, 10}}
{:float, #Decimal<16.00>}
** (MatchError) no match of right hand side value: :error
[...]
```
this field is defined at the Ecto level as:
```
   field :amount,         :float
```

**Comment by josevalim** [comment]
Ok, we have two options here:

1. Declare the type as `:decimal`

2. Allow numeric types from the database (which come as decimals) to be converted into floats

Right now I am more inclined to ask you to convert the type to :decimal in your schema. What do you think? (I have just pushed better error messages to master).

**Comment by herenowcoder** [comment]
I go for (1). My app should use it anyway.

I think I was having a schema with `float` since a year when either you didn't have Decimal type handled in Ecto or I didn't care. :D

Thx @josevalim for help. Detailed error message will definitely be a good thing
