### ISSUE TITLE
-1 to assoc-in-select deprecation

### ISSUE THREAD

**Issue by herenowcoder** [elixir-lang/ecto#365]
Hi,

now catching up changes from 0.2.5 to 0.5.1 and syncing my production with it.

A few words on this change:

* assoc/2 in select is deprecated, please use Ecto.Query.preload/3 instead

I don't agree. Preloading isn't a single solution to obtaining the data from a related entity.

In fact, preloading means having many `select`s underneath, which may be a perf killer. Good to have an easy preloading when you don't care about many selects, but also good to have ability to consciously fetch all needed data in one sql op - with an explicit join.

I have a specific codebase with lots of constructs like this (dumbing down to blog example):

```Elixir
from p in Post,
  where: p.foo == some_condition,
  join: c in p.comments,    # yeah this is pre-0.4.0 syntax
  select: assoc(p, comments: c)
```
..precisely to get the data in one select.

Now with such arbitrary deprecation I can't do this anymore.

**Comment by josevalim** [comment]
You can! :D

```elixir
from p in Post,
  where: p.foo == some_condition,
  join: c in assoc(p, :comments),
  preload: [comments: c]
```

**Comment by josevalim** [comment]
Basically, preload means preloading the associations, you can specify a join and, if you don't, it means it will be fetched afterwards. So we have slightly change its semantics but you still can do everything you want with it. :)

**Comment by herenowcoder** [comment]
Well I tried sth like you wrote but more in a way:
```Elixir
from p in Post,
  where: p.foo == some_condition,
  join: c in assoc(p, :comments),
  preload: :comments
```
- then it ended as 2 selects.

Now you say it should go like: `preload: [comments: c]` where `c` is specified in a join. Sounds legit.

**Comment by herenowcoder** [comment]
Well it isn't working for the cases where a table we start joining doesn't have pk. I got the `Ecto.NoPrimaryKeyError`.

And before I start to answer "why I don't have pk on a table" - there's a reason for that - a note, I was under impression that an association defined is enough for using the preload you described.

Now about a lack of pk. Well I have tables with 'artificial keys' - they are not autogenerated but they reflect some other "parent" id and should stay the same. So such key logically is both a pk (but arbitrary) and a fk. Imagine that this is a "optional subfeature" table for some other entity. Not so bad design - somewhat XX-century though - and more important, I can't change this design for a particular customer.

So, in order to have it working in Ecto, I made the schema with `primary_key: false` and declared this specific id in terms of `belongs_to` - because, logically, it belongs to the "parent" entity. Everything was fine, but now I can't use queries like you described. :]

**Comment by josevalim** [comment]
Can't you define `@primary_key {:id, ..., ...}` with that column? It can be any column that is unique.

**Comment by herenowcoder** [comment]
yup that's 1st thing I tried, but I got:
```Elixir
== Compilation error on file lib/model/entities/cite.ex ==
** (ArgumentError) field/association `cite_id` is already set on schema
    lib/ecto/schema.ex:506: Ecto.Schema.put_struct_field/3
    lib/ecto/schema.ex:372: Ecto.Schema.__field__/4
    lib/model/entities/cite.ex:63: (module)
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:121: :erl_eval.exprs/5
```

I believe it may be because this column also occurs in the `belongs_to` relation, that is my impression

**Comment by herenowcoder** [comment]
So it would boild down to a case that Ecto currently can't handle a pk which is at the same time fk to another table, if I'm right

**Comment by herenowcoder** [comment]
I can't say if this is unusually arcane corner case or typical, but well, that's the databases I inherited :)

**Comment by josevalim** [comment]
@herenowcoder ah, I completely see this. Try this hack for now. Before you call `schema/2`, please define:

    def __schema__(:primary_key), do: :cite_id
    @primary_key false

I will release v0.6.0 tomorrow and I will guarantee to have a fix for your case.

**Comment by josevalim** [comment]
If that doesn't work, try this:

```elixir
schema ... do
  Module.delete_attribute(__MODULE__, :struct_fields)
  # your fields
end
```

**Comment by herenowcoder** [comment]
The 1st hack works. Thank's for the support :DD. Lookin forward 0.6.0

**Comment by jamiesunderland** [comment]
I wish this was in the documentation.

**Comment by michalmuskala** [comment]
What exactly? This issue refers to the version that is 2.5 years old and was fixed a long time ago. The setting `auto_field` introduced in the fix is currently called `define_field` and is documented in [`belongs_to/3` documentation](https://hexdocs.pm/ecto/Ecto.Schema.html#belongs_to/3):

> `:define_field` - When false, does not automatically define a `:foreign_key` field, implying the user is defining the field manually elsewhere

**Comment by wkhere** [comment]
Hi folks!

I believe Michał @michalmuskala is right. The issue was created in a really hot period, when Ecto's both API and implementation was changing almost every month.
It's not the case anymore :)

cheers,
W.
