### ISSUE TITLE
Support subqueries

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#371]

**Comment by gjaldon** [comment]
I would like to try my hand on this, @josevalim. Did you already have anything in mind for how the API would look like for this?

**Comment by josevalim** [comment]
@gjaldon I was thinking about supporting `where: e in ^q` where q is another query. I also want to be upfront and say this feature requires *a lot* of work.

**Comment by renatomoya** [comment]
@josevalim Does it require work to be done in the adapters packages at some level? Any chance this can be split into two smaller but related issues?

**Comment by josevalim** [comment]
@renatomoya no, no work should be required on the adapters packages themselves.

**Comment by gjaldon** [comment]
I have a lot of free time this week so will finally get started with this.

**Comment by josevalim** [comment]
We should also support subqueries in joins. Maybe start by supporting subqueries in joins since the in cases can be rewritten as joins but not all join cases can be written with in.

**Comment by darkbaby123** [comment]
Just a note, subqueries are also used in "from". Although most of time "join" can do the same work, sometimes "from (subquery) as xxx" is a better choice than join.

**Comment by michalmuskala** [comment]
@josevalim Does it mean we do support subqueries, or that we won't for now and you were cleaning the issues?

**Comment by mitchellhenke** [comment]
@michalmuskala looks like support :)

https://github.com/elixir-lang/ecto/pull/1231
