### ISSUE TITLE
Docs Update

### ISSUE THREAD

**Issue by jakerobers** [elixir-lang/ecto#372]
https://github.com/elixir-lang/ecto/blob/master/lib/ecto/query.ex#L606
should "created_at" be changed to "inserted_at"?

Also at https://github.com/elixir-lang/ecto/blob/master/lib/ecto/migration.ex#L57
If the first code block ( do change) is the same as the second ( do up ), should there be a timestamps method call in the second code block?

**Comment by josevalim** [comment]
Perfect, thank you! Both fixed
