### ISSUE TITLE
Allow "lazy expressions" for queries

### ISSUE THREAD

**Issue by yrashk** [elixir-lang/ecto#376]
Imagine I have a query the results of which I need to process (for example, run through Enum.map or filter). Wouldn't it be great to have something like this:

```elixir
from(i in Item) |> where([i], i.something == "something") |> pipe(fn(coll) -> Enum.map(coll, ...) end)
```

**Comment by josevalim** [comment]
I like this idea. It makes up for the lack of direct enumerable in the query. @ericmj, thoughts?

**Comment by ericmj** [comment]
It feels weird to add something like this to ecto. It can easily be solved by closures.

**Comment by josevalim** [comment]
@ericmj well, I disagree it can be solved by closures because now you are passing a closure instead of something that the adapter knows how to work with.

Here is an example of where this could be useful: we could implement preload completely with pipes and remove it from the repository if we had such feature. :)

**Comment by yrashk** [comment]
Wow, I haven't thought of this. Now I want thus feature even more

On Tuesday, January 20, 2015, José Valim <notifications@github.com> wrote:

> @ericmj <https://github.com/ericmj> well, I disagree it can be solved by
> closures because now you are passing a closure instead of something that
> the adapter knows how to work with.
>
> Here is an example of where this could be useful: we could implement
> preload completely with pipes and remove it from the repository if we had
> such feature. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/376#issuecomment-70637365>.
>


-- 
Y.
My company is hiring: https://trustatom.com/jobs

**Comment by ericmj** [comment]
Why would you pass things directly to the adapter?

```elixir
fn repo ->
  query
  |> repo.all
  |> Enum.map(...)
end
```

**Comment by yrashk** [comment]
The whole idea here is to transparently return query able things. In any
project, there's a lot of functions that can be chained together; however
this wouldn't work with something that requires closures. If we had pipes...

On Tuesday, January 20, 2015, Eric Meadows-Jönsson <notifications@github.com>
wrote:

> Closed #376 <https://github.com/elixir-lang/ecto/issues/376>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/376#event-221525706>.
>


-- 
Y.
My company is hiring: https://trustatom.com/jobs

**Comment by ericmj** [comment]
How do you generically chain things together with pipes without knowing the format of the previous pipe or of the select? As you say preload could be implemented as pipes and preload actually has this issue, it requires you to select the model in the from.

You can compose all query functions in ecto without making assumptions about the original query, except for preload, I don't think we should add another one.

**Comment by josevalim** [comment]
After a talk with @ericmj we decided to not add this feature.

**Comment by yrashk** [comment]
What were the most important decision points?

On Wed, Feb 18, 2015 at 2:29 AM, José Valim <notifications@github.com>
wrote:

> After a talk with @ericmj <https://github.com/ericmj> we decided to not
> add this feature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/376#issuecomment-74735222>.
>



-- 
Y.
My company is hiring: https://trustatom.com/jobs
