### ISSUE TITLE
Allow table name in fragments

### ISSUE THREAD

**Issue by yrashk** [elixir-lang/ecto#379]
I have some fairly complex queries, and I often have to resort to queries. For simple ones, having something like `fragment("column = ?", ^value)` is sufficient, however, once the joins get into the picture, there is always a chance for column ambiguity (especially if you're joining with the same table). Ecto generates queries with table aliases like `f0`. Is there any way we can get this in fragments?

**Comment by troyk** [comment]
I wish ecto would support something similar to ActiveRecords find_by_sql

**Comment by josevalim** [comment]
It already supports both:

1. `fragment("? = ?", p.column, ^value)`

2. Ecto.Adapters.SQL.query(repo, "ANY SQL YOU WANT", [])

**Comment by josevalim** [comment]
The second one is available only on master.

**Comment by cmititiuc** [comment]
For others trying to access jsonb data, you can do

`fragment("?->>'json_key' = ?", a.column_name, ^some_value)`

results in `a0."column_name"->>'json_key' = ($1)` in your query

**Comment by lkananowicz** [comment]
Is there a way to use custom/varying column names in fragment? I mean the situation where I have 2 almost similar tables coming from different databases. Only couple of columns are different for historical reasons and I use those column names inside fragment(s). I want to unify Ecto queries to both of those tables as they were executed separately before.

Using simple questionmark notation `fragment("?", column_name)` causes column name to be appended into fragment however column ends up wrapped into double-quotes which is not desired.

**Comment by OvermindDL1** [comment]
> causes column name to be appended into fragment however column ends up wrapped into double-quotes which is not desired.

Why not?  That's what column names should be overall?

Also, should ask this on the Elixir forums, it won't really get visibility in a dead issue.  :-)

**Comment by lkananowicz** [comment]
@OvermindDL1 Thanks for the tip. I am going to ask on Elixir forums.
