### ISSUE TITLE
Changeset.validate_change behavior question

### ISSUE THREAD

**Issue by jordan0day** [elixir-lang/ecto#390]
It seems a little weird to me that all the built-in validation functions (inclusion, exclusion, etc.) update the errors list with a {field, error} tuple, but the validate_change function doesn't pass the field to the custom validator, so you have to jump through a few hoops to write a reusable validator that can also return the errors in this form.

That is, say I had a validator that ensured that `value` wasn't just whitespace (ignoring the fact we could probably do this with a regex and `validate_format`):

    def blank?(value) do
      length = value |> String.strip |> String.length
      if length == 0, do: ["cannot be blank"], else: []
    end
      
So if I did `validate_change(changeset, :whatever, &blank?/1)`, the returned changeset's error's list would be `["cannot be blank"]`, rather than `[{:whatever, "cannot be blank"}]`.

Additionally, if this same validator is used for two separate fields in the same changeset, the changeset's error list becomes: `["cannot be blank", "cannot be blank"]`

It seems to me that it might make sense to either have `validate_change` store the field name and the validator function's error's as a tuple, as the other validate functions do, or to pass the field and value to the validator function, rather than just the value.

**Comment by josevalim** [comment]
@jordan0day So we are theoretically supporting the same validator to attach multiple error messages in different fields, that's why it works the way they do. We could though "pass the field and value to the validator function, rather than just the value".

/cc @drewolson @jeregrine @ericmj thoughts?

**Comment by drewolson** [comment]
I struggled with exactly this problem after reading the docs. I did some source reading and it seems to me that `validate_change` is intended to be used as an internal helper function for custom validators. It should be used to write custom validators that only fire on changes.

@jordan0day I would probably write your validator as:

```elixir
def validate_present(changeset, field) do
  validate_change(changeset, field, fn val ->
    length = value |> String.strip |> String.length
    if length == 0, do: [{field, "cannot be blank"}], else: []
  end)
end
```

If you wanted to reuse `blank?` you could partially apply it.

```elixir
def validate_present(changeset, field) do
  validate_change(changeset, field, &blank(field, &1))
end
```

You could use it in your changeset like so:

```elixir
def changeset(model, params \\ nil) do
  params
  |> cast(model, ~w(...), ~w(...))
  |> validate_present(:field1)
  |> validate_present(:field2)
end
```
At the end of the day, I think we should focus on making the docs for `validate_change` clear that it is intended to be used as an "internal" helper for writing custom validations.

That said, for reusability I do think it might make sense to have the function passed to `validate_change` have an arity of 2 and accept the field name.

**Comment by josevalim** [comment]
I have changed `validate_change` to pass the field as argument too. Pull requests to improve the documentation are *always* welcome!

**Comment by jordan0day** [comment]
:+1: 

Thanks @josevalim and @drewolson!
