### ISSUE TITLE
Support adding/dropping indexes concurrently

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#391]

**Comment by josevalim** [comment]
* Docs from Postgres: http://www.postgresql.org/docs/9.2/static/sql-createindex.html
* How Rails implements it: http://robots.thoughtbot.com/how-to-create-postgres-indexes-concurrently-in

This pull request consists of four parts:

1. Adding the option to Ecto.Migration.Index
2. Changing the adapter to be aware of this new option
3. Support the `@disable_ddl_transaction true` inside Ecto.Migration that will automatically remove the transaction in Ecto.Migrator
4. Tests (could all be unit ones)

**Comment by whatyouhide** [comment]
I'm having a shot at this and I have one question.

Since `CREATE INDEX CONCURRENTLY` is Postgres-specific, am I doing the right thing by adding a `:concurrently` field to the `Ecto.Migration.Index` struct? Thanks in advance!

**Comment by josevalim** [comment]
Yes! It should default to false and other databases should likely raise!

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by whatyouhide** [comment]
Ok, I'm halfway through the implementation. I'll add the `@disable_ddl_transaction` functionality and then some tests. Thanks!
