### ISSUE TITLE
Ecto.Changeset.cast/4 should fail on atom keys or convert them

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#392]

**Comment by hahuang65** [comment]
I think converting the params in Ecto.Changeset.cast/4 would be very convenient for developers so that they won't have to manually convert maps and pass them in.

I'm wondering what the main worry of not converting them might be?

**Comment by josevalim** [comment]
@hahuang65 I know you were planning to work on this but I have pushed a quick fix since I want to include it on 0.7.0 which is being released right now. :)

**Comment by hahuang65** [comment]
Not a worry! Awesome to see this up!
