### ISSUE TITLE
Composable cast?

### ISSUE THREAD

**Issue by yrashk** [elixir-lang/ecto#401]
I have a use case in a webmachine where I create the changeset progressively, each time picking some parts of the params. `cast/4` can work only with models, but couldn't it be extended to support changesets as well?

**Comment by josevalim** [comment]
:+1:.

**Comment by josevalim** [comment]
There is one issue with this. What happens when params are given twice. Should we merge then? What if we have a map of maps, which is what we are going to have with associations? Should we deep merge or override the previous one? (I am going more with override).

Can't you simply accumulate all the params and call the changeset just at the end?

**Comment by josevalim** [comment]
I guess you need the changeset since the beginning because you need to validate the data. A pull request for this one is welcome.

**Comment by josevalim** [comment]
And, to answer my previous question, the parameters should be simply merged (not deep merged).

**Comment by yrashk** [comment]
Great! Will make sure this happens rather sooner.

**Comment by josevalim** [comment]
Ping?

**Comment by whatyouhide** [comment]
Hey there @josevalim and @yrashk, I'm working on this if that's ok. So far I got a solidish prototype working, but I wanted to be sure I understood the requirements first.

Base case:

```elixir
base_changeset = cast(%{}, %Post{title: "foo"}, ~w(title), ~w())
changeset = cast(my_params, base_changeset, required, optional)
```

The parameters in the second call to `cast/4` are merged with the parameters in the first call (but not deep-merged, as José specified in the comments above) and I'm assuming that `my_params` takes precedence (`Dict.merge(params, new_params)`) and that goes for the changes too.

Errors are just concatenated (and made unique with `Enum.uniq/1`).

As for the `:required` and `:optional` fields of the changeset, let me know what you think of this behaviour:

* required fields are obtained from the required fields of the first and second changesets, concatenated and then made unique;
* optional fields are obtained by concatenating the optional fields of the first and second changeset and then removing all the fields that are in the new required fields.

Perhaps easier to understand with an example:

```elixir
base_changeset = cast(%{body: "body"}, %Post{title: "title"}, ~w(body), ~w(title))
base_changeset.required #=> [:body]
base_changeset.optional #=> [:title]

new_changeset = cast(%{title: "new title"}, base_changeset, ~w(title), ~w())
# Now :title is required in the latest call to cast/4, so it should be
# required and not appear in both the :required and :optional fields right?
# (assuming :required has "more power" over :optional)
new_changeset.required #=> [:body, :title]
new_changeset.optional #=> []
```

Let me know what you think!

**Comment by josevalim** [comment]
Don't call uniq on errors and remember to call Map.merge rather than dict merge when merging params. Everything else sounds great to me!
