### ISSUE TITLE
Case for merging/rendering a changeset back into the model

### ISSUE THREAD

**Issue by yrashk** [elixir-lang/ecto#402]
Consider I have model + changeset. Unless I merge changeset back into the model, there is no trivial way for me to render a JSON for the model... essentially before saving it.

P.S. Or did I miss something and there's already a way to do this?

**Comment by josevalim** [comment]
When you insert/update, you get the updated model. Why would you want to render an invalid version of the model? Its rendering can even fail (because you will have invalid data).

**Comment by yrashk** [comment]
I didn't say it is invalid. My *current* reasons right now: 1) logging/debugging (I can't see the model clearly) before inserting/updating 2) for functions that only accept the original model, not the changeset, I want to pass an updated model, not an old version.

**Comment by josevalim** [comment]
For 2, why can't you do it after you update/insert?

**Comment by yrashk** [comment]
By its nature, changeset is not a destructive, irreversible modification of the model. You can go model -> changeset; therefore it should be possible to go back changeset -> model. It just completes the "type". 

Imagine you use a library that works with a model, and there's a function that only accepts models (cast is being one of the current examples, #401). You have to render the model back yourself. I will end up having this helped written myself. Why not include it into Ecto?

**Comment by josevalim** [comment]
:+1: for this then. Just need to think of a good name. apply/2 would be cool but this module is frequently imported and it would clash with Kernel's apply.

**Comment by hahuang65** [comment]
This was solved by https://github.com/elixir-lang/ecto/pull/403.
