### ISSUE TITLE
Automatically generated UUIDs, like regular ids

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/ecto#408]
I'm very new to Ecto and still trying to figure it out. I have a model that I want to index through unique `uuid`s:

```elixir
defmodule MyModel do
  @primary_key {:id, Ecto.UUID, []}
  schema "mymodel" do
    field :myfield, :string
  end
end
```

The migration that creates that table goes something like:

```elixir
create table(:mymodels, primary_key: false) do
  add :id, :uuid, primary_key: true
  add :myfield, :string
end
```

It all works well if I insert records in the db:

```elixir
iex> Repo.insert(%MyModel{myfield: "foo", id: Ecto.UUID.generate})
%MyModel{id: "3D2F8741-093B-49D5-9860-BEB07902CEAF", myfield: "foo"}
```

My question: is there a way to avoid specifying the UUID on each insertion the way regular ids work? With a regular id, I could just do:

```elixir
iex> Repo.insert(%MyModel{myfield: "bar"})
%MyModel{id: 1, myfield: "bar"}
```

In the example above, the id was automatically taken care of.

Are changesets the solution?

```elixir
defmodule MyModule do
  schema ...
  def changeset(instance, params) do
    params = Dict.put(params, "id", Ecto.UUID.generate)
    # ...
  end
end
```

Thanks in advance and I'm sorry if it turns out I missed something!

**Comment by josevalim** [comment]
Afaik that's how UUIDs work. Or you generate them yourself or you ask the
database to explicit generate one for you by using default values.

I am not sure there is a better way. Maybe Google a bit around.


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by whatyouhide** [comment]
@josevalim Probably generating them by yourself before talking with the database is the cleanest solution: it requires simple code from Ecto's perspective and it leaves users enough freedom.

Postgres, for example, allows automatic generation of UUIDs (in a `serial`-like fashion) but only if an additional module is loaded ([open-ossp](http://www.postgresql.org/docs/9.1/static/uuid-ossp.html) for reference).

I hope that this can be useful to others too. As always, thanks José!

**Comment by ericmj** [comment]
If you want to generate the UUID on the application server you can use a `before_insert` callback. If you need the primary key before inserting there is no way around generating it yourself.
