### ISSUE TITLE
Migrations: modify(column, type, null: false) generates wrong SQL syntax

### ISSUE THREAD

**Issue by yrashk** [elixir-lang/ecto#409]

**Comment by josevalim** [comment]
We don't allow null nor default in modify for now.

**Comment by yrashk** [comment]
Then the documentation needs to reflect that

On Tuesday, January 27, 2015, José Valim <notifications@github.com> wrote:

> Closed #409 <https://github.com/elixir-lang/ecto/issues/409>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/409#event-225300253>.
>


-- 
Y.
My company is hiring: https://trustatom.com/jobs

**Comment by josevalim** [comment]
It has been updated too.
