### ISSUE TITLE
Join query fails when passed to Repo.update_all but works in Repo.all

### ISSUE THREAD

**Issue by gjaldon** [elixir-lang/ecto#410]
The query `assoc(checklist, :checklist_associations) |> join(:inner, [a], i in Item, i.id == a.checklist_item_id)` works when passed to Repo.all but fails when passed to Repo.update_all.

Below is the error returned from Repo.update_all:
```elixir
** (Ecto.QueryError) only `where` expressions are allowed in query:

from a in Association,
  join: i in Item,
  on: i.id == a.item_id,
  where: a.checklist_id in ^...

    (ecto) lib/ecto/query/planner.ex:262: Ecto.Query.Planner.normalize/3
    (ecto) lib/ecto/query/planner.ex:70: Ecto.Query.Planner.query/3
    (ecto) lib/ecto/repo/queryable.ex:112: Ecto.Repo.Queryable.update_all/6
```

**Comment by josevalim** [comment]
@gjaldon ping. do you want someone to take this issue forward? :)

**Comment by gjaldon** [comment]
@josevalim I'll make time later today to finish this off. :)

**Comment by josevalim** [comment]
Awesome!
