### ISSUE TITLE
Changeset.cast uses String.to_atom

### ISSUE THREAD

**Issue by yrashk** [elixir-lang/ecto#414]
Knowledge of this fact will allow attackers to overflow the atom table fairly quickly (the only mitigation is rate limiting and IP blocking, but in absence of restarts, the attacker will eventually succeed).

Is this a reasonable concern for Ecto developers? If yes, then the most reasonable thing to do would be to prepare a list of accepted fields as strings compile-time and `to_atom` part of cast should check whether the key belongs to that list. If this is an agreeable solution, I can spend some time preparing a PR.

**Comment by josevalim** [comment]
We only call String.to_atom on the fields that you pass as required and optional fields. That's exactly why we ask the list of fields. Furthermore, those fields *must* exist in the model before we cast. We could make this clearer in the doc but I think the protection mechanism is already in there.

**Comment by yrashk** [comment]
You are right. My fault, was a quick glance

On Wednesday, January 28, 2015, José Valim <notifications@github.com> wrote:

> We only call String.to_atom on the fields that you pass as required and
> optional fields. That's exactly why we ask the list of fields. Furthermore,
> those fields *must* exist in the model before we cast. We could make this
> clearer in the doc but I think the protection mechanism is already in there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/414#issuecomment-71793591>.
>


-- 
Y.
My company is hiring: https://trustatom.com/jobs
