### ISSUE TITLE
Document supported RDBMSs

### ISSUE THREAD

**Issue by brandondrew** [elixir-lang/ecto#416]
It appears that Postgres is the only supported database.   In many ways this makes sense for a language and ORM that is cutting edge&mdash;I don't know why anyone would *choose* any other RDBMS for a new project if they had a choice.  

But unfortunately many clients are tied to their legacy databases, and not necessarily up for setting up Postgres with foreign data wrappers to pull data from Oracle or SQL Server or whatever.

For this reason it would be very useful to have explicit documentation of which databases are supported currently, and which are planned or under consideration.  If Postgres is all that will ever be supported, that would be good to know.   If others *are* already supported, that would be very good to know.

**Comment by jhosteny** [comment]
@josevalim has been doing a lot of refactoring work so that other databases can be supported. There is a pull request (#383) for a MySQL adapter. I can't comment on what other RDBMS are being considered, however.

**Comment by josevalim** [comment]
Pushed docs to master!
