### ISSUE TITLE
has_many and no primary key

### ISSUE THREAD

**Issue by handnot2** [elixir-lang/ecto#420]
Ecto 0.7.2
Here is the association: A has_many B
B does not have any primary key (@primary_key false)
When doing a query on A with preload to get the associated records from B, the query fails with NoPrimaryKeyError.

**Comment by handnot2** [comment]
Just wanted to add that, B has appropriate "belongs_to" association defined with A's primary key (which happens to be :uuid) as FK.

**Comment by josevalim** [comment]
Many associations features require a primary key because we use it to
detect conflicts, do joins and so on. So you need to add a primary key.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by josevalim** [comment]
If the uuid is unique, you can set it as primary key, but we do need one.
