### ISSUE TITLE
change doesn't work when it creates a table and an index

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#423]

**Comment by alanpeabody** [comment]
Is this adding and index option to the table DSL?

```elixir
 create table(:posts) do
      add :title, :string
      add :body,  :string
      add :slug,  :string, index: true
      timestamps
    end
```

**Comment by josevalim** [comment]
That doesn't solve it really because people can have complex indexes that are not column based. I think the best solution is to indeed provide two new functions: `drop_if_exists` and `create_if_not_exists`. This way, when reversing the create and drop operations, we can reverse to the if exists variants. Thoughts?

**Comment by alanpeabody** [comment]
True. I will take a stab at that when I get a chance. I suppose a similar option would be a flag/option similar to the concurrently flag WIP. I may be overlooking what the advantage of a new method is.

```elixir
create index(:posts, [:slug], force_drop: false, force_create: true)
```

**Comment by josevalim** [comment]
The new function is similar to how databases actually work. Also, force != if_exists. One deletes the previous one and create a new one, the other does not perform any operation if it exists. Does it make sense?

**Comment by alanpeabody** [comment]
Okay, sounds good. I will take a shot at this.

**Comment by josevalim** [comment]
Sorry, I got completely side-tracked in this discussion. I thought we were discussing that `change` doesn't work on rollback when you add an index after you create the table because the table is dropped.

This particular issue is about supporting GIS and GIST indexes in Postgres. :S

**Comment by josevalim** [comment]
I have renamed the issue. @alanpeabody we can also look at what rails does to solve this.

**Comment by alanpeabody** [comment]
Sorry I hijacked the issue. :-D

So I have dug into the rails code, and it is pretty clever. Rails hijacks the connection, sends all the commands to it, stores each one, and then lets you play them back in reverse order (at which point you need to reverse them).

See: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration.rb#L490-L498 & https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration/command_recorder.rb

I actually think we can accomplish something similar using an agent in the runner to record all commands then actually execute at the end. (Similar to how the subcommands work now, but for whole commands).

I will throw something together for feedback in the next day or two.

**Comment by josevalim** [comment]
I honestly think we should not do the same thing as Rails... for example, what to do in this case:

    # do_something
    if exists? index(...) do
  
    end

We do need to return something for this `if`expression... in this case, what? So I do believe using softer variants like if_exists is the way to go. :)

**Comment by alanpeabody** [comment]
That is a good point. I will take a stab at adding create_if_not_exists and drop_if_exists in the next day or two.

Thanks for your patience with this, I am excited to help and I have enjoyed studying the ecto codebase more in depth.
