### ISSUE TITLE
Changes to schema_migrations schema causes migrations to fail in existing applications

### ISSUE THREAD

**Issue by drewolson** [elixir-lang/ecto#426]
The commit 40ddec217ea0ede4df848552518b1f0f50b7239f introduces timestamps to the `schema_migrations` table. If an ecto application was already in production (or any environment where the database is not frequently dropped / recreated), the `schema_migrations` table would have already been generated without the `inserted_at` column and further migrations would fail to run because of a non-existent `inserted_at` column at the time of row creation (at the end of the migration run).

Considering that the library is pre-1.0, the solution here might just be to manually update the table in your application (that's what I did). In the future, it might be good to consider a solution for seamlessly upgrading old versions of the `schema_migrations` table.

**Comment by josevalim** [comment]
Yup, I later added a note to the CHANGELOG but we should definitely avoid
it in the long term.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer
