### ISSUE TITLE
Allow only atoms in lock

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#449]

**Comment by josevalim** [comment]
@ericmj passing strings can lead to SQL injection. So we are going with atoms that must be made public by the adapter.

**Comment by ericmj** [comment]
@josevalim We should allow only literal strings like with fragments. That should be safe?

**Comment by MSch** [comment]
I think the right way to do this is to use literal strings, Postgres' locking syntax is not that easy:

> [ FOR { UPDATE | NO KEY UPDATE | SHARE | KEY SHARE } [ OF table_name [, ...] ] [ NOWAIT | SKIP LOCKED ] [...] ]

There can be multiple lock clauses each applying to one or more tables and they acquire different locks and deal with locked rows differently (thought that is [new in 9.5](http://www.depesz.com/2014/10/10/waiting-for-9-5-implement-skip-locked-for-row-level-locks/)))

**Comment by josevalim** [comment]
We are forcing literal strings everywhere now.
