### ISSUE TITLE
Allow setting reset queries to be executed before checking in a connection

### ISSUE THREAD

**Issue by MSch** [elixir-lang/ecto#454]
Someone can muck up a checked out connection by forgetting to clean up various things (`SET SESSION`, session-level advisory locks or just keeping a transaction open (using the `Ecto.Adapters.SQL.query`)

pgBouncer recommends setting a custom reset query that is run when checking in the connection.

```sql
ROLLBACK;
DISCARD ALL;
```

http://www.postgresql.org/docs/9.4/static/sql-discard.html

http://jakub.fedyczak.net/post/pgbouncer-and-server-reset-query/

Consider allowing to set reset queries when beginning a (top level) transaction that is run before the connection will be returned to the pool. (I'm guessing running a second query for every query outside a tx is too much overhead and I can't think of a case where anything that requires a `DISCARD ALL` cleanup would be necessary without keeping the same connection around for a while)

I think the worker monitors (links?) to the process using it, if that process gets killed during e.g. a transaction, will it be rollbacked or does the worker also die? In that case a default rollback & discard all certainly shouldn't hurt IMO.

```elixir
MyRepo.transaction reset_queries: ["DISCARD ALL"], fn ->
  Ecto.Adapters.SQL.query("SET myapp.current_user = $1", ["msch"])
  Ecto.Adapters.SQL.query("SELECT pg_advisory_lock(1))
end
```

**Comment by ericmj** [comment]
What happens today if a caller receives an EXIT signal inside the transaction? Am I correct that after clauses doesn't run when receiving an EXIT signal? If so, we may check in connections to the pool that are running a transaction, the same would happen for DISCARD ALL.

/cc @josevalim @fishcakez

**Comment by josevalim** [comment]
If the caller dies inside a transaction, the worker will notice and assume the connection is stale, discarding it completely.

**Comment by josevalim** [comment]
The first step in the transaction is to link the transaction owner with the worker:

https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/sql/worker.ex#L84

If the owner dies, we wipe the state:

https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/sql/worker.ex#L218

**Comment by fishcakez** [comment]
Just to quick note, exit signals are sent before monitor messages (UNDOCUMENTED!) so the worker will get the exit signal of the client before poolboy gets the monitor `:DOWN` message. This means the worker will close the connection process before it handles any calls from the next client.

**Comment by fishcakez** [comment]
> Am I correct that after clauses doesn't run when receiving an EXIT signal?
Sorry I missed this, you are correct.

**Comment by josevalim** [comment]
@MSch do you still need this? Or is this a nice to have? Are you using a workaround currently?

**Comment by MSch** [comment]
@josevalim Since Ecto's worker closes the connection to Postgres if the transaction owner dies I don't need this.

Thank you all for clearing this up for me!
