### ISSUE TITLE
The log() callback is shown to take a 2-tuple in the docs

### ISSUE THREAD

**Issue by alco** [elixir-lang/ecto#457]
Here: https://github.com/elixir-lang/ecto/blob/v0.8.0/lib/ecto/repo.ex#L493

However, with Ecto 0.8.0, I'm getting a 3-tuple `{:query, sql, parameter_list}`. Also, is there a list of all possible values for the first element in the tuple?

**Comment by josevalim** [comment]
We use only :query as atom but adapters may provide other ones.



*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer
