### ISSUE TITLE
Add returning option to Repo.update_all and Repo.delete_all

### ISSUE THREAD

**Issue by MSch** [elixir-lang/ecto#460]
c.f. #332

Any objections @ericmj @josevalim?

**Comment by josevalim** [comment]
I don't think all DBs support it... so I am unsure. Can we check MySQL and MSSQL?

**Comment by josevalim** [comment]
Actually, we can support it regardless of the DB. We would just need to raise in those cases. Although I would still like to wait on it a bit.

**Comment by josevalim** [comment]
@MSch do you have any thoughts on the syntax?

**Comment by MSch** [comment]
I'm opposed to waiting for obvious reasons :) Currently `Ecto.Adapters.SQL` and `Ecto.Adapters.SQL.Connection` already require support for `RETURNING` for `insert` and `update` from the underlying DB/Adapter. MSSQL supports it and the adapter already uses it. MySQL on the other hand doesn't and it seems there's no alternative, so that adapter will have to do something else altogether anyhow.

Syntax wise I think the easiest thing would be:

```elixir
Repo.update_all(from u in User, where: u.id == ^id, [email: ^email, updated_at: fragment("now()")],
  returning: [:updated_at, fragment("foo + ?", ^bar))
```

With returning being run through a limited version of `Ecto.Query.Builder` that only allows column names (atoms) and `fragment`s.

**Comment by josevalim** [comment]
@MSch :) Regarding syntax: I also thought about simply allowing select to be given, what do you think?

 This will also change the return type of update_all. Should it be a tuple? `{count, [row]}`?

We can agree on the specs and you can add them as part of a fork for now but I would like to wait because we are working on the MySQL adapter and I can't juggle that many balls at the same time, sorry!

**Comment by josevalim** [comment]
@MSch ping. :)

**Comment by MSch** [comment]
Sorry, I didn't want to distract you away from the MySQL merge. :)

IMO When using `update_all` with `RETURNING` I never care about the row count, I care about the actual rows, but having `update_all` return either `count` or `[row]` depending on the query supplied is highly confusing. So I guess, like you said, it should return `{count, nil}` if no `RETURNING` is specified and `{count, [row]}` if `RETURNING` is specified.

I'm not sure about using `select` to specify `RETURNING`, I'm thinking ideally I could build an `UPDATE` query just like I build a `SELECT` today and depending on whether I use `select: ...` or `update: ...` it becomes an `SELECT` or `UPDATE` query:

```elixir
from u in User,
  update: u.email = ^email and u.updated_at = fragment("DEFAULT"),
  where: u.id == ^id,
  returning: [u.updated_at, fragment("foo + ?", ^bar)]
```

But that is probably a different decision.

**Comment by josevalim** [comment]
I think this is a great idea work exploring. Today we run into an annoying issue where you can't call update_all dynamically because it is a macro. This would solve this problem neatly. However, I am still a bit skeptical about using returning instead of select as it forces adding a another field to the query struct, more functions and so on. I will put more thoughts into it, this is a very productive discussion.

**Comment by josevalim** [comment]
Maybe returning makes sense if we consider that the default would be to return something like `returning: :count`. Something else we need to discuss is if users should call Repo.update_all even if they have update already in the query (I would rather say yes).

**Comment by josevalim** [comment]
So I believe we are finally ready to support this. A couple updates:

* We have added insert_all to Ecto which supports returning but does not support Ecto.Query
* We have added dynamic fields to select. `from Post, select: [:id, :title]` will return a Post with only id and title fields

That said, I am planning to support returning as a separate option given to insert_all, update_all and delete_all that is simply a list of fields:

    Repo.insert_all Post, [%{title: ...}], returning: [:id, :inserted_at]
    #=> [%Post{id: ..., inserted_at: ...}]

If you want all fields, I am thinking we could support either:

    returning: :all

or:

    returning: :*

What if we choose for returning should be mirror in `:select`. The only downside of this solution is that custom expressions won't be supported, only fields. But i believe this is enough for now.

/cc @MSch @michalmuskala :)

**Comment by michalmuskala** [comment]
With MongoDB there's no support for anything like `returning`.

For all fields I think `returning: :all` is much better than `:*`. I agree that we should keep this API and `:select` in sync.

`Repo.insert_all/3` is a regular function so there should be no problem with dynamically passing the list of required fields to `:returning` if that's needed. We should keep it simple for now.

**Comment by josevalim** [comment]
In master.

**Comment by atomkirk** [comment]
@josevalim this doesn't seem to work (nor is documented) for `delete_all`. Was that intentional?

**Comment by josevalim** [comment]
From the CHANGELOG:

>    * [Ecto.Repo] The `:returning` option for `update_all` and `delete_all` has been deprecated as those statements now support `select` clauses

i.e. use select in your queries instead.

**Comment by floodico** [comment]
> From the CHANGELOG:
> 
> > * [Ecto.Repo] The `:returning` option for `update_all` and `delete_all` has been deprecated as those statements now support `select` clauses
> 
> i.e. use select in your queries instead.

`":select is not supported in update_all by MySQL"`
https://github.com/elixir-ecto/ecto_sql/blob/8727a7400b8e5b0996334c99e7d1663dd0b88243/lib/ecto/adapters/myxql/connection.ex#L111

**Comment by josevalim** [comment]
Yeah. MySQL didn’t support returning either.
