### ISSUE TITLE
UUID as primary key

### ISSUE THREAD

**Issue by pynixwang** [elixir-lang/ecto#463]
```elixir
defmodule Res.Category do
  use Ecto.Model

  @primary_key {:id, :uuid, [default: Ecto.UUID.generate |> Ecto.UUID.dump |> elem(1) |> Map.get :value ]}

  schema "category" do
    field :title, :string
    timestamps
  end
end
```

I just want to set the default value of uuid field,but I get this long expression.

I know I can use insert_before. but the expression is the same.

and uuid representaion is so bad in iex.
```
%Res.Category{__state__: :loaded,
 id: <<91, 56, 40, 235, 9, 82, 67, 27, 129, 26, 224, 73, 136, 143, 131, 217>>,
 inserted_at: %Ecto.DateTime{day: 14, hour: 19, min: 34, month: 2, sec: 42,
  year: 2015}, title: "AAA",
 updated_at: %Ecto.DateTime{day: 14, hour: 19, min: 34, month: 2, sec: 42,
  year: 2015}}
```

something broken?

**Comment by josevalim** [comment]
The default value is computed at compilation time, so yes, it will always be the same. Use before_insert instead.

**Comment by pynixwang** [comment]
@josevalim thanks. this is a big "keng".

**Comment by stevegraham** [comment]
Is there a reason for Ecto to generate the UUID when Postgres can do it? e.g. `default uuid_generate_v4()`

**Comment by pynixwang** [comment]
migrate to mysql?

**Comment by josevalim** [comment]
@stevegraham you can do it. Pass a default in your migration and remember to set `read_after_writes: true` in your UUID.

**Comment by pynixwang** [comment]
@josevalim  `read_after_writes` will cause a select operation?

**Comment by josevalim** [comment]
@pynixwang no, it uses the returning option on insert/update. Maybe `return_on_writes` or `read_on_writes` would be a better name?

**Comment by josevalim** [comment]
I have opened an issue for naming discussion on #530.

**Comment by pynixwang** [comment]
@josevalim  it 's a pgsql feature. mysql can 'nt do this.

**Comment by josevalim** [comment]
Right. MySQL also does not have functions for generating UUIDs (afaik).
