### ISSUE TITLE
`like/2` in query not working in certain scenarios

### ISSUE THREAD

**Issue by gjaldon** [elixir-lang/ecto#464]
I have a query that works in this form:
```elixir
from(u in User, join: ee in assoc(u, :entity_engagements), where: like(u.email, ^email) and ee.type == "admin"l) |> Repo.all
```

but below returns the error `** (CompileError) iex:34: cannot use ^email outside of match clauses`:
```elixir
from(u in User, join: ee in assoc(u, :entity_engagements), where: ee.type == "admin") and like(u.email, ^email) |> Repo.all
```

Switching the order of where `like/2` is called in the query expression makes it work or fail.

**Comment by ericmj** [comment]
You close the macro with `)` after `"admin"` which stops the ecto query expression. The error you get is because the elixir compiler is trying to process it as a normal elixir code.
