### ISSUE TITLE
Postgrex.Timestamp <==> :datetime

### ISSUE THREAD

**Issue by troyk** [elixir-lang/ecto#472]
I needed to mess around with postgrex:master to bring in some functionality I needed and noticed master is now returning timestamps as the Postgrex.Timestamp.

I patched ecto DateTime with `def load({day, hour, min, month, msec, sec, year})` and am up and running again, and I know dropping an issue from the master branch of a driver might be jumping the gun, but I have a tight deadline and need to be productive in Elixir so any guidance on the best way to move forward would be awesome.

I can submit a pull request if I'm headed down the right path...  btw, initially i just tried to use Postgrex.Timestamp as the data type in the models schema, but I could not get past a `module Postgrex is not loaded and could not be found` error, even though I have `require Postgrex` at the top of the model file

**Comment by ericmj** [comment]
Feel free to submit a PR after postgrex v0.8.0 is released. Ecto uses the stable version, so until then we are going to use v0.7.0 :).

> I can submit a pull request if I'm headed down the right path... btw, initially i just tried to use Postgrex.Timestamp as the data type in the models schema, but I could not get past a module Postgrex is not loaded and could not be found error, even though I have require Postgrex at the top of the model file

`require` is not needed. You probably misspelled something, somewhere.

**Comment by troyk** [comment]
I think I have the spelling right, maybe it just cant be used as Ecto field type without wrapping it?

```
== Compilation error on file web/models/contact.ex ==
** (ArgumentError) invalid or unknown field type `Postgrex.Timestamp`
    lib/ecto/schema.ex:681: Ecto.Schema.check_type!/2
    lib/ecto/schema.ex:527: Ecto.Schema.__field__/4
```

**Comment by ericmj** [comment]
@troyk That's another error then the one you posted initially :). A type needs to implement the `Ecto.Type` behaviour, that's why ecto says it's invalid. See `Ecto.DateTime` for an example.

**Comment by josevalim** [comment]
Opening this because we need to figure this out.

**Comment by josevalim** [comment]
Ok, Postgrex 0.8 support has landed on master.
