### ISSUE TITLE
Allow {source, model} to be given as queryable

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#478]
The idea is to allow a model to be used with different sources. We are going to support such configuration in associations too, either in the format:

    has_many :emails, {"users_emails", Email}

Or

    has_many :emails, Email, source: "users_emails"

**Comment by tony612** [comment]
Hi, @josevalim , I'm trying to implement this. But I think `source`  should be used with `through`.

**Comment by josevalim** [comment]
Source is not the same as a source in Rails associations. It to is



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by josevalim** [comment]
Oops, premature send. It is the name of the table where we can find the
model.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by tony612** [comment]
@josevalim Yeah, found that just now :smile: I'll try to implement this :)

**Comment by tony612** [comment]
@josevalim Glad to see the PR was merged. :) So I think it's time for the association.

**Comment by josevalim** [comment]
Yes, I will document in the association PR soon. :)

**Comment by josevalim** [comment]
Ok, now that we support `{source, model}` in queries, we can support it in associations. From the two syntaxes mentioned above, I think the first makes more sense:

    has_many :emails, {"users_emails", Email}

Then we just need to be sure associations accept that as input. Another change is that we will likely need to introduce a queryable field to associations. Because we still need `refl.assoc` for things like build, while everything else should likely use the new `refl.queryable`.

@tony612 thoughts?

**Comment by tony612** [comment]
@josevalim Yeah, the first format is very suitable. And `refl.queryable` is a good idea :+1:

**Comment by josevalim** [comment]
Reopening as we still need to tackle build.
