### ISSUE TITLE
Primary Key Options list should merge with defaults

### ISSUE THREAD

**Issue by mobileoverlord** [elixir-lang/ecto#482]
I have a model where I am defining the primary key as :uuid by declaring at the top of the model
```@primary_key {:id, :uuid, []}```

When I do this I loose the default of ```read_after_writes: true``` unless I explicitly pass it. The options here should be merged.

**Comment by josevalim** [comment]
@mobileoverlord it is on purpose (it is a change in master, written to the changelog). In theory, uuid should not require read_after_writes though, unless you are generating them in the database side?
