### ISSUE TITLE
Update Ecto.DateTime and Ecto.Time to have usec

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#491]
Today we already receive `usec` information from the database, we just need to change parsing and update our structs. Let's do this after 0.9 is out though to avoid too many changes in the same release.

**Comment by josevalim** [comment]
This is now ready for tackling! /cc @briksoftware @whatyouhide

**Comment by whatyouhide** [comment]
I'd like to have a shot at this tomorrow if that's okay :).

**Comment by lau** [comment]
u != μ

Can we call microseconds something other than usec? 

μ is the lower case version of a greek M. Pronounced a bit like "me" in English or "mi" en Spanish.
see https://en.wikipedia.org/wiki/Mu_%28letter%29

My suggestion: microsec

I know that some people have used usec before in other languages. But this is a new project and we have a chance to correct it.

**Comment by ericmj** [comment]
And microsec != micro_seconds :). Using u instead of μ is just fine imo. If you understand μsec you should also understand usec given the context.

**Comment by josevalim** [comment]
The unified code for units actually specifies `u` can be used in case sensitive scenarios where only the ascii codepoints is available: http://unitsofmeasure.org/ucum.html (section 4.1, no direct link, sorry).

More about the code: http://en.wikipedia.org/wiki/Unified_Code_for_Units_of_Measure

**Comment by lau** [comment]
OK, I won't argue with the unified code for units of measure. I will also change the struct in Kalends from microsec to usec for consistency.
