### ISSUE TITLE
Ecto.Model.primary_key should return a list

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#505]
Or potentially a keyword list / map with field name: value.

**Comment by josevalim** [comment]
@tony612 I think we should go ahead and make `__schema__(:primary_key)` return a list too. Can you please take care of this change too? :)

**Comment by tony612** [comment]
@josevalim Of course :D

**Comment by josevalim** [comment]
@hamiltop those changes makes it much closer for us to support composite primary keys. In case you want to give another try on your patch, please let us know.

**Comment by tony612** [comment]
@josevalim It seems that `__schema__(:primary_key)` can't be expected to return a [key, value] list because it's a function on the Module instead of on a struct :(

**Comment by josevalim** [comment]
@tony612 right! it should return a list of the fields only! (instead of field | nil). :)

**Comment by tony612** [comment]
@josevalim ok, I'll check it later :)

**Comment by tony612** [comment]
@josevalim Done.
