### ISSUE TITLE
Convert validation error messages from atom to strings

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#512]
And allow them to be configured via a :message option. We just need to discuss the syntax to interpolate terms. Is it going to be `$count`, `%count` or `%{count}`?

/cc @chrismccord @ericmj @whatyouhide

**Comment by whatyouhide** [comment]
I like `$count` or `%count`. `%{count}` seems superfluous in my opinion. Is it always gonna be just `count` right?

**Comment by josevalim** [comment]
It is only going to be count but the format we choose is the one we are going to use in our I18n library. :)

**Comment by whatyouhide** [comment]
On second thought, maybe `%{count}` is the easiest to "spot" in a string. Let's wait for other feedbacks too :)

**Comment by tony612** [comment]
Agree with @whatyouhide . And I prefer `%count` because `$count` will remind me of variables in other language, e.g. global variable in Ruby :D

**Comment by josevalim** [comment]
Let's go with %{count} because they are easier to spot and replace.

**Comment by josevalim** [comment]
I am on this. :)
