### ISSUE TITLE
Provide options to run ecto migrations on production

### ISSUE THREAD

**Issue by shankardevy** [elixir-lang/ecto#521]
Currently, when a release is made, there is no way to call the ecto migrations on the server. Ecto could provide an option for this.

Related discussion happening on exrm: https://github.com/bitwalker/exrm/issues/67#issuecomment-80977035

**Comment by ericmj** [comment]
This is actually already possible with `Ecto.Migrator`.

**Comment by phillipp** [comment]
I can't find anything about it in the docs, where is the usage documented?

**Comment by ericmj** [comment]
This is the module to use to run migrations manually https://hexdocs.pm/ecto/Ecto.Migrator.html.
