### ISSUE TITLE
PostgresSQL CHECK and CONSTRAINT

### ISSUE THREAD

**Issue by hunterboerner** [elixir-lang/ecto#524]
Is there a way I can use the PostgreSQL CHECK and CONSTRAINT feature on my fields? http://www.postgresql.org/docs/8.1/static/ddl-constraints.html

It also has stuff like NOT NULL, NULL, and UNIQUE (which can be done through indexes)

Thanks

**Comment by josevalim** [comment]
In your migrations, just call `execute/1` to run any statement. Also, please the elixir-ecto mailing list for questions. :)
