### ISSUE TITLE
Rename read_after_writes to read_on_writes

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#530]
That's because we are not doing a read after writing, we are reading/returning on the same command that we write. Another alternative is `return_on_writes`. Thoughts?

**Comment by tony612** [comment]
Yeah, it's more reasonable.

**Comment by ericmj** [comment]
We are still reading _after_ the write since the purpose of the command is to get defaults and read after triggers run.

**Comment by josevalim** [comment]
Should we call it then return_on_writes? To be clearer it is using returning and not doing another operation?

**Comment by josevalim** [comment]
We decided to keep the same name and work on the docs instead, thanks for the feedback everyone!
