### ISSUE TITLE
Uniqueness scope

### ISSUE THREAD

**Issue by hunterboerner** [elixir-lang/ecto#534]
To check for uniqueness with a scope something like this: `where: field(m, ^scope) == ^scope_value` needs to be added to this query https://github.com/elixir-lang/ecto/blob/d8034fd15da4202d8c9925420ef24cd174120274/lib/ecto/changeset.ex#L745

Those two vars can be obtained with: 

```
scope = opts[:scope]
scope_value = Map.get(params, Atom.to_string(scope)) || Map.get(model, scope)
```

**Comment by josevalim** [comment]
Please send a pull request with tests. Or alternatively wait until some adds this for you. :)

**Comment by hahuang65** [comment]
I was actually planning to do a PR on this. I started looking at the code and was thinking maybe a more general approach would be better than just a scope.

A scope is just an additional criteria added to the query, it's not a true scope right?
For example:
`select: field(m, ^field), where: field(m, ^scope) == ^scope_value`

Would be the same as `where: field(m, ^scope) == ^scope_value && field(m, ^field) == ^field_value` is it not?

A more general approach might be to allow uniqueness to be a query in itself so you can have scopes of scopes, or multiple conditions of uniqueness.

I haven't started a PR at all yet so feel free to do so, but I'd also love to hear feedback on this thought. Perhaps it's not a good thought at all?

**Comment by josevalim** [comment]
@hahuang65 that's a nice idea. We can support a `:query` parameter and you just pass the parameter in whatever you want. By default, the query will default to the model name.

**Comment by hahuang65** [comment]
@hunterboerner want to give this a shot? Let me know since you originally wanted to work on it. If not, I'll start something on this.

**Comment by hunterboerner** [comment]
@hahuang65 err... I think I should start with something more basic. You should probably take this.

**Comment by hahuang65** [comment]
@josevalim So you'd like something that looks like:

`validate_unique(changeset, query: some_queryable, on: Repo)`
where some_queryable defaults to the model name.

And if that query returns any results at all, it'll fail the check.

**Comment by hahuang65** [comment]
I'm not sure how much I like that. It makes `query` seem more like an option than the actual uniqueness check.

Just kind of feels weird.

**Comment by josevalim** [comment]
@hahuang65  the query is the scope (we could call it that). For example, you could do this:

    validate_unique(changeset, :email, query: where([u], not is_nil(u.deleted)))

**Comment by hahuang65** [comment]
That's a good example. I think using the word `scope` would be more descriptive here.

I'll see if I can come up with a working prototype.

**Comment by hahuang65** [comment]
We've discussed having a `validate_unique(changeset, scope: some_scope, on: Repo)` where `some_scope` is an `Ecto.Queryable`.

It would look something like this:
```
some_scope = Post |> where([p], p.author_id != 1)
changeset(%{"title" => "hello"})
|> validate_unique(:title, scope: some_scope, on: Repo)
```

However, I've run into some issue with this. The current function definition for `validate_unique/2` looks like:
```
def validate_unique(%{model: model} = changeset, field, opts) when is_list(opts) do
  repo = Keyword.fetch!(opts, :on)
  validate_change changeset, field, :unique, fn _, value ->
    struct = model.__struct__
    query  = from m in struct, select: field(m, ^field), limit: 1
    # ...
```
At first, I was hoping I'd be able to add:
```
    query =
      if opts[:scope] do
        # Some way to merge queries
        query |> opts[:scope]
      end
    end
```
But it won't work of course. As @ericmj points out, we cannot merge two queries at this point.

A workaround would be:
```
def validate_unique(%{model: model} = changeset, field, opts) when is_list(opts) do
  repo = Keyword.fetch!(opts, :on)
  validate_change changeset, field, :unique, fn _, value ->
    struct = model.__struct__
    query  =
      if opts[:scope] do
        from m in opts[:scope], select: field(m, ^field), limit: 1
      else 
        from m in struct, select: field(m, ^field), limit: 1
      end
      # ...
```
But this would be trouble as we'd need to check/guarantee that the source for the query is the same for `opts[:scope]` and `struct`. This would be very awkward and unwiedly, and @ericmj agrees.

So my proposal now is to make the scope option a list of atoms that refer to field names on the struct, such that calling the `validate_unique` would look like:
```
changeset(%{"title" => "hello"})
|> validate_unique(:title, scope: [:author_id], on: Repo)
```
And in the source, we can reduce the list into a bunch of composable queries based on the models fields and values.

What do you guys think?

**Comment by hahuang65** [comment]
I've got a tested working prototype here:
https://github.com/hahuang65/ecto/commit/d5a8d7c8266f3c22cef9aa8791ba468f6a2ef6f9

**Comment by josevalim** [comment]
I think the previous approach is fine. We should do:

     opts[:scope] || model.__struct__

I don't think we need to worry about having different sources because queries are usually built starting from the source (i.e. it is very hard to start a query without a source).

**Comment by josevalim** [comment]
We could also support both:

1. If scope is nil, use model.__struct__
2. If scope is a list, generate the where based on the model automatically
3. If scope is a anything else, use it as a queryable

For now though, I think it is fine for us to start with scope as a list. :) So good job!

**Comment by ericmj** [comment]
Can you provide scopes that can be written with queries but not with a list of fields? If not, I don't think we need the extra complexity.
