### ISSUE TITLE
[mysql] multiple failing tests with MySQL 5.1.73

### ISSUE THREAD

**Issue by liveforeverx** [elixir-lang/ecto#536]
Results:

```
MIX_ENV=mysql mix test
89 tests, 39 failures, 4 skipped
```

The same tests are passed with different newer versions ( 5.5, 5.6 ), with MariaDB (10.X).

Example, what not passed:
```
 37) test Repo.insert escape (Ecto.Integration.SQLEscapeTest)
     integration_test/cases/sql_escape.exs:15
     Assertion with == failed
     code: ["'"] == TestRepo.all(query)
     lhs:  ["'"]
     rhs:  ["1", "2", nil, "1", nil, nil, "2", "1", "2", "1", "3", nil, nil, "3", nil, "1", "2", "foo", nil, "foo", "1", "2", "x", "x", "x", "x", "x", "2", "3", nil, nil, "1", "1", "1", "1", "2", nil,
            nil, "1", "2", "1", "2", "3", nil, nil, "1", "2", "1", "2", "3", ...]
     stacktrace:
       integration_test/cases/sql_escape.exs:19
```

Seems, that nested transactions haven't rollbacked the subtransactions back:
```
  1) test transaction commits (Ecto.Integration.TransactionTest)
     integration_test/cases/transaction.exs:46
     match (=) failed
     code: [] = TestRepo.all(Trans)
     rhs:  [%Ecto.Integration.TransactionTest.Trans{__meta__: %Ecto.Schema.Metadata{source: "transactions", state: :loaded}, id: 1, text: "1"}]
     stacktrace:
       integration_test/cases/transaction.exs:50: anonymous fn/0 in Ecto.Integration.TransactionTest.test transaction commits/1
       (ecto) lib/ecto/adapters/sql.ex:443: Ecto.Adapters.SQL.transaction/3
       integration_test/cases/transaction.exs:47
```

There are 2 questions:
1) Should ecto supports MySQL 5.1.73
2) If it should, what are reasons for failing tests.

May be, that answer to question 2 should give answer to question 1. May be, there is minimal configuration needed for MySQL 5.1.73 to work with. @laurocaetano may be do you have an idea, can take a look?

Related [Mailing List question](https://groups.google.com/forum/#!topic/elixir-ecto/3HwLjhqLs9E)

The mariaex tests are passed with 5.1.73 (related mariaex issues [1](https://github.com/xerions/mariaex/issues/39), [2](https://github.com/xerions/mariaex/issues/40), [3](https://github.com/xerions/mariaex/issues/41)).

**Comment by laurocaetano** [comment]
Thanks for opening the issue :)

I think it's worth supporting 5.1 if it requires just small changes. I'll take a look on this issue tomorrow.

**Comment by liveforeverx** [comment]
I've started to looking into. And I have a first observation.
The insert from PoolRepo is seen from TestRepo too (and crashes of course)

```elixir
    PoolRepo.transaction(fn ->
      e = PoolRepo.insert(%Trans{text: "1"})
      assert [^e] = PoolRepo.all(Trans)
      assert [] = TestRepo.all(Trans) # gets [e]
    end)
```

TestRepo.all see the inserted e.

**Comment by liveforeverx** [comment]
first example:

```elixir
iex(1)> {:ok, p} = Mariaex.Connection.start_link(username: "root", database: "test")
iex(2)> Mariaex.Connection.query(p, "BEGIN", [])
iex(3)> Mariaex.Connection.query(p, "INSERT INTO test VALUES(4, 't')", [])
```

And from mysql I see, before entering commit:
```
MySQL [test]> select * from test where id = 4;
+----+------+
| id | test |
+----+------+
|  4 | t    |
+----+------+
1 row in set (0.01 sec)
```

That is the first problem.

**Comment by liveforeverx** [comment]
This can be closed now, I think. With InnoDB storage all tests are passing, and with MyISAM not.

**Comment by josevalim** [comment]
I think this is still a bug. We should default the engine to InnoDB then when creating the database.

**Comment by josevalim** [comment]
I have created #538.
