### ISSUE TITLE
Dates before 2000-01-01 not handled correctly

### ISSUE THREAD

**Issue by john-vinters** [elixir-lang/ecto#539]
Ecto appears to not decode dates correctly that are before 2000-01-01.

For example, modifying the date={...} line in the test "test update all with casting and dumping" in ecto/integration_test/cases/repo.ex causes a test failure with any date component before 2000-01-01.

From tests with the code that originally showed the problem the date appears to be correctly written to the database but not decoded correctly when read-back.

Running the code in `Ecto.Adapters.Postgres.DateTime.encode`, 1999-12-31 encodes as `<<255, 255, 255, 255>>`.  Using this as an input to `Ecto.Adapters.Postgres.DateTime.decode` results in the date `{11761221, 1, 19}`, which corresponds with what I get in my own code when I use this date.

I've tried this with Erlang 17.4.1, Elixir 1.0.3, Ecto 0.10.0, Postgrex 0.8.0 and PostgreSQL 9.4.1 on Mac OS X 10.10.2.

**Comment by josevalim** [comment]
Thank you for the report. If you can send a pull request, it would be appreciated, otherwise I will take a look at it later. This problem likely exists in Postgrex too /cc @ericmj
