### ISSUE TITLE
Migration task error in production after upgrading to 0.10.0

### ISSUE THREAD

**Issue by drewolson** [elixir-lang/ecto#541]
Running the `mix ecto.migrate` task is returning an error in my production environment after upgrading to ecto 0.10.0. I'm seeing the following:

```bash
(Mix) The database for repo MyApp.Repo couldn't be created, reason given: ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)
HINT:  Use the same encoding as in the template database, or use template0 as template.
```

My database already exists, I'm not sure why it's attempting to run the create.

Edit: Also, maybe `ecto.migrate` shouldn't attempt to `create` the database if the `MIX_ENV` is `prod`?

**Comment by drewolson** [comment]
I did two things at to resolve this issue.

* I explicitly added `template: "template0"` to my `prod.exs` config for my Repo
* I passed the `--create false` flag to the `mix ecto.migrate` task

Still, this seems like it might be a bug?

**Comment by josevalim** [comment]
Yeah, we added a mechanism to automatically create the database if one did not exist on migrations but I was afraid of running into issues exactly like these. It is better to revert.

**Comment by drewolson** [comment]
Alternatively, a distinct ecto.reset command could be provided that drops,
creates and migrates the database for development and testing environments.
