### ISSUE TITLE
Add conditionals to callbacks

### ISSUE THREAD

**Issue by mschae** [elixir-lang/ecto#545]
Hey,

how do you feel about conditionals for callbacks. E.g.

```Elixir
defmodule User do
  use Ecto.Model

  struct "users" do
    field :username
    field :email
  end

  after_insert :send_welcome_email, if: &Dict.has_key?(&1.changes, :email)
end
```

**Comment by mschae** [comment]
PS: If we want that functionality I'd be happy to implement it.

**Comment by josevalim** [comment]
:-1: for two reasons:

1. It is easily done inside the callback

2. The code above will only work if it has no variables from the current context. For example, this can't be made to work in Elixir:

    email = :email
    after_insert :send_welcome_email, if: &Dict.has_key?(&1.changes, email)
