### ISSUE TITLE
Provide an Ecto.Adapter for redis datastore

### ISSUE THREAD

**Issue by aforward** [elixir-lang/ecto#546]
I am looking to create a Repo working around a redis datastore.  I am thinking of using exredis as the underlying library for interacting with redis, but wanted to manage it as a supervised worker, so I was looking at possibly adding support into Ecto.

Should I simply add support directly into exredis, or would this be of interest looking at redis a nosql integration?

**Comment by josevalim** [comment]
Can we bring this discussion to the mailing list? My first thought is that
Redis doesn't map to Ecto at all, so I wouldn't even worry about it.
Handling the pooling in exredis is likely better, you could also copy the
connection pool from Phoenix (we have a pool for pub sub and it is simpler
than the Ecto one).


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by aforward** [comment]
Hi all,

I posted a reply in https://groups.google.com/forum/#!forum/elixir-ecto but
then I saw this reply here.  Sorry for posting to the wrong mailing list (I
deleted and will continue the thread here).

I am going to proceed with enhancing exredis directly, but this fall I
might check back to see what happens this summer with the nosql development.

Here's the link to google summer of code (posted on the mailng list above
posted by Pedro Medeiros
https://github.com/beamcommunity/beamcommunity.github.com/wiki/Project:-Elixir#idea-3-nosql-adapters-for-ecto

andrew f


On Wed, Apr 1, 2015 at 6:15 AM, José Valim <notifications@github.com> wrote:

> Can we bring this discussion to the mailing list? My first thought is that
> Redis doesn't map to Ecto at all, so I wouldn't even worry about it.
> Handling the pooling in exredis is likely better, you could also copy the
> connection pool from Phoenix (we have a pool for pub sub and it is simpler
> than the Ecto one).
>
>
> --
>
>
> *José Valim*
> www.plataformatec.com.br
> Skype: jv.ptec
> Founder and Lead Developer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/546#issuecomment-88426870>.
>



-- 
aforward
