### ISSUE TITLE
Possible to use "text" for migration :string in Postgres instead of varchar?

### ISSUE THREAD

**Issue by jeregrine** [elixir-lang/ecto#548]
Right now we have an artificial cap on "string" to varchar 255, I understand we need to be compatible with other databases but In postgres the preferred method is text.

http://stackoverflow.com/questions/4848964/postgresql-difference-between-text-and-varchar-character-varying

**Comment by ericmj** [comment]
You can pass in any atom as the migration type, so just `:text` would work in this case.

**Comment by jeregrine** [comment]
Ahh. Well still think it is a useful default.

**Comment by ericmj** [comment]
It was discussed which one to make the default and the decision was made for varchar(255) because that will work across databases.

**Comment by jeregrine** [comment]
Not sure if thats how it should be decided though? Especially when NoSQL
db's start getting added etc. Each database has different semantics...

**Comment by ericmj** [comment]
I agree with you. Just saying why the decision was made.

**Comment by josevalim** [comment]
The concern was not multiple databases but the fact text columns have no limit. If we have an easy way of limiting them... then i am all in.

**Comment by jeregrine** [comment]
José sorry I missed this originally. Limiting columns in the database is
less valuable IMO than limiting them at the application layer level, ie
changeset.

**Comment by orestis** [comment]
Just as a data point, in Postgres the Text column has identical performance than the varchar: from https://www.postgresql.org/docs/current/static/datatype-character.html

> Tip: There is no performance difference among these three types, apart from increased storage space when using the blank-padded type, and a few extra CPU cycles to check the length when storing into a length-constrained column. While character(n) has performance advantages in some other database systems, there is no such advantage in PostgreSQL; in fact character(n) is usually the slowest of the three because of its additional storage costs. In most situations text or character varying should be used instead.

I would argue that the default should be Text - however this seems like a case where the adapter should make the decision?

**Comment by kim366** [comment]
> Just as a data point, in Postgres the Text column has identical performance than the varchar: from https://www.postgresql.org/docs/current/static/datatype-character.html
> 
> > Tip: There is no performance difference among these three types, apart from increased storage space when using the blank-padded type, and a few extra CPU cycles to check the length when storing into a length-constrained column. While character(n) has performance advantages in some other database systems, there is no such advantage in PostgreSQL; in fact character(n) is usually the slowest of the three because of its additional storage costs. In most situations text or character varying should be used instead.
> 
> I would argue that the default should be Text - however this seems like a case where the adapter should make the decision?

Tha'ts very interesting. I wonder why text is faster only in Postgres. Unfortunately there is no further technical expanation, but it's good to know and I will default to it from now on

**Comment by kasvith** [comment]
According to [Don't Do This](https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_varchar.28n.29_by_default) guide for PostgreSQL

We should use `text` or `varchar`(without `n`) to store any text data unless you know exact size. PostgreSQL suggest to use a constraint to limit the number of characters like follows

```sql
CREATE TABLE products (
    product_no INTEGER,
    name TEXT CONSTRAINT namechk CHECK char_length(name) <= 255,
)
```

I think adapter should make this decision.
