### ISSUE TITLE
Ecto 0.10 Changeset error messages are inconsistent.

### ISSUE THREAD

**Issue by hahuang65** [elixir-lang/ecto#554]
Based on what is passed into a changeset, it's errors give different messages.
When doing `validate_required`:
passing nothing yields: `"can't be blank"`
passing `nil` yields: `"can't be blank"`
passing `""` yields: `:required`

```elixir
defmodule Todo do
  use Ecto.Model

  schema "todos" do
    field :task, :string
    field :due_date, Ecto.Date
    field :completed, :boolean, default: false
    timestamps

    belongs_to :user, User
  end

  def changeset(params, :create) do
    %Todo{}
    |> cast(params, ~w(task user_id), ~w(completed due_date))
    |> validate_required(:task)
  end

  def changeset(params, :update, todo) do
    todo
    |> cast(params, [], ~w(task completed due_date))
    |> validate_required(:task)
  end
end
```

```elixir
iex(6)> changeset = %{} |> Todo.changeset(:create)
iex(7)> changeset.errors
[task: "can't be blank", user_id: "can't be blank"]

iex(8)> changeset = %{task: nil} |> Todo.changeset(:create)
iex(9)> changeset.errors
[task: "can't be blank", user_id: "can't be blank"]

iex(10)> changeset = %{task: ""} |> Todo.changeset(:create)
iex(11)> changeset.errors
[task: :required, user_id: "can't be blank"]
```

**Comment by hahuang65** [comment]
I don't know if this is really a bug, or intentional, but since these ALL used to be `:required`, I assumed that the string versions were put in for more informational messaging.

If so, they should probably be uniform no matter what is passed in, so that they can be easily surfaced on the view layer.

**Comment by ericmj** [comment]
I agree, they should all be strings.

**Comment by josevalim** [comment]
Bug definitely! I love want to do a new Ecto release today so this came
just in time!

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by hahuang65** [comment]
:) @josevalim You'll probably fix it, but in case you don't have time today, mention me and I can take a look this weekend also :)

**Comment by josevalim** [comment]
Well, we don't have `validate_required` in Ecto.... so that seems to be something coming from your code. :)

**Comment by hahuang65** [comment]
Woops, forgot about that. :D Sorry.

**Comment by josevalim** [comment]
No worries... you helped me find an `:invalid` atom that was supposed to be a "is invalid" string... :D
