### ISSUE TITLE
Support `from Model, where: email == ...`

### ISSUE THREAD

**Issue by paulcsmith** [elixir-lang/ecto#560]
This is based off a [discussion on Twitter](https://twitter.com/josevalim/status/590882681400983552). Sometimes simple queries can be a bit verbose. Here's a comparison of roughly the same query in ActiveRecord and Ecto.

```ruby
User.find_by(email: my_email)
```
 
```elixir
where(u in User, where: u == ^my_email) |> Repo.one
```

Maybe there should be a syntax like: `from User, where: email == ^my_email`?

**Comment by jeregrine** [comment]
With ruby sequel
```ruby
User.where(email: my_email).first 
```
Possible:
```elixir
where(User, email: my_email) |> Repo.one
```

**Comment by josevalim** [comment]
@jeregrine's suggestion is definitely doable.

**Comment by jeregrine** [comment]
maybe have some functions that take a query and options, so that all functions kinda act like `from`. The biggest trick might be that joins and preloads might not quite work

```elixir
where(User, email: my_email) |> limit(1) |> order_by([:name, [:created_at, :asc]]) |> Repo.all 
```

**Comment by jeregrine** [comment]
Pretty sure MOST of that is possible :-P

**Comment by paulcsmith** [comment]
I like your example, but it would be sad to lose the support for other operators in the query like `>` `<`, etc.

Is this possible/a good idea? `where(User, email == ^my_email) |> limit(1)`?

**Comment by josevalim** [comment]
@paulcsmith unfortunately that is ambiguous. I mean, we could support it, but it is just too confusing. In the same way we could get rid of `^` but we leave it there for clarity.

We could possibly add `Repo.get_by/2` instead of supporting the low-level keyword syntax in where. Trade-offs, trade-offs.

**Comment by paulcsmith** [comment]
@josevalim That makes sense. Now that I look at it, it is pretty unclear. It could work with the syntax I proposed above, but maybe that's worse/harder to implement.

**Comment by jeregrine** [comment]
Always a trade off! I think having some handy functions is good. Maybe we just include this in a guide/blog post where we show how easy it is to extend Repo :)

**Comment by ericmj** [comment]
@jeregrine's proposal is also ambiguous unless we decide that an atom should always refer to the first source or that we just error if `:email` can belong to two sources. The second alternative is impossible when we are dealing with string sources.

If we do add shorthand syntax I don't think we should add them to queries. Ecto queries are very clear and flexible today, it would be a shame to complicate them by adding more syntax to them.

I would prefer adding functions to the repo, such as `Repo.find_by(User, email: "foo@bar.com")`.

**Comment by paulcsmith** [comment]
:+1: `find_by` (though I think `get_by` is more in line with the rest of the Repo api).

Do you imagine the function would also accept `limit`, `order`, `preload`, etc.?

**Comment by scrogson** [comment]
:+1: for `Repo.get_by(User, email: email)`
