### ISSUE TITLE
Ecto changeset cast should fail on nil (use a more explicit atom for dry run)

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#564]

**Comment by tony612** [comment]
Does this mean the test
```elixir
    assert_raise ArgumentError, ~r"expected model not to be a nil, got nil", fn ->
      cast(nil, %{title: "foo"}, ~w(title), ~w())
    end
```

But I don't understand the meaning of *use a more explicit atom for dry run* :sweat_smile:

**Comment by ericmj** [comment]
No, this issue is talking about the case where the params are nil.

**Comment by tony612** [comment]
@ericmj So, `cast(model, nil, ~w(), ~w())` will raise a error and `case(model, :atom, ~w(), ~w())` will behave like current code, right?

**Comment by ericmj** [comment]
Correct, and we are discussing what atom we should use in place for `:atom`.

**Comment by tony612** [comment]
@ericmj Yeah, it's a problem. How about `:invalid`?

**Comment by ericmj** [comment]
The changeset is neither invalid or valid in the sense of validations (since they never run). It's basically a dry-run of the changeset used to annotate the changeset for forms such as Phoenix.HTML.FormData.

**Comment by scrogson** [comment]
How about :new ?

**Comment by josevalim** [comment]
We have gone with `:empty`. Thanks everyone!
