### ISSUE TITLE
Support type(value, query.field) in query syntax

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#565]

**Comment by tony612** [comment]
Does this mean something like the example below?
```elixir
iex> Repo.all(from p in Post, select: type(^"1", p.id))
[1] # p.id is integer type
```

**Comment by josevalim** [comment]
Yes!

**Comment by gjaldon** [comment]
I'd like to work on this, if available.

Just to clarify, is `type/2` a convenience like `field/2` that casts the value according to the type of the provided field?

**Comment by josevalim** [comment]
`type/2` already exists but it does not accept the second argument to be a field afaik.

**Comment by gjaldon** [comment]
Ok got it and will be working on this :)

**Comment by gjaldon** [comment]
@josevalim I'm stuck with this and need some help. I've defined an `Query.Builder.escape/5` function that matches on the `type(^1, m.x)`. I was thinking of calling `__schema__(:field, field)` on `m` given the ff expression `Model |> select([m], type(^"1", m.id))` from inside the `escape/5` function I defined.

Is it possible to do that? If not, how do I get the type for the field `m.id`?

**Comment by josevalim** [comment]
@gjaldon you cannot call it during compilation time. So you need to escape it, generating AST that is going to be checked and validated in Ecto.Query.Planner. The AST can likely be `type(^"1", m.id)` itself.

**Comment by josevalim** [comment]
@gjaldon I have some time to clean up Ecto backlog. May I take this?

**Comment by gjaldon** [comment]
@josevalim ok please go ahead. I was having trouble taking this on and
would be happy to see how you would solve it. :)

On Wed, Jun 24, 2015 at 5:13 PM, José Valim <notifications@github.com>
wrote:

> @gjaldon <https://github.com/gjaldon> I have some time to clean up Ecto
> backlog. May I take this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/565#issuecomment-114797796>.
>



-- 
Gabe Jaldon
