### ISSUE TITLE
Support reserving a worker

### ISSUE THREAD

**Issue by MSch** [elixir-lang/ecto#569]
(as discussed at ElixirConf with @josevalim @ericmj)

We have a scenario like this: One `GenServer` `GlobalStuff` that needs to use an Ecto worker from time to time to do its work and a lot of concurrent requests handled by short-lived e.g. `plug` processes all of which need to call `GlobalStuff` while in a transaction before succeeding.

In our load-testing we always run into a deadlock, where we got all Ecto workers checked out by our short-lived processes and in a transaction, waiting for a call to `GlobalStuff` to return. `GlobalStuff` meanwhile is trying to check out an Ecto worker from poolboy, but none is available since all are checked out by the short-lived processes.

Our solution was to manually reserve an Ecto worker for `GlobalStuff`:

```elixir
defmodule PS.Repo do
  @doc ~S"""
  Manually reserve an Ecto worker permanently without creating a transaction (avoid long-running
  Postgres transactions) by pretending to create a transaction.
  """
  def reserve_ecto_worker! do
    worker = :poolboy.checkout(PS.Repo.pool, true, :infinity)
    Ecto.Adapters.SQL.Worker.link_me(worker, :infinity)
    Process.put({:ecto_transaction_pid, PS.Repo.pool}, {worker, 1})
    worker
  end


  @doc "Expose the internal `poolboy` pool"
  def pool do
    __pool__ |> elem(0) |> Process.whereis
  end
end
```

I'd like some public API that exposes this functionality (even better would be a solution that doesn't involve permanently assigning one Postgres connection to a single GenServer, but I don't think there's one)

**Comment by josevalim** [comment]
If we expose an API for reserving, do we also need an API for checking it back in?

**Comment by MSch** [comment]
In our use case the processes that reserve workers do so in `init` and keep the same worker around forever, so there's no need for checking it back in. One performance optimization we have planned would require us to hand the worker from one process to another and back again, but also not giving it back to the pool.

**Comment by fishcakez** [comment]
> One performance optimization we have planned would require us to hand the worker from one process to another and back again, but also not giving it back to the pool.

This sounds like something poolboy would be good at. Have you considered making a repo of 1 connection just for this purpose?

**Comment by MSch** [comment]
@fishcakez not really, I thought the need to either duplicate all involved models and functions using the repo or pass the repo around as argument to them, and then having to figure out how to DRY up the configuration for those two repos would make that a worse workaround.

I think the real problem I have is that the pool and the repo are linked together. If I could define multiple pools and select which pool to use for a given repo and process (similar to how a transaction already reserves a worker) that would be a better solution, I would even get away with only one worker in the "reserved" pool instead of having one per process.

**Comment by josevalim** [comment]
@MSch we could support an option on every query called :worker. If this option exists, we use instead of checking one out, I don't think this would fix your problem though because then you need to pass this option everywhere.

**Comment by MSch** [comment]
@josevalim exactly, it'd have to be in the pdict, like transactions work right now.

**Comment by josevalim** [comment]
Hell just called, they confirmed they have a place for you. ;)

**Comment by MSch** [comment]
Hehe :)

But I always did think that the automatic checkin/checkouts feel a bit too much like magic to me, maybe being explicit about the worker and passing it around everywhere would even not be so bad. (On the other hand we've already written all that code where we don't pass around the worker)

**Comment by fishcakez** [comment]
@MSch you're right, the duplication would be a pain and is asking for trouble :(.

**Comment by josevalim** [comment]
@fishcakez Would such a feature work well with sbroker? Because if it won't, we need to come up with another approach for this.

**Comment by fishcakez** [comment]
It should work fine. The only difference with sbroker is that the worker
checks itself in - instead of the client.

**Comment by MSch** [comment]
We've right now implemented it like this (since we need to hand over the Ecto worker to the subprocess)

```elixir
  @doc ~S"""
  Manually reserve an Ecto worker permanently without creating a transaction (avoid long-running
  Postgres transactions) by pretending to create a transaction.
  """
  def reserve_ecto_worker! do
    worker = checkout_worker
    set_worker!(worker)
    worker
  end

  def checkout_worker do
    :poolboy.checkout(PS.Repo.pool, true, :infinity)
  end

  def set_worker!(worker) do
    Ecto.Adapters.SQL.Worker.link_me(worker, :infinity)
    Process.put({:ecto_transaction_pid, PS.Repo.pool}, {worker, 1})
    :ok
  end

  def unset_worker! do
    key = {:ecto_transaction_pid, PS.Repo.pool}
    {worker, 1} = Process.get(key)
    Ecto.Adapters.SQL.Worker.unlink_me(worker, :infinity)
    Process.delete(key)
  end

  @doc "Expose the internal `poolboy` pool"
  def pool do
    __pool__ |> elem(0) |> Process.whereis
  end
```

Should I send a PR? Maybe just exposing the underlying pool and the set/unset_worker functions is enough to provide the necessary building blocks?

**Comment by fishcakez** [comment]
This will break in `0.12.0-rc` as the pdict entry stores more information.

**Comment by MSch** [comment]
@fishcakez working on upgrading our codebase to `0.12.0-rc` right now, are you saying there's no way to fake the transaction pdict any more or just that we need to adopt the pdict entry?

**Comment by josevalim** [comment]
You need to adapt the pdict entry only.

**Comment by josevalim** [comment]
The new pool is in. We can start working on this! @MSch pull request please? :)

**Comment by MSch** [comment]
@josevalim @fishcakez Thinking about how to best implement this. My thoughts so far are to add the public API to `Ecto.Adapters.Pool` so it's not cluttering up `Repo`:

* Add a `checkout` function, that given a Repo checks out a worker. It uses the Poolboy Pool callback module to call `Worker.checkout` with `:manual`.
* Add a `checkin` function, that does `Worker.checkin` and `:poolboy.checkin` using the callback module
* Add a `give_away` function similar to `:ets.give_away` to transfer the worker from one process to another. There also needs to be a corresponding function for the child to "receive" the worker.
* I'd also like a way to set a `heir` - again like in ETS - so that the worker can be passed back with a corresponding message if the process that got it via `give_away` crashes.
* Extend the `transaction` function to not check in the worker if it's in `:manual` mode.

The rationale for `give_away` and `heir` is that right now we've got two GenServers that need a reserved connection to prevent deadlocks as described above. Since one of those is an important bottleneck we've made it run the SQL operation asynchronous in a child process so that it can continue to serve others during that time. (Until it can't then it blocks on the child `Task`.) So my thoughts are to make the parent process spawn its child worker, give it the Ecto worker using `give_away` and get it back using the `heir` message if its child crashes.

**Comment by fishcakez** [comment]
`give_away` is going to be tricky with `poolboy`. `poolboy` is going to monitor the process that checked out the worker/connection. This means that if checked out processes crashes but it gave the connection away to a new owner, then the owner believes it owns the connection. However `poolboy` will give the connection to another process.

Is it possible to split your problem in two?

We support custom pools now so it is possible to run a custom pool that is actually 2 pools (in your case a poolboy of size N and a "reversed" poolboy of size 1). We just need a way to tell the custom pool which of its two pools to choose. This could be done by replacing the `timeout` argument in the pool interface with `opts`. You would then need to add the "reversed" pool option when using the "reserved" pool. Assuming that the "reserved" pool is using the your new manual `checkout`, this only needs to be done there.

**Comment by MSch** [comment]
Good point, I didn't think of that, with `sbroker` it would work though?

To me doing it with a custom size-1 pool seems less elegant than doing `give_away`, but I'm by far no OTP guru and of course it doesn't work with `poolboy`.

What about adding a function to manually start a worker? That worker would then have to be managed by the process that started it of course.

With your approach of splitting the problem in two I don't understand how the reserved pool wouldn't have the same problem as my initial `give_away` approach with poolboy: The reserved pool would still checkout its workers from the "main" pool, so poolboy would still monitor the wrong process?

**Comment by josevalim** [comment]
My initial thought is that this sounds too complex. It feels easier to say "just pass the repository as argument" and have two of them. Because if we support this, it is going to become more and more complex as we add more pools. :(

**Comment by MSch** [comment]
I unfortunately don't fully understand @fishcakez's approach, but I think it boils down to manually specifying a custom pool. That would be a lot nicer than having multiple repos wouldn't it? So instead of passing a repo as argument I pass the pool as argument? (If I understand correctly)

**Comment by josevalim** [comment]
@MSch Well, the whole benefit of this patch though would be that no change would be required for code calling the repo. So if you need to pass *any* argument, why not the repo?

**Comment by MSch** [comment]
@josevalim see https://github.com/elixir-lang/ecto/issues/569#issuecomment-99409781 I'd prefer to pass a `worker` or `pool` option than to have two Repo modules that aren't DRY. E.g. just having to implement `log` twice feels very wrong to me.

**Comment by fishcakez** [comment]
@MSch I can do an example for later but for now I mean something like this:

```elixir
def open_transaction(pool, opts) do
  sub_pool = Keyword.get(opts, :pool, "One")
  sub_pool = Module.concat(pool, sub_pool)
  case Ecto.Adapters.Poolboy.open_transaction(sub_pool, opts) do
     {:ok, worker, conn} -> {:ok, {sub_pool, worker}, conn}
     {:error, _} = error    -> error
  end
```

**Comment by MSch** [comment]
@fishcakez got it. Thanks.

**Comment by fishcakez** [comment]
Ofc we need to switch `timeout` to `opts` to support that

**Comment by josevalim** [comment]
@MSch 

```elixir
for mod <- [MyApp.Repo1, MyApp.Repo2] do
  defmodule mod do
    use Ecto.Repo

    def ...
  end
end
```

:P ?

**Comment by josevalim** [comment]
Another option, I have been discussing this with Eric, is to allow the following:

  1. allow custom names to be given to the pools
  2. allow you to customize __pool__ function to return a particular name

This way you can start the repo twice with different options:

    supervisor(Repo, [[name: Hello1, size: 30]])
    supervisor(Repo, [[name: Hello2, size: 1]])

And specify a custom function which tells which repository to use (then you can use pdict or whatever you want to change that).

**Comment by josevalim** [comment]
The benefit of the solution above is that all the logic is in the Repo. The adapter just need to continue calling `__pool__` to get the proper pool.

**Comment by MSch** [comment]
@josevalim That seems like a great and simple approach that solves the problem.

But why not support multiple pool implementations instead of just multiple pool names? Isn't the work necessary about the same?

Another minor nitpick is that I'd prefer to have the Pool adapters in my supervisor spec instead of the Repo, but in the end it doesn't matter if it's

```elixir
supervisor(Ecto.Adapters.Poolboy, [[repo: Repo, name: SingleWorker, size: 1]])
supervisor(Ecto.Adapters.Sbroker, [[repo: Repo, name: Repo, size: 30]])
```

or 

```elixir
supervisor(Repo, [[pool: Ecto.Adapters.Poolboy, name: SingleWorker, size: 1]])
supervisor(Repo, [[pool: Ecto.Adapters.Sbroker, name: Repo, size: 30]])
```

**Comment by josevalim** [comment]
Yes, we could support the second easily. We could make `__pool__` overridable and support options on `start_link` (which we would merge with the config). That would be all that is required, really, everything should work as long as `__pool__` returns the proper thing. We will keep the `__pool__` contract informal though (not documented but supported in tests).

**Comment by MSch** [comment]
This seems like the best approach to me! Thanks @josevalim @ericmj!

@fishcakez do you agree?

I'd start implementing this ASAP.

(On a sidenote, since the deadlocks happen as soon as two processes that use Ecto sometimes call each other (at sufficient concurrency) I would document this explicitly, since I expect more people will run into it.)

**Comment by fishcakez** [comment]
This sounds great.

**Comment by josevalim** [comment]
@msch i would like you to try it out and be confident that `__pool__` is not going to change before documenting it officially.
