### ISSUE TITLE
need a way to handle the interpolation in a changeset error

### ISSUE THREAD

**Issue by adamkittelson** [elixir-lang/ecto#571]
e.g. [name: {"should be at least %{count} characters", 2}] -> [name: "should be at least 2 characters"]

Looks like phoenix_ecto has a thing for this for displaying the error in a form, but for people wanting to return errors in an API they'd need to roll their own.

**Comment by whatyouhide** [comment]
Hey @adamkittelson, what you want is very common and the cleanest solution will most likely be [gettext](https://github.com/elixir-lang/gettext) when it will be ready :).

**Comment by josevalim** [comment]
@whatyouhide btw, we have a bug in Ecto.Changeset for Poison, don't we?

https://github.com/phoenixframework/phoenix_ecto/blob/master/lib/phoenix_ecto/json.ex

This should interpolate %{count} but we don't...

**Comment by josevalim** [comment]
@adamkittelson right now, just do a `String.replace string, "%{count}", n`. We will streamline the experience on gettext comes out. :)

**Comment by ericmj** [comment]
Is gettext going to be a dependency of ecto? Ecto should include a way to format the error messages it produces.

**Comment by josevalim** [comment]
@ericmj no, that is not planned. We could provide some conveniences but honestly it is very straight-forward.
