### ISSUE TITLE
`mix ecto.migrate --no-start` fails because Logger application is not started

### ISSUE THREAD

**Issue by jordan0day** [elixir-lang/ecto#574]
Running into this issue when trying to run migrations without starting the application:
```
mix ecto.migrate --no-start
** (RuntimeError) Cannot use Logger, the :logger application is not running
    (logger) lib/logger/config.ex:50: Logger.Config.__data__/0
    (logger) lib/logger.ex:401: Logger.log/3
    lib/ecto/migration/runner.ex:21: Ecto.Migration.Runner.run/6
    lib/ecto/migrator.ex:113: Ecto.Migrator.attempt/6
    lib/ecto/migrator.ex:63: anonymous fn/4 in Ecto.Migrator.do_up/4
    lib/ecto/adapters/sql.ex:443: Ecto.Adapters.SQL.transaction/3
    lib/ecto/migrator.ex:218: anonymous fn/4 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:977: Enum."-map/2-lc$^0/1-0-"/2
```

All the other mix ecto.* tasks that have a --no-start option (create, drop, gen.migration) work fine with the --no-start option, as none of them appear to be using the logger.

I'll submit a PR shortly that turns off logging when the --no-start flag is used, but I wonder if it's preferable to just start the logger application, even if --no-start is used?

**Comment by josevalim** [comment]
Which Elixir version? I think this is fixed in Elixir itself.

**Comment by josevalim** [comment]
It is definitely fixed in master. We only stop the logger if we are starting the app:

https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/app.start.ex#L52-L60

Thank you! :)

**Comment by jordan0day** [comment]
D'oh! You're right, I was on 1.0.2, appears to work in 1.0.3 & 1.0.4.
