### ISSUE TITLE
put_change/3, put_new_change/3 and change/2 should check if the value is different from the one in the model

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#582]
If the value is the same as in the model, we won't add it to the list of changes. If it is different, we add it.

We will also introduce `force_change/3` which works as `put_change/3` today.

Is someone interested in picking this up? We should release v0.11.1 afterwards with those fixes.

**Comment by bernardoamc** [comment]
@josevalim I will try to come up with something tonight. :)
