### ISSUE TITLE
validate_unique should be resilient to nil in the :scope attributes if they are required.

### ISSUE THREAD

**Issue by drewolson** [elixir-lang/ecto#584]
Currently, if the attribute provided to `validate_unique` is both a required attribute and `nil`, `validate_unique` will not run. However, if an attribute provided to the `:scope` option is both required and `nil`, the function raises and exception. I believe it should not run in this case as well.

**Comment by ericmj** [comment]
The bug is that `validate_change` only runs if the field changed. But with the scope we are looking for multiple changes; the field and all the scopes. We can add `validate_changes` that checks multiple changes?

**Comment by drewolson** [comment]
I really like the idea of `validate_changes` and I think it would both solve this issue and be useful in its own right.

**Comment by josevalim** [comment]
We have decided to run validations if any field has changed and there is no validation error in any of them.

**Comment by drewolson** [comment]
This seems reasonable to me.

**Comment by drewolson** [comment]
Awesome, thanks. @josevalim are you planning on releasing 0.11.2?

**Comment by drewolson** [comment]
And I see it's already done. You're too quick for me.
