### ISSUE TITLE
Need process for dynamically setting database port/host. 

### ISSUE THREAD

**Issue by noizu** [elixir-lang/ecto#587]
I run elixir within a docker instance and need the ability to set the database port/host at runtime from :os.environment variables. 

The ability to set credentials via environment variables is also a common requirement for build systems where database details may not be known in advance.  Is there already the ability to do this with the current code base. I've glanced things over for a bit but am fairly new to elixir/erlang and didn't spot an instance of this being done, nor do I know what the standard idiom would be to do so if the system follows some standard idiom that passes values in via start link settings etc. 

If ability is available let me know the rough steps and I'll fork and update your docs for you with details. If not I'll go in and implement the capability for you. 

Much thanks in advance. This library is a great resource either way ^_^. 

- Noizu

**Comment by josevalim** [comment]
It should be possible via the URL option or just reading environment variables in your config:

```elixir
config :my_app, MyApp.Repo, port: System.get_env("PORT"), host: System.get_env("HOST")
```

And so on.

**Comment by noizu** [comment]
ack,  that works. Thanks for the prompt reply that was killing me.


*   Keith Brings *
   President, Noizu Labs, Inc.

*    Email: *
    keith.brings@noizu.com

*    Skype: *
    keith.brings
    (718) 618-4265

**Comment by noizu** [comment]
Specifically:

  port: System.get_env("MYSQL_PORT_3306_TCP_PORT") |> Integer.parse |> elem(0),
  hostname: System.get_env("MYSQL_PORT_3306_TCP_ADDR") |> to_char_list

since matching fails on String Port. 

note, allowing for matching on String Port followed by integer parse might save some users config headaches in the future.
