### ISSUE TITLE
Problem with interpolated UUIDs in Ecto.Query

### ISSUE THREAD

**Issue by stevegraham** [elixir-lang/ecto#589]
Given the example query:

```elixir
from a in Model, where: a.uuid_column == ^uuid
```

This results in a function clause error in `Postgrex.Extensions.Binary.encode/4` when running the query. Looking at the function it matches on the byte encoding of a UUID, e.g. `<<90, 240, 69, 115, 43, 113, 66, 222, 162, 208, 226, 89, 85, 39, 254, 42>>` rather than the ASCII encoding `5af04573-2b71-42de-a2d0-e2595527fe2a` handed by Ecto. 

I'm currently working around the problem using `Ecto.UUID.dump` to dump the bytes before interpolation. Is this a bug or am I doing something wrong?

**Comment by ericmj** [comment]
Use `Ecto.UUID` as a type if you use the string representation.

**Comment by stevegraham** [comment]
Thanks @ericmj!
