### ISSUE TITLE
Creating foreign key in a migration with references/2 leads to FunctionClauseError

### ISSUE THREAD

**Issue by Theemuts** [elixir-lang/ecto#593]
If I add a foreign key which references the id (contains UUIDs) column with 
```references(:tblname, type: uuid)```
a FunctionClauseError is raised in lib/ecto/adapters/postgres/connection.ex:525 when I try to migrate. Considering that I'm passing a reference to column_type/2, I would expect that the function should have pattern matched on the first definition in line 519, rather than the third.

**Comment by josevalim** [comment]
Can you provide the complete example of your migration just so we are sure?

**Comment by Theemuts** [comment]
Of course, when I'm copying my migration and decide to try one final thing, I find my error. I defined a type when adding the reference (```add :fkey, :uuid, references(:tblname, type:uuid)``` rather than ```add :fkey references(:tblname, type:uuid)```

That way, the reference was passed to column_type as the options, rather than as the first argument.
