### ISSUE TITLE
custom SQL queries

### ISSUE THREAD

**Issue by skyeagle** [elixir-lang/ecto#594]
An [example](https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/sql.ex#L138) from docs doesn't work for me.

```elixir
iex> Ecto.Adapters.SQL.query(MyRepo, "SELECT $1 + $2", [40, 2])
```

```elixir
** (Postgrex.Error) ERROR (ambiguous_function): operator is not unique: unknown + unknown
stacktrace:
  (ecto) lib/ecto/adapters/sql/worker.ex:26: Ecto.Adapters.SQL.Worker.query!/4

```

So, it doesn't interpolate arguments which were passed as array.

**Comment by josevalim** [comment]
I think it is because the operator is ambiguous. Maybe:

    iex> Ecto.Adapters.SQL.query(MyRepo, "SELECT $1::integer + $2::integer", [40, 2])

?

**Comment by skyeagle** [comment]
Yeap, you are right! Thank you!

**Comment by laurocaetano** [comment]
I guess this can be closed now, right?
