### ISSUE TITLE
After Connect Hook on Repo

### ISSUE THREAD

**Issue by mitchellhenke** [elixir-lang/ecto#599]
My use case is related to using pg_trgm to search text.  The default limit is 0.3 (http://www.postgresql.org/docs/9.1/static/pgtrgm.html#PGTRGM-FUNC-TABLE), and if you set it using`set_limit()`, it will reset to that default after disconnecting, so my solution has been to call `set_limit()` using an after connect in other [ORMs](http://sequel.jeremyevans.net/rdoc/classes/Sequel/ConnectionPool.html#attribute-i-after_connect).

It could look something like this:
```elixir
defmodule App.Repo do
  use Ecto.Repo, otp_app: :app

  def after_connect do
    Ecto.Adapters.SQL.query(App.Repo, "SELECT set_limit($1)", [0.1])
  end
end
```

If this sounds good, I can start working on a PR.

**Comment by jeregrine** [comment]
I am thinking it could work similar to how the query logger works. I *think* we should be able to put the hook here https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/sql.ex#L333

**Comment by MSch** [comment]
+1ing that as well.

Our use case is getting the Postgres backend pid for the connection for metrics/logging.

**Comment by JonathanTron** [comment]
Ok, to continue the discussion about providing an `after_connect` hook on `Ecto.Repo`, which would get passed the connection `pid`. 

I have something working with the new internal changes:

1. Add the repo to the options given to `pool_mod.start_link/2` in `Ecto.Adapters.SQL`
2. Add a call to `repo.after_connect/1` in `Ecto.Adapters.Postgres.Connection.connect/1` and `Ecto.Adapters.MySQL.Connection.connect/2`
3. Add the overridable `Ecto.Repo.after_connect/1` which takes the connection pid

This is at most a naive approach, with the pitfall that `Ecto.Repo.after_connect/1` is called synchronously before returning the connection pid to the pool, this means that if `after_connect/1` should take less than the pool's timeout.

For my usage, setting the `search_path` when a new connection is opened, this is perfect as I'm sure the connection would not be used before I have a chance to set it. 

But If I recall correctly, there was some questions about this approach.

I will try to come up with some test and send a new PR.

**Comment by josevalim** [comment]
Awesome! I will leave it up to you and @MSch to iron out the details. The only downside I can think of this approach is that queries will need to be done via Postgrex API directly and not `Ecto.Adapters.SQL`, but is likely fine.
