### ISSUE TITLE
no function clause matching in Postgrex.Extensions.Binary.encode/4

### ISSUE THREAD

**Issue by Kabal** [elixir-lang/ecto#602]
I just started playing with Ecto (with Phoenix framework) and I keep getting this error when trying to do a simple query. I'm probably doing something incorrectly - I don't really know Elixir I'm just kind of fudging my way through it :-)

Anyway, I have a model  that has a :integer called facebook_id, and I'm trying to do this:

    query = from u in User,
      where: u.facebook_id == ^userID

    case Repo.all(query) do
       # stuff goes here
    end

But I just get the error "no function clause matching in Postgrex.Extensions.Binary.encode/4" with a stack trace that has none of my code :(

I tried using the REPL to play around but it doesn't seem to work at all there:

    iex(6)> User.all(from u in User, where: u.facebook_userid == 1234)
    ** (RuntimeError) undefined function: u/0

Can anyone throw me a bone?

**Comment by josevalim** [comment]
Please post your postgrex and Ecto versions. In any case, be sure you are
on latest. Also, if you can print userID, it would be great. For the
terminal, you need to import Ecto.Query before using "from".

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by nurugger07** [comment]
It's been awhile but...

Try adding the `select u` to the end of your query so

` from u in User, where: u.facebook_id == 1234, select u`

Hope this helps :)

**Comment by Kabal** [comment]
Thanks for the import Ecto.Query tip. Playing around in iex I realised it worked fine for small numbers. So I checked my postgresql table and sure enough it was integer instead of bigint. Changing it to bigint made it work just fine.

Is there any way to make the built in table generation use a bigint? From what I can make out from the Eco.Schema docs :integer is the only integer number type?

**Comment by josevalim** [comment]
In your migration you can pass any database type as the column. In this
case, bigint, integer, serial, all map to :integer in your model.

@ericmj is it possible to raise a nice error message in this case?

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by ericmj** [comment]
@josevalim We could improve the error messages for some type.

**Comment by josevalim** [comment]
Move the issue to postgrex. Thank you!

**Comment by Kabal** [comment]
:bigint in the migration works great, thanks again.

I'm really liking this library by the way (and phoenix, and elixir!). Thanks for your hard work @josevalim

**Comment by andrewshatnyy** [comment]
I see this issue is closed but this is still a problem in Ecto. 1.0

     query = from u in Univer, where: u.id > 4, select: u

Blows up with `** (RuntimeError) undefined function: u/0`. Not only that model but other models as well
my deps

      {:postgrex, "~> 0.9.1"},
      {:poison, "~> 1.5"},
      {:httpoison, "~> 0.7.2"},
      {:ecto, "~> 1.0"},
      {:floki, "~> 0.5"}

Do you guys have any check list handy to see where to start troubleshooting? I haven't tried to change all my integers into `:bigint` tho.

For the reference.

      defmodule Univer do
        use Ecto.Model

        import Ecto.Query

        schema "univers" do
          field :ref, :integer
          field :name, :string
          field :legal_name, :string
          field :city, :string
          field :type, :string
          field :address, :string
          field :contacts, {:array, :string}
          field :fax, :string
          field :phones, {:array, :string}
          field :email, :string
          field :url, :string
          has_many :schools, School
          has_one :place, Place
          timestamps
        end
      end

and the migration

      defmodule Univer.Repo.Migrations.AddUniversTable do
        use Ecto.Migration

        def up do
          create table(:univers) do
            add :ref, :integer
            add :name, :text
            add :legal_name, :text
            add :type, :string
            add :fax, :string
            add :city, :string
            add :contacts, {:array, :string}
            add :address, :text
            add :phones, {:array, :string}
            add :email, :string
            add :url, :string
            timestamps
          end
        end

        def down do
          drop table(:univers)
        end
      end

P.S. don't judge the relation this is throw-all-in-one-pile test project

**Comment by ericmj** [comment]
That's an unrelated issue. Looks like you just forgot to import Ecto.Query or something similar like that.

**Comment by andrewshatnyy** [comment]
@ericmj yeah that's imported frist module `Univer` has it on line 2

**Comment by ericmj** [comment]
Include the full code and send the question to the mailing list, stack
overflow or IRC.

On Monday, 5 October 2015, Andrew Shatnyy <notifications@github.com> wrote:

> @ericmj <https://github.com/ericmj> yeah that's imported frist module
> Univer has it on line 2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/602#issuecomment-145596702>.
>


-- 
Eric Meadows-Jönsson
