### ISSUE TITLE
feature: ecto fixtures

### ISSUE THREAD

**Issue by skyeagle** [elixir-lang/ecto#603]
Hello Ecto Team!

Are there any plans to implement ecto fixtures like AR in Rails does or are there any other ways to so?

In my experience fixtures are more useful for larger projects than model factories.

Thank you.

**Comment by scrogson** [comment]
You can easily do this without any added feature using `mix run`. 

I've created a file in `priv/repo/seeds/seed.exs` that is simply:

```elixir
MyApp.Repo.insert %MyApp.Model{name: "blah"}
```

If you need helper functions to set values, just wrap in a module and create a `run/0` function and call it at the end of the file. 

Hope that helps.

**Comment by scrogson** [comment]
Oh and then to run it: `mix run priv/repo/seeds/seed.exs`

**Comment by skyeagle** [comment]
@scrogson You recommend to populate tetst with seed data but I want to have `named fixtures` in my tests. So, for example, I could able to write some thing like this:

users.yaml
```yaml
quentin:
  id: 1
  name: 'Quentin'
  # ...
```

tests/user_test.exs
```elixir
defmodule UserTest do
  include FixturesHelper

  test "with user Quentin" do
    quentin = users(:quentin)
    # some test goes below
    ...
  end
end
```

Anyway, thanks for the reply.

**Comment by scrogson** [comment]
Have you looked at Blacksmith? It's on hex.

**Comment by skyeagle** [comment]
@scrogson yes, I've looked at Blacksmith but for complex projects with a lot of associations it's really hell to raise up all association dependencies in a way (factories) like they do. So, I bet for fixtures.

**Comment by josevalim** [comment]
I am also a fixtures fan but we don't plan to ship it fixtures nor factories with 1.0. I would really appreciate if the community starts exploring those tools though so we can make an informed choice/decision in the future.
