### ISSUE TITLE
Add put_source to Ecto.Model

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#606]

**Comment by tony612** [comment]
Does it just mean something like this?
```elixir
  def put_source(model, new_source) do
    put_in model.__meta__.source, new_source
  end
```
Or maybe I didn't get the point?

**Comment by josevalim** [comment]
Exactly. Do we need this function? Or should we ask people to go through meta? @ericmj?

**Comment by ericmj** [comment]
I think it makes sense to support this with a proper function.

**Comment by josevalim** [comment]
Great. @tony612 can you please send a PR?

**Comment by tony612** [comment]
@josevalim Of course :)
