### ISSUE TITLE
Nested transaction does not rollback or raise if SQL exception caught

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/ecto#610]
Using the `Simple` example and a raw query that raises because `bad` is not a column:
```elixir
defmodule SimpleTransaction do
  def test do
    Simple.Repo.transaction(fn ->
        Simple.Repo.transaction(fn ->
          try do
            Ecto.Adapters.SQL.query(Simple.Repo, "UPDATE weather SET bad = bad + 1", [])
          catch
            _, _ ->
              :ok
          end
        end)
        Simple.sample_query()
        :ok
    end)
  end
```
Results in the following exception when `Simple.sample_query/0` is called:
```
** (Postgrex.Error) ERROR (in_failed_sql_transaction): current transaction is aborted, commands ignored until end of transaction block
      (ecto) lib/ecto/adapters/sql/worker.ex:26: Ecto.Adapters.SQL.Worker.query!/4
      (ecto) lib/ecto/adapters/sql.ex:187: Ecto.Adapters.SQL.use_worker/3
    (simple) lib/simple.ex:13: Simple.Repo.log/2
      (ecto) lib/ecto/adapters/sql.ex:380: Ecto.Adapters.SQL.all/5
      (ecto) lib/ecto/repo/queryable.ex:20: Ecto.Repo.Queryable.all/4
    (simple) lib/simple.ex:48: anonymous fn/0 in SimpleTransaction.test/0
      (ecto) lib/ecto/adapters/sql.ex:442: Ecto.Adapters.SQL.transaction/3
```
If the above nested transaction was a top level transaction the transaction would be rolled back on commit - but only the top level transaction can `COMMIT`. If `RELEASE` was used when "committing" nested transaction the above nested transaction would raise when trying to "commit".

**Comment by fishcakez** [comment]
Thank you to @ericmj for help verifying this issue.

**Comment by ericmj** [comment]
We should be able to fix this by detecting when the transaction has been aborted (when the query returns a `%Postgrex.Error{}`). We continue executing commands in the query (they will all return "transaction aborted"). At the end of the transaction we roll back to the transaction's savepoint and we should be able to continue in a valid, outer transaction.

**Comment by fishcakez** [comment]
This one is tricky because mysql and postgres behave differently - mysql does not raise when calling `sample_query` and so probably should not be rolledback. I assume other databases may have different behaviours. I think we should use `RELEASE` (and rollback if that raises) so that the driver's behaviour is enforced. Otherwise will likely have to move transaction logic to the connection process.

**Comment by josevalim** [comment]
We have agreed that if begin/rollback/savepoint command fails, we will always assume the connection has gone bad because it is impossible to know the reason the command fail without checking case by case or going adapter specific.
