### ISSUE TITLE
Discuss if adapters should enable keep alive by default

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#616]
A user posted an issue with connection being dropped of with Postgres:

https://groups.google.com/forum/#!topic/elixir-ecto/XDIQfwMhHd8

Some search revealed that libpq, for example, enables keepalive by default. Should we do the same in our adapters?

At least I recommend all adapters to support configuring the tcp connection. I have pushed this commit to Postgrex and I recommend the other adapters to the the same: https://github.com/ericmj/postgrex/commit/5704b6988fecb0bf8841da453c355190a6733629

/cc @ericmj @liveforeverx @mobileoverlord @fishcakez (please ping this thread once you have added the socket_options and your opinions regarding keep alive).

**Comment by liveforeverx** [comment]
Added: https://github.com/xerions/mariaex/commit/d4c5cb7a5b4ddb64e091f8771659667b8e0bb681 and released 0.1.5. 

Inactive clients will be proactive closed by MariaDB (at least on Galera Cluster per default). It has there very tiny default inactive interval (something like 1 second, and after that connection will be closed).  If there will be something like network split, without keepalive, the connection willn't be proactive closed, seems, that it would be good to have keep-alive for this case.

**Comment by fishcakez** [comment]
If the connection is regularly dropped within 10mins on the network, as in the email, I think `raw` socket options will be required to set a low enough keepalive interval. These are OS specific.

@liveforeverx Keep alive is at the tcp level so wont prevent application level idle timeouts.

**Comment by liveforeverx** [comment]
@fishcakez , I know. But, keepalive should help on network splitts and firewalls(which are mostly drop inactive connections too).

**Comment by fishcakez** [comment]
Ah I am confused by your 1 second comment.

**Comment by liveforeverx** [comment]
@fishcakez want only mention, that I doesn't seen such behaviour(as in error in mailing list) with Mariadb/MySQL at all, as it wasn't silently closed, that it was always explicit closed. With galera cluster, I'll see after one second of inactivity the connection is closed. Connection closed explicitly in this inactive interval, and for next query ecto starts simple new connection without errors.

**Comment by josevalim** [comment]
The cause of the issue was another one. Let's not change keep alive defaults but still provide :socket_options so users can configure it. Thanks everyone.

**Comment by mobileoverlord** [comment]
All up to date
livehelpnow/tds@ 3f9ebb4757821627b0ac07a15c1798fa445a8d89
