### ISSUE TITLE
Allow queries that check if an entry is in an array

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#623]
We can either support it on top of `in/2` (it may mess up type inference) or provide one specific operator for it. It is worth checking how other databases handle this.

**Comment by ericmj** [comment]
I thought the issue was that only postgres supported this?

**Comment by josevalim** [comment]
Well, only postgres supports arrays... so I guess it doesn't hurt adding this anyway? The big issue we had before though was that `in/2` behaved specially for Postgres so we just need to be careful with semantics here.
