### ISSUE TITLE
Introducing id and binary_id

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#624]
Different databases (or even within the same database), they are two types of primary keys:

  1. the ones (auto) generated in the database, for example, integer serial keys 
  2. the ones (auto) generated in the client, for example, UUID in postgres

In Ecto, only the first is well supported via the `:read_after_writes` option. Read after writes (RAW)  allow us to read a particular field back after performing writes (insert or update).

The motivation for this proposal, however, is the lack of support for the second option. Today you need to use a UUID column and then either: 1. use `:read_after_writes` and generate the value in the database, or 2. define a callback that will generate the field for you on the client. The callback option is considerably verbose though, so many end-up relying on RAW once again which, as we will see next, adds its own problems.

## Read after writes (RAW)

The `:read_after_writes` option can be given per field in your schema:

    field :uuid, Ecto.UUID, read_after_writes: true

It is also important to mention that fields declared as RAW are not sent to the database on insert if they are nil. The trouble with RAW is that they are not properly supported by all databases:

  1. PostgreSQL and MSSQL supports RAW without issues due to RETURNING clauses
  2. MySQL does not support RAW. It can only read the primary key back
  3. NoSQL databases do not support RAW. However, since most of them don't have trigger and similar features, it doesn't really matter, as the value sent is always the value read back

In other words, users that rely heavily on RAW in their schema are likely writing a schema that depends on features that are database specific. Although Ecto embraces the diversity and supports database specific features, we should aim for a common ground as much as possible and proper primary key support is essential for this.

## Auto-generation

Instead of RAW, we actually want to support auto-generation of values:

    field :uuid, Ecto.UUID, autogenerate: true

This pushes the responsibility to the client without any drawback as UUIDs are meant to be generated on the client too. Passing `:autogenerate` is going to invoke a function on the type (likely `generate/0`) before inserting it to the database.

## UUIDs? 

Although we have used only UUID as examples, the truth is that many databases have their own ID type. PostgreSQL support UUIDs that can be generated in the client or server, while MySQL requires them to emulated in the client, Mongo provides ObjectID which is client-based while OrientDB uses RecordID which is generated in the database.

What all those types share in common is that they are ultimately stored as binaries. Hence we propose two new types: `:id` (supporting the current integer fields) and  `:binary_id` (for the binary ones).

Both types are special as many of its functionalities are delayed until we know the adapter we are currently working against, including autogeneration itself. For the binary field, loading/dumping/casting is delayed allowing the adapter to impose its own format.

## IDs × autogenerate

Since the new two types pushes the autogenerate semantics to the database. Let's study those combinations one by one.

#### Autogenerate for :id

If the database supports autoincrement, the field is generated in the database.

If the database does not support autoincrement using the `:id` colum with autogenerate will fail at the adapter level. In fact, the `:id` column without `:autogenerate` is synonymous with `:integer`.

#### Autogenerate for :binary_id

Autogeneration for `:binary_id` happens at the adapter or the database level. Ecto simply does not care where.

#### What about the primary keys?

Because some databases like MySQL and OrientDB support only one autogenerating `id`/`binary_id` column, as they are very tied to primary keys, maybe we should close the deal and impose particular restrictions on `id`/`binary_id`:

  * We can have just one of those as autogenerated in a schema
  * Marking `id`/`binary_id` as autogenerated outside of a primary key will raise an error

As one final note, not all databases may allow its autogenerated field to be assigned. This is true for primary keys in MSSQL, RecordID in OrientDB and others. If this is the case, we need to provide the proper foundation so the adapter itself can detect such cases and raise.

## Old features, old habits

Although binary_id is a binary column in the database, it will be represented as a string in the model. For this reason, I would like to remove `:uuid` as a user-accessible type in favor of only `Ecto.UUID`.

I would also like to deprecate `:read_after_writes`. The proposed features supports most of `:read_after_writes` use cases and I would like to push users to try it out. Maybe we won't remove it at the end but we can then promote it less and only for special cases.

## Summing up

This proposal advocates for adding an `:autogenerate` option to schema fields. This is available for custom types and will invoke the generate function on the custom type.

This proposal also advocates for two new field types: `:id` (integer) and `:binary_id` (binary). The semantics of those fields are specified by the adapter, including loading/dumping/casting of the latter. If one of the primary keys are of one of those types, they may be marked as autogenerated as well, and the semantics will be controlled by the adapter too.

As consequence, both `:uuid` type and `:read_after_writes` option will be deprecated. The former will definitely be removed, the second will be removed based on feedback.

**Comment by whatyouhide** [comment]
Great proposal! I'm particularly :+1: for allowing each custom type to autogenerate "itself", this will make things very easily extensible. Awesome work!
