### ISSUE TITLE
Store MD5 (or other hash) of file in migration log table?

### ISSUE THREAD

**Issue by stevenproctor** [elixir-lang/ecto#626]
I just read @drewolson's post on Sanity Tests (http://blog.drewolson.org/sanity-tests/), and it got me wondering if it would make sense to track the MD5 (or some other hash) of the file in the table that logs the migrations that were run.

This would allow the migrations to be checked against was was actually run against the database, e.g. a commit/tag that was run, e.g. rc-1 vs rc-2 where a fix was made to the migration during testing.

The default behavior could still be to run as they do today, but give warnings for any migration files that don't match.

Maybe for those who want it, there could be a strict mode that does a check first before running any migrations to make sure everything still matches, or there is a dry run mode that would not do any migrations but just give a success or failure and any migrations that need to be reviewed.

Feel free to let me know if I am off target in my thinking of how this works, or could work.

**Comment by josevalim** [comment]
I think it is a good starting point but md5 file digests are too brittle. Maybe someone does an operation repo-wise that removes trailing whitespace and then... oops, you are stuck with a trailing whitespace for the rest of your live. :)

We would need some sort of mechanism that allows the hash to be updated in case the file changes for external reasons.

**Comment by stevenproctor** [comment]
I was kind of thinking about that as well, but wasn't sure if that would get in the way of getting the idea out there as far as the first pass idea goes to get ideas on it.

That one one of the reasons I threw out a "dry run" style check, where you could do a dry run, and either have it just report issues, or give you the opportunity to address changes like that to a migration.

Another case where I *might* see a migration needing to be modified post run in production, is going back and adding some indexes at the time of a table create, e.g. migration goes out to production, DBA is monitoring a table (à la New Relic or something like it) and sees there is performance issues because of a lack of index and adds one live in production, which we then want to get added back to source control and migrations, especially if there are multiple release branches because you wind up hosting different releases/instances per customer.

Just more food for thought.  I know the best way is to add the migration at the time it is realized, but I also know that things sadly don't always work out that way.

**Comment by stevenproctor** [comment]
Definitely expecting this to get some hammock time and larger feedback from others. ;)

**Comment by josevalim** [comment]
I am closing this because we can't act on it right now and we have bigger fish to catch. :) If you have any break through on how we can implement this, suggestions are welcome!
