### ISSUE TITLE
Ecto.Changeset.cast/4 does not support custom error messages

### ISSUE THREAD

**Issue by Theemuts** [elixir-lang/ecto#627]
When validating a change, it's possible to set a custom error message, this is not the case for Ecto.Changeset.cast/4. If any required fields are blank, it returns a default error message in English. It would be very nice I could override the default behaviour, e.g. by introducing Ecto.Changeset.cast/5 which accepts a new argument `message: [attr1: message1, attr2: message2, ...]`,  which overrides the "cannot be blank"-message for those fields with the new messages.

**Comment by josevalim** [comment]
Right now we indeed do not support any mechanism but we don't plan to. It is very easy to do a follow up pass after casting that translates the "cannot be blank" and "is invalid" to the appropriate format by traversing `changeset.errors`. The reasoning is that we are not sure yet how I18n will work with Ecto, so we don't want to prematurely complicate the cast API.

**Comment by Theemuts** [comment]
Ah okay, I understand. Thank you for the reply, I'll work around it for now.
