### ISSUE TITLE
Way to specify field as read-only (do not insert)?

### ISSUE THREAD

**Issue by citizenparker** [elixir-lang/ecto#629]
I have a field whose value must be generated by the DB at insertion time by calling a Postgres function. I have defined the column as `extern_id varchar(10) NOT NULL DEFAULT next_extern_id()` I would like the application to read the value of this field, however.

I have tried both `:read_after_write` and `:autogenerate` on my field definitions but unfortunately they still try to pass an explicitly null value for this column. Is there a way to specify this field should not be part of any INSERT or UPDATE statement, but should be part of a RETURNING clause?

**Comment by josevalim** [comment]
`:read_after_writes` only reads the column back after writes, it still does not change the value sent. To avoid sending values, you can define a callback that removes the changes from the changeset:

    before_insert Ecto.Changeset, :delete_change, [:extern_id]
    before_update Ecto.Changeset, :delete_change, [:extern_id]

This way the value will never be sent to the database and, with read_after_writes, the proper one will be read back.

**Comment by citizenparker** [comment]
@josevalim Thanks, I didn't think of that. What does the recent deprecation of `:read_after_writes` mean for this? Is it safe to assume that if it every truly goes away, I'll have some other means of accomplishing this kind of behavior in Ecto?

**Comment by josevalim** [comment]
It is very likely we can't really deprecate it... so it will stay. I do want to push though towards autogenerate in the next release though.
