### ISSUE TITLE
Editing a previously-compiled module that uses @derive generates a warning

### ISSUE THREAD

**Issue by citizenparker** [elixir-lang/ecto#632]
When I initially add something like `@derive {Phoenix.Param, key: :name}` to an Ecto model and compile, I get no warning and everything is fine. However, any subsequent edits to that file (regardless of whether they change the schema or protocol derivation) generate a warning like `nofile:1: warning: redefining module Phoenix.Param.TestParams.Dog`

https://github.com/citizenparker/test_params/blob/master/web/models/dog.ex reproduces this issue with a fresh out-of-the-box Phoenix / Ecto application.

**Comment by josevalim** [comment]
Thank you so much for giving an application that reproduces the issue, it makes fixing the bug a thousand times easier!
