### ISSUE TITLE
Adapter support for Decimal module?

### ISSUE THREAD

**Issue by jazzyb** [elixir-lang/ecto#634]
One of the integration tests in type.exs relies on adapters supporting the Decimal module.  How important is it that adapters support that module?  And if it is optional, can the assertions for Decimal be moved to a separate test (for tagging and exclusion)?

The test in question:  https://github.com/elixir-lang/ecto/blob/master/integration_test/cases/type.exs#L13

**Comment by josevalim** [comment]
@jazzyb I would advise you to depend on Decimal and add Decimal support to sqlite3 (unless it doesn't support Decimal for some reason). If for some reason you can't or don't want to do that, then we can tag it.

**Comment by jazzyb** [comment]
I'll see how difficult it would be to depend on Decimal.  I'm sure it can be done.  Thanks.
