### ISSUE TITLE
Tag Migrations Relying on Modification and Removal of Columns

### ISSUE THREAD

**Issue by jazzyb** [elixir-lang/ecto#638]
https://github.com/elixir-lang/ecto/blob/master/integration_test/support/migration.exs#L76-L81

SQLite cannot alter or drop columns on tables.  Would it be possible to tag the `modify` and `remove` lines in such a way that they are not run, e.g.:

```elixir
    alter table(:users) do
      if can_alter_column?, do: modify :name, :text
      add :custom_id, :uuid
      if can_drop_column?, do: remove :to_be_removed
      timestamps
    end
```

or Is there some way to tag tests relying on the above migration in such a way that the migration is never run?

I haven't looked too deeply into this yet, so I wanted to open this issue to discuss it.

**Comment by josevalim** [comment]
@jazzyb We should probably move those to a separate test. We were trying to optimize by using the migrations themselves as tests but we should probably move them apart.

**Comment by jazzyb** [comment]
I will work on separating these.  I might not be able to get to it until this weekend.

**Comment by josevalim** [comment]
@jazzyb there is no need to rush. I believe you are the only who needs it anyway. :)

**Comment by josevalim** [comment]
Btw, once SQlite3 tests are passing, feel free to send a pull request to update the table in the README. :) Thank you for working on it!

**Comment by jazzyb** [comment]
Thanks for all your help.  I'll send you a PR once the integration tests are working.
