### ISSUE TITLE
Implement Inspect protocol for Ecto types

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ecto#641]
Specifically the DateTime types and UUID.

**Comment by josevalim** [comment]
There is no UUID struct. :)

**Comment by tony612** [comment]
What's the format should we adopt for Date(Time)? Just call `to_string` or there's a better format for it?

**Comment by ericmj** [comment]
I would prefer ISO8601 over to_string, we also need to wrap it in the struct name, like this: `#Ecto.DateTime<2015-06-12T22:32:00.123456Z>`.

**Comment by trevorriles** [comment]
As @josevalim pointed out, `Ecto.UUID` is a string and not a struct so I *think* we are stuck with the string types `inspect/2` implementation unless we change `Ecto.UUID` module to use a struct.

Please correct me if I'm wrong :)

**Comment by williamgueiros** [comment]
Only to link

https://github.com/elixir-lang/ecto/issues/613
