### ISSUE TITLE
Force insert/update options for Repo

### ISSUE THREAD

**Issue by liveforeverx** [elixir-lang/ecto#652]
Support for force insert/update options in Repo.insert
'INSERT ... ON DUPLICATE KEY UPDATE'

Example can be something like it:

```elixir
Repo.insert(Model, if_exists: :update | :ignore | :error) # => default to error

Repo.update(Model, if_not_exists: :error | :insert | :ignore) # => default to error
```

**Comment by ericmj** [comment]
It should be performed on `Repo.insert` because all databases do it on insert and we need to make sure with the upcoming postgresql syntax, mongodb's upsert as well as mysql.

**Comment by jazzyb** [comment]
SQLite does not have built-in syntax like this for "upsert".  According to [this stackoverflow thread](http://stackoverflow.com/questions/418898/sqlite-upsert-not-insert-or-replace/4330694#4330694) I may be able to emulate the functionality, but I don't know how difficult a generic solution would be.

I'll need to spend some time thinking about it.

**Comment by jazzyb** [comment]
On the SQLite front:  `if_exists: :ignore` can be implemented very easily, but there is no clear solution for implementing `if_exists: :update`.  If the feature is added, I recommend separate integration tests with the `:update` test tagged so my tests can ignore it.

**Comment by mobileoverlord** [comment]
Upsert is available in MSSQL.

**Comment by josevalim** [comment]
Ok, let's support this. If the adapter does not support a given option, it is easy to raise. No need to emulate.

**Comment by gjaldon** [comment]
@josevalim I'd like to take this on, if that's ok.

**Comment by josevalim** [comment]
Go ahead please!

**Comment by gjaldon** [comment]
I'm on this!

**Comment by gjaldon** [comment]
@josevalim @ericmj what to do for upsert in Postgres? Been searching for a reliable solution for upsert prior to PG 9.5(which has UPSERT support). Haven't found one yet. 

Should I just implement for the new UPSERT sytnax? It will fail for PG's pre-9.5. Is there a way to check for PG version within ecto or should we just document that upsert with Postgres adapter will only work for 9.5?

**Comment by gjaldon** [comment]
@josevalim @ericmj thinking to just raise when using PG adapter, for now. Created another issue to keep track of upsert for PG when 9.5 is released. Let me know if I should approach it differently.

**Comment by ericmj** [comment]
Implement the new syntax and document that it will only work on 9.5.

**Comment by gjaldon** [comment]
Ok will do that instead. :)

**Comment by josevalim** [comment]
Closing in favor of #746.
