### ISSUE TITLE
Repo.insert_all

### ISSUE THREAD

**Issue by liveforeverx** [elixir-lang/ecto#653]
Support for batch write of more data.

Make it sense to have it, like delete_all, update_all?

**Comment by ericmj** [comment]
The mongo driver will soon have support for this, postgrex does not support it yet. Does the mysql driver support it?

**Comment by liveforeverx** [comment]
Not yet, but we started to work on support for it.

**Comment by liveforeverx** [comment]
We have researched, and found only one possibility to make batching with files(LOAD LOCAL DATA) in MySQL, which is not more typesave. We haven't found nothing, what can be helpfull in MySQL for it.

Only if doing something like this for prepared query:

```
String.duplicate("(? ?)", 100)
```

Do Postgres have some better support for the task?

**Comment by josevalim** [comment]
I don't like insert_all because `update_all` and `delete_all` does not run callbacks, so some may expect `insert_all` does not either. Maybe we should just allow a list to be given to insert? Not sure how it would in case of a list of changesets...

**Comment by liveforeverx** [comment]
Sometimes, it is better to insert/update/delete many values and run consistent check only once after, for all changes?

**Comment by josevalim** [comment]
I am closing this because we are certainly not going to tackle this before 1.0. :)
