### ISSUE TITLE
[MySQL] - Assert that full concurrency is allowed during the DDL

### ISSUE THREAD

**Issue by laurocaetano** [elixir-lang/ecto#656]
The [Online DDL documentation](https://dev.mysql.com/doc/refman/5.6/en/innodb-create-index-overview.html) says that MySQL 5.6+ supports concurrency on DDL. Although no syntax change is required in the `CREATE INDEX` or `DROP INDEX` commands, it's possible to assert that the concurrency is allowed using `LOCK=NONE`.

We could add this assertion on the MySQL adapter. @josevalim what do you think?

Thanks @morgo for pointing it on this commit https://github.com/laurocaetano/ecto/commit/0d807e27b65c235b7779b8d8945b2a5adfbdf383#commitcomment-11634210

**Comment by josevalim** [comment]
Yes, let's do this!
