### ISSUE TITLE
Update documentation for UUID Primary Keys

### ISSUE THREAD

**Issue by tzveeJ** [elixir-lang/ecto#658]
I'm really struggling with the UUID primary keys in ecto with postgres. Could you update the documentation to make it clearer how to set this up for other folks? At the moment I have this (but something is broken):

```
defmodule Conversation do
  use Ecto.Model
  schema "conversation" do
    field :subject, :string
  end
end

defmodule Bucket.Repo.Migrations.CreateReleaseTables do
  use Ecto.Migration
  def up do
    # Note: user must be set up as SUPERUSER to do this. Maybe this shouldn't be in a migration.
    execute "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\""
    create table(:conversation, primary_key: false) do
      add :id, :uuid, primary_key: true, default: fragment("uuid_generate_v1mc()")
      add :subject, :string
    end
  end
  def down do
    execute "DROP EXTENSION IF EXISTS \"uuid-ossp\""
    drop table(:conversation)
  end
end
```

But on inserting into the database, I get a crash with log:

[error] #PID<0.257.0> running AppRouter terminated
Server: 10.0.2.2:4000 (http)
Request: POST /api/conversations
** (exit) an exception was raised:
    ** (ArgumentError) cannot load `<<94, 131, 69, 222, 16, 163, 17, 229, 138, 42, 195, 116, 166, 123, 31, 73>>` as type :integer
        (ecto) lib/ecto/type.ex:345: Ecto.Type.load!/2
        (ecto) lib/ecto/repo/model.ex:148: anonymous fn/3 in Ecto.Repo.Model.do_load/3
        (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/repo/model.ex:146: Ecto.Repo.Model.do_load/3
        (ecto) lib/ecto/repo/model.ex:141: anonymous fn/4 in Ecto.Repo.Model.load_into_changeset/3
        (elixir) lib/access.ex:113: Access.Map.get_and_update!/3
        (ecto) lib/ecto/repo/model.ex:141: Ecto.Repo.Model.load_into_changeset/3
        (ecto) lib/ecto/repo/model.ex:34: anonymous fn/8 in Ecto.Repo.Model.insert/4

**Comment by tzveeJ** [comment]
Darn, just found an answer. I just had to add this in the Conversation model and it worked. Could still be worth updating the documentation.

@primary_key {:id, Ecto.UUID, read_after_writes: true}

**Comment by josevalim** [comment]
@tzveeJ that's it. I will improve the docs for those in upcoming versions. Thank you!

**Comment by mrwade** [comment]
In case anyone else comes across the same issue as I did, you also have to make sure the `@primary_key` declaration is above your `schema` declaration in your model.
