### ISSUE TITLE
Passing Postgres backend pid to Repo.log

### ISSUE THREAD

**Issue by MSch** [elixir-lang/ecto#667]
Opening a separate issue to discuss https://github.com/elixir-lang/ecto/pull/665#issuecomment-111852900 /cc @fishcakez 

With #665 I wanted to register the Ecto/Postgrex processes $somewhere so I can look up the mapping between Erlang pid and Postgres backend OS pid, so that I can add it as metadata when logging in `Repo.log/2`.

But if the process isn't in a transaction there isn't a way to find out which Ecto/Postgrex processes are actually handling the query, since nothing is in the pdict.

What about adding `worker_pid` to `Ecto.LogEntry`? What about both `worker_pid` and `connection_pid`?

Then I would "just" use an ETS table where I store the mappings which I update in `after_connect` and a process that monitors the connections and clears the mappings when the processes die.

What about having a `metadata` map where I can put in the Postgres pid in `after_connect` and which is present in `Ecto.LogEntry`? That would be a very specific solution to my specific problem. But then IMO having the Postgres backend pid in the Ecto logs would be helpful for everyone using Ecto with Postgres and has no performance impact except that one query when connecting (and passing around the data).

To make that more attractive: MySQL and MSSQL also have connection ids that can be retrieved with a query :)

**Comment by josevalim** [comment]
Let's start with worker_pid and connection_pid for now. We can discuss the PG pid once we move to a new pool and support after_connect.

**Comment by fishcakez** [comment]
Why is the `worker_pid` useful? I think the `connection_pid` and `connection_module` should be added to `Ecto.LogEntry`.

**Comment by josevalim** [comment]
I was thinking that, if we support after_connect, it will be invoked from the worker and, if you need to store something somewhere, it would be on the worker. I guess though it doesn't matter because the whole point would be to abstract the storing of metadata from the worker so you don't need to access it anyway.

**Comment by fishcakez** [comment]
Ah ok. I have slight concern there could be confusion over a worker having multiple connections over its lifetime.

**Comment by MSch** [comment]
> Why is the worker_pid useful?

I wasn't sure which pid to use, but thought it'd be easier to let `Repo.log` know about the worker pid than about the connection pid. (And then associate a worker pid with a postgres backend in `after_connect)

> I have slight concern there could be confusion over a worker having multiple connections over its lifetime.

If mapping postgres backend to worker pid it certainly would help to have a `after_disconnect` as well to remove the mapping.

> We can discuss the PG pid once we move to a new pool and support after_connect.

:+1: looking forward to it

**Comment by josevalim** [comment]
@MSch we are ready for this too. Because the worker may not always exist, let's store only the `connection_pid`.

**Comment by MSch** [comment]
@josevalim @fishcakez Thinking about how to best implement this. My thoughts so far are to add the public API to `Ecto.Adapters.Pool` so it's not cluttering up `Repo`:

* Add a `checkout` function, that given a Repo checks out a worker. It uses the Poolboy Pool callback module to call `Worker.checkout` with `:manual`.
* Add a `checkin` function, that does `Worker.checkin` and `:poolboy.checkin` using the callback module
* Add a `give_away` function similar to `:ets.give_away` to transfer the worker from one process to another. There also needs to be a corresponding function for the child to "receive" the worker.
* I'd also like a way to set a `heir` - again like in ETS - so that the worker can be passed back with a corresponding message if the process that got it via `give_away` crashes.
* Extend the `transaction` function to not check in the worker if it's in `:manual` mode.

The rationale for `give_away` and `heir` is that right now we've got two GenServers that need a reserved connection to prevent deadlocks as described above. Since one GenServer is a bottleneck we've made it run the SQL operation asynchronous in a child process so that it can continue to serve others during that time. (Until it can't then it blocks on the child `Task`.) So my thoughts are to make the parent process spawn its child worker, give it the Ecto worker using `give_away` and get it back using the `heir` message if its child crashes.

**Comment by josevalim** [comment]
@MSch i am closing this now that we have after_connect. Please check what are the missing pieces for you to implement this and let us know.

**Comment by MSch** [comment]
Pinging everyone about this, we're currently upgrading to Ecto 1.1 and our simple workaround where we looked up the OS to BEAM pid association when printing the `Ecto.LogEntry` now fails, because the BEAM pid is already sometimes dead by the time we print the log (this didn't happen previously)

I still think this is a valuable feature, and nowadays Ecto already comes with its own supervisor end ETS tables, so adding support for the OS<->BEAM pid mapping to Ecto wouldn't be a quantum leap in complexity, like it was here https://github.com/elixir-lang/ecto/pull/774#issuecomment-120731484

Thoughts?

**Comment by josevalim** [comment]
@MSch dies postgrex have this information? If so, can we store it in the connection and return as part of the postgrex result?

**Comment by MSch** [comment]
@josevalim I recently learned that the postgres protocol sends that info to the client after the handshake

**Comment by fishcakez** [comment]
Postgrex stores this information in its state under backend_key.

**Comment by josevalim** [comment]
@MSch should we then just find a way to retrieve this? Or always add it to Postgrex.Result?

**Comment by fishcakez** [comment]
@MSch can you explain the change in behaviour? Or this because postgrex is closeing the connection itself, whereas before ecto would have to close it in some error cases?

**Comment by MSch** [comment]
@josevalim I think conceptually it's better if it isn't a part of `Postgrex.Result`, but just stored in `Ecto.Adapters.Postgres.Connection`/`Ecto.Adapters.SQL` and then added to the `Ecto.LogEntry` in `query`.

@fishcakez I think that's is it yes, but I haven't investigated, just saw that our test case where we force a timeout failed in 1.1 because the `connection_pid` is already dead by the time `Repo.log` gets called

**Comment by fishcakez** [comment]
If `connection_pid` remains in `2.0` it will be somewhat broken for @msch because connection pids will get re-used and so the wrong information might be displayed. I think we should remove it and look at adding a `connection_id` or similar that uniquely identifies a postgres backend_key (or equivalent).

**Comment by MSch** [comment]
:+1: `connection_id`. For Postgres the OS pid (one half of what makes up `backend_key`) is IMO perfect. That's something that can also be printed to the Postgres log, is used in Postgres' internal admin/stats views, etc. (MySQL has the `CONNECTION_ID` function.)

When you have a plan of action that needs implementing, let me know.

**Comment by fishcakez** [comment]
OK great, I forgot to mention the important bit that `connection_pid` is very awkward with `db_connection` because it breaks the abstraction of pools/single connections being opaque.
