### ISSUE TITLE
[mysql] tiny int, which are booleans in schema, should be converted to boolean

### ISSUE THREAD

**Issue by liveforeverx** [elixir-lang/ecto#679]
This change will support to use tiny ints as integers ( related issue: xerions/mariaex#63 ).

**Comment by liveforeverx** [comment]
Seems, like it working, the tests are passing at least with mariaex 0.3.0, I'll check implementation.

**Comment by josevalim** [comment]
Apparently we already check it: https://github.com/elixir-lang/ecto/blob/master/lib/ecto/type.ex#L363-L364

Nothing to do here. :)
