### ISSUE TITLE
Can't get JSON extension to work

### ISSUE THREAD

**Issue by fbjork** [elixir-lang/ecto#682]
Hi,

I added the `extensions` line to the Repo config in `dev.exs` to enable the JSON extension:

```elixir
config :feed_service, FeedService.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "feed_service_dev",
  size: 10, # The amount of database connections in the pool
  extensions: [{Postgrex.Extensions.JSON, library: Poison}]
```

But when I add a `:jsonb` field to my schema:

```elixir
  schema "feeds" do
    field :name, :string
    field :filters, :jsonb
    timestamps
  end
```

I get the following error:

```elixir
== Compilation error on file web/models/feed.ex ==
** (ArgumentError) invalid or unknown type :jsonb for field :filters
    lib/ecto/schema.ex:831: Ecto.Schema.check_type!/3
    lib/ecto/schema.ex:665: Ecto.Schema.__field__/5
    web/models/feed.ex:6: (module)
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
```

Any ideas what I'm doing wrong?

**Comment by josevalim** [comment]
You need to tell Ecto how to work with your data type too. However, it is probably just easier for you to use Ecto master, which supports a `:map` type that will serialize to jsonb in databases like postgres.

**Comment by fbjork** [comment]
@josevalim ok thanks. Do you have an example of how to tell Ecto to work with the data type?

**Comment by josevalim** [comment]
There is information here: http://gabrieljaldon.com/articles/using-json-type-in-ecto.html

If you use Ecto master though, you don't need any of that.

**Comment by fbjork** [comment]
Got it, thanks. Ok, last newbie question, how do I use dependencies via git?

**Comment by josevalim** [comment]
Add to `deps` in your `mix.exs`: `{:ecto, github: "elixir-lang/ecto"}`

**Comment by fbjork** [comment]
@josevalim great, that worked! 

Do I need to make any more changes in the model or controller for `:map` fields to work properly?

I get a 422 when I try the following:

```
[info] POST /feeds
[info] Processing by FeedService.FeedController.create/2
  Parameters: %{"feed" => %{"filters" => [%{"foo_id" => ["123"]}], "name" => "Test", "user_id" => "123123"}, "format" => "json"}
  Pipelines: [:api]
[info] Sent 422 in 20ms
```

Here's the model:

```elixir
defmodule FeedService.Feed do
  use FeedService.Web, :model

  schema "feeds" do
    field :user_id, :string
    field :name, :string
    field :filters, :map
    timestamps
  end

  @required_fields ~w(user_id name)
  @optional_fields ~w(filters)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If `params` are nil, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end
```

and the controller action:

```elixir
  def create(conn, %{"feed" => feed_params}) do
    changeset = Feed.changeset(%Feed{}, feed_params)

    if changeset.valid? do
      feed = Repo.insert!(changeset)
      render(conn, "show.json", feed: feed)
    else
      conn
      |> put_status(:unprocessable_entity)
      |> render(FeedService.ChangesetView, "error.json", changeset: changeset)
    end
  end
```

**Comment by josevalim** [comment]
Which errors are you getting? Hard to know without seeing what is rendered back.

**Comment by fbjork** [comment]
Oops, forgot the JSON payload:

```json
{
  "errors": {
    "filters": [
      "is invalid"
    ]
  }
}
```

**Comment by josevalim** [comment]
@fbjork if you look at the parameters... you can see filters are being inside a list. is that what you really want?

**Comment by fbjork** [comment]
Omg, sorry about that! Thanks so much.

Unrelated question, I'm trying to deploy this to Heroku, but I get this error during the deploy:

```
       == Compilation error on file lib/feed_service/repo.ex ==
       ** (ArgumentError) missing :adapter configuration in config :feed_service, FeedService.Repo
       lib/ecto/repo/config.ex:13: Ecto.Repo.Config.parse/2
       lib/feed_service/repo.ex:2: (module)
       (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
```

The DATABASE_URL is set and exported using this build pack: https://github.com/HashNuke/heroku-buildpack-elixir. Any ideas?

**Comment by josevalim** [comment]
As the error says, you still need adapter: Ecto.Adapter.Postgres in your
config files." For the repository

On Thursday, June 25, 2015, Fredrik Björk <notifications@github.com> wrote:

> Omg, sorry about that! Thanks so much.
>
> Unrelated question, I'm trying to deploy this to Heroku, but I get this
> error during the deploy:
>
>        == Compilation error on file lib/feed_service/repo.ex ==
>        ** (ArgumentError) missing :adapter configuration in config :feed_service, FeedService.Repo
>        lib/ecto/repo/config.ex:13: Ecto.Repo.Config.parse/2
>        lib/feed_service/repo.ex:2: (module)
>        (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
>
> The DATABASE_URL is set and exported using this build pack:
> https://github.com/HashNuke/heroku-buildpack-elixir. Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/682#issuecomment-115023924>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by fbjork** [comment]
That did the trick, forgot the adapter part and just had url in there. This feels just like 2005 when I was learning Rails:)

Now I'm getting an error when I push it to Heroku, but it works locally. 

```
Unchecked dependencies for environment prod:
* ecto (git://github.com/elixir-lang/ecto.git)
  the dependency is not available, run `mix deps.get`
** (Mix) Can't continue due to errors on dependencies
```


Here's the mix.exs file:
```
  defp deps do
    [{:phoenix, "~> 0.13.1"},
     {:phoenix_ecto, "~> 0.5"},
     {:ecto, github: "elixir-lang/ecto", override: true},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 1.0"},
     {:phoenix_live_reload, "~> 0.4", only: :dev},
     {:cowboy, "~> 1.0"}]
  end
```

**Comment by fbjork** [comment]
@josevalim never mind. This is an issue with github Mix dependencies and Deis (http://deis.io), a Heroku clone. Thanks again for all the help!

**Comment by benbonnet** [comment]
[reading here](https://robots.thoughtbot.com/why-ecto-s-way-of-storing-embedded-lists-of-maps-makes-querying-hard), what's the pratical difference and the use cases between using `{:array, :map}`, or `:map` only ?
