### ISSUE TITLE
Adapter support for maps

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#684]
For @elixir-lang/ecto-adapters ,

* [x] MySQL
* [x] Postgres
* [x] MSSQL
* [x] SQLite3
* [x] Mongo

Here is the relevant commit: https://github.com/elixir-lang/ecto/commit/6f6b300273d352a326c040f66b7c849ace7e5474. If your database supports JSON natively, copy Postgres changes. If it doesn't, copy the MySQL ones (which encodes them when emitting the query).

**Comment by mobileoverlord** [comment]
Added to Tds 
livehelpnow/tds_ecto#80b5a270aad761d54e4d9d1650e79f5311e44930

**Comment by jazzyb** [comment]
Running `mix deps.get` in sqlite_ecto doesn't install the Poison dependency, so when I run the map integration test, I get the error "module Poison is not available".  I suspect this has something to do with the dependency being "optional".  Do I need to specify the Poison dependency in my own mix.exs file?  I would rather not explicitly specify the library in sqlite_ecto in case, e.g., Ecto switches to a different JSON library in the future.

**Comment by josevalim** [comment]
@jazzyb you can add it as a test dependency then. `{:poison, only: :test}` will hopefully be enough.

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/0851183228d4f670aeabf061d27c2f2b2f20ca3c
