### ISSUE TITLE
Handle (or raise) keyword fragments

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#685]
For @elixir-lang/ecto-adapters,

* [x] MySQL
* [x] Postgres
* [x] MSSQL
* [x] SQLite3
* [x] Mongo

Due to the upcoming NoSQL support, we now allow keyword fragments. We recommend SQL databases to simply raise in case such structure is given.

Here is the relevant commit (just copy MySQL or PostgreSQL): https://github.com/elixir-lang/ecto/commit/ea32def0136b333f994a03c0c9346affc0bd22d7

**Comment by mobileoverlord** [comment]
Added to Tds
livehelpnow/tds_ecto@6ce3d5186baa09d29f9861abbfdb5728abfbaf45
livehelpnow/tds_ecto@9135aef1012d2a12ed2e462263d5a828b49170a0

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/1bebaed4767298c2e2e5beb9753144f82531e573
