### ISSUE TITLE
Support left in right

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#686]
For @elixir-lang/ecto-adapters,

* [x] MySQL
* [x] Postgres
* [x] MSSQL
* [x] SQLite3
* [x] Mongo

We now allow `left in right` expressions in Ecto. Here is the relevant commit: https://github.com/elixir-lang/ecto/commit/1d7a4a4c3136391da7fb79c9a75ca88dd13f1306

Note that most databases define "IN" as a shortcut to "= ANY" and that's the one we decided to use. However some SQL databases, like SQLite3, may not allow such, in this case, we advise using "IN" itself.

NoSQL databases will need to check support case-by-case. In particular, note that `1 in p.tags` is now allowed (if you support the array type).

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/43d43ba2f4d27a363fcc251a2372a7e2e0a6da77

SQLite doesn't have an `ANY` keyword so `IN` was the way to go.

**Comment by michalmuskala** [comment]
Added to Monngo michalmuskala/mongo_ecto@50444de

**Comment by mobileoverlord** [comment]
I don't believe that MSSQL supports this until ANY in 2016
https://msdn.microsoft.com/en-us/library/ms189526.aspx
I tried running this through sql management using IN, but I don't think that supports it.

**Comment by josevalim** [comment]
> I tried running this through sql management using IN

Running what exactly? Wouldn't the following be valid SQL:

    frpm p in Post, where: p.id in fragment("SELECT 1")

If so, that's all you need to support. You don't need to worry about the array syntax as there are no arrays in MSSQL.

**Comment by mobileoverlord** [comment]
I added this to tds_ecto
livehelpnow/tds_ecto@8bc0106af010c10287c7234bcf46eb09b6f4693b
livehelpnow/tds_ecto@5377ada3554836971fdcb8ea0c09b8d4b0bf70d4

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
