### ISSUE TITLE
Documentation out of date on hexdocs.pm

### ISSUE THREAD

**Issue by maxnordlund** [elixir-lang/ecto#687]
The docs for [Ecto.Repo](http://hexdocs.pm/ecto/Ecto.Repo.html) dosen't include [`update_all`](https://github.com/elixir-lang/ecto/blob/v0.12.0/lib/ecto/repo.ex#L330-L351), and perhaps more things are missing.

Please push a fresh new version :bow:

**Comment by josevalim** [comment]
@maxnordlund just that one is missing. it is a bug in the docs generator which has been fixed but we are waiting for other fixes to ship a new version. Sorry! :fearful:
