### ISSUE TITLE
crash with '?' in password, function_clause in Regex, :match?

### ISSUE THREAD

**Issue by umatomba** [elixir-lang/ecto#688]
using the url short format with '?' in password, like this:

```
config :app, App.Repo,
  adapter: Ecto.Adapters.MySQL,
  url: "ecto://test:test?@127.0.0.1:3306/app"
```

i got:

```
** (Mix) Could not start application app: exited in: App.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, TpossCcs.Repo, {:EXIT, {:function_clause, [{Regex, :match?, [~r/^\/([^\/])+$/, nil], [file: 'lib/regex.ex', line: 158]}, {Ecto.Repo.Config, :parse_url, 1, [file: 'lib/ecto/repo/config.ex', line: 61]}, {Ecto.Repo.Config, :config, 2, [file: 'lib/ecto/repo/config.ex', line: 31]}, {App.Repo, :start_link, 0, [file: 'lib/app/models.ex', line: 2]}, {:supervisor, :do_start_child, 2, [file: 'supervisor.erl', line: 314]}, {:supervisor, :start_children, 3, [file: 'supervisor.erl', line: 297]}, {:supervisor, :init_children, 2, [file: 'supervisor.erl', line: 263]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 306]}]}}}}}
            (app) lib/app.ex:17: App.start/2
            (kernel) application_master.erl:272: :application_master.start_it_old/4
```

if my definition format is correct, this point must be tested for all possible characters

**Comment by josevalim** [comment]
@umatomba No, that is not valid. The error message could be better though.

**Comment by umatomba** [comment]
@josevalim should the userinfo part be automatically encoded |> URI.parse |> decoded in ecto?

**Comment by umatomba** [comment]
and i dont understand why in erlang:
```
http_uri:encode("http://dc:d?c@dc.com/So me").
"http%3A%2F%2Fdc%3Ad%3Fc%40dc.com%2FSo%20me"
```

but in elixir only the part after @ will be encoded
``
URI.encode("http://dc:d?c@dc.com/So me")        
"http://dc:d?c@dc.com/So%20me"
```
Is it a bug in URI.encode?

I think http_uri:decode(http_uri:encode("http://dc:d?c@dc.com")).
could be a good solution

**Comment by hwinkel** [comment]
please keep in mind that URL encoded paswords have own rules for encoding due to the fact of URL special characters. We should decide either

a) to NOT allow special characters from a operational perspective
b) use another schema to configure parameters in a K/V fashion and not URL
c) train all operations people to further encode the passwords with the URL encoded escaping.

Background:

https://app.zencoder.com/docs/guides/getting-started/special-characters-in-usernames-and-passwords

**Comment by josevalim** [comment]
@umatomba not a bug in URL encoded. check URL.encode and URL.encode_www_form.

**Comment by liveforeverx** [comment]
@josevalim I personally see only one problem:

```elixir
Ecto.Repo.Config.parse_url "ecto://test:test%3F@127.0.0.1:3306/app"
[username: "test", password: "test%3F", database: "app", hostname: "127.0.0.1",
 port: 3306]
```

At the moment it is impossible to have `?` in password nor as percent-encoded with URIs in ecto. I think, this is a primary bug? Or it is desired behaviour?

**Comment by hwinkel** [comment]
specially a password with a ":" would raise problems here. I would not like to train OPS staff to learn URL encoding rules to encode a already complex password to fit URL encoding rules. If this abstracted away in some form i.e. connection string -> URL encoded string. K7V Fields -> URL encoded string I'm happy and fine. May this can happen in the Application Config above the ecto library ?!?!

**Comment by liveforeverx** [comment]
@hwinkel : My preferable solution is, If percent-encoded will works, than we can modify our configuration parser, that it takes configuration `db = test:test?@127.0.0.1:3306/app` transforms to `ecto://test:test%3F@127.0.0.1:3306/app`

Than, we do not need to train(not the c)), not need to use other schema(not the b)), if we can forbid `:` from operational perspective, because it is separator between username and password. If it not an option, than b) is our way.

**Comment by hwinkel** [comment]
@liveforeverx You are right but then the thing is not a URL anymore, because it not follows  URL encoding and it is just  string. BTW: anybody knows how DB tool interpreted this "connection string" usually. Do they assume this connection string is an URL and therefore needs to be encoded as URL?

**Comment by umatomba** [comment]
@liveforeverx the url_encoding or decoding is not our task. I think it must be on ecto side

**Comment by liveforeverx** [comment]
@umatomba do not agree, the ecto should encode URI string, as RFC specifies it. If we want to allow not to encode, we need to do it on our side.

**Comment by hwinkel** [comment]
@liveforeverx if I would look from untrained OPS perspective I would assume something is wrong as the string is changing. In this context I would say have K/V app config wich transforms to a (hidden) URL encoded string. Or use the URL just for the resource and encode db.user db.pass separately like:

db.db = mysql://127.0.0.1:3306/app
db.user = user
db.pass = test?

This also tells the db repo driver in use?

**Comment by umatomba** [comment]
@hwinkel yes

**Comment by liveforeverx** [comment]
@hwinkel : String changes are not seen by OPS, as they do not see the erlang term configuration at all. (Only, if they will try to check running erlang term configuration).

**Comment by hwinkel** [comment]
@liveforeverx let leave our OPE 3rd Level Support question alone for now, I think this has may no interest for the ex community. I'm fine with a encoded URL string in the ex context as long it will be not exposed in this form to the higher level application which uses the ecto library,

**Comment by umatomba** [comment]
the solution that we take is to combine the possibility of short host, port and database definition using URI format and username and password options. it's look like:

```
url: "ecto://localhost:3306/ecto_simple",
username: "user", 
password: "pass_][?/<~#`!@$%^&*()+=}|;:',>{_word"
```
