### ISSUE TITLE
MySQL Test Assertion Redundancy

### ISSUE THREAD

**Issue by mobileoverlord** [elixir-lang/ecto#689]
I noticed some redundant test assertions and didn't know if they should be removed or if it was supposed to be checking for some additional case.

https://github.com/elixir-lang/ecto/blob/master/test/ecto/adapters/mysql_test.exs#L388-L392
https://github.com/elixir-lang/ecto/blob/master/test/ecto/adapters/mysql_test.exs#L396-L400

**Comment by laurocaetano** [comment]
@mobileoverlord they should be removed. My mistake :sweat_smile:
