### ISSUE TITLE
Raise for selectors without models

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#694]
For @elixir-lang/ecto-adapters,

* [x] MySQL
* [x] Postgres
* [x] MSSQL
* [x] SQLite3

Here is the commit: https://github.com/elixir-lang/ecto/commit/a70d018c63c59a6c1e1caf1fcefbb16c0baf3ca9. Just copy the changes done to MySQL or PostgreSQL.

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/53544cebf0f65207674b47e7a530129bd0acec5c

**Comment by mobileoverlord** [comment]
MSSQL: livehelpnow/tds_ecto@c1c01eddf3ce30eff9af13d54acb0486989d1707
