### ISSUE TITLE
Missing requirement when running Ecto 0.12.0 integration tests

### ISSUE THREAD

**Issue by jazzyb** [elixir-lang/ecto#696]
I'm trying to run the latest integration tests from Ecto 0.12.0 in hex.pm for sqlite_ecto, and I get the following error:

```
** (Code.LoadError) could not load /vagrant/sqlite_ecto/deps/ecto/test/support/file_helpers.exs
```

The file `ecto/integration_test/cases/migrator.exs` requires a file in the `ecto/test` directory which is not shipped with the ecto hex package.  I had previously been using the github repo as a dependency so I did not notice this earlier.

I've been running the integration tests from the `deps` directory [like so](https://github.com/jazzyb/sqlite_ecto/blob/ecto-0.12.0/integration/sqlite/all_test.exs).  Is there a better way to run the integration tests, or is this a mistake in the hex package?

**Comment by josevalim** [comment]
It is a bug. We need to move file_helpers into `integration_test/support/file_helpers.exs` and change the relevant require_file. Can you please send a PR? :)

**Comment by jazzyb** [comment]
Will do.
