### ISSUE TITLE
Support for Database Level Integrity Features

### ISSUE THREAD

**Issue by zmoshansky** [elixir-lang/ecto#697]
Perhaps related to #671.

Is there support/openness to utilizing more of the capabilities of the underlying database? #690 would allow for some more of this manually, but it would be nice to have the generators apply these, especially for #183. 

My motivation is that getting integrity constraints right is "$:*ing tough, and the kind folks behind Postgres, Maria, MYSQL, etc have put enormous effort into making it correct and optimize performance. 

- **FOREIGN KEY CONSTRAINTS**
- ~~NOT NULL~~
- CHECK
- CASCADES (Useful for Many 2 Many)
- UNIQUE
- etc.

ex.) 
```
 schema "comments" do
    belongs_to :post, Post, null: false, delete: :cascade 
    timestamps
  end
```
SQL
```
"CREATE TABLE IF NOT EXISTS comments(
      post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
      inserted_at TIMESTAMP NOT NULL,
      updated_at TIMESTAMP NOT NULL)"
```

**Comment by josevalim** [comment]
Yes, definitely.

We already support unique and references in migration (foreign key constraints), no?

I am ok with supporting cascade and check depending on how well it is supported across databases. Can you please do a survey and investigate the syntax for those for Sqlite3, MySQL, PostgreSQL and MSSQL?

Also, those shouldn't be in the schema, but in the migration.

**Comment by zmoshansky** [comment]
@josevalim They do work, I just didn't find them :embarrassed: I'll create a new issue with results of syntax and summarizing scope for check/cascade. The following is for posterity.

**REFERENCES**
(@zmoshansky RTFM closer), references work just great! Turns out the phoenix generator does not use them though. ex.) ```phoenix.gen.model Cat cat owner:belongs_to name:string```

In Migration Do:
```
add :owner_id, references(:owners)
```

**UNIQUE**
For future readers, UNIQUE CONSTRAINT doesn't exist ATM, however an INDEX that is UNIQUE across multiple columns can be created, and they are only very subtly different. [Differences](https://msdn.microsoft.com/en-us/library/ms187019.aspx).

In Migration Do:
```
    create index(:cat, [:name, :owner_id], unique: true)
```

**Comment by wutania** [comment]
@zmoshansky / @josevalim i care a lot about database level integrity, and would like to open an issue on creating unique constraint (and potentially contributing to it) on the migration level, how do i go about that? 🙏🏼 Thanks!

**Comment by josevalim** [comment]
Hi @wutania! 👋  unique coinstraints and similar are already supported in the `ecto_sql` project (note this issue is 8 years old)
