### ISSUE TITLE
Support options on table creation

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#701]
For @elixir-lang/ecto-adapters,

* [x] MySQL
* [x] Postgres
* [x] MSSQL
* [x] SQLite3

Here is the pull request: https://github.com/elixir-lang/ecto/pull/690

Keep in mind that, once you support this in your driver, it will no longer work with earlier Ecto versions as it is expecting the options field.

**Comment by jazzyb** [comment]
I'm a little confused about this change being incompatible with earlier Ecto versions.  If I access the `options` in the `Table` struct with `Map.get(table, :options)` instead of `table.options`, won't that maintain backwards compatibility?

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/bff9c2823722f1f9a8e5e84a80bae7a36db20c3c

**Comment by josevalim** [comment]
> I'm a little confused about this change being incompatible with earlier Ecto versions. If I access the options in the Table struct with Map.get(table, :options) instead of table.options, won't that maintain backwards compatibility?

Yes, that would maintain. Just remember to remove the Map.get later. :)

**Comment by josevalim** [comment]
@jazzyb btw, #704 is definitely introducing backwards incompatible changes. So you may as well do a new release and start introducing backwards incompatible changes now. :) My plan is to get the new update in and then release 0.13.0 not long after.

**Comment by jazzyb** [comment]
@josevalim Elixir question:

> Just remember to remove the Map.get later

I was under the impression that structs, like Table, were just syntactic sugar around Maps and that I could use them interchangeably.  I take it by your response that I shouldn't do that :)  In what situation should one use `table.options` instead of `Map.get(table, :options)` and why?

**Comment by josevalim** [comment]
@jazzyb because you want your code to be as assertive as possible. If you expect options to be there, then use the syntax that asserts it is there. More info here: http://blog.plataformatec.com.br/2014/09/writing-assertive-code-with-elixir/ :)

**Comment by jazzyb** [comment]
Understood.  Thanks for the pointer.  Good article by the way.

**Comment by mobileoverlord** [comment]
All done for MSSQL :smile: 
livehelpnow/tds_ecto@f4c4428fa91a9ddd429c09f978c3b957677438dd
