### ISSUE TITLE
CHECK and CASCADE support

### ISSUE THREAD

**Issue by zmoshansky** [elixir-lang/ecto#703]
The SQL syntax for CHECK and CASCADE across databases (Following from #697).

**CHECK**
MySQL:
LOL, doesn't support CHECK, just ignores it [src](https://bugs.mysql.com/bug.php?id=3464)

SQL Server / Oracle / MS Access / Postgres / SQLLITE : [src](http://www.w3schools.com/sql/sql_check.asp) [src2](http://zetcode.com/db/sqlite/constraints/)
```
CREATE TABLE Persons
(P_Id int NOT NULL CHECK (P_Id>0),
```

or with complex statements 
SQL Server / Oracle / MS Access / Postgres / [SQLLITE](https://www.sqlite.org/lang_createtable.html#ckconst)
```
CREATE TABLE Persons
(P_Id int NOT NULL,
City varchar(255),
CONSTRAINT chk_Person CHECK (P_Id>0 AND City='Sandnes'))
```

**ON [UPDATE, DELETE]**
Options:
 1. SET NULL
 2. CASCADE
 3. SET DEFAULT
 4. NO ACTION (This is what happens by default)

Postgres / SQL Server / SQLLITE / MySQL [src] (https://www.sqlite.org/foreignkeys.html#fk_actions) [src] (https://dev.mysql.com/doc/refman/5.6/en/create-table-foreign-keys.html) [src] (http://www.postgresql.org/docs/8.2/static/ddl-constraints.html)
```
CREATE TABLE cats
(....,
owner_id INTEGER REFERENCES owners(id) ON DELETE [OPTION],)
```

*note* CASCADE ON UPDATE isn't often (ever**) needed if using surrogate keys, which Ecto does by default if I'm not mistaken. 
** if surrogate keys are immutable then they never update :) , which in most applications they will be treated so

**Comment by josevalim** [comment]
We can support a `:on_delete` option in `references/1` in migration which can have three values: `nothing` (do nothing), `nilify_all` (SET NULL) or `delete_all` (CASCADE). Similar to what have been described in #655. @hubertlepicki would you like to tackle this one too? :D

**Comment by josevalim** [comment]
Thanks @zmoshansky for all the research. That's very appreciated! <3

**Comment by hubertlepicki** [comment]
sure, @josevalim but not today. With all the exciting Elixir stuff going on I forgot I need to do some paid work. ;) Can probably add that tomorrow (Saturday) morning.

**Comment by josevalim** [comment]
No problem!

**Comment by hubertlepicki** [comment]
@josevalim `:nothing` should be default, right?

**Comment by josevalim** [comment]
Yes. Which means we don't need to even generate anything. You should get back to work though. :)

**Comment by hubertlepicki** [comment]
I have an hour until my US client wakes up. Maybe that will be enough!

**Comment by hubertlepicki** [comment]
@josevalim and `nilify_all` is a typo and in fact should be `nullify_all` or that's intentional?

**Comment by josevalim** [comment]
It is `nilify_all` according to #655!

**Comment by aerosol** [comment]
Hey, sorry for digging out the old ticket -- was the idea of supporting `CHECK` constraints abandoned?

**Comment by josevalim** [comment]
It is on master and it will be part of 2.0. You can check the CHANGELOG for more info. :)

**Comment by aerosol** [comment]
Whoa, lovely, thanks!

**Comment by davidkuhta** [comment]
From CHANGELOG:
> [Postgres] Add migration and changeset support for PostgreSQL check constraints. Example: `create constraint(:products, "positive_price", check: "price > 0")` and `check_constraint(changeset, :price, name: :positive_price, message: "must be greater than zero")`

And for others who may have searched github issues before the docs...
[Ecto.Changeset.check_constraint/3](https://hexdocs.pm/ecto/Ecto.Changeset.html#check_constraint/3)
[Ecto.Migration.constraint/3](https://hexdocs.pm/ecto/Ecto.Migration.html#constraint/3)
