### ISSUE TITLE
Introduce new Repo.update_all syntax

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#704]
I have discussed this a bit more with @ericmj and @michalmuskala, trying to consider upcoming requirements. Here is the new update syntax:

    Repo.update_all Post,
      set: [title: "foo"],
      inc: [changes: 1]

`update_all` will no longer be a macro instead it will receive a series of operations to perform on the data. For more complex cases, one should be able to write:

    from p in Post,
      update: [set: [changes: fragment("? + 1", p.changes)]]

In fact, that's what `Repo.update_all` will internally compile to. We will also use this opportunity to change `Repo.update_all`  and `Repo.delete_all` return results to be `{count, entries}`, paving the way for #460.

**Comment by michalmuskala** [comment]
Just a heads-up: Mongo won't be able to return entries from `update_all` or `delete_all`. I would propose to allow the return value to be `{count, nil}` in that case.

**Comment by josevalim** [comment]
Ah, yes. The default for now will be `nil` until we support returning. MySQL can't support it too.
