### ISSUE TITLE
Support on_delete on table references

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#707]
For @elixir-lang/ecto-adapters,

* [x] MySQL
* [x] Postgres
* [x] MSSQL
* [x] SQLite3

Here is the pull request: #705

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/8d2ae42fd775cc9868d3b8bdb4b84941242f3b22

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by jazzyb** [comment]
@elixir-lang/ecto-adapters 

FYI:  This commit: https://github.com/elixir-lang/ecto/commit/d0ecba8956da5efbffa4b7bf333401a8f905213f, changed the new `:nillify_all` option to `:nilify_all`.

**Comment by mobileoverlord** [comment]
MSSQL: livehelpnow/tds_ecto@adbfadc1d7f8df781b2341047aecfab5603800a6

**Comment by josevalim** [comment]
Good catch @jazzyb!
