### ISSUE TITLE
`references` does not work with `alter` `table` at least with PostgreSQL

### ISSUE THREAD

**Issue by sumerman** [elixir-lang/ecto#722]
OS: OS X 10.10.3
Ecto: v0.13.0
PostgreSQL: 9.4.4

Currently migration like:
```
    alter table(:sale_deployments) do
      modify :sale_id, references(:sales, on_delete: :delete_all, type: :serial)
    end
```
will generate following SQL statement:
` ALTER TABLE "sale_deployments" ALTER COLUMN "sale_id" TYPE integer REFERENCES "sales"("id") ON DELETE CASCADE` 
wich is wrong according to pg's docs: http://www.postgresql.org/docs/9.1/static/sql-altertable.html

Correct expression should be something like: `ALTER TABLE "sale_deployments" ADD CONSTRAINT "sale_deployments_FK"  FOREIGN KEY (sale_id) REFERENCES "sales" ("id") ON DELETE CASCADE;` Another way to deal with it may be to prohibit usage of `references ` inside `alter` block and suggest using plaing SQL.

**Comment by chvanikoff** [comment]
I guess `execute/1` should be currently used for such queries

**Comment by sumerman** [comment]
That's exactly what I'm doing. But I spent some time before figured out what was happening. So compile-time check or at very least a line in the documentation should mention this.

**Comment by josevalim** [comment]
It is a bug, we should figure out how to support it. :)

**Comment by sumerman** [comment]
Another related bug.

I got:
```
argument error
    :erlang.atom_to_binary(%Ecto.Migration.Reference{column: :id, on_delete: :delete_all, table: :platforms, type: :serial}, :utf8)
    (ecto) lib/ecto/adapters/mysql/connection.ex:601: Ecto.Adapters.MySQL.Connection.ecto_to_db/1
    (ecto) lib/ecto/adapters/mysql/connection.ex:540: Ecto.Adapters.MySQL.Connection.column_type/2
    (ecto) lib/ecto/adapters/mysql/connection.ex:487: Ecto.Adapters.MySQL.Connection.column_change/1
    (elixir) lib/enum.ex:1008: anonymous fn/4 in Enum.map_join/3
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1007: Enum.map_join/3
    (ecto) lib/ecto/adapters/mysql/connection.ex:444: Ecto.Adapters.MySQL.Connection.execute_ddl/1
```

```
    alter table(:sale_deployments) do
      add :platform_id, references(:platforms, on_delete: :delete_all, type: :serial)
    end
```
After trying my migrations on MySQL

**Comment by josevalim** [comment]
Yes, and once we do this we should add tests for those features in the integration suite.

**Comment by josevalim** [comment]
@hubertlepicki this is also in the adapter area you are a bit familiar with. Would you like to give this a try? :)

**Comment by hubertlepicki** [comment]
sure happy to have a look. You know, @josevalim, one day I'll actually need to use this library

**Comment by hubertlepicki** [comment]
This is not yet done (so not a PR yet) but the implementation for postgres will be along those lines: https://github.com/amberbit/ecto/commit/c0d059319e1187757af5a39e6734edac0f8f6a5f

I need to work further on MySQL and test if it actually works agains real database backend, not just concatinating and comparing strings ;)

**Comment by josevalim** [comment]
Awesome! Integration tests can be added here: https://github.com/elixir-lang/ecto/blob/master/integration_test/sql/migration.exs

**Comment by rodolfospalenza** [comment]
Hello, this problem is fixed? Ecto return this error when I try modify table with references.

```
18:32:30.821 [info]  alter table videos
** (Postgrex.Error) ERROR (duplicate_object): constraint "videos_user_id_fkey" for relation "videos" already exists
```

- ecto 2.0.6
- postgres (PostgreSQL) 9.6.1

```elixir
def up do
  alter table(:videos) do
    modify :user_id, references(:users, on_delete: :delete_all)
  end
end
```

Thanks.

**Comment by OvermindDL1** [comment]
@rodolfospalenza Might be better to ask on the mailing list or forums, however I'm thinking that your `:user_id` column already has a foreign reference on it and you are trying to change the `:on_delete` functionality?  If so this might sound worth opening a new PR for.  Should show the prior migration for the same table though too.

**Comment by rodolfospalenza** [comment]
Hello @OvermindDL1,

Thank for your answer. I will try IRC elixir channel.
The migration to create videos table is this.

```elixir
defmodule Rumbl.Repo.Migrations.CreateVideo do
  use Ecto.Migration

  def change do
    create table(:videos) do
      add :url, :string
      add :title, :string
      add :description, :text
      add :user_id, references(:users, on_delete: :nothing)

      timestamps()
    end
    create index(:videos, [:user_id])

  end
end
```

**Comment by rodolfospalenza** [comment]
To fix this problem I used execute to remove fkey.

```elixir
defmodule Rumbl.Repo.Migrations.ChangeUserIdFromVideos do
  use Ecto.Migration

  def up do
    execute "ALTER TABLE videos DROP CONSTRAINT videos_user_id_fkey"

    alter table(:videos) do
      modify :user_id, references(:users, on_delete: :delete_all)
    end
  end

  def down do
    execute "ALTER TABLE videos DROP CONSTRAINT videos_user_id_fkey"

    alter table(:videos) do
      modify :user_id, references(:users, on_delete: :nothing)
    end
  end
end
```

And works! (:

**Comment by mhanberg** [comment]
The current solution to [this](https://github.com/elixir-ecto/ecto/issues/722#issuecomment-266236264) is similar, but you don't need to drop to raw SQL. The above example can be written as

```elixir
defmodule Rumbl.Repo.Migrations.ChangeUserIdFromVideos do
  use Ecto.Migration

  def up do
    drop constraint("videos", "videos_user_id_fkey")

    alter table(:videos) do
      modify :user_id, references(:users, on_delete: :delete_all)
    end
  end

  def down do
    drop constraint("videos", "videos_user_id_fkey")

    alter table(:videos) do
      modify :user_id, references(:users, on_delete: :nothing)
    end
  end
end
```

**Comment by markquezada** [comment]
> ```elixir
> defmodule Rumbl.Repo.Migrations.ChangeUserIdFromVideos do
>   use Ecto.Migration
> 
>   def up do
>     drop constraint("videos", "videos_user_id_fkey")
> 
>     alter table(:videos) do
>       modify :user_id, references(:users, on_delete: :delete_all)
>     end
>   end
> 
>   def down do
>     drop constraint("videos", "videos_user_id_fkey")
> 
>     alter table(:videos) do
>       modify :user_id, references(:users, on_delete: :nothing)
>     end
>   end
> end
> ```

For posterity, it appears this can now be reduced to:

```elixir
defmodule Rumbl.Repo.Migrations.ChangeUserIdFromVideos do
  use Ecto.Migration

  def change do
    alter table(:videos) do
      modify :user_id, references(:users, on_delete: :delete_all),
        from: references(:users, on_delete: :nothing)
    end
  end
end
```
