### ISSUE TITLE
Require new pool tests

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#732]
For @elixir-lang/ecto-adapters,

* [x] MySQL
* [x] Postgres
* [x] MSSQL
* [x] SQLite3
* [x] Mongo

Just do this: https://github.com/elixir-lang/ecto/commit/16f27f64c5ca2480568fad10e40c26522ffbf793#diff-2c5b8dbebddda6206ddb2951ce5b1bc8R9

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/9e9bf3d4bd4efa402db3d1157504a81f02008d74

**Comment by mobileoverlord** [comment]
MSSQL: livehelpnow/tds_ecto@9b19c28e6683591480f70d98ecb220076706897f

**Comment by michalmuskala** [comment]
Mongo: https://github.com/michalmuskala/mongodb_ecto/commit/7f44dbb8cbfd4b00fc99bee7958153c37dec9f23

Also I had to change how I handle pools after changes in Mongo.Adapters.SQL, I noticed one thing that worries me. In `start_link` we are using pool that can be provided in options, but then in `query` always the default one is used. Wouldn't this cause issues?
`start_link`: https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/sql.ex#L355-363
`query`: https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/sql.ex#L180

**Comment by josevalim** [comment]
Michal, btw, you don't need to use the Ecto.Adapters.SQL.Sandbox pool. Just
keep size as 1.

It won't cause issues because the idea is that if you are using custom
pools, you will override __pool__ too.



*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by michalmuskala** [comment]
I reverted the change with the sandbox pool https://github.com/michalmuskala/mongodb_ecto/commit/ac58a6589e39a86a6466e91e26cb8319d497f964

**Comment by josevalim** [comment]
@michalmuskala I also see that you are defining a new pool just because of those tests, I will try to change it so it is not required.

**Comment by josevalim** [comment]
@michalmuskala i have pushed a commit to master so you no longer need to define a pool only for those tests, they all use test repo now!

**Comment by michalmuskala** [comment]
I updated the tests: https://github.com/michalmuskala/mongodb_ecto/commit/f6da6ffd72e5fe50a904d0ecee0a8749fef21060
