### ISSUE TITLE
Ecto should provide the time it spends on processing data returned from the DB

### ISSUE THREAD

**Issue by alco** [elixir-lang/ecto#734]
Let's say we have a function `F` that executes some Ecto queries and does other things. We're collecting metrics to see how much time is spent executing `F` and how much of that time is spent executing each individual type of query against the DB.

So far `LogEntry` returns only part of the total time Ecto spends executing a query. While investigating a single query I have found out that in the following code in `Ecto.Adapters.SQL.all` the post-processing of the fetched data takes up a noticeable amount of time:

```elixir
  def all(repo, sql, query, params, id_types, opts) do
    %{rows: rows} = query(repo, sql, params, opts)      # ~75% of total time
    fields = extract_fields(query.select.fields, query.sources)
    Enum.map(rows, &process_row(&1, fields, id_types))  #  ~25% of total time
  end
```

It would be very nice to have those approx. 25% returned in `LogEntry` too, either as part of `query_time` or as an additional field (I'm not sure which would be best).

**Comment by josevalim** [comment]
This is tricky. Is there a way we can do this cleanly?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by alco** [comment]
OK, let's think about what would the goals be for an application trying to measure the amount of time it spends performing DB-related tasks. We'd be interested in answering the following questions:

  1. For any given application-level task, how much time of that task is taken up by doing DB operations (any kind of operations: querying, inserting, updating, deleting)?
 
  2. What part of the total DB-time is actually taken up by the DB itself and what part of it is Postgrex/Ecto's processing? This is useful for discovering DB bottlenecks.

The first half of 2 is already provided to us by the `queue_time + query_time` combo. We could actually achieve both goals by having a wrapper module `TimedRepo` that would have the following:

```elixir
defmodule TimedRepo do
  def all(query, options \\ []) do
    {time, result} = :timer.tc(fn ->
      ActualRepo.all(query, options)
    end)
    Logger.info "Time spent doing X = #{time} us"
    # or call a function store_time(:all, time)
    result
  end

  # and so on for every other Repo function
end
```

Then we will have the total time the `app -> (Ecto -> Postgrex -> ... -> DB -> Ecto) -> app` pipeline takes up. And by subtracting the query times we get in `Ecto.Repo.log/1` from that we can get the time it takes Ecto to perform additional processing of the raw DB data.

An obvious problem with this approach is that the code for `TimedRepo` needs to be duplicated in every app that wants to do this kind of measurements, probably in an incomplete or buggy way.

Could Ecto provide this out of the box by wrapping all of its `Ecto.Repo` functions in `:timer.tc` and then calling an additional callback similar to how `Ecto.Repo.log/1` works now? I think a more suitable name for the current `log` function would be `log_sql` (since it only has access to stringified SQL of the query) and the extra function could be called just `log(query, AnotherLogEntry?)` where `query` is an instance of `Ecto.Query`?

**Comment by josevalim** [comment]
I wouldn't like to call log twice. For example, for things like insert/update/delete, that would include time in callback which I don't think we should?

For `all/2`, maybe we instead use `query/5` which returns the log entry and augment it with the processing information? I would simply include the processing time in the query time (since postgrex does processing too which is already included in the query time). We just need to clearly document what the query time is.

**Comment by alco** [comment]
Are you really proposing to throw away `Ecto.Query` calls from our codebase and write SQL queries as strings instead? :)

**Comment by josevalim** [comment]
Not at all. I am proposing we should change the internal implementation of `all/2` so it calls the internal `query/5`, returning us the log entry, allowing us to add the time taken for processing. Or, even better, allow functions to be passed to query/5, invoking it inside :timer.tc, allowing us to measure everything at once.

**Comment by alco** [comment]
That could turn out more complicated though. Ecto can also call repo functions like here https://github.com/elixir-lang/ecto/blob/d9fc592e13b218cfd94551dd2b944299ccc54a00/lib/ecto/repo/preloader.ex#L96. It will need to thread the returned processing info back to the original repo call. Is that what you're thinking?

Also, if we do it like that, will `Repo.log/1` be deprecated?

**Comment by josevalim** [comment]
This will be solved with #768.

**Comment by phanimahesh** [comment]
@josevalim What happened to this one? Looks like #768 was rolled back according to your comment in #773.

**Comment by josevalim** [comment]
Yes, it did not get in. There is a lot of complexity tied to it.
