### ISSUE TITLE
Implement upsert for PG once Postgres 9.5 is released

### ISSUE THREAD

**Issue by gjaldon** [elixir-lang/ecto#735]
For reference: 
- https://github.com/elixir-lang/ecto/issues/652
- www.craigkerstiens.com/2015/05/08/upsert-lands-in-postgres-9.5/

**Comment by theduke** [comment]
Why was this closed?

Is it already implemented?

**Comment by gjaldon** [comment]
@theduke it's not yet implemented but the feature should still be welcome
