### ISSUE TITLE
validate_length function returns `{"should be at most %{count} characters", 65536}` on errors

### ISSUE THREAD

**Issue by sylane** [elixir-lang/ecto#738]
Is it the expected behavior ?

If so how to I format `"should be at most 65536 characters"` out of it without knowing the placeholder ?

**Comment by josevalim** [comment]
The placeholder is always %{count} so you can replace it. Please look for
similar previous discussions on the tracker.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
