### ISSUE TITLE
Source is not respected in Preloading

### ISSUE THREAD

**Issue by reset** [elixir-lang/ecto#739]
I have an application which leverages Postgres schemas to "shard" data. There are X number of replicas contained within schemas named something like "account_1", "account_2", etc.

In Ecto 10 the ability to query on source was added by specifying `{"account_1.accounts", MyApp.Account}` in a query instead of just `MyApp.Account`. The source is annotated in any records found and it works very nicely when updating or deleting those records.

Preloading associations is a problem, however. The source tagged in the metadata of a record is not used when attempting to preload an association, so I see an error like this:

```
** (Postgrex.Error) ERROR (undefined_table): relation "relationships" does not exist
```

Where I would instead expect the relation to be "account_1.relationships".

Thank you so much for the support. Ecto is really kicking ass for us at Undead Labs!

**Comment by gjaldon** [comment]
@josevalim I'd like to work on this, if available :)

**Comment by josevalim** [comment]
Excellent. This change can be done in a couple steps: 

1. Let's change how `from` is stored in queries to instead of being a tuple with two elements `{"source", Model}` to become `{"search_path", "source", Model}`. For now, let's just make `search_path` be nil everywhere.

2. Next, let's change Ecto.Queryable and Ecto.Query.Builder.from to accept a tuple with three elements as queryable/argument

3. Then we should change SQL adapters to make use of this new information

4. The next two steps is to make use of this on models and preload but we can cross that bridge when we get there. :)

**Comment by josevalim** [comment]
@gjaldon ping!

**Comment by gjaldon** [comment]
@josevalim sorry for the delay! I'm on this now :)

**Comment by josevalim** [comment]
@reset we have a new way to tackle this issue in master.

The idea is that you can now set a prefix that applies to the whole query. There is no official function for setting it but it is just a matter of:

    %{query | prefix: "my_custom_prefix"}

Once you do so, the query source (from), the joins, all models and preloads will be tagged with such prefix, affecting all operations.

**Comment by reset** [comment]
@josevalim got it. So I should assign the key/value on the query struct instead of setting it in this way:

```elixir
from(a in {"shard_1.table", __MODULE__}, where: a.id == ^id)
```

**Comment by josevalim** [comment]
@reset yes! the goal is that you write the queries normally and set the prefix later on:

    query = from(a in __MODULE__, where: a.id == ^id)
    %{query | prefix: "shard_1"}

Btw, where are you keeping the current shard? Process dictionary?

**Comment by reset** [comment]
@josevalim perfect, I understand clearly.

The shard is determined by hashing/modding a particular value. You just run a function to determine which shard something is on by passing it a value. Example:

```elixir
iex> account_id = 68867870355890246
iex> Shard.for(account_id)
70
```

And this function looks like this:

```elixir
defmodule Shard do
  use Bitwise
  @max_size 128

  def for(value) do
    __MODULE__.for(value, @max_size)
  end

  def for(value, divisor) do
    (value &&& (divisor - 1))
  end
end
```

**Comment by reset** [comment]
@josevalim I bumped our applications to use Ecto 0.14.1 and all of these changes are working well. Thank you so much for the continued support!

**Comment by josevalim** [comment]
Glad to hear! I will remove the old code from Ecto now.
