### ISSUE TITLE
has_many association scope query

### ISSUE THREAD

**Issue by foxnewsnetwork** [elixir-lang/ecto#749]
So in Rails, we had
```ruby
has_many :posts,
  -> { where deleted_at: nil }
```
Which exposed a way to add scopes onto has_many (or even has_one) associations. This was particularly useful when constructing complex relationships with models that you were paranoid about deleting.

Can we please implement this feature into Ecto also? Folks like me who got hooked on ActiveRecord years ago need this feature and we need it *badly*. We need it with the sort of obsession and degenerate craving we're ashamed to tell our parents about.

So badly, in fact, I actually looked into how to do it:
Change:
https://github.com/elixir-lang/ecto/blob/master/lib/ecto/association.ex#L258

To:
```elixir
defstruct [:cardinality, :field, :owner, :assoc, :owner_key, :assoc_key, :queryable, :on_delete, :scope]
```

Change:
https://github.com/elixir-lang/ecto/blob/master/lib/ecto/association.ex#L293

To:
```elixir
%__MODULE__{
      field: name,
      cardinality: Keyword.fetch!(opts, :cardinality),
      owner: module,
      assoc: assoc,
      owner_key: ref,
      assoc_key: opts[:foreign_key] || Ecto.Association.association_key(module, ref),
      queryable: queryable,
      on_delete: on_delete,
      scope: opts[:scope]
    }
```

And finally change:
https://github.com/elixir-lang/ecto/blob/master/lib/ecto/association.ex#L322

To:
```elixir
def assoc_query(refl, values) do
    (refl.scope || refl.queryable)
    |> where([x], field(x, ^refl.assoc_key) in ^values)
  end
```

Then, in your model schema `web/models/thread.ex`, you'd be able to do something like:

```elixir
defmodule App.Thread do
...
  schema "threads" do
    has_many :posts, App.Post, foreign_key: :warehouse_id, scope: App.Thread.posts_scope
  end

  def posts_scope do
    from p in App.Post,
      where: is_nil(p.deleted_at) and is_nil(p.marked_offensive_at)
  end
...
end
```

What do you guys think?

This is in reference to this from the user group:

https://groups.google.com/forum/#!topic/elixir-ecto/iTCBgv2ZhxQ

**Comment by josevalim** [comment]
Yes, we already have an oopen issue for it, i will tackle it soon.

**Comment by foxnewsnetwork** [comment]
thanks for the update! (sorry I didn't see the issue)

**Comment by josevalim** [comment]
Please see discussion upcoming #659.
