### ISSUE TITLE
Group by which doesn't aggregate

### ISSUE THREAD

**Issue by houshuang** [elixir-lang/ecto#751]
I don't know if this is relevant at all, but it just struck me that I have come across this a number of times, and maybe it would be relevant. So for example I have a table called design groups, with a key called sig_id. I want to list design groups grouped by SIGs, so intuitively I feel like I want to "group by" sig_id... However, that only works if I use an aggregation function like count. Instead, what I want is

```elixir
sig_id group_name
1      'hi'
1      'hola'
2      'ni hao'
2      'zdrastovoyte'
```

should be

```elixir
%{1=> ["hi", "hola"], 2=> ["ni hao", "zdrastovoyte"]}
```

So far I've done this manually, by first doing the query, and then Enum.group_by etc. But it just struck me that it seems like a common pattern, and I wonder if it fits into Ecto. Or maybe it could be generalized to an external function. (Actually I would love to be able to do nested group_by, first by one key and then by a second key).

**Comment by josevalim** [comment]
Yes, our group by ties in to the database. If you want to group by as you mentioned, then Enum.group_by is the proper alternative. I don't think we should provide such patterns in Ecto yet.
