### ISSUE TITLE
Adding mix ecto.new task

### ISSUE THREAD

**Issue by miwee** [elixir-lang/ecto#752]
The idea is quickstart for a new ecto app. Essentially you give the app name and --database option for selecting database backend (default being PostgreSQL), and it will generate the sample app (as given in examples/sample folder). It need not generate the models, but placeholders for them, with comments.

**Comment by josevalim** [comment]
We already have something that generates a repo or a migration, which allows you to rum them anytime. I don't believe we need much more than that, really. :)
