### ISSUE TITLE
PostgreSQL test failure

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/ecto#756]
I noticed that sometimes when I run PostgreSQL's tests (when running `MIX_ENV=pg mix test`) I get following failure:
```
  1) test storage up (twice in a row) (Ecto.Integration.StorageTest)
     integration_test/pg/storage_test.exs:33
     Assertion with == failed
     code: Postgres.storage_up(correct_params) == :ok
     lhs:  {:error, :already_up}
     rhs:  :ok
     stacktrace:
       integration_test/pg/storage_test.exs:34
```

As I said it's only sometimes and not always, so it seems there's some race condition somewhere. I tried to investigate but I was unable to find anything that might be causing this issue.

**Comment by josevalim** [comment]
Fix coming soon.
