### ISSUE TITLE
Make date/time/datetime use Ecto.*

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#759]

**Comment by tony612** [comment]
I'd like to try this, but I'm not sure what are the date/time/datetime you mentioned. Is there any more clue?

**Comment by josevalim** [comment]
Thanks @tony612! The plan is to make :date the same as Ecto.Date and so on. In order to do that, I believe it is mostly a matter of changing Ecto.Type functions (cast/load/dump) for `:date` and friends to call their counterparts in `Ecto.Date` and so on respectively.

**Comment by tony612** [comment]
@josevalim I'll try to implement this these days and I'll ping you if I have any question :)
