### ISSUE TITLE
Raise ecto query errors in MySQL and Postgres

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#766]
@michalmuskala is doing this in his mongo adapter and we should do the same, otherwise users are stuck with errors like these that do not emit the query:

https://github.com/drewolson/scrivener/blob/master/lib/scrivener.ex#L153

@michalmuskala can you please give us a hand in here and do this change for pg/mysql too?

**Comment by michalmuskala** [comment]
Sure, I'll take a look at this once the embedding is finished.
