### ISSUE TITLE
Ecto, Postgres performance

### ISSUE THREAD

**Issue by zepplock** [elixir-lang/ecto#771]
I have benchmarked ecto/phoenix performance and got very weird results:
https://github.com/zepplock/phoenix-showdown/blob/master/README.md

The whole project is json api, just 1 resource.
Benchmarks are based on https://github.com/mroth/phoenix-showdown

The first table is just Phoenix serializing a static hash (original test).
The results are good, ~10x against Rails.

The second table is Phoenix+Ecto getting data (just 10 rows from a table) from Postgres.
The results are weird, ~50% slower than Rails.

Could somebody try it and explain it.

p.s. I'm very new to Elixir so maybe I did something wrong

**Comment by josevalim** [comment]
That code is running very old Ecto and Phoenix versions. Try upgrading to Phoenix v0.13.1 before (there is a [pull request here](https://github.com/omnibs/phoenix-showdown/commit/acc040cb690bd59a15dd0bd61de1ea64fc3d3c08)) and remember to configure your pool size. You want at least 20 connections for running in production/benchmark environment.

**Comment by josevalim** [comment]
Also, which command are you using to benchmark them? Be sure you are running both Phoenix and Rails in prod environment. We are typically more than 10x faster than Rails.

**Comment by zepplock** [comment]
Hello Jose, thanks for the tips.
I have generated a new Phoenix app using ``mix phoenix.new benchmarker --no-brunch`` and got much better numbers. Default configuration, just logger set to error level. About 4x vs Rails.
Results are here: https://github.com/zepplock/phoenix-showdown/blob/master/README.md

**Comment by josevalim** [comment]
Glad to hear @zepplock! That's better, but we can definitely do more. If you don't mind, can you run some other benchmarks? You will need Ecto master for this, so in your `mix.exs` file:

    {:ecto, github: "elixir-lang/ecto"}

And please try those:

1. Try changing the pool size in production. The default now should be 20. Try moving it down to 10 and up to 30. How does it affect the results? To be clear, to change the size just set in your config:

        size: 30 # or 10

2. We have different pool strategies. Why not try another sojourn with a timeout broker?

        pool: Ecto.Pools.SojournBroker,
        broker: Ecto.Pools.SojournBroker.Timeout,
        size: 20

3. We have different pool strategies. Why not try another sojourn with a codel broker?

        pool: Ecto.Pools.SojournBroker,
        broker: Ecto.Pools.SojournBroker.CoDel,
        size: 20

We will be merging even more performance improvements to master, are you ok if I ping you to try them out too?

**Comment by zepplock** [comment]
Results (2nd table): https://github.com/zepplock/phoenix-showdown/blob/master/README.md

Ran with:
``wrk -t4 -c100 -d30S --timeout 2000 "http://127.0.0.1:4000/stories"``
``MIX_ENV=prod elixir -pa _build/prod/consolidated -S mix phoenix.server``

Code change: https://github.com/zepplock/phoenix-showdown/commit/a4894e67bf362b0242b082223a57e766cdd265e8

Old dependencies:
```
Dependency resolution completed successfully
%{"cowboy": {:hex, :cowboy, "1.0.2"},
  "cowlib": {:hex, :cowlib, "1.0.1"},
  "decimal": {:hex, :decimal, "1.1.0"},
  "ecto": {:hex, :ecto, "0.13.1"},
  "fs": {:hex, :fs, "0.9.2"},
  "phoenix": {:hex, :phoenix, "0.13.1"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "0.5.0"},
  "phoenix_html": {:hex, :phoenix_html, "1.2.1"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "0.4.3"},
  "plug": {:hex, :plug, "0.13.0"},
  "poison": {:hex, :poison, "1.4.0"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "postgrex": {:hex, :postgrex, "0.8.4"},
  "ranch": {:hex, :ranch, "1.1.0"}}
```  

New dependencies:
```
%{"cowboy": {:hex, :cowboy, "1.0.2"},
  "cowlib": {:hex, :cowlib, "1.0.1"},
  "decimal": {:hex, :decimal, "1.1.0"},
  "ecto": {:git, "git://github.com/elixir-lang/ecto.git", "c2e26c7f7e22fd6a3a22ba8d2018746527f8b1c3", []},
  "fs": {:hex, :fs, "0.9.2"},
  "phoenix": {:hex, :phoenix, "0.13.1"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "0.5.0"},
  "phoenix_html": {:hex, :phoenix_html, "1.2.1"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "0.4.3"},
  "plug": {:hex, :plug, "0.13.0"},
  "poison": {:hex, :poison, "1.4.0"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "postgrex": {:hex, :postgrex, "0.9.0"},
  "ranch": {:hex, :ranch, "1.1.0"}}
```

**Comment by josevalim** [comment]
Thank you! Is Ecto master the one shown as `Phoenix13(Ecto)`? Does it mean we are a bit slower than last benchmarks?

**Comment by zepplock** [comment]
Yes, ``Phoenix13(Ecto)`` is the one from git HEAD.

Jose, I think the results are within margin of error. It is done on my MacBookPro and I have Chrome and other things running ;)

I would say that that there's no clear performance degradation here. Maybe just a few percent.

**Comment by zepplock** [comment]
@josevalim I also updated Ecto with various pool sized. No surprises there.
Results are here, last table: https://github.com/zepplock/phoenix-showdown/blob/master/README.md

p.s. is there an elixir/phoenix IRC or Gitter where you usually hang out?

**Comment by josevalim** [comment]
@zepplock we are on #elixir-lang on irc.freenode.net!

**Comment by josevalim** [comment]
I was able to verify that it indeed got slower, we will go back to previous times once new adapter versions are released, thank you!

**Comment by zepplock** [comment]
I also added Play/Scala performance numbers. It's a bit faster than Phoenix/Elixir but was using more CPU at the same client workload

**Comment by josevalim** [comment]
@zepplock those are awesome! this means we can likely push more data to the database? I will try to find out why we are not being able to. When we add query caching, it should help us get closer too.

**Comment by zepplock** [comment]
@josevalim I spent very little time on it and I'm not even sure I'm using Play/Scala right.
There are other considerations, for example, Rails 4 started using prepared statements but I'm not sure if all frameworks in the my tests use them. Also connection pool sizes, logging, etc are all factors.

If it is worth doing, I think we should come up with a few workloads, for example: a) pure JSON API serialization, b) same but with DB, c) same but with some crypto functions (to stress CPU) and then run this on a dedicated box/service every release or even every PR (just like Travis can do). What do you think?

**Comment by josevalim** [comment]
I think this is a good idea. Another option is to test scripts that perform a certain amount of operations and measure it instead of going through HTTP.
