### ISSUE TITLE
Should we run tests for CoDel broker too?

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#772]
@fishcakez Today we run tests only for timeout broker, should we include both brokers in tests? If so, do we need to run both integration and unit tests with both kinds of brokers?

**Comment by fishcakez** [comment]
We should definitely run the unit tests to check it works because we want to be sure the broker's configuration is valid and that custom brokers are supported. I'm not sure we get much value from running the integration tests too.
