### ISSUE TITLE
Decode result sets outside of pool

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#773]
Hello @elixir-lang/ecto-adapters and @liveforeverx.

* [x] Postgres
* [x] MySQL
* [ ] MSSQL
* [ ] SQLite3
* [ ] MongoDB

The pull request #768 introduces two big changes to adapters in Ecto:

1. Now we expect result sets to return a list of lists instead of lists of tuples

2. We now support decoding queries outside of the connection and outside of the pool, this means we will hold the connection for shorter period of times

Changing 1 is straight-forward but cumbersome. Changing 2 is a bit more complex so let's talk about it more.

You will notice that we now require a new function to be implemented by SQL adapters called `decode/2`, this function will receive the result set returned by `query/4` and a mapper function invoked when traversing the result. The idea is that adapters should be able to return a result set without being decoded so we can do it later on **once**, after putting the connection back in the pool.

Here is how the changes for the Postgres adapter look like: https://github.com/elixir-lang/ecto/commit/54429aa4397d41a11e5d00faa677fa2c164dacbf#diff-ee25bf8df5589fbf812f652738bfbdae

In order to support this feature, we did two changes to the Postgres driver:

1. First we moved the response decoding from server to client: https://github.com/ericmj/postgrex/commit/c99653c2e07bcc4030661f9d824836d076fc10d0

2. Then we allow the decoding to be controlled with an option: https://github.com/ericmj/postgrex/commit/2ea75b9e8f51ed79f02597fedda50e532d70a234

If for some reason you can't do client side decoding, you can emulate it (but we don't recommend it), which is what the MySQL adapter does today (we will change it soon™):

https://github.com/elixir-lang/ecto/commit/54429aa4397d41a11e5d00faa677fa2c164dacbf#diff-975ad8a7b1f8e27ac59595bcdbdd0a07R31

If you have any questions, please let me know!

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/ddc7495ea828bb913d004a36476be216a1833088

**Comment by josevalim** [comment]
Folks from other adapters, please hold on those changes. I am running some benchmarks and it seems that the cost of decoding in the client does not really pay off as the connection spends more time copying the data to send to the client. I am investigating to be sure.

**Comment by josevalim** [comment]
It is official, let's rollback those changes. I get more than 10% slow down doing things on the client, things get worse the bigger the dataset.

**Comment by josevalim** [comment]
Sorry @jazzyb, I see you comitted just now :(

**Comment by jazzyb** [comment]
No problem.  Even more activity/contributions for my profile ;)
