### ISSUE TITLE
Table renaming in migrations

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#777]
Hello @elixir-lang/ecto-adapters,

* [x] Postgres
* [x] MySQL
* [x] MSSQL
* [x] SQLite3
* [x] MongoDB

See #775.

**Comment by michalmuskala** [comment]
MongoDB: https://github.com/michalmuskala/mongodb_ecto/commit/067a383e90f8d90da26dc8a07842269bb7f93dee

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/a38cf99260d109a4f4a97b5d916d10ab3c90c54d

**Comment by mobileoverlord** [comment]
MSSQL: livehelpnow/tds_ecto@09896764d79de32eb47cbd13af087ccf88701e6a
