### ISSUE TITLE
Support intervals in query API

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#779]
We need to support [intervals](http://www.postgresql.org/docs/9.1/static/datatype-datetime.html) in the query API.

The tricky part in supporting intervals is to find a common subset of features that would work in all databases. In particular, for the main databases, we need to answer:

1. Are interval values? For example, could we have an interval type that would be interpolated in queries:

        from p in Post, where: p.date > fragment("? + ?", ^Ecto.DateTime.utc, ^%Ecto.Interval{value: 1, range: :days})

    If we do, we need to introduce this new type.

2. How can interval values be interpolated in query? I.e. do we need to have both values as literals or they can be parameters:

        from p in Post, where: p.date > fragment("? + ?", ^Ecto.DateTime.utc, interval(^count, ^range))

  Once we answer this question, we can implement an interval/2 function in queries that may expect either any query expression (if dynamically values are allowed) or literals.

3. Which kind of modifiers are allowed? days? months? seconds? etc.

/cc @chrismccord

**Comment by josevalim** [comment]
I have answers for PG and MySQL.

1. Only postgres supports interval as values.

2. The interval value can be interpolated (for example `INTERVAL ? DAY` in MySQL) but the day bit cannot.

3. year, month, week, day, hour, minute, second, microsecond (milisecond not supported by mysql)

**Comment by josevalim** [comment]
The interpolated value can be int, float or decimal.

**Comment by josevalim** [comment]
I would also like to discuss operations that calculate the interval on a given date or utc.

**Comment by chrismccord** [comment]
Could we support `:millisecond` in the mysql adapter by translating to microsecond?

**Comment by josevalim** [comment]
Yeah, we could. Amended.
