### ISSUE TITLE
ecto.migrate says database does not exist

### ISSUE THREAD

**Issue by mesosteros** [elixir-lang/ecto#781]
I'm working with Windows 8.1 64 bits and Phoenix Framework.
However following the guide (http://www.phoenixframework.org/docs/ecto-models) for Ecto Models hands me this error when I get to ```mix ecto.migrate```.
Steps to recreate:
1. Create new project (```mix phoenix.new ectoTest```).
2. Compile and run (```mix phoenix.server```)
3. Stop the execution after localhost:4000 is served with Ctrl+C.
4. ```mix phoenix.gen.html User users name:string email:string bio:string number_of_pets:integer```
5. Add ```resources "/users", UserController``` to the router.ex file.
6. (this step is not even mentioned in that guide) ```mix ecto.create```
7. ```mix ecto.migrate```

This outputs the following error:

```C:\Users\mesos_000\Desktop\elixir Projects\ectoTest>mix ecto.migrate
** (exit) exited in: GenServer.call(#PID<0.134.0>, {:query, "SELECT count(1) FROM pg_class c\n  JOIN pg_namespace n ON n.oid = c.relnamespace\n WHERE c.relkind IN ('r','v
','m')\n       AND c.relname = 'schema_migrations'\n       AND n.nspname = ANY (current_schemas(false))\n", []}, :infinity)
    ** (EXIT) %Postgrex.Error{message: nil, postgres: %{code: :invalid_catalog_name, file: "src\\backend\\utils\\init\\postinit.c", line: "794", message: "database \"ecto
Test_dev\" does not exist", pg_code: "3D000", routine: "InitPostgres", severity: "FATAL"}}
    (elixir) lib/gen_server.ex:356: GenServer.call/3
    (postgrex) lib/postgrex/connection.ex:87: Postgrex.Connection.query/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:40: Ecto.Adapters.Postgres.Connection.query/4
    (ecto) lib/ecto/adapters/sql.ex:201: Ecto.Adapters.SQL.query/7
    (ecto) lib/ecto/adapters/pool.ex:274: Ecto.Adapters.Pool.do_run/4
    (ecto) lib/ecto/adapters/sql.ex:189: Ecto.Adapters.SQL.query/5
    (ecto) lib/ecto/adapters/sql.ex:164: Ecto.Adapters.SQL.query/4
    (ecto) lib/ecto/adapters/postgres.ex:61: Ecto.Adapters.Postgres.ddl_exists?/3```

However in my pgAdminIII I get the database. I also connected it in the pgAdmin GUI and tried ```ecto.migrate``` again, with no results.

![ectotest](https://cloud.githubusercontent.com/assets/1943233/8671127/746f3836-2a1a-11e5-8112-1a5a1a0a3cc4.jpg)

**Comment by josevalim** [comment]
Yes, you need to run mix ecto.create if you haven't run it previously.

**Comment by mesosteros** [comment]
Yes but I did. And it still hands me down this error.

**Comment by josevalim** [comment]
@mesosteros ok, I will investigate. Btw the guide says right after you need to create the database. :)

**Comment by josevalim** [comment]
Oh wow, I have found the bug. Database names are case insensitive, so if we invoke `CREATE DATABASE FoO`, it is the same as `CREATE DATABASE foo` unless you use quotes. Because your app name had an uppercase char in it, you got the error the database was not found. We have fixed by ensuring we quote the DB name when creating the DB.

**Comment by mesosteros** [comment]
It's always the simple things. :+1: Managed to get through that step now.
