### ISSUE TITLE
Doesn't realize that select fragment and group by fragment are identical

### ISSUE THREAD

**Issue by houshuang** [elixir-lang/ecto#785]
I have the following query:
```elixir
    result = (from t in query, select: [count(t.id), 
      fragment("?->>?", field(t, ^column), ^qid)],
      where: (fragment("length(?->>?)", field(t, ^column), ^qid)) > 0,
      group_by: fragment("?->>?", field(t, ^column), ^qid))
      |> Repo.all
```

It compiles OK, but when executing it, I get the following:

```elixir
** (Postgrex.Error) ERROR (grouping_error): column "r0.response" must appear in the GROUP BY clause or be used in an aggregate function
2015-07-14 22:42:50.903 [debug] SELECT count(r0."id"), r0."response"->>$1 FROM "reflections" AS r0 WHERE (length(r0."response"->>$2) > 0) GROUP BY r0."response"->>$3 ["4", "4", "4"] ERROR query=50.2ms queue=0.1ms
```

I think the problem is that it doesn't realize that r0.response->>$1 is equivalent to r0.response->>$3. If I replace the $1, $2, $3 with the value "4", the query executes without problem in Postgres.

I realize I could replace this entire thing with a pure SQL query, and initially I had that, but currently I let users provide their own query, which sometimes already has a where-clause.

**Comment by josevalim** [comment]
@houshuang question: can you somehow write this using as? In the select:

    fragment("?->>? as my_name", field(t, ^column), ^qid)

And using `my_name` in group_by? Or the opposite?

**Comment by houshuang** [comment]
Brilliant, that worked, thanks so much. I actually tried something similar,
with `fragment("?->>? as my_name", field(t, ^column), ^qid)`, group_by:
f.my_name`, which didn't work because Ecto didn't know about f.my_name, but
using group_by: fragment("my_name") worked great.

Thanks again

On Wed, Jul 15, 2015 at 12:17 AM, José Valim <notifications@github.com>
wrote:

> @houshuang <https://github.com/houshuang> question: can you somehow write
> this using as? In the select:
>
> fragment("?->>? as my_name", field(t, ^column), ^qid)
>
> And using my_name in group_by? Or the opposite?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/785#issuecomment-121294854>.
>



-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by josevalim** [comment]
Excellent. We may make it easier in the future but not right now (because I have no ideas about how to fix it in ecto without supporting aliases in ecto itself).
