### ISSUE TITLE
json array support?

### ISSUE THREAD

**Issue by adamkittelson** [elixir-lang/ecto#790]
I just noticed that the :map type had been added, stored in a jsonb column in Postgres which is awesome, I'm using a number of jsonb columns in my app with a custom Ecto type. I'm able to replace most of these with the new :map type, but I do have a few columns where I'm storing an array of maps in a jsonb column instead of a single map which doesn't work with the new :map type.

I was just wondering if there's anything built-in for that use case (or planned, or any discussion I could catch up on) or if I should keep using my custom type for that case. I'm not quite sure what such a thing would look like with built-in support. :map doesn't quite fit, and {:array, :map} would make it seem like it was using Postgres arrays as opposed to jsonb...

Anyway was just wondering if there'd been any thoughts about that use-case.

Thanks!

**Comment by josevalim** [comment]
Hey @adamkittelson! We are working on embeds many and the plan is to support two containers:

1. array containers: it would use `{:array, :map}`. Do you see by any chance any problem with this approach?

2. map containers: it would use a map as parameter with keys being auto generated binary ids (like Ecto.UUID)

**Comment by adamkittelson** [comment]
Thanks @josevalim! 

The only potential issue I see with `{:array, :map}` is potential confusion with how differently that's represented in postgres with `{:array, :integer}` / `{:array, :string}`, but that's probably not a big deal and nothing documentation can't solve.

There are other things that are valid json that can't be represented with just `:map` and `{:array, :map}` though that I could see wanting to store in a jsonb column. For something like an array of arrays of maps I'm not sure if it would make more sense to allow nesting in the schema definition (i.e. `{:array, {:array, :map}}`) or just draw a line in the sand and provide a generic json type for anything that doesn't work with `:map` / `{:array, :map}`

**Comment by josevalim** [comment]
Ah, definitely. If you want a storage where you can put anything you want then you don't definitely don't want maps but at least you can leverage the fact Postgres will ship with a decoder, so you just really need a custom type.

**Comment by adamkittelson** [comment]
Thanks for answering my questions Jose, sounds good.

**Comment by x-ji** [comment]
@josevalim is the second approach you mentioned, i.e. 

> 2. map containers: it would use a map as parameter with keys being auto generated binary ids (like Ecto.UUID)

eventually implemented? It seems that I still can't use `:map` type if I want to directly store a JSON array without a key attached to it.
