### ISSUE TITLE
Support datetime_add and date_add

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#793]
For @elixir-lang/ecto-adapters,

* [x] PG
* [x] MySQL
* [x] SQLite3
* [x] MSSQL

We have added datetime_add and date_add with intervals to Ecto. Here is the commit: https://github.com/elixir-lang/ecto/commit/df37f43a55006ff1e780b87d717901894613dec6

Your adapter should require the new test file and implement the two functions in case date/time interval operations are supported. Otherwise, it should just raise.

**Comment by jazzyb** [comment]
@josevalim I noticed that the MySQL changes allow microsecond precision in intervals and that the MySQL adapter excludes `:uses_usec` tests.  Is that a mistake?  Should the `:uses_usec` exclusion be removed from `integration_test/mysql/test_helper.exs`, or should two different tags be used for the tests in `integration_test/cases/interval.exs` and `integration_test/cases/repo.exs`?

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/03623a39a1abf3ad2f16099acf3794a0fe0f7057

**Comment by mobileoverlord** [comment]
Had a little restructuring on my connection. Now the intervals are working.
MSSQL:  livehelpnow/tds_ecto@ 9033bc2931cf4ef8388a5deaa7db217ce9657094

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by bbhoss** [comment]
The documented code seems not to work on postgres
```elixir
assert TestRepo.all(from p in Post, where: p.inserted_at >
                             datetime_add(^Ecto.DateTime.utc, -1, "month"))
```
Gives me an argument error
```
** (ArgumentError) argument error
    :erlang.apply(0, :type, [])
    (ecto) lib/ecto/type.ex:230: Ecto.Type.match?/2
    (ecto) lib/ecto/query/builder.ex:259: Ecto.Query.Builder.assert_type!/3
    (ecto) lib/ecto/query/builder.ex:90: Ecto.Query.Builder.escape/5
    (ecto) lib/ecto/query/builder.ex:142: Ecto.Query.Builder.escape/5
    (ecto) lib/ecto/query/builder/filter.ex:16: Ecto.Query.Builder.Filter.build/5
    (ecto) expanding macro: Ecto.Query.where/3
    integration_test/cases/interval.exs:223: Ecto.Integration.IntervalTest."test datetime_add with dynamic"/1
```

**Comment by bbhoss** [comment]
Looks like this was reported in #833
