### ISSUE TITLE
Support query prefixes

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#798]
For @elixir-lang/ecto-adapters,

* [x] PG
* [x] MySQL
* [x] Mongo
* [x] MSSQL
* [x] SQLite3

Query prefixes allow developers to change the schema or the database a query will run on. Here is the relevant commit: https://github.com/elixir-lang/ecto/commit/5ab34242d393f634074315c9982c73f5a1973bac

The prefix can be found in the query itself and should be considered for all operations (all, update_all, delete_all). Note that insert, update and delete now receive an extra argument too, which is the prefix. Here are the test you change and add to test the relevant changes:

https://github.com/elixir-lang/ecto/blob/5ab34242d393f634074315c9982c73f5a1973bac/test/ecto/adapters/postgres_test.exs

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/980038b1967a2555d728002773a24bbe388e6533

**Comment by michalmuskala** [comment]
MongoDB: https://github.com/michalmuskala/mongodb_ecto/commit/7323e46d4f6cc8cb2dec7394783dccf9d75c60ae

**Comment by mobileoverlord** [comment]
MSSQL: livehelpnow/tds_ecto@20abb725d3571562626b0a51cd504ebff6438364
