### ISSUE TITLE
Use new load/dump for custom behaviour

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#809]
For @elixir-lang/ecto-adapters,

* [x] PG
* [x] MySQL
* [x] Mongo
* [x] MSSQL
* [x] SQLite3

We have dropped the `id_types/0` callback in favor of `load/2` and `dump/2` callbacks allowing adapters to handle any custom type cleanly, without pushing the concern to Ecto. Here is an example from MySQL:

https://github.com/elixir-lang/ecto/commit/66ee4a28c401857b04884bc5dc9c60b67a44b637#diff-3288d8519970fae8e5772a616f895463R96

Adapters that need to emulate maps with JSON in binary columns, like MSSQL and SQLite3, will need to add at least the following definition:

```elixir
def load({:embed, _} = type, binary) when is_binary(binary),
  do: super(type, json_library.decode!(binary))
def load(:map, binary) when is_binary(binary),
  do: super(:map, json_library.decode!(binary))
def load(type, value), do: super(type, value)

defp json_library, do: Application.get_env(:ecto, :json_library)
```

You may also use this function to handle other types, like MySQL handles booleans (as it is not supported in the database).

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/e9914d70e61cd7ef62c4fb599d64299d690c5650

**Comment by michalmuskala** [comment]
MongoDB: https://github.com/michalmuskala/mongodb_ecto/commit/7323e46d4f6cc8cb2dec7394783dccf9d75c60ae

**Comment by mobileoverlord** [comment]
MSSQL: livehelpnow/tds_ecto@8ad844c61585c9f76dac9aed0dcb44c67fd2758d

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
