### ISSUE TITLE
Ensure a changeset where action == update and changes == %{} is not stored as change for embeds

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#810]
We need to ensure this happens for embeds_one and it also happens for embeds_many in the case **all** entries in the list match the criteria above.

AFAIK we do this for `embeds_one` but there are no tests. We need to ensure and test both cases.

**Comment by michalmuskala** [comment]
I'm not sure what do you mean by "not storing" them? Skip sending them to the database? Skip adding them to the changes if one uses something like `put_change`? Or something else entirely?

**Comment by josevalim** [comment]
> Skip adding them to the changes if one uses something like put_change?

Skip adding them. If the embeds one is valid, action update and no changes or all in the embeds_many are valid, action update and no changes, there is no reason to store them in the parent as changes.
