### ISSUE TITLE
Create test db from development schema

### ISSUE THREAD

**Issue by bcardarella** [elixir-lang/ecto#814]
Copied from https://github.com/phoenixframework/phoenix/issues/1035

I am migrating a node.js application over to Phoenix. the database already exists. My development migrations are to normalize the schema with many table/column renames. I currently cannot test the application without creating the test db manually from the development db as a template. This is fine for my development machine, but doesn't work within the context of running the application on Travis where that development db doesn't exist at all.

**Comment by bcardarella** [comment]
re: db versions producing conflicting schema files:

Couldn't we output the db version and use this as a constraint on the schema? If the db version is a mismatch for what the schema expects, run migrations as normal? I realize the concept behind an ORM is to allow one to use different dbs but I've already found in reality this to be non-trivial. Especially with the pace that Postgres has had over the past few years, we typically require developers to all be on the same patch version of the database that is being used. Then we'll explicitly install that version on Travis, staging, and production.

**Comment by josevalim** [comment]
@bcardarella storing the DB name and version in the schema file is a great idea. Then we can compare and ask the users what to do before continuing (they can either do it anyway, choose to migrate or abort).

>  I realize the concept behind an ORM is to allow one to use different dbs but I've already found in reality this to be non-trivial.

Agreed. I am not worried about this use case at all for schemas. Once you have a schema then you already choose a DB for your application and I really don't think you should be switching. To me, the advantage of an ORM or something like Ecto is that I can write a tool like Devise that would work on any database. However, in such tools, we are not worried about schema at all so :+1: for having dumped schemas being DB specific.

**Comment by josevalim** [comment]
@bcardarella btw, are you planning to tackle this? Do you have any idea how hard it is to write the dumping code for PostgreSQL and MySQL?

**Comment by bcardarella** [comment]
@josevalim I already started to look into it. Both Postgres & MySql support dumping the db schema without data:

* postgres: `pg_dump -d dbname -s  > schema.sql`
* mysql: `mysqldump -u root -p --no-data dbname > schema.sql`

We could use this to start with. I would suggest just supporting the dump of raw sql rather than exploring a elixir/dsl schema export similar to ActiveRecord.

We could capture the schema export and put it into a data structure:

```elixir
# priv/repo/schema.exs
%{
  "db": "postgresql",
  "version": "9.4.4",
  "schema": """
#{schema}
"""
}
```

**Comment by josevalim** [comment]
@bcardarella that sounds great. I agree we are not going to have a schema export DSL.

Exporting the data as an elixir data structure is interesting. I was originally thinking about dumping it as schema.sql and leaving the DB + VERSION as a comment. What are your thoughts on each format? The upside of being .sql is that you could run it directly, although it is less structured.

**Comment by bcardarella** [comment]
@josevalim :+1: on the comment idea, feels cleaner

I can take a shot at this later in the week

**Comment by josevalim** [comment]
Just a heads up we are planning on releasing Ecto 1.0 in no more than a month. :)

**Comment by bcardarella** [comment]
Thanks for the heads up. I'm going to take a look at this tonight hopefully. I do want to complete the rename_column PR I have out there too.

**Comment by josevalim** [comment]
Hey, just a heads up, we are on schedule to have Ecto 1.0.0 in about 2 weeks. :)

**Comment by josevalim** [comment]
Closing in favor of the PR.
