### ISSUE TITLE
Association examples

### ISSUE THREAD

**Issue by herenowcoder** [elixir-lang/ecto#819]
Hi...

coming back after a couple of versions, I need to say I really miss the fine & clear examples from the readme, esp. on associations & preloading.

I believe associations usage is, say, 1st advanced/ non-trivial topic one is confronted when starting to use Ecto. Now only for newcomers; after a few months of break in hacking my code which uses Ecto (and it works on production already) I need it by myself. Add the fact that API & semantics of preloading changed few times - not that I complain, this is pre-1.0, but! in the past Readme contained excellent up-to-date examples on how to use it.

That was much better than API docs, which are, well, as 'dry' as usual API docs. 

Can you bring it back somewhere?

**Comment by josevalim** [comment]
Everything that was in the readme is now in the Ecto module, which is the
first page of the docs linked in the readme. If you think they could be
improved, please send PRs.



-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by herenowcoder** [comment]
No. I did my homework. It is not there. I wouldn't be raising anything if these docs - including very well written examples which you already had! -  were reasonably findable from the main readme.

**Comment by josevalim** [comment]
Can you find in the old tags which example do you have in mind? It would be really silly to throw good docs away!

**Comment by herenowcoder** [comment]
The commit is 28c08e067351d.

But - my apologies. The docs are certainly there. I continuously mistook Overview page for an Ecto-module page. What I was looking for resides in http://hexdocs.pm/ecto/Ecto.html as you said.

**Comment by josevalim** [comment]
Oops, that page should be the home page. I will fix it.

**Comment by josevalim** [comment]
Fixed in the repo, it will be fixed in the docs with the next release.

**Comment by herenowcoder** [comment]
That's very nice! 
Thanks for fixing. :)
