### ISSUE TITLE
Ensure virtual fields are not stored in embeds

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#826]

**Comment by LostKobrakai** [comment]
It seems virtual fields are persisted for embeds in the current stable version. Is it supposed to be that way?

**Comment by josevalim** [comment]
No, can you plaese open up an issue with a mechanism to reproduce the error? thank you!

**Comment by LostKobrakai** [comment]
Ah, might be because I'm using a map field with: 
```
    prepare_changes(changeset, fn changeset ->
      update_change(changeset, :data, fn changes ->
        changes |> apply_changes() |> Map.from_struct()
      end)
    end)
```
Sorry for the disturbance :)
