### ISSUE TITLE
Deprecation of Repo.insert/2, update, delete in favor of Exception throwing versions

### ISSUE THREAD

**Issue by werbitzky** [elixir-lang/ecto#832]
Shouldn't those methods exist in parallel to each other?

Quote from http://elixir-lang.org/getting-started/try-catch-and-rescue.html

> In practice, however, Elixir developers rarely use the try/rescue construct. For example, many languages would force you to rescue an error when a file cannot be opened successfully. Elixir instead provides a File.read/1 function which returns a tuple containing informations about whether the file was successfully opened:

In my particular case: I would like to use the optimistic lock on a model and in case of an unsuccessful update due to a version conflict, I would like to get the record from the database again, apply the changes and try to update again.

With only an error throwing method however, I would need to use *try/rescue* as a flow control mechanism as I do not want to crash my process because of the `Ecto.StaleModelError`.

**Comment by josevalim** [comment]
We have added the insert/delete/update back. It is very unlikely though that they will handle StaleModelError as such errors can be raised in other situations besides the lock ones (like ID being removed). So you will need to use the try/catch until we come up with a better solution (if there is any).

**Comment by werbitzky** [comment]
Ah, yes! Sorry didn't see that one.

https://github.com/elixir-lang/ecto/commit/96a50fb1e6c08154cc4c3ba1f43fcb7731bc78f7
