### ISSUE TITLE
Support create_if_not_exists and drop_if_exists

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#836]
For @elixir-lang/ecto-adapters,

* [x] MySQL
* [x] PostgreSQL
* [x] MSSQL
* [x] SQLite
* [x] MongoDB

Here is the relevant commit: https://github.com/elixir-lang/ecto/commit/b567992d6836aa53a2ffc5ef203ae2c390c9b439. Just duplicate the changes and unit tests added to MySQL or PostgreSQL. Notice that `ddl_exists` is gone and can be removed.

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/44a4f27006ed77286c1b0858df7b888d5aebb598

**Comment by michalmuskala** [comment]
MongoDB: https://github.com/michalmuskala/mongodb_ecto/commit/3145129243992ebefa239bb0bb43ccc0b14a541d

**Comment by mobileoverlord** [comment]
MSSQL: livehelpnow/tds_ecto@99e92dba120d945e5ddbc562a7caaf3e91d86754
