### ISSUE TITLE
Support rename columns

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#838]
For @elixir-lang/ecto-adapters,

* [x] MySQL
* [x] PostgreSQL
* [x] MSSQL
* [x] SQLite
* [x] MongoDB

Here is the relevant commit: https://github.com/elixir-lang/ecto/commit/1fc57c3b61b38985d78ae459170f25d1628dd95f. Just duplicate the changes and unit tests added to PostgreSQL.

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/ee82c27c363519f607cc4ba01726f1448518251a

**Comment by michalmuskala** [comment]
MongoDB: https://github.com/michalmuskala/mongodb_ecto/commit/3145129243992ebefa239bb0bb43ccc0b14a541d

**Comment by mobileoverlord** [comment]
MSSQL: livehelpnow/tds_ecto@3b530308e29e94a8bce1b11ad061ddde9472fcb2
