### ISSUE TITLE
validate_number does not work with decimal

### ISSUE THREAD

**Issue by jonhkr** [elixir-lang/ecto#841]
I don't know if it was supposed to work but since Ecto implements the decimal type it should.

It fails with negative decimals, eg:
```Elixir
iex(1)> Decimal.new(1) > Decimal.new(-3)
false
```

**Comment by gjaldon** [comment]
@jonhkr this should be fixed in master :)

**Comment by jonhkr** [comment]
Thank you @gjaldon. I'll check it out :smile:
