### ISSUE TITLE
Allow of escaping of ? in fragment

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ecto#847]
Today you can't have ? in a fragment string without it being converted to $N.

**Comment by ctlevi** [comment]
How would '?' need to be escaped in the fragment string?

I have a few tests and a hacky way below using a regex and a double backslash to escape the ?. I added this to the escape method in Ecto.Query.Builder, replacing the ```pieces = String.split(query, "?")```. Is there a better way than using a regex and a replacement?

```elixir
pieces = String.split(query, ~r{(?<!\\)[?]}) 
  |> Enum.map(fn(x) -> String.replace(x, "\\?", "?") end)
```

**Comment by josevalim** [comment]
You can implement the splitting by hand by recurring on the binary. Please give it a try and let me know if you need help. :)

**Comment by syamilmj** [comment]
Came across this today and gave it a try:

```
defmodule Drupal.Query do
  def parse(string, []), do: string

  def parse(<< ??, tail::binary >>, [param | params]) do
    parse("#{param}", tail, params)
  end

  def parse(<< c::binary-size(1), tail::binary >>, params) do
    parse(c, tail, params)
  end

  def parse(head, << ??, tail::binary >>, [param | params]) do
    parse(head <> "#{param}", tail, params)
  end

  def parse(head, << c::binary-size(1), tail::binary >>, params) do
    parse(head <> c, tail, params)
  end

  def parse(string, "", []), do: string

  def parse(_, _, _) do
    raise "Please check your query"
  end
end
```
