### ISSUE TITLE
Unsupported nullable array columns in Ecto?

### ISSUE THREAD

**Issue by stavro** [elixir-lang/ecto#848]
Ecto version 0.14.3
Postgrex version 0.9.1

My schema has a column of type `{:array, :integer}` which, at the database level, supports a `NULL` value.

At the database level there **is** a difference between a `NULL` value and an empty array.  However, it appears as though Ecto does not support `nil` values for (at least) integer array columns.

To set up:

```sql
CREATE TABLE test_array_table (
  id           SERIAL PRIMARY KEY,
  array_column INT []
)

INSERT INTO test_array_table (array_column) VALUES (NULL);
```

Upon loading the previously created row into an Ecto Model, the `NULL` column **silently becomes an empty array**:

```elixir
defmodule TestArrayTable do
  use MyApp.Web, :model

  schema "test_array_table" do
    field :array_column, {:array, :integer}
  end
end

record = Repo.one(TestArrayTable)
#=> %TestArrayTable{__meta__: %Ecto.Schema.Metadata{source: {nil, "test_array_table"}, state: :loaded}, array_column: [], id: 1}
```

And trying to coerce the column into `NULL` results in an error:

```elixir
Repo.update(%TestArrayTable{record | array_column: nil})
```
```
** (Ecto.ChangeError) value `nil` for `TestArrayTable.array_column` in `update` does not match type {:array, :integer}
      (ecto) lib/ecto/query/planner.ex:33: anonymous fn/6 in Ecto.Query.Planner.fields/4
    (stdlib) lists.erl:1261: :lists.foldl/3
      (ecto) lib/ecto/query/planner.ex:21: Ecto.Query.Planner.fields/4
      (ecto) lib/ecto/repo/model.ex:109: anonymous fn/11 in Ecto.Repo.Model.update/4
```

**Comment by josevalim** [comment]
We have added this behaviour quite recently. I think, however, it was misguided. I will revert it and fix this in Ecto.
