### ISSUE TITLE
Ecto configuration table prefix

### ISSUE THREAD

**Issue by liveforeverx** [elixir-lang/ecto#853]
Most database frameworks supports possibility to set global prefix([rails](http://stackoverflow.com/questions/2674191/rails-specify-a-table-prefix-for-mysql) supports ).

Example of using with ecto can be: 

```elixir
config :ecto
  prefix: "test_"
```

```elixir
defmodule User do
   use Ecto.Model

   schema "users" do
     field :name
     field :email
     field :age, :integer
   end
end
```

This will use "test_users" as table name. Best case, the same is applied to schema_migrations too (test_schema_migrations), that it possible to share the same database between different instances of the same application.

Should something like it be supported in `ecto`? Make it sense to support such per running instance prefix?

**Comment by josevalim** [comment]
I would rather not support it. It is implicit and global behaviour, which I think we should avoid. Also, let's start pushing feature discussions to the mailing list. :)

**Comment by liveforeverx** [comment]
Ok, next time will start on mailing list, sorry :) Understand.
