### ISSUE TITLE
Failed when creating where query using `datetime_add`

### ISSUE THREAD

**Issue by yoavlt** [elixir-lang/ecto#855]
I wanted to create a query like the below.

```:elixir
from b in Book,
where b.published_at > datetime_add(^Ecto.DateTime.utc, -1, "month")
```

It causes an error.
    :erlang.apply(0, :type, [])
    lib/ecto/type.ex:230: Ecto.Type.match?/2
    lib/ecto/query/builder.ex:259: Ecto.Query.Builder.assert_type!/3
    lib/ecto/query/builder.ex:90: Ecto.Query.Builder.escape/5
    lib/ecto/query/builder.ex:142: Ecto.Query.Builder.escape/5
    lib/ecto/query/builder/filter.ex:16: Ecto.Query.Builder.Filter.build/5
    expanding macro: Ecto.Query.where/3
    web/models/book.ex:28: BasketServer.Book.published_recently/1

Is this feature unsupported yet?

**Comment by josevalim** [comment]
It is a bug that has been fixed in more recent Ecto versions. please update Ecto.
