### ISSUE TITLE
'mix ecto.rollback' does not work with 'modify' in 'alter table'

### ISSUE THREAD

**Issue by Ruchika1001** [elixir-lang/ecto#858]
PostgreSQL: 9.4.3
Ecto:ec 0.14.3

I am executing command "mix ecto.rollback" on an already up migration 
<img width="378" alt="screen shot 2015-08-06 at 2 24 56 pm" src="https://cloud.githubusercontent.com/assets/7416427/9108075/7254acc0-3c49-11e5-92fa-5cfb48a88c9c.png">

It gives error like:
<img width="760" alt="screen shot 2015-08-06 at 2 43 28 pm" src="https://cloud.githubusercontent.com/assets/7416427/9108109/9b8d8580-3c49-11e5-9721-8d600bde00d6.png">

**Comment by josevalim** [comment]
You need to define up/down in this migration because once you change the type, we don't know how to revert to the previous type.
