### ISSUE TITLE
Add a connectivity check

### ISSUE THREAD

**Issue by felipesere** [elixir-lang/ecto#861]
When booting my application, it takes my DB significantly longer to come up than my Phoenix app.
I have modified the Phoenix app to run migrations when starting, so I need the DB to be there or wait.

I'd like to see a function `MyApp.Repo.available?` that will return a boolean. Underneath it could do something like `SELECT 1` or similar. This could also be made configurable.

I'd work on this myself, but I don't know where best to place this behaviour.

**Comment by josevalim** [comment]
@felipesere please take those discussions to the ecto mailing list. If there is a plan or a concrete solution, we can start discussing if it should be added to Ecto or not. At first, something seems iffy about your setup, so let's continue it there.
