### ISSUE TITLE
Support names in references

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#863]
For @elixir-lang/ecto-adapters,

* [x] MySQL
* [x] PostgreSQL
* [x] MSSQL
* [x] SQLite
* [x] MongoDB

Here is the relevant commit: https://github.com/elixir-lang/ecto/commit/34bc420c09588172d430c5bb39867f956362b6eb. Just duplicate the changes and unit tests added to PostgreSQL/MySQL.

Here is the test: https://github.com/elixir-lang/ecto/commit/34bc420c09588172d430c5bb39867f956362b6eb#diff-56abcdb75cb6afa2275af793d936932fR463

This is the one of 2 changes before Ecto v1.0! I am waiting for feedback.

**Comment by michalmuskala** [comment]
With Mongo there's no references at all, so there's nothing to do.

**Comment by josevalim** [comment]
@michalmuskala so if I try to create a child model that links to a parent model that does not exist... it would just work?

**Comment by michalmuskala** [comment]
Yes. The links in Mongo are at application level - there are no facilities for that in the database.

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/3ea9113fb80b33011548f588729c5b01a5381daa

**Comment by mobileoverlord** [comment]
MSSQL: livehelpnow/tds_ecto@f60939cf655465d23b7ca2bf7caa26b9f1498e72
