### ISSUE TITLE
Fragments in default field values

### ISSUE THREAD

**Issue by thousandsofthem** [elixir-lang/ecto#864]
Is there a way to define default field value (especially primary key but point valid for every column)
as a fragment (i.e. without further escaping), e.g.

```elixir
field :some_id, :string, default: fragment("generate_object_id()")
```

or 

```elixir
@primary_key {:id, :string, autogenerate: false, default: fragment("generate_object_id()")}
```

(Code above don't work obviously)

P.S. one more example:
```elixir
field :did_something_at, : datetime, default: fragment("now()")
```

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by thousandsofthem** [comment]
As far as i understand that's the issue/enhancement. There are no way of doing so (according to my understanding of source code - because of strict type validation)
And this ability would be really useful for many people

**Comment by josevalim** [comment]
@thousandsofthem it is possible. Also, if it was a feature, we should first discuss them in the mailing list, with everyone. Please open up a discussion in the mailing list.

**Comment by thousandsofthem** [comment]
Ok, thanks
