### ISSUE TITLE
Support context in metadata

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#869]
For @elixir-lang/ecto-adapters,

* [x] MySQL
* [x] PostgreSQL
* [x] MSSQL
* [x] SQLite
* [x] MongoDB

We have added a context field to the metadata and passing it to adapters. The changes are minimal for SQL adapters: instead of receiving a tuple, insert/update/delete now receive a map:

https://github.com/elixir-lang/ecto/commit/65c4b7922e6721c74605c17606ddf693b7db1bef#diff-390cecbd5d47004a498f0c6f09e07f7dL10

If you are matching on the second argument for insert/update/delete, you need to match on a map now.

NoSQL adapters need to change a couple other places, the commit above can be used as reference.

**Comment by jazzyb** [comment]
SQLite:  None of the changes look applicable.  Latest integration tests pass.

**Comment by michalmuskala** [comment]
MongoDB: https://github.com/michalmuskala/mongodb_ecto/commit/1e872687cd1cc0b80759ed5ef4f4637bb856fcda

**Comment by mobileoverlord** [comment]
MSSQL: integration tests passing.
