### ISSUE TITLE
Ensure null, defaults and references are used on alter table

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#870]
For @elixir-lang/ecto-adapters,

* [x] MySQL
* [x] PostgreSQL
* [x] MSSQL
* [x] SQLite
* [x] MongoDB

There were some bugs when generating modify clauses in migrations for PostgreSQL and MySQL so you may have inherited those too. To improve this, I have added integration tests and I have added some unit tests too. All has been done in this commit: https://github.com/elixir-lang/ecto/commit/f8f8b875fb6e4d353d8f3890f35787c5f206bb50

Note I have cleaned up the tests, unifying a bunch of small tests into large chunks. All you need to do is to update those 3 tests in your suites and pass the integration tests and you should be good to go:

1. https://github.com/elixir-lang/ecto/blob/f8f8b875fb6e4d353d8f3890f35787c5f206bb50/test/ecto/adapters/mysql_test.exs#L437

2. https://github.com/elixir-lang/ecto/blob/f8f8b875fb6e4d353d8f3890f35787c5f206bb50/test/ecto/adapters/mysql_test.exs#L459

3. https://github.com/elixir-lang/ecto/blob/f8f8b875fb6e4d353d8f3890f35787c5f206bb50/test/ecto/adapters/mysql_test.exs#L504

**Comment by michalmuskala** [comment]
MongoDB does not support null constraints, defaults, or references

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/4361e211c4e30eea768d53d35bcd253dde9183dc

**Comment by mobileoverlord** [comment]
This has been handled along side the constraints for me.
MSSQL: livehelpnow/tds_ecto@5bd6b2a97e20fd5627d139d268e37eb4f6434a48
