### ISSUE TITLE
Recent version of Ecto refers to renamed `Utils` module by the old name

### ISSUE THREAD

**Issue by sumerman** [elixir-lang/ecto#871]
With `0.15` in my `mix.exs` I got an error:

```
(UndefinedFunctionError) undefined function: Ecto.DateTime.Util.usec/1 (module Ecto.DateTime.Util is not available)
        (ecto) lib/ecto/query/planner.ex:116: Ecto.Query.Planner.prepare/3
        (ecto) lib/ecto/query/planner.ex:66: Ecto.Query.Planner.query/4
        (ecto) lib/ecto/repo/queryable.ex:91: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
```

**Comment by sumerman** [comment]
Full deps cleanup and then full recompilation have solved the problem. Looks like Elixir protocol related issue.

**Comment by josevalim** [comment]
That was supposed to work without issues, you shouldn't explicitly need to fully recompile. Unless you had a path/git dependency and changed to Hex (which is currently an Elixir bug). Is that the case?

**Comment by sumerman** [comment]
@josevalim nope, it's not the case. I've just bumped versions.

**Comment by josevalim** [comment]
Can you tell me your previous Ecto version, the new one as well as your current Elixir version?

**Comment by josevalim** [comment]
Ping.

**Comment by sumerman** [comment]
@josevalim sorry, for my unresponsiveness. Here is the excerpt from the `mix.lock` diff.
```
-  "ecto": {:hex, :ecto, "0.14.1"},
+  "ecto": {:hex, :ecto, "0.15.0"},
```
