### ISSUE TITLE
Support count with distinct (and possibly other aggregators too)

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#874]
First we need to check how well supported in SQL databases this is.

**Comment by vanstee** [comment]
Looks like all the SQL databases that Ecto has an adapter for currently support `COUNT(DISTINCT expr)`

* PostgreSQL http://www.postgresql.org/docs/9.4/static/sql-expressions.html#SYNTAX-AGGREGATES
* MySQL https://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html#function_count-distinct
* MSSQL https://msdn.microsoft.com/en-us/library/ms175997.aspx
* SQLite3 https://www.sqlite.org/lang_aggfunc.html

**Comment by josevalim** [comment]
Beautiful, thanks for doing the research @vanstee!

**Comment by vanstee** [comment]
Figured I'd do a little bit more work on this. Looks like ecto supports distinct via fragments like this:

```
from user in User, select: count(fragment("DISTINCT ?", user.country))
```

So I'm guessing this PR is for something a little fancier to avoid any raw sql. What do you think of an API like this?

```
from user in User, select: count(distinct: user.country)
```

To keep things simple we could just require that the value of the `distinct` key has to be a field for now, but still allow anyone to build up a more complex distinct query with a fragment. While I'm at it I can apply this to the other aggregate functions as well.

**Comment by parkerl** [comment]
@vanstee I like you proposed API. However I'm wondering if simply `count_distinct` would be clearer and easier to document than overloading `count`? Just a thought. 

Either way I love that you are working on adding this to the query API!

**Comment by josevalim** [comment]
`count_distinct` sounds good. It increases the API surface but it is the simplest. What do you think @ericmj / @michalmuskala?

**Comment by michalmuskala** [comment]
I like `count_distinct` too. It's clear what it does. It will also keep the AST for adapters clean. Something like `count(dictinct: model.field)` would add yet another case.

On the other hand this will only allow us to use `dictinct` with `count`. As @vanstee outlined above we could support `dictinct` in other aggregate functions too (I'm not sure how useful distinct is with a `sum` though). In this case I don't like adding `sum_distinct`, `min_dictinct`, etc...

**Comment by josevalim** [comment]
Here is another idea:

    count(model.field, :distinct)

It is still making the API wider (`count/1` and `count/2`) but it is fairly easy to match on the AST side and does not introduce `count_distinct`, `sum_distinct` and friends.

**Comment by michalmuskala** [comment]
I like this much better, it also allows the adapters to be backwards compatible.

**Comment by parkerl** [comment]
:+1:

**Comment by josevalim** [comment]
If someone sends a PR it would be much appreciated!

On Saturday, September 12, 2015, Lew Parker <notifications@github.com>
wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/874#issuecomment-139751861>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by parkerl** [comment]
I can take this one as well if no one has picked it up.

**Comment by josevalim** [comment]
Please do!

**Comment by parkerl** [comment]
OK so I have hacked this out for postgres in the wip above. Looking for feedback to see if I'm on the right track.

**Comment by josevalim** [comment]
Thank you @parkerl! You are definitely in the right track, good job! I have added some comments. :D

**Comment by parkerl** [comment]
@josevalim thanks for the feedback. I was happy to just make it work end to end. I will work on cleaning it up.

**Comment by parkerl** [comment]
Updated per comments. What's next?

**Comment by josevalim** [comment]
This looks great, i just left some nitpicks in there. We need mysql support and we will be ready to ship it :D

**Comment by parkerl** [comment]
@josevalim no need to apologize for nit picks. I just hadn't worried about cleaning house yet. Thought we were a ways off from a PR. How does it look now? I have not manually tested MySQL. Should I write an integration spec for that connection?

Thanks.

**Comment by josevalim** [comment]
Looks good to me! if `mix test.all` passes, we are good to go!

**Comment by parkerl** [comment]
@josevalim tests pass, code clean, are we done? Should I open a separate PR for documentation?

**Comment by josevalim** [comment]
Closing in favor of the pr.
