### ISSUE TITLE
get_field for nested changesets should filter out deleted entries for has_many relations

### ISSUE THREAD

**Issue by sumerman** [elixir-lang/ecto#875]
When I use `Changeset.get_change` I expect it to return what it returns now, but for the `Changeset.get_field` the expectation is to return the value as if it comes from the model.

**Comment by josevalim** [comment]
Agreed. @michalmuskala can you please take a look?

**Comment by michalmuskala** [comment]
Yes, I'll look into this.

**Comment by michalmuskala** [comment]
Should it return changesets or models? I believe it should be applied models

**Comment by sumerman** [comment]
@michalmuskala that would be the least surprising thing

**Comment by sumerman** [comment]
@michalmuskala thanks
