### ISSUE TITLE
No validation of options specified in validate_number()

### ISSUE THREAD

**Issue by filipabramowicz** [elixir-lang/ecto#877]
There is no validation of options specified in validate_number(changeset, field, opts).

According to the documentation, only the following options are allowed:

```
:less_than
:greater_than
:less_than_or_equal_to
:greater_than_or_equal_to
:equal_to
:message
```

However when incorrect options are used, such code fails silently (it doesn't validate and it doesn't fail at compilation) - there is no indication that something is wrong:

```elixir
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> validate_number(:duration, min: 10, max: 60000)
  end
```

Is it for some reason or could it be improved?

**Comment by josevalim** [comment]
I could definitely be improved.

**Comment by filipabramowicz** [comment]
Do you plan to implement it or do you need some help?

**Comment by josevalim** [comment]
Please try a pull request if you would like to. I won't have time to tackle this one soon.

**Comment by josevalim** [comment]
Fixed in master.
