### ISSUE TITLE
Changeset generated with params set to :empty never picks up params added by subsequent changes

### ISSUE THREAD

**Issue by sumerman** [elixir-lang/ecto#878]
As described in phoenixframework/phoenix_ecto#24 for some reason I have to do `Model.changeset(Model.changeset(model), params)` in order to properly initialize my changeset. But to my further surprise this is not enough, and values from `params` are not visible from a form generated out of this changeset. 

It happens because `Model.changeset(model)` will set params to `nil` and then, next merging logic will be applied to subsequent changes: `new_params  = cs1.params && cs2.params && Map.merge(cs1.params, cs2.params)`. 

In the end, I have to do `Model.changeset(%{ Model.changeset(model) | params: %{}}, params)` which not only looks ugly but also is hard to come up with.

**Comment by josevalim** [comment]
Fixed in master.
