### ISSUE TITLE
Support parallel preloads

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#881]
The idea is to check out multiple connections from the pool and issue async queries. We will need Elixir v1.1 for this.

**Comment by xtagon** [comment]
What's the use case for this? Would asynchronously preloading associations in parallel actually be faster than just combining each JOIN into a single database query? With a single query at least the database is responsible for optimization.

**Comment by josevalim** [comment]
@xtagon preloading does not perform joins. Join may be slightly faster in some database but it is much more expensive on the network and processing side because the amount of results returned are M * N. Preload only returns M + N data. This is particularly aggravating as you want to return more data.

So the idea here is: if you have to preload 3 associations, we will get 3 connections from the pool, query them in parallel, and put the results back together.

**Comment by xtagon** [comment]
Ah, that makes sense. Thanks for explaining.

**Comment by MSch** [comment]
Please make this opt-in (for SQL adapters at least), to not break transaction isolation by default.

**Comment by josevalim** [comment]
Ah, good point.

**Comment by gjaldon** [comment]
@josevalim I'd like to take a stab at this. Reading the description in your first post, I first assumed I'd end up using `pool_mod.checkout/2`. But read the code and looks like I only need to call `Repo.all` and that `Preloader.preload_each/3` preloads asynchronously?

Why is Elixir 1.1 needed for this? Is there a feature/function that should be used for this? Did you have in mind `Task.yield/2` for this?

**Comment by josevalim** [comment]
@gjaldon we need 1.1 because we need to change the adapters to support non-blocking queries. Adapters support only call queries, which are blocking. We need to use cast + whereis and whereis is available only in 1.1.

**Comment by gjaldon** [comment]
Chatted with @josevalim on IRC. As a first step, we'll need to add support for async queries in Postgrex and Mariaex. Async queries are going to be casts that return a reply.

**Comment by liveforeverx** [comment]
On which time do you plan to drop support for elixir 1.0.0 in ecto?

**Comment by josevalim** [comment]
I would say in about 2 or 3 months. Elixir 1.2 will come out first. Folks should be considering migrating to Erlang 18 and Elixir 1.1. Both migrations should be straight-forward.

**Comment by josevalim** [comment]
@fishcakez to implement this, we will need to know if we are inside a transaction. Does DBConnection provide such API?

**Comment by fishcakez** [comment]
It doesn't but when the SQL adapter is inside a transaction then its
private `get_conn/1 returns the DBConnection reference.

**Comment by josevalim** [comment]
@fishcakez if that is reliable that's all I need. :)

**Comment by fishcakez** [comment]
Its reliable as long as we don't start using `DBConnection.run` explicitly.

**Comment by josevalim** [comment]
@fishcakez I think we should add something to the pool API to support this. I am thinking of a boolean flag that indicates it won't support running multiple commands in different tasks. Ideas?
