### ISSUE TITLE
Support sorted indexing

### ISSUE THREAD

**Issue by ricn** [elixir-lang/ecto#882]
In ActiveRecord you can do this:

```
add_index :posts, :released_at, order: { released_at: "DESC NULLS LAST" }
```

It would be nice if we could do it like this in Ecto:

```
create index(:posts, [:released_at], order: "DESC NULLS LAST")
```
This can be done in Ecto today like this:

```
create index(:posts, ["released_at DESC NULLS LAST"])
```

**Comment by josevalim** [comment]
We are feature frozen for Ecto 1.0 but we could add this after v1.0 is out. The main question is: how do these options work between databases? Could you do a quick check? MySQL, PG, SQLite3 and MSSQL? Do they all accepts things like NULLS LAST?

**Comment by ricn** [comment]
I can do a quick check to see which databases that have support for it.

**Comment by michalmuskala** [comment]
With MongoDB, you can specify direction (ascending or descending) of each field in index.
I agree it would be useful, but I think it would be quite hard to do that in a database-agnostic way, maybe it would be possible to do this at least for SQL databases.

**Comment by josevalim** [comment]
I am closing this as we can support it with:

    create index(:posts, ["released_at DESC NULLS LAST"])

It is known we support expressions in this place and according to SQL those fields are just extensions to the underlying expression. If it is not supported by a given database, please reopen so we can consider another way.

**Comment by akaKuruma** [comment]
Is it still supported?
