### ISSUE TITLE
Support partial indexing

### ISSUE THREAD

**Issue by ricn** [elixir-lang/ecto#883]
In ActiveRecord you can do this:

```
add_index :orders, :billed, where: "billed = false"
```

It would be nice if we could do it like this in Ecto:

```
create index(:orders, [:billed], where: "billed = false")
```

The only way I have figured out to do this in Ecto is to use the execute function:

```
execute("CREATE INDEX index_orders_on_billed_idx ON orders(billed) WHERE billed = false")
```

**Comment by josevalim** [comment]
We are feature frozen for Ecto 1.0 but we could add this after v1.0 is out. The main question is: how do these options work between databases? It would be nice if we could use Ecto's query syntax here. But we probably won't be able to.

**Comment by ricn** [comment]
Sqlite seems to support the same syntax that PG uses. Not sure about the other ones but I can look it up.

**Comment by ricn** [comment]
Postgres, Sqlite & MSSQL have support for partial indexes (sometimes referred to as filtered indexes) & they all support it by appending a WHERE clause to the CREATE INDEX statement. 

MySQL does not seem to support partial indexes.

**Comment by matthewrudy** [comment]
I had a go at this.
https://github.com/elixir-lang/ecto/compare/master...matthewrudy:create-partial-indexes

Currently just send a string into the `WHERE` clause

``` elixir
def change do
  create index(:posts, [:permalink], unique: true, where: "public IS TRUE")
end
```

I haven't tried using ecto query syntax yet, but the Postgres implementation of partial indexes supports full query syntax, so it should be useful.
http://www.postgresql.org/docs/8.0/static/indexes-partial.html

**Comment by josevalim** [comment]
A PR is welcome. Let's just support passing a string for now.

**Comment by matthewrudy** [comment]
@josevalim PRed https://github.com/elixir-lang/ecto/pull/1152
