### ISSUE TITLE
Add way to customize error message for required field in cast/4

### ISSUE THREAD

**Issue by gjaldon** [elixir-lang/ecto#884]
Right now, we need to go through the errors and replace the `"can't be blank"` ones with the custom error message. It would be convenient to have some support to customize this within Ecto.

Would it be worth adding a `cast(model_or_changeset, params, required, optional \\ [], custom_error_message)` for?

**Comment by JustMikey** [comment]
I wonder why can't it be done the same way it's done in Rails? I mean, let `required fields` remove the extra fields (kinda what `strong params` in Rails do) and just add `validates_presence` validation ?

**Comment by josevalim** [comment]
Just traverse the errors list after wards and replace "can't be blank" by whatever you want.

**Comment by erikreedstrom** [comment]
Is this still a valid answer with the addition of gettext?

**Comment by josevalim** [comment]
Yes, that's exactly what you should do with gettext. You should traverse all messages and translates them with the given domain. That's why we have added `Ecto.Changeset.traverse_errors/2` :)
