### ISSUE TITLE
Why required fields are checked in casting only if they are nil and not if they are empty strings?

### ISSUE THREAD

**Issue by JustMikey** [elixir-lang/ecto#886]
I just wonder why a parameter with an empty string is considered to be present during the casting of required fields? What I mean is that if I have a field `email` and I add it to the list of required fields and it equals to an empty string, I don't get any errors, and I wonder what the reason for this is?

**Comment by josevalim** [comment]
Please don't use the issues tracker for questions.

That's because it is not up to the model layer to remove empty strings. They are a wart from HTML forms. In Phoenix you have `plug :scrub_params when action in [:create, :update]` to remove them.

**Comment by JustMikey** [comment]
@josevalim I apologize for posting a question here. And thank you for your reply

**Comment by josevalim** [comment]
No problem! :D
