### ISSUE TITLE
change to rename/2

### ISSUE THREAD

**Issue by bcardarella** [elixir-lang/ecto#887]
Thoughts on the following change to `rename/2`, having it return the table that is being acted upon. This way we can write the following in a migration:

```elixir
table(:foo)
|> rename :bar, to: :baz
|> rename :qux, to: quxx
```

**Comment by josevalim** [comment]
:+1:

**Comment by josevalim** [comment]
btw, you will need parenthesis around your rename calls.

**Comment by josevalim** [comment]
We should probably change create and drop to do this too. Just for consistency.

**Comment by bcardarella** [comment]
@josevalim why on drop?

**Comment by josevalim** [comment]
No idea. I just listed the functions that receive tables. :)
