### ISSUE TITLE
cast(cast(model, :empty, ...), params, ...) sometimes leaves relations in invalid state

### ISSUE THREAD

**Issue by sumerman** [elixir-lang/ecto#890]
Not sure if it's a bug or just behaviour to be documented. Below I'll try to explain what happens as I understand it.

As expected `cast(model, :empty, ...)` marks all generated changes as invalid. Later on, if `params` of subsequent `cast` lead to generation of a change that is considered no-op (`:skip`) the original "invalid" change stays in the changeset. So in the end we can have an inconsistent changeset with top-level `valid?` set to true, but with nested changesets having their `valid?` fields set to false.

**Comment by josevalim** [comment]
Can you give me a more concrete example here too? It could even be a simple file or a simple test case that defines the models and shows the scenario happening. It does feel like a bug but without a way to reproduce it, I am thinking it will be really hard to fix it. :(

**Comment by josevalim** [comment]
Ping? I wanted to release Ecto 1.0 today and this is holding it back.

**Comment by sumerman** [comment]
@josevalim it's not present in `v0.16.0`, sorry for disturbance.
