### ISSUE TITLE
False positive "missing parameter" errors on subsequent cast calls

### ISSUE THREAD

**Issue by sumerman** [elixir-lang/ecto#891]
`cast(cast(ch0, %{x: ..., y: ...}, ...), %{z: ...}, ...)`  will mark `x` and `y` as absent, although they are present in the changes set.

**Comment by josevalim** [comment]
Can you give a more concrete example? What is the third parameter in both cases?

**Comment by josevalim** [comment]
Ping? I wanted to release Ecto 1.0 today and this is holding it back.

**Comment by sumerman** [comment]
Ouch, I'm on vacation right now. I can try to come up with the example in a couple of hours, or you can release it as is and fix this later.

**Comment by josevalim** [comment]
If I understand this one, I don't think it is a bug. The required parameters are meant to check the values being given, not the ones in the changeset. So this likely isn't a bug, so no worries.

However, if you have a couple minutes today to help us solve #890, that would be preferred, because that one seems closer to a bug.

Thank you and enjoy the vacation! :)

**Comment by sumerman** [comment]
@josevalim agreed, it's rather usability issue than a bug. Since it's quite common to have `Model.changeset/2` wrapper over the `cast` and other validations it would be nice to have such wrappers composable.

**Comment by josevalim** [comment]
Ok, thank you for confirming the issues. I think we are good to go, we won't be fixing this one as the current behaviour is per design. :) Cheers!

**Comment by sumerman** [comment]
@josevalim won't be fixing for 1.0 or ever?

**Comment by josevalim** [comment]
Ever.

**Comment by josevalim** [comment]
Actually, ignore me. We should fix this. We already check the model, we should likely check the changes to.

**Comment by sumerman** [comment]
Hah :) Thanks :+1:
