### ISSUE TITLE
Consider raising if embed/assoc is set on model on insert

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#894]
I think it would be helpful as a guidance. I am aware we can't be consistent on all Repo actions but it would help remove confusion. See this discussion on SO: http://stackoverflow.com/questions/32110434/how-to-handle-one-to-one-association-with-unique-constraints-in-both-models-in-p

@michalmuskala thoughts?

**Comment by michalmuskala** [comment]
It may be fine to raise, if the association is in model and not in changeset on insert. This may help with confusion.
Regarding the code from the question: if one doesn't want to go through cast with the association, but handle it themselves, something like that should probably work too:
```elixir
profile_changeset = Profile.changeset(%Profile{}, user_params["profile"])
user_changeset = 
  User.changeset(%User{}, user_params)
  |> Ecto.Changeset.put_change(:profile, profile_changeset)

case Repo.insert(user_changeset) do
  # handle success and failure
end
```

**Comment by josevalim** [comment]
Fixed in master.
