### ISSUE TITLE
Nested relation changes ordering sometimes breaks DB constraints.

### ISSUE THREAD

**Issue by sumerman** [elixir-lang/ecto#896]
It's probably an uncommon case, but during the update I have to destroy and recreate the whole set of related models and I have a uniqueness constraint for these models. Unfortunately changes list is ordered in a such way that insertions come first and only then deletions. So, during `Repo.insert ` exception is risen.

For now I have this (relation field is renamed) as a workaround: 
```elixir
Map.update!(res, :changes, &(Map.update(&1, :relation_field, [], fn d -> Enum.reverse d end)))
```

P.S.: I'm on `v0.16.0` now.

**Comment by michalmuskala** [comment]
We create deletions after insertions, as it's impossible to know what to delete without the information what to keep. We need to traverse all the params, and only then we can know what to delete. 

A possible workaround is to have a specIal param, and explicitly mark models for deletion based on it, similar to how José does this in his article http://blog.plataformatec.com.br/2015/08/working-with-ecto-associations-and-embeds/ in the "deleting todo items" part.

**Comment by sumerman** [comment]
@michalmuskala but it's a way to get into uniqueness troubles in general. Why not to reverse the changes list after params traversal is done?

**Comment by josevalim** [comment]
@michalmuskala We have two options: we order in the changeset and then we just perform the order in the changeset in the repo or we order in the repo. I prefer the first, thoughts? Also, can you help me tackle this one?

**Comment by michalmuskala** [comment]
I agree we should do this during casting/changing -this gives more flexibility. It should be fairly easy to place the autogenerated ones at the beginning. Should we also move those that the user explicitly sets the action to delete? I don't think so.

I'll be able to take this one but only in the evening. I'm traveling today the whole day.

**Comment by josevalim** [comment]
> Should we also move those that the user explicitly sets the action to delete? I don't think so.

I don't think so too but we need to make sure that the order given as parameter is the respected order (if we don't yet).
