### ISSUE TITLE
Support fragment sources in join

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#900]
For @elixir-lang/ecto-adapters,

* [x] PG
* [x] MySQL
* [x] MSSQL
* [x] SQLite

This is small change to the query syntax to allow complex expressions in joins. Here is the relevant commit: 372380174b1f83357610c31617cab7e1b6301cd1. Just copy the test and replication the changes done to Postgres.

**Comment by mobileoverlord** [comment]
MSSQL: livehelpnow/tds_ecto@aef941b9f9fe8300bd836c47e2c8ba47f6f4b900

**Comment by jazzyb** [comment]
SQLite: https://github.com/jazzyb/sqlite_ecto/commit/a7e3dceb378f1899e999573908bdc61b1ddaff14

**Comment by jazzyb** [comment]
@josevalim I commented on a possible bug in the PG tests.  Github might have notified you, but I don't want it to get lost:  https://github.com/elixir-lang/ecto/commit/372380174b1f83357610c31617cab7e1b6301cd1#commitcomment-12847348

**Comment by josevalim** [comment]
@mobileoverlord you have inherited the PostgreSQL mistake, please check master and fix your test accordingly.

**Comment by mobileoverlord** [comment]
@josevalim was this in create_names?

**Comment by josevalim** [comment]
@mobileoverlord sorry, here is the fix: 8c1f7646d3d949af67fa3278d054686e5258ea80

I forgot to push. :D

**Comment by mobileoverlord** [comment]
all good livehelpnow/tds_ecto@374155eb303dd7be50d90dc10e4e6f3b50ae194c
