### ISSUE TITLE
Repo.get! throws wrong exception with invalid UUID

### ISSUE THREAD

**Issue by kurtisnelson** [elixir-lang/ecto#909]
I use Ecto.UUID as my primary key type with postgres. However, if a user goes to a URL with an invalid UUID http://localhost:4000/users/zzzz for example, they get a 500 with `cannot dump "zzzz" to type Ecto.UUID` instead of a 404 or a bad request.

**Comment by josevalim** [comment]
Which error is raised?

**Comment by kurtisnelson** [comment]
`Ecto.CastError at GET /users/random-junk`
deps/ecto/lib/ecto/repo/queryable.ex:188: value `"random-junk"` in `where` cannot be cast to type Ecto.UUID in query:

**Comment by josevalim** [comment]
Are you using Phoenix or just Plug? Ecto does not know anything about
status code, so you need to tell it to render cast errors as 403. Phoenix
takes care of it automatically though.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Here is how phoenix does it: http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by kurtisnelson** [comment]
This is with phoenix.

**Comment by josevalim** [comment]
Do you have phoenix_ecto as a dependency? Can you provide an app that reproduces the issue?

**Comment by kurtisnelson** [comment]
This project replicates the bug. https://github.com/kurtisnelson/bug-repro

**Comment by josevalim** [comment]
I cannot reproduce it. In dev, it shows the debug page and the status code is 400:

```
[info] GET /users/jadahjada
[debug] Processing by Bugrepro.UserController.show/2
  Parameters: %{"id" => "jadahjada"}
  Pipelines: [:browser]
[info] Sent 400 in 40ms
````

If I disable debug errors, I get the same thing. The same for production. The only thing is that production render "Server internal error" because that's what you have in your error view by default:

https://github.com/kurtisnelson/bug-repro/blob/master/web/views/error_view.ex#L4-L10

**Comment by kurtisnelson** [comment]
Should this make it throw a 500?

https://github.com/kurtisnelson/bug-repro/commit/842b017fe375a2ede2147be0931d4ad7f4e66510

I'll try and get [this](http://websymphony.net/blog/2015/06/28/how-to-use-uuid-as-primary-key-in-ecto-phoenix/) blog post fixed.

**Comment by josevalim** [comment]
Yes, this is a bug. :)

**Comment by josevalim** [comment]
Can you please try Ecto master and let us know if it addresses your concerns? Thank you!

**Comment by kurtisnelson** [comment]
It's still sending a 500 for me. Additionally I just noticed that if you go to `/model/valid_uuid` when the corresponding table is empty, you get a 500 also.

```
[info] GET /users/896ad747-442e-4438-aee5-b85cf234a40b
[debug] Processing by Bugrepro.UserController.show/2
  Parameters: %{"id" => "896ad747-442e-4438-aee5-b85cf234a40b"}
  Pipelines: [:browser]
[debug] SELECT u0."id", u0."email", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."id" = $1) [<<137, 106, 215, 71, 68, 46, 68, 56, 174, 229, 184, 92, 242, 52, 164, 11>>] OK query=0.5ms
[info] Sent 500 in 8ms
[error] #PID<0.329.0> running Bugrepro.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /users/896ad747-442e-4438-aee5-b85cf234a40b
** (exit) an exception was raised:
    ** (Ecto.NoResultsError) expected at least one result but got none in query:

from u in Bugrepro.User,
  where: u.id == ^"896ad747-442e-4438-aee5-b85cf234a40b"

        (ecto) lib/ecto/repo/queryable.ex:57: Ecto.Repo.Queryable.one!/4
        (bugrepro) web/controllers/user_controller.ex:29: Bugrepro.UserController.show/2
        (bugrepro) web/controllers/user_controller.ex:1: Bugrepro.UserController.phoenix_controller_pipeline/2
        (bugrepro) lib/phoenix/router.ex:265: Bugrepro.Router.dispatch/2
        (bugrepro) web/router.ex:1: Bugrepro.Router.do_call/2
        (bugrepro) lib/bugrepro/endpoint.ex:1: Bugrepro.Endpoint.phoenix_pipeline/1
        (bugrepro) lib/plug/debugger.ex:90: Bugrepro.Endpoint."call (overridable 3)"/2
        (bugrepro) lib/phoenix/endpoint/render_errors.ex:34: Bugrepro.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by kurtisnelson** [comment]
Whoops sorry, I only pulled in phoenix_ecto master. Looking into this further...

**Comment by kurtisnelson** [comment]
:+1: all good now.
