### ISSUE TITLE
shutdown: failed to start child on :ok from start_link

### ISSUE THREAD

**Issue by webengineer-max** [elixir-lang/ecto#913]
Hi,

[start_link](http://hexdocs.pm/ecto/Ecto.Adapter.html#c:start_link/2) specify that :ok may be returned. But it leads to 

    ** (EXIT from #PID<0.49.0>) shutdown: failed to start child: Mnesia.Ecto
        ** (EXIT) :ok

during `mix test`.

**Comment by josevalim** [comment]
Yes, it is not supported. I will update the docs.

**Comment by josevalim** [comment]
Thank you, code updated. It will be correct in the next release.
