### ISSUE TITLE
Mark as loaded

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#917]
We need a helper that marks the model as loaded. Specially useful during tests, when you need a loaded model but you don't want to necessarily query the database to get one.

/cc @ericmj @michalmuskala @chrismccord @batate thoughts?

**Comment by ericmj** [comment]
Where is ecto checking if a model is loaded?

**Comment by josevalim** [comment]
Ecto doesn't. But, for example, Phoenix.Ecto implements things based on the state.

**Comment by michalmuskala** [comment]
Why not have something like `put_state(model, :loaded)`? It would be useful not only in tests, but also in places we're setting model's state inside Ecto (e.g. `Ecto.Repo.Model`). 

I'm not sure though where such a function could live.

**Comment by josevalim** [comment]
Likely in Ecto.Model. I am wondering if we should use something more specific than put_state though. put_model_state? Unsure.

**Comment by michalmuskala** [comment]
My only issue for this living directly in `Ecto.Model` is that each time you import or use `Ecto.Model` you would get this. And it's like a half-public API.

Regarding naming - we already have `put_source`.

**Comment by josevalim** [comment]
@michalmuskala what about `put_model_meta` or `put_meta` that will encapsulate this and `put_source`?

**Comment by michalmuskala** [comment]
@josevalim How would you use it? `put_model_meta(model, :source, value)`?
I don't think we can replace the whole meta since we have the `context` field we want to preserve.

**Comment by josevalim** [comment]
put_meta model, state: :loaded

You can pass many fields and it will change only the ones you specify.



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by michalmuskala** [comment]
It's good but the `source` part of meta is currently a tuple, and we allow to only pass a table name without prefix. Should we special case `put_meta mode, source: "table_name"`?

**Comment by josevalim** [comment]
Yes. Source would be one part of the tuple, prefix the other. We will also
support context and state. Put_source can be undocumented and later
deprecated.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by michalmuskala** [comment]
:+1: I like this.

**Comment by josevalim** [comment]
Excellent. I'll add this and once @michalmuskala sends a PR for the relation changes we can release 1.0.2.

**Comment by josevalim** [comment]
In master.
