### ISSUE TITLE
%Postgrex.Error{message: "tcp connect: nxdomain", postgres: nil} when running mix ecto.migrate

### ISSUE THREAD

**Issue by jespr** [elixir-lang/ecto#932]
I just installed Phoenix 1.0.1. I successfully ran `mix ecto.create` and I can see that the database has been created. When I run `mix ecto.migrate` I see the following error:

```
** (exit) exited in: GenServer.call(#PID<0.144.0>, {:query, "CREATE TABLE IF NOT EXISTS \"schema_migrations\" (\"version\" bigint PRIMARY KEY, \"inserted_at\" timestamp)", []}, :infinity)
    ** (EXIT) %Postgrex.Error{message: "tcp connect: nxdomain", postgres: nil}
    (elixir) lib/gen_server.ex:356: GenServer.call/3
    (postgrex) lib/postgrex/connection.ex:102: Postgrex.Connection.query/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:31: Ecto.Adapters.Postgres.Connection.query/4
    (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.query/7
    (ecto) lib/ecto/pool.ex:159: Ecto.Pool.do_run/4
    (ecto) lib/ecto/adapters/sql.ex:231: Ecto.Adapters.SQL.query/6
    (ecto) lib/ecto/adapters/sql.ex:209: Ecto.Adapters.SQL.query/5
    (ecto) lib/ecto/adapters/sql.ex:170: Ecto.Adapters.SQL.query!/5
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:55: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migrator.ex:36: Ecto.Migrator.migrated_versions/1
    (ecto) lib/ecto/migrator.ex:134: Ecto.Migrator.run/4
    (ecto) lib/mix/tasks/ecto.migrate.ex:61: Mix.Tasks.Ecto.Migrate.run/2
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:307: Code.require_file/2
```

I found a blog post (http://iamvery.com/2015/08/29/phoenix-database-config.html) that said that `hostname` should be set to `localhost` in Phoenix's dev.exs - which it already is..

I'm running Mac OS X Yosemite and have installed postgres using homebrew.

**Comment by jespr** [comment]
Postgres is version 9.4.4 btw :)

**Comment by josevalim** [comment]
@jespr can you verify that postgres is running? unless you install it to launchctl, you always need to start it manually.

**Comment by fishcakez** [comment]
`:nxdomain` means that the hostname lookup failed. Postgrex could improve the error by converting the error atom to a string using `:inet.format_error/1`.

**Comment by jespr** [comment]
@josevalim sorry, my bad. Should of course also have shown you that that was the case

`ps ax|grep postgres`

```
 4583   ??  S      0:00.10 /usr/local/opt/postgresql/bin/postgres -D /usr/local/var/postgres -r /usr/local/var/postgres/server.log
 4585   ??  Ss     0:00.02 postgres: checkpointer process
 4586   ??  Ss     0:00.08 postgres: writer process
 4587   ??  Ss     0:00.04 postgres: wal writer process
 4588   ??  Ss     0:00.08 postgres: autovacuum launcher process
 4589   ??  Ss     0:00.20 postgres: stats collector process
```

Running `mix ecto.create` gives `The database for BlogPhoenix.Repo has already been created.`

**Comment by jespr** [comment]
Ok.. Something might be weird in my system 

`ping localhost` -> `ping: cannot resolve localhost: Unknown host`

sorry about wasting your time

**Comment by josevalim** [comment]
> sorry about wasting your time

@jespr you have not. Poor error messages are bugs. :)

**Comment by josevalim** [comment]
I am closing this though as an issue has been opened in Postgrex. Other drivers (/cc @elixir-lang/ecto-adapters) should probably incorporate something similar. THank you!

**Comment by jespr** [comment]
I solved the localhost issue (an entry was missing from `/etc/hosts`), however now I get `econnrefused`

This is me connecting to my running postgres

```
psql -U postgres -W -d blog_phoenix_dev;
Password for user postgres: # used postgres
psql (9.4.4)
Type "help" for help.

blog_phoenix_dev=#
```

But when I run `mix ecto.migrate` I get the following:
```
mix ecto.migrate
** (exit) exited in: GenServer.call(#PID<0.142.0>, {:query, "CREATE TABLE IF NOT EXISTS \"schema_migrations\" (\"version\" bigint PRIMARY KEY, \"inserted_at\" timestamp)", []}, :infinity)
    ** (EXIT) %Postgrex.Error{message: "tcp connect: econnrefused", postgres: nil}
    (elixir) lib/gen_server.ex:356: GenServer.call/3
    (postgrex) lib/postgrex/connection.ex:102: Postgrex.Connection.query/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:31: Ecto.Adapters.Postgres.Connection.query/4
    (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.query/7
    (ecto) lib/ecto/pool.ex:159: Ecto.Pool.do_run/4
    (ecto) lib/ecto/adapters/sql.ex:231: Ecto.Adapters.SQL.query/6
    (ecto) lib/ecto/adapters/sql.ex:209: Ecto.Adapters.SQL.query/5
    (ecto) lib/ecto/adapters/sql.ex:170: Ecto.Adapters.SQL.query!/5
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:55: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migrator.ex:36: Ecto.Migrator.migrated_versions/1
    (ecto) lib/ecto/migrator.ex:134: Ecto.Migrator.run/4
    (ecto) lib/mix/tasks/ecto.migrate.ex:61: Mix.Tasks.Ecto.Migrate.run/2
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:307: Code.require_file/2
```

This is what my `config/dev.exs` in the repo contains:
```
# Configure your database
config :blog_phoenix, BlogPhoenix.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "blog_phoenix_dev",
  hostname: "localhost",
  pool_size: 10
```

Any way to debug this? :/

**Comment by josevalim** [comment]
Maybe postgres is configured with a filter that allows connections only from some IPs?

**Comment by jespr** [comment]
I'm running both on localhost, do you still think that would be an issue? It's just `brew install postgres` configuration default

**Comment by josevalim** [comment]
No idea. Have you restarted postgres after  changing /etc/hosts?

**Comment by fishcakez** [comment]
With `:econnrefused` on localhost its likely to be the port is wrong. You can use `netstat -l` to find the listening port. Then try connecting over tcp: `psql -h localhost -p PORT`.

**Comment by jespr** [comment]
Yeah. Rebooted and everything. Oh well :) I'll keep digging :)

**Comment by mariochavez** [comment]
I'm having same issue. I'm using Postgresql.app and my server is running and accessible. With a Rails app I can connect to the server without a problem but with Phoenix/Ecto I'm getting `%Postgrex.Error{message: "tcp connect: econnrefused", postgres: nil}`

From the terminal I'm able to connect with `psql -h localhost -p PORT` where `PORT` is the same as teh one in:

    State: %{backend_key: nil, bootstrap: false, extensions: [{Ecto.Adapters.Postgres.DateTime, []},    {Postgrex.Extensions.JSON, [library: Poison]}, {Postgrex.Extensions.Binary, nil}, {Postgrex.Extensions.Text, nil}], listener_channels: #HashDict<[]>, listeners: #HashDict<[]>, opts: [username: "postgres", timeout: 5000, otp_app: :dash, repo: Dash.Repo, adapter: Ecto.Adapters.Postgres, database: "dash_dev", hostname: "localhost", extensions: [{Ecto.Adapters.Postgres.DateTime, []}, {Postgrex.Extensions.JSON, [library: Poison]}], port: 5432], parameters: %{}, portal: nil, queue: {[%{command: {:connect, [username: "postgres", timeout: 5000, otp_app: :dash, repo: Dash.Repo, adapter: Ecto.Adapters.Postgres, database: "dash_dev", hostname: "localhost", extensions: [{Ecto.Adapters.Postgres.DateTime, []}, {Postgrex.Extensions.JSON, [library: Poison]}], port: 5432]}, from: nil, reply: :no_reply}], []}, rows: [], sock: nil, state: :ready, statement: nil, tail: "", types: :types_removed, types_key: {'localhost', 5432, "dash_dev", [{Ecto.Adapters.Postgres.DateTime, []}, {Postgrex.Extensions.JSON, [library: Poison]}]}}
** (exit) %Postgrex.Error{message: "tcp connect: econnrefused", postgres: nil}

Database `dash_dev` exists and `localhost` resolves to `127.0.0.1`.

BTW I'm using Postgresql 9.4.4 also.

**Comment by josevalim** [comment]
@mariochavez if you remove `hostname: "localhost"` from your config files, does it work? I am aware you said localhost is resolving correctly, but right now I am lost for ideas. The only other idea is the username/password combination but you probably set that too.

One other idea is if blank password and not passing password at all is the one causing the differences.

**Comment by mariochavez** [comment]
@josevalim I tried without `hostname` but still the same. My postgresql is setup to trust all local connections.

This is my config right now:

    config :dash, Dash.Repo,
      adapter: Ecto.Adapters.Postgres,
      database: "dash_dev",
      pool_size: 10

I'm really sure that I have no issues to connect to Postgresql. Right now I'm downgrading Postgresql to see if that fix the issue.

**Comment by josevalim** [comment]
@mariochavez I assume you have tried it with `username: "postgres", password: ""`? Because at least the state you have posted above contains a `username: "postgres"`.

I am asking because, if your DB does not require a username and you haven't given one, someone may be injecting one, causing the error.

**Comment by mariochavez** [comment]
I went from Postgresql 9.4.4 to Posqtgresql 9.4.1 and still getting `%Postgrex.Error{message: "tcp connect: econnrefused", postgres: nil}`

I cloned Postgrex and ran:
   
    $ iex -S mix

    Interactive Elixir (1.0.5) - press Ctrl+C to exit (type h() ENTER for help)
    iex(1)> alias Postgrex.Connection, as: P
    nil
    iex(2)> opts = [ database: "dash_dev" ]
    [database: "dash_dev"]
    iex(3)> P.start_link(opts)
    {:ok, #PID<0.130.0>}
    ** (EXIT from #PID<0.125.0>) %Postgrex.Error{message: "tcp connect: econnrefused", postgres: nil}
    01:58:34.450 [error] GenServer #PID<0.130.0> terminating
    Last message: nil
    State: [password: :REDACTED, hostname: "localhost", username: "localuser", database: "dash_dev"]
    ** (exit) %Postgrex.Error{message: "tcp connect: econnrefused", postgres: nil}

From console if I try to connect it works

    $ psql -h localhost -p 5432
    psql (9.4.1)
    Type "help" for help.

    localuser=#

**Comment by mariochavez** [comment]
@josevalim still the same is I try with my localuser - which is set to be trusted by postgresql - or with `postgres` user.

    iex(1)> alias Postgrex.Connection, as: P
    nil
    iex(2)> opts = [ database: "dash_dev", port: 5432, username: "postgres", password: "" ]
    [database: "dash_dev", port: 5432, username: "postgres", password: ""]
    iex(3)> P.start_link(opts)
    {:ok, #PID<0.128.0>}
    ** (EXIT from #PID<0.124.0>) %Postgrex.Error{message: "tcp connect: econnrefused", postgres: nil}

    Interactive Elixir (1.0.5) - press Ctrl+C to exit (type h() ENTER for help)
    iex(4)>
    02:05:34.015 [error] GenServer #PID<0.128.0> terminating
    Last message: nil
    State: [password: :REDACTED, hostname: "localhost", database: "dash_dev", port: 5432, username: "postgres"]
    ** (exit) %Postgrex.Error{message: "tcp connect: econnrefused", postgres: nil}

    $ psql -U postgres -h localhost -p 5432
    psql (9.4.1)
    Type "help" for help.

    postgres=#

**Comment by ericmj** [comment]
I don't know what's happening but it would be interesting to know how rails connects since that reportedly works. Could be that postgres is only set up for unix domain sockets. Can you paste your `pg_hba.conf` file? You can find its location with `psql -t -P format=unaligned -c 'show hba_file'`.

**Comment by mariochavez** [comment]
@ericmj this is my `pg_hba.conf` file:

```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     marioch                                trust
#host    replication     marioch        127.0.0.1/32            trust
#host    replication     marioch        ::1/128                 trust
```

**Comment by josevalim** [comment]
Yeah, the same as mine. :(

**Comment by ericmj** [comment]
@mariochavez This is a long shot but can you try removing `127.0.0.1/32` from the `host    all             all             127.0.0.1/32            trust` line?

**Comment by mariochavez** [comment]
@ericmj still the same, I'm getting `"tcp connect: econnrefused"`. I did try with the Rails app and it still able to connect after the change in `pg_hba.conf`, sorry to reference the Rails app but is my sanity test for now. BTW I did restarted my Postgresql server after the change.

**Comment by Tica2** [comment]
Please provide output of commands:

> which psql
> env | grep PG
> netstat -lnta | grep 5432
> psql -U postgres -h localhost -p 5432 dash_dev

see log file:
tail -n 200 /usr/local/var/postgres/server.log

**Comment by mariochavez** [comment]
After trying a few things around I found that localhost entry in my /etc/hosts was in 3rd position like

```
::1               localhost
fe80::1%lo0       localhost
127.0.0.1         localhost
```

Changing the order to 

```
127.0.0.1         localhost
::1               localhost
fe80::1%lo0       localhost
```

Did the trick, sorry about all the hassle.

**Comment by josevalim** [comment]
Awesome, I am just glad this is solved. Go have some fun now @mariochavez! :D

**Comment by mariochavez** [comment]
For what is worth, I did notice that `pg` gem from Ruby did use IPV6 to connect to Postgresql and that is why with my original `hosts` it ws able to connect but `Postgrex` was only trying IPV4.

**Comment by luccasmaso** [comment]
If you came here from docker getting this error, remember to `docker-compose restart` your service (=

**Comment by saper** [comment]
I have also trouble to connect to IPv6-only PostgreSQL instance. More details: https://git.pleroma.social/pleroma/pleroma/issues/214 

It maybe related to the problem that [:gen_tcp](http://erlang.org/doc/man/gen_tcp.html#connect-3) needs to know which protocol and callback TCP library to use.
