### ISSUE TITLE
Do not drop DB in ecto.drop without confirmation if build_embedded is true

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#934]

**Comment by ericmj** [comment]
Shouldn't we check environment instead of build_embedded?

**Comment by josevalim** [comment]
No because what if folks have a prod_1 and prod_2? We should never check for environments, I think build_embedded is as closest as we can get to production.

**Comment by stevedomin** [comment]
Don't mind my opinion too much but it kind of feels wrong to use build_embedded as a proxy to whether it's a production environment or not.

Also by default in a new mix project we set build_embedded by checking if Mix.env is equal to `:prod`, so can't we can assume if people have multiple prod environment they know what they're doing?

**Comment by josevalim** [comment]
Actually, start_permanent would be a much better flag to check here.

**Comment by ericmj** [comment]
start_permanent only matters for people starting their app with mix.

**Comment by josevalim** [comment]
I have no idea then. I am confident we should not check the environment.

**Comment by stevedomin** [comment]
Can't we always confirm before dropping? And add a `-y` flag to bypass the confirmation

**Comment by ericmj** [comment]
What's the underlying issue? Do we have reports of people running ecto.drop by mistake? Maybe it should always prompt unless you pass --force?

**Comment by josevalim** [comment]
Github once accidentally dropped the whole production database: https://github.com/blog/744-today-s-outage

I don't want to ask for -y always because it is not necessary in development.

**Comment by ericmj** [comment]
If we are worried about multiple production environments maybe we should instead check `Mix.env != :dev`?

**Comment by josevalim** [comment]
Hardcoding env in any way is bad. I don't think we should do it nor set the precedent for such case. dev is just a name, it should not imply in any property.

**Comment by ericmj** [comment]
Then I don't think we can change this because the same is true for all project configurations.

**Comment by stevedomin** [comment]
Just throwing out ideas here (which I'm not really satisfied with but it might lead to a better on):

Could we add a `confirm_drop` config to Ecto, set to `false` by default but `true` in production.

In `config/prod.exs`:

```
# Configure your database
config :ex_playground, ExPlayground.Repo,
  adapter: Ecto.Adapters.Postgres,
  confirm_drop: true,
  url: System.get_env("DATABASE_URL"),
  pool_size: 20
```

**Comment by gjaldon** [comment]
An option for it sounds like the way to go. How 'bout requiring confirmation by default before dropping the db? Also, should we confirm too before doing a rollback? Both `drop` and `rollback` are destructive actions.

**Comment by josevalim** [comment]
Probably a "safe_mode" flag.

**Comment by gjaldon** [comment]
:+1: on `safe_mode` flag. Should it be `true` by default?

**Comment by josevalim** [comment]
Yes, it should be true by default. Phoenix should set it to false in dev and test. Does everyone agree?

**Comment by gjaldon** [comment]
:+1: here!

**Comment by stevedomin** [comment]
:+1:

**Comment by Tica2** [comment]
If I see this flag 'safe_mode', I don't understand what mean.

If I see: `safe_to_drop` is more clear (Or similar)

Related to default. If this flag do not exists, then DATA need to be safe.
If I upgrade from old version to new one, this mean my data is safe to be deleted?,
just becaouse I fogot to insert this flag?

My option:
1) long and clear property: save_to_drop_objects (similar)
2) if not exists DATA is considered safe.  save_to_drop_objects=false
if is set explicit to save_to_drop_objects=true 
3) destructive actions in mix need to be confirmed with database name
--yes_drop=my_test_or_drop_db

mix task check env[database_name] with  --yes_drop=my_test_or_drop_db
if are equals then drop action is performed
If not drop fail. 

4) If  --yes_drop=xxx is not provided, then mix ask
if you agree to drop objects in env[database_name] just type Y/N


most common ussaje is:
mix ecto.drop
Do you agree to drop database:  env_database_name Y/N? y
Drop done.


Ideea is to have double check do DROP.
a) in env with flag
b) to tape Y

or
a) in env with flag
b) explicit db_name_safe_to_drop in script

Just my notes :)

**Comment by josevalim** [comment]
I don't like how `safe_to_drop` reads. What about `droppable: true`?

**Comment by stevedomin** [comment]
`droppable` doesn't feel right as in the end they are always droppable, the only difference is whether you get a confirmation or not

**Comment by michalmuskala** [comment]
How about `enable_safety_warnings`?

**Comment by josevalim** [comment]
I really like `enable_safety_warnings`. Since it is going to be true by default, instead of setting it to false, we should probably have `disable_safety_warnings: true`.

Also, I don't think we should require one for rollback. A rollback is as harmful as a migrate and rollbacks can still be automated, specially if your deploy script fails. I can't think of a case you would like to run drop in production though.

**Comment by stevedomin** [comment]
Sounds really good to me!

**Comment by Tica2** [comment]
Again what I see:
1) flag sed if we can run drop/destructive action.
2) If destructive action is enable (default not)
   we show question with Y/N

**Comment by Tica2** [comment]
If I can control source code (conf for prod env).
I really do't care what a junior can do in console ... simple can't drop database.
