### ISSUE TITLE
Add ecto.reset (drop+create+migrate) and ecto.setup (create+migrate) as tasks

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#936]
I am doing `mix do ecto.drop, ecto.create, ecto.migrate` ALL the time. Or we ship with it or we generate them as default in new Phoenix apps as an example of aliases.

/cc @ericmj and @michalmuskala @chrismccord @lancehalvorsen. Thoughts?

**Comment by lexmag** [comment]
:+1: an example of aliases.

**Comment by stevedomin** [comment]
:+1: on `ecto.reset` and `ecto.setup`

**Comment by Tica2** [comment]
Who come first time need to deal with a lot of terms.
Some of them has different meaning in different context.

Good to chose these names with great care. 

Good to have alias suport for mix.
alias.exs
And to put, if we want, what we need.

and to keep 
mix help
short

For me: this 2 commands will causes 
forever confusion
ecto.reset, ecto.setup what do one? what is diference?

also we can use alias from linux.unix

**Comment by michalmuskala** [comment]
I would be :+1: for aliases if they can be documented. If not it may be confusing, and I'll go with separate tasks.

**Comment by gjaldon** [comment]
:+1: here for aliases too.

**Comment by Tica2** [comment]
```elixir
defmodule Myproj.Mixfile do
  use Mix.Project

  def project do
    [app: :pyproj,
     version: "0.0.1",
     elixir: "~> 1.0",     
     deps: deps,
     aliases: aliases]
  end

  def application do
    [mod: {myproj, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger,
                    :phoenix_ecto, :postgrex, :sqlite_ecto]]
  end

  defp deps do
    [
     {:sqlite_ecto, "~> 1.0.1"},
     {:ecto, "~> 1.0"},
     {:phoenix, "~> 1.0.0"},
     {:phoenix_ecto, "~> 1.1"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.1"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:cowboy, "~> 1.0"}]
  end
     
  defp aliases do 
     [
       {:setup, {mix, ["ecto.drop", "ecto.create"]}},
       {:reset, {mix, ["ecto.drop", "ecto.create", "ecto.reset"]}}
     ]   
  end	  
end

```

**Comment by josevalim** [comment]
Now with the proper alias syntax:

```elixir
["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
 "ecto.reset": ["ecto.drop", "ecto.setup"]]
```

**Comment by Tica2** [comment]
hex can have own aliase
pheonix own aliases

Owner of elixir package, can automate to push to hex repository.

**Comment by josevalim** [comment]
Closed and opened an issue in Phoenix.
