### ISSUE TITLE
Doesn't validate presence of an association included in the cast method's required fields

### ISSUE THREAD

**Issue by JustMikey** [elixir-lang/ecto#938]
How to reproduce the problem:

1) Pull https://github.com/JustMikey/phoenix-test-app
2) install deps and migrate
3) Go to /registration path
4) Open developer's panel (usually F12 key)
5) Remove profile's username input tag (second left)
6) Correctly fill other fields
7) Submit the form
8) User is created without a profile

I apologize if I got something wrong.

**Comment by josevalim** [comment]
Thank you for another great report. I am investigating it now!

**Comment by JustMikey** [comment]
@josevalim My pleasure :)

**Comment by josevalim** [comment]
It should be fixed in master. Can you please give it a try? :)

**Comment by JustMikey** [comment]
@josevalim Seems to be working now, thank you very much

**Comment by josevalim** [comment]
Awesome! Let's leave this open so I don't forget to release 1.0.3. :)

**Comment by JustMikey** [comment]
@josevalim Sure
