### ISSUE TITLE
select and preload at the same time errors 

### ISSUE THREAD

**Issue by olivermt** [elixir-lang/ecto#942]
The gist covers a use case for three models + the query and the resulting error.

https://gist.github.com/olivermt/64f0164074baf1263223

Removing the select part entirely works just as it should.

**Comment by josevalim** [comment]
I am suspecting this to be a cache issue. Our cache does not expire if the model changes, so it looks like a new column was added to the model and the cache was using the old query. Just let us know if you can reproduce the issue by restarting the server and running the query. If you can't reproduce it, it is the query cache.
