### ISSUE TITLE
Insert test data for Simple example (examples/simple)

### ISSUE THREAD

**Issue by Tica2** [elixir-lang/ecto#945]
is good to have some real data in example to query in iex>
also to add more example and with expected outputs.

Is priv/repo/migrations right place to insert in data?

**Comment by josevalim** [comment]
The best is to just have scripts in `priv/repo/seeds.exs` which insert the data. We can run it as `mix run priv/repo/seeds.exs`. PR please? :)

**Comment by josevalim** [comment]
PR is welcome!

**Comment by Tica2** [comment]
PR will come over week :)
