### ISSUE TITLE
Warning of locate not supported

### ISSUE THREAD

**Issue by esdrasedu** [elixir-lang/ecto#961]
Ecto not support locale different from en_US, when execute task with ```mix ecto.create``` (and the database is already created) instead result is ```The database for #{database} has already been created.```, the result is a FATAL error.

The Ecto could not verify locate before a task? using ```SHOW LC_COLLATE;```

**Comment by josevalim** [comment]
Can you provide more information? Which Ecto version are you using? What are you giving as input and what is the exact output you are getting?

**Comment by esdrasedu** [comment]
OS: Arch
Erlang 18
Elixir 1.0.5
Postgresql 9.4.4
Ecto: 1.0.0

After I used locate pt_BR.UTF-8, and error ``` FATAL:  banco "XXXX" já existe```

**Comment by josevalim** [comment]
Ah, I see. Perfect. :)

**Comment by Tica2** [comment]
psql process return exit error(<>)0, database exists.

LC_COLLATE affects only psql process. And show messages according values. 

@esdrasedu 
What mean: "Ecto not support locale different from en_US"? 
What is your expectation? Do you mean output messages?

**Comment by esdrasedu** [comment]
@Tica2 i think will be nice the Ecto warning of locate on psql is not corret!

**Comment by josevalim** [comment]
Fixed with #1079 !
