### ISSUE TITLE
Support map update syntax

### ISSUE THREAD

**Issue by Gazler** [elixir-lang/ecto#962]
Currently, if you want to fetch an association using `joins` that reflects the data structure from a `preload` you have to do the following:

### joins

```elixir
query =
  Ecto.Query.from(r in Room,
    join: ru in RoomUser, on: ru.room_id == r.id,
    where: ru.user_id == ^user.id,
    select: {r, ru}
  )
rooms = Repo.all(query) |> Enum.map(fn ({r, ru}) -> %{r | room_users: [ru]} end)
```

### preload

```elixir
room_user_query = Ecto.Query.from(ru in RoomUser, where: ru.user_id == ^user.id)
query =
  Ecto.Query.from(r in Room,
    join: ru in RoomUser, on: ru.room_id == r.id,
    where: ru.user_id == ^user.id,
    preload: [room_users: ^room_user_query]
)
```

If the map update syntax was supported, there would be no need for the `Enum.map`. e.g.:

```elixir
query =
  Ecto.Query.from(r in Room,
    join: ru in RoomUser, on: ru.room_id == r.id,
    where: ru.user_id == ^user.id,
    select: %{r | room_users: [ru]}
  )
```

**Comment by lexmag** [comment]
Strongly :+1:.

**Comment by Tica2** [comment]
Question? List length will remain the same?

What if we have:
where: ru.room_id == ^room.id, 
```
query =
  Ecto.Query.from(r in Room,
    join: ru in RoomUser, on: ru.room_id == r.id,
    where: ru.room_id == ^room.id,
    select: %{r | room_users: [ru]}
  )
```
You want to cumulate rooms and insert RoomUser in room_users?
I see a lot of confusion here.

:-1: 
rows number returned from SQL = list length in Elixir.
No agregation in Elixir.

if you have list of {%A, %B} is so easy to work in Elixir, do that!

**Comment by ericmj** [comment]
@Tica2 If you want to aggregate you can do that the usual ecto ways, if you dont want to you dont have to.

**Comment by Tica2** [comment]
@ericmj Aggregate is passed to SQL... correct?
Here proposal try to aggregate SQL results in ecto.

**Comment by josevalim** [comment]
@Tica2 aggregation should **not** happen here. The list size should stay the same. I actually think the example here may lack a bit of clarity because we don't know the cardinality between the associations but it will only work reasonably if the cardinality is one, as you still get `M x N` results.

**Comment by Tica2** [comment]
@josevalim agree. Is exact what I try to say... different words :)

**Comment by ericmj** [comment]
If the cardinality is not one you can group and get aggregate functions, this is not any different than allowing: `select: {post, comment}` or `select: %{p: post, c: comment}`.

**Comment by parkerl** [comment]
@Gazler do you have your wip on this somewhere? I'd love to take a look at it.

**Comment by Gazler** [comment]
Hey Lew - I might have it unless I did a `git checkout-- .`

I'll check when I get home in a couple of weeks.

**Comment by parkerl** [comment]
@Gazler cool. Just curious. Have fun in SF.

**Comment by josevalim** [comment]
We should also find a way of supporting returning only some fields and not the whole model. I am adding this here as a note, because they are tightly related, but I am not sure yet how it should look like.

**Comment by parkerl** [comment]
@josevalim did that come from the SO question yesterday? I was looking in to that. It looks like Ecto ensures all fields of the "from" are included. Would it be enough to loosen that to just the primary key?

**Comment by josevalim** [comment]
@parkerl I am thinking we need a syntax. We either need a way to specify some fields, be it something like this:

    select: p.{foo, bar}

Or by only declaring fields:

    fields: [:foo, :bar]

Another idea is, because we want to support returning on update/delete, and returning only applies to the current model, we could do something like: "returning: :all" or "returning: [:foo, :bar]". There are many options, I am not sure which one to use yet.

**Comment by josevalim** [comment]
It is also worth mentioning that the syntax we support it would likely make sense for group_by too.

**Comment by josevalim** [comment]
If we support this, we can also support structs: `select: %SomeOtherStruct{....}`.
