### ISSUE TITLE
mix ecto.gen.migration should generate consistent filenames

### ISSUE THREAD

**Issue by kyledecot** [elixir-lang/ecto#963]
When generating migrations with `mix ecto.gen.migration` you can get filename inconsistencies:

`mix ecto.gen.migration CreateFooForBar` # CreateFooForBar.exs
`mix ecto.gen.migration create_foo_for_bar` # create_foo_for_bar.exs

I think that we should downcase and underscore the filename regardless of how the user typed the name for the migration.

**Comment by josevalim** [comment]
Sounds good, thank you!

**Comment by kyledecot** [comment]
@josevalim I'm *very* new to phoenix/ecto (or elixir for that matter) but it shouldn't be too hard so I'll try and take a crack at it

**Comment by josevalim** [comment]
@kyledecot  that will be awesome. If you have any questions, feel free to ask them here. :)
