### ISSUE TITLE
Fields in model marked null/notnull or tag system for fields

### ISSUE THREAD

**Issue by Tica2** [elixir-lang/ecto#966]
I start with real example used in java language, https://gist.github.com/Tica2/e80b6849a11463c4d50a

To create similar model in Ecto I need to

 schema "clients" do
     field client_id,  :integer
     field client_parent_id, :integer
     field clientNumber
     field  clientCode
     field  clientTypeId
     field  name
     field  status
     field  streetId
     field  streetNumber
     field  bloc
     field  scara
     field  etaj
     field  apartament
     field  address
     field  contact
     field  functia
 ....
and so on ..

To have consistent data we create a rule, that say all table columns are not null, only 
if we have FK that require null, we accept null, or 1-2 exceptions with good reason.

This is my use case.
My problem is with template: ...

@required_fields ~w(....)
@optional_fields ~w(...)
where I need to rewrite this list of fields again.

To put here some fields, is fine, but I need also to maintain ... 
(add new col, rename, I forget already 2-3 times)

Will be good to have a way to mark if field in ecto is null or not,
and to query this fields directly.

 @default_notnull = true
 schema "clients" do
     field client_id,  :integer
     field client_parent_id, :integer
     field clientNumber
     field  clientCode
     field  clientTypeId      , :null  # Posible exception 
     field  name
     field  status
     field  streetId             , :null   # Posible exception

No  @required_fields, @optional_fields
# @required_fields ~w(....)
# @optional_fields ~w(...)

def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)

is rewrited in:

def changeset(model, params \\ :empty) do
    model
    |> cast(params, __schema__(:notnull_fields), __schema__(:null_fields))

or

def changeset(model, params \\ :empty) do
    model
    |> cast(params,  __schema__(:required_fields), __schema__(:optional_fields))

or similar ...

New idea is to have tag mechanism for fields

   field name, :string, tags: [:require, :update]
   And to query fields based on these tags.

Anyway I can write also now my own function 
def required_fields () 
that 
call __schema__(:fields) and remove some fields

But **I prefer to have** nice mechanism implemented in model/Ecto.

do not criticize too much :)

Thanks!

**Comment by josevalim** [comment]
Please use the mailing list for feature discussions and not the issues tracker. :) THank you!

**Comment by Tica2** [comment]
I ask you, if I can create a issue and you agree ... :D
Is fine also on discussions list.

**Comment by josevalim** [comment]
@Tica2 if I agreed I was probably needing some sleep. Sorry. The ecto mailing list is the place to go with this.
