### ISSUE TITLE
Add Repo.all_by as a mirror to Repo.get_by

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ecto#969]

**Comment by michalmuskala** [comment]
I'm afraid we will soon need `Repo.update_by` and `Repo.delete_by`.

Wouldn’t it be better to have a `Ecto.Query.by_fields/2` function to generate a query, and use regular `Repo.one`, `Repo.all`, etc. with it?

It would be used like this:
```elixir
Ecto.Query.by_fields(MyModel, fields) |> Repo.all
Ecto.Query.by_fields(MyModel, fields) |> Repo.one
```

This would also remove the need for `Repo.get_by`. It also promotes using composable queries, and allows easy use of preloads, etc. if needed.

**Comment by gjaldon** [comment]
The `Ecto.Query.by_fields/2` option sounds great! Instead of `by_fields/2`, how about we overload `Ecto.Query.where` with this behavior?

**Comment by michalmuskala** [comment]
I'm not sure that's doable, because `where` is a macro, and I think a normal function would be enough here.

**Comment by ericmj** [comment]
Is `Ecto.Query.by_fields(MyModel, foo: 123)` really that much better than `from(m in MyModel, where: m.foo == 123)`?

**Comment by josevalim** [comment]
@ericmj it is not the point of which one is better but in allowing things to be dynamic. Imagine I want to convert params data in Phoenix to a query. If we can do it dynamically i can do:

    attrs = 
      for {k, v} in params,
        k in ~w(age title gender),
        do: {String.to_atom(k), v}
    Profile |> by_fields(attrs) |> Repo.all

I don't like `by_fields` as a name but the idea is definitely worth exploring.

**Comment by parkerl** [comment]
:heart: this! 

Names are hard.

```
Profile |> matching(attrs) |> Repo.all
Profile |> filter_for(attrs) |> Repo.all
Profile |> filter_by(attrs) |> Repo.all
Profile |> query_for(attrs) |> Repo.all
```

eh?

**Comment by gjaldon** [comment]
Right, we can't overload `where` with this. 

Of the options @parkerl suggests, `filter_by/2` sounds the most suitable to me.

**Comment by parkerl** [comment]
@gjaldon I like that one too but is it confusing that it won't be running the query and returning results but rather creating a query?

**Comment by parkerl** [comment]
Is anyone picking this one up? I'd love to take a stab.

**Comment by josevalim** [comment]
We haven't decided an API yet, so let's wait a bit :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by parkerl** [comment]
@josevalim ok I'll be patient. ;-) Was just wondering if some code might facilitate the conversation?

**Comment by paulcsmith** [comment]
It seems that you would be able to use `where` As a regular function. I am fairly certain that would work, especially since it's a different arity than the current `where/3` macro. Since this is doing what the where function is doing, but with different parameters, I think it makes sense to keep the function name. It's clear and simple IMO. 


```
def completed(query) do
  # a lot cleaner and super easy to understand what's going on
  query |> where(completed: true)
end
```

And of course it allows for the types of things @josevalim mentioned above

**Comment by josevalim** [comment]
@paulcsmith you are right, that's a great pick. The question is if we still need `get_by`?

**Comment by parkerl** [comment]
Ok I  like the idea but maybe I'm missing something. Without the binding how do we know what model to build the where clause against? 

Also, would this expand in keyword syntax?

**Comment by parkerl** [comment]
@josevalim speaking of `get_by` can I ask a potentially stupid question? Why does it throw an exception when multiple results return? If it just returned all the results (as I expected it to do the first time I used it) then we are done here by just taking two lines out of a case statement.

**Comment by josevalim** [comment]
@parkerl it will always apply to the model in "from". Btw, implementing this feature using `where` is actually quite complicated because it requires changes to the query builder but I think it is the way to go.

Regarding the second question: the goal of `get` functions is to return a single result, so we should not change its behaviour.

**Comment by parkerl** [comment]
@josevalim ok that makes sense. 

On the second point, I was expecting `get` and `get_by` to function like AR's `find` and find_by`. I need to stop doing that. ;-)

**Comment by parkerl** [comment]
@josevalim @paulcsmith I'd still be happy to take a stab at this unless you already have code in the works.

**Comment by josevalim** [comment]
I don't have anything in the works. :)

**Comment by parkerl** [comment]
Ok I will see what I can come up with.

**Comment by parkerl** [comment]
@josevalim looking for feedback on the wip above. Again, I must be missing something because this naive implementation seems to work. I spent some time digging around looking for more complexity. Can you expound on:

"Btw, implementing this feature using where is actually quite complicated because it requires changes to the query builder but I think it is the way to go."

I drove this out with integration tests in the repo cases but I know that they don't belong there. Where should this be tested? In `query_test.exs` I could test that the query returned has the correct `wheres`.

**Comment by josevalim** [comment]
@parkerl if we are adding it to where, I should look like this:

    query |> where([], [foo: 1]) # i don't care about the bindings
    query |> where([p, q], [foo: q.foo])

If we support the syntax above, then we can do:

    (from Post, where: [foo: 1])

Or:

    (from Post, ..., where: [foo: 1.foo])

But we should also support:

    where = [foo: 1.foo]
    (from Post, ..., where: ^where)

And all of those require changing the query builder API.

**Comment by paulcsmith** [comment]
@josevalim that is a cool idea! That'll be really nice. I assume that what @parkerl did should also supported? So you can leave the binding parameter out completely?

**Comment by josevalim** [comment]
@paulcsmith it should not be support. We generally don't support versions without binding to keep the API simple, specially since the keywords syntax is prefered.

**Comment by paulcsmith** [comment]
@josevalim I see your point, but I think that `query |> where([], [foo: 1])` reads very strangely. I think it would be weird to try to explain to someone why you still need to pass in an empty list if you don't care about the binding? Anyway, just a thought :) Even with the binding I will be quite happy to try this out in some of our apps!

**Comment by josevalim** [comment]
All macros need the binding, so at the moment you go into the macro syntax, you need to explain that each macro operation requires the binding. :)

**Comment by paulcsmith** [comment]
I'm confused, @parkerl wrote a version that seems to work without passing an empty list? I'm probably just misunderstanding though. I admit I don't know the internals of how queries work very well

**Comment by josevalim** [comment]
All I am saying is that all operations `where`, `order_by`, `select` today expect the binding so I don't see why we should have a special variation of `where` that does not. Doing so would be the exception and the one likely confusing.

**Comment by paulcsmith** [comment]
Ah I see what you're saying :) That makes sense. I thought you meant it wasn't possible. Thanks for the explanation!

One thing that *could* be done is to allow where, order_by, select and friends to also have an optional binding, but maybe that's a bit too crazy :)

**Comment by parkerl** [comment]
@josevalim here is my wip on this. However, I think I'm still not understanding your vision here. I ended up with this in Filter so that I could iterate to build multiple "wheres". I attempted to push this down in the builder but `escape` doesn't seem want to return multiple statement. Is that a part of what you see changing?

Another question, when you say this above

```
(from Post, ..., where: [foo: 1.foo])
```
are you saying where the binding "foo" has the value "1"? Or is it that the binding in position "1" has the value "foo"?

Thanks,

**Comment by josevalim** [comment]
@parkerl sorry, I have updated the code samples above. The `1` was a mistake.

Your WIP is a very good starting point! I would do the following changes next:

1. you don't really need the first binding. The first binding is always `{:&, [], [0]}` in the AST
2. instead of reducing on the query by calling build multiple times, you can just join the different fragments with and. Something like `Enum.reduce parts, &{:and, [], [&1, &2]}`
3. Move that code out of `build` and into `escape` (still in Filter)

Good work!

**Comment by parkerl** [comment]
Thanks for those updates. That makes it more clear. I will make those changes asap.

**Comment by parkerl** [comment]
@josevalim it had my back against the wall for a time but I have it working with your edits above. Care to take a look? What's next?

**Comment by paulcsmith** [comment]
Thanks for working on this @parkerl. I'm stoked to try this out. 

I've been thinking a lot about this and I really believe that the binding should be *truly* optional. If you don't want it, remove it completely. Trying to explain that you have an empty list there because you don't need a binding doesn't make sense to people. Maybe I'm explaining it wrong, but IMO it is not intuitive. 

To make this work well across the Query API, I think that making the binding optional for `order_by`, `limit`, `where`, and whatever other query functions are needed would make writing queries so much simpler.

To me this makes total sense and is really easy to explain to people, but maybe that's just me
`User |> where(admin: true) |> order_by(:name) |> offset(10) |> limit(10)`

I think it would be worth it to do this for all of the query functions and would be happy to help with a PR :)

**Comment by parkerl** [comment]
Thanks @paulcsmith. I will defer to @josevalim to respond to your comments.

**Comment by josevalim** [comment]
I am ok with dropping the bindings for where, having, offset and limit. @ericmj?

**Comment by parkerl** [comment]
@josevalim I might finally have a lock on this. Tests pass. Take a look?

**Comment by josevalim** [comment]
Looks good! Please send a PR when you are ready!

**Comment by parkerl** [comment]
@josevalim updated.

**Comment by josevalim** [comment]
Perfect, please send a PR! :)

**Comment by josevalim** [comment]
@parkerl, thank you! Are you ready for the next and final step? We also need to allow the following: 

```elixir
list_of_values = [title: "hello"]
from Post, where: ^list_of_values
```

The bad news is that we cannot re-use the code we just wrote, because the interpolation happens at runtime, and everything we did was compile time. The good news is that the runtime version should be simpler.

In order to implement this, we have roughly those steps:

1. on escape, we need to match on anything like `{^, _, [var]}` and delegate the work to runtime. Something like this:

```elixir
def escape(kind, {^, _, [var]}, _, _) do
  {quote(do: Ecto.Query.Builder.Filter.runtime!(unquote(kind), unquote(var))), %{}}
end
```

2. At runtime, you are now going to convert the keyword list to ands. The good news is that we no longer need to worry about escaping and what not. Everything is happening at runtime. Here is a sample input/output of the runtime! function called above:

```elixir
runtime!(:where, [title: "hello", id: 3])
#=> {:and, [],
   [{:==, [],
     [{{:., [], [{:&, [], [0]}, :title]}, [], []},
      %Ecto.Query.Tagged{tag: nil, type: {0, :title}, value: "hello"}]},
    {:==, [],
     [{{:., [], [{:&, [], [0]}, :id]}, [], []},
      %Ecto.Query.Tagged{tag: nil, type: {0, :id}, value: 3}]}]}
``` 

Notice each value is wrapped in `Ecto.Query.Tagged` and the type is the same we pass in your latest PR.

3. Write tests, change Repo.get_by to use `where: ^where` instead of the loop it uses today and we are ready to ship it!

We are almost there! Let me know if you have any questions!

**Comment by parkerl** [comment]
@josevalim great! Thanks for the detailed task list. I will dive in!

**Comment by parkerl** [comment]
@josevalim how's that look so far?

**Comment by josevalim** [comment]
> To make this work well across the Query API, I think that making the binding optional for order_by, limit, where, and whatever other query functions are needed would make writing queries so much simpler.

@paulcsmith could you please send a pull request for this?

**Comment by paulcsmith** [comment]
@josevalim Yeah I can do that. Is there any time limit on this? It might take a week or two before I have time. if that's ok I'm happy to work on it!

**Comment by josevalim** [comment]
@paulcsmith that would be completely fine. I will open up a new issue and ping you on it. :)

**Comment by josevalim** [comment]
Closing this in favor of the latest PR. :)

**Comment by wojtekmach** [comment]
I submitted a PR: https://github.com/elixir-ecto/ecto/pull/4576. :)
