### ISSUE TITLE
Interpolated parameters of a custom struct type cause UndefinedFunctionError

### ISSUE THREAD

**Issue by bitwalker** [elixir-lang/ecto#970]
I discovered this issue while troubleshooting https://github.com/bitwalker/timex_ecto/issues/8

Basically, given a model containing a field with a custom type (in this case `Timex.Ecto.DateTime`, a type defined in the `timex_ecto` library, which maps `Timex.DateTime` to Ecto's `:datetime` type), if you attempt to do a simple query with a `where` clause which contains an interpolated value of the mapped type (`Timex.DateTime` in this example), it will result in an UndefinedFunctionError for `Timex.DateTime.type/0`.

To reproduce, clone `git@github.com/bitwalker/timex_ecto_test`, make sure you edit `config.exs` appropriately, and run the following SQL against the database you will connect to:

```sql
CREATE TYPE datetimetz AS (
      dt timestamptz,
      tz varchar
);
CREATE TABLE users (
  id integer,
  name varchar,
  date_test date,
  time_test time without time zone,
  datetime_test timestamp with time zone,
  datetimetz_test datetimetz
);
```

Then perform the following steps:

- `iex -S mix` in project directory
- `EctoTest.seed` insert a test record
- `EctoTest.all` to verify everything is good to go
- `EctoTest.recent` to run the query which fails

I have been able to pinpoint the issue to [here](https://github.com/elixir-lang/ecto/blob/master/lib/ecto/query/planner.ex#L258) and [here](https://github.com/elixir-lang/ecto/blob/master/lib/ecto/type.ex#L230). The actual error is caused by the latter, and is where I believe the bug to be, but the former is the caller which is passing `Timex.DateTime` and `Timex.Ecto.DateTime` as values to `match?/2`. From what I can tell, the call to `match?/2` should succeed, return false, at which point `Ecto.Type.cast(Timex.Ecto.DateTime, %Timex.DateTime{})` would be called, and work as expected.

This bug is more general than just the `Timex.Ecto` use here, but it makes for an easy test case.

**Comment by bitwalker** [comment]
I can confirm that the following change to `Ecto.Type` fixes this (for this case anyway):

```elixir
def match?(schema_type, query_type) do
  if primitive?(schema_type) do
    do_match?(schema_type, query_type)
  else
    if {:type, 0} in schema_type.__info__(:functions) do
      do_match?(schema_type.type, query_type)
    else
      false
    end
  end
end
```

I haven't attempted to validate that this is even the correct way to handle it, but I can at least confirm that it behaves as expected with that change in place.

**Comment by bitwalker** [comment]
@josevalim @ericmj Do you want me to try and build a fix/PR for this? What are your thoughts on my analysis of the issue, is it correct? Is the solution I mentioned above going down the right path?

**Comment by josevalim** [comment]
The analysis is great, I am not sure about the solution yet. I need to discuss with @ericmj but we have both been busy.

The main issue is that we rely on the current logic to allow any date to be given to datetime_add. If you don't rely on that logic, which in your case you do not, they won t work for you, and we will need to find a way to fix that.

**Comment by bitwalker** [comment]
@josevalim No worries!

Yeah I would like `timex_ecto` to work with `datetime_add` (not that it's necessary, but there's really no reason it can't), and after some testing I see the issue. I'll poke around a bit to see what I can come up with, but any thoughts you may have on it as you think of them would come in handy ;)

**Comment by mspanc** [comment]
+1

**Comment by bitwalker** [comment]
@josevalim @ericmj Do you have a recommendation on how I should proceed in addressing this? I don't mind putting in the work for a PR, I just want to make sure I've got a clear goal in mind. My little patch fixes this, but I don't know what it breaks (if it breaks anything), and I'm not sure if it's the right fix.

**Comment by josevalim** [comment]
So the solution for this is to use protocols. Since I still need to check some stuff out, don't worry about it, I can take care of fixing this. I really appreciate the issue being brought up. This will certainly be part of Ecto v1.1!

**Comment by bitwalker** [comment]
Thanks José! If you find yourself needing a hand, just give me a shout!

**Comment by bitwalker** [comment]
@josevalim This is great thanks! I see you've got this slated for v1.1, just curious if you guys have a ballpark on when you think that might be released, just want to update my issue tracking this so people know when they might expect to see a fix. No rush :)

**Comment by josevalim** [comment]
I would like to release it at maximum next week, so it should be soon. :)
