### ISSUE TITLE
Ecto.Preloader.do_preload ignores internal stack trace leading to odd error msg

### ISSUE THREAD

**Issue by djm** [elixir-lang/ecto#975]
Hi,

Elixir: 1.0.4
Ecto: 1.0.2 (but the [relevant code](https://github.com/elixir-lang/ecto/blob/9445e106e0a3e1d9e3790b0949c38ea0ca02d7b5/lib/ecto/repo/preloader.ex#L48) is still in `master 9445e` as of now).

I'm raising this ticket as I encountered an error message which caused some confusion...

Running a query to Repo.all with a preload attached resulted in the following error:

```bash
[error] #PID<0.494.0> running TestBed.Endpoint terminated
Server: 127.0.0.1:4000 (http)
Request: GET /v1/directory/1/listings
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (ecto) lib/ecto/repo/preloader.ex:51: Ecto.Repo.Preloader.do_preload/4
        (ecto) lib/ecto/repo/preloader.ex:19: Ecto.Repo.Preloader.query/5
        (ecto) lib/ecto/repo/queryable.ex:99: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
        (test_bed) web/controllers/listings_controller.ex:9: TestBed.ListingsController.index/2
        (test_bed) web/controllers/listings_controller.ex:1: TestBed.ListingsController.phoenix_controller_pipeline/2
        (test_bed) lib/phoenix/router.ex:265: TestBed.Router.dispatch/2
        (test_bed) web/router.ex:1: TestBed.Router.do_call/2
```

This left me none the wiser as to what was up so I hunted down [the code in Ecto](https://github.com/elixir-lang/ecto/blob/9445e106e0a3e1d9e3790b0949c38ea0ca02d7b5/lib/ecto/repo/preloader.ex#L48) raising the error and commented out the rescue & re-raise lines and got this error instead:

```bash
[error] #PID<0.494.0> running TestBed.Endpoint terminated
Server: 127.0.0.1:4000 (http)
Request: GET /v1/directory/1/listings
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (stdlib) :ets.lookup(:tzdata_current_release, :release_version)
        lib/tzdata/release_reader.ex:41: Tzdata.ReleaseReader.current_release_from_table/0
        lib/tzdata/release_reader.ex:13: Tzdata.ReleaseReader.simple_lookup/1
        lib/tzdata/release_reader.ex:5: Tzdata.ReleaseReader.zone_list/0
        lib/tzdata/release_reader.ex:22: Tzdata.ReleaseReader.periods_for_zone_or_link/1
        lib/tzdata.ex:137: Tzdata.periods/1
        lib/tzdata.ex:216: Tzdata.periods_for_time/3
        lib/calendar/date_time.ex:391: Calendar.DateTime.from_erl_timezone_validity/4
```
As you can see, the error is in a different library completely and knowing that allows me to hunt it down (in the morning anyway) (*Edit: if you came across this error, it's fixed by placing `:calendar` in your `applications` list to start it when your app starts*).

I asked in IRC an ericmj said the reason for re-raising would be to shorten the stack trace, so I thought I'd start a discussion here as to whether that is beneficial when it ends up hiding an error like this. I also realise that the stack trace in the 2nd one does not read back to the developer's app code so...is there a way we can get the best of both worlds?

Thanks all!

Darian

**Comment by ericmj** [comment]
I think we should remove the reraise and recommend increasing the stacktrace limit if ecto truncates it.
