### ISSUE TITLE
Support non-public PostgreSQL schemas in model definition

### ISSUE THREAD

**Issue by avitex** [elixir-lang/ecto#978]
Referencing [the question](http://stackoverflow.com/questions/32717299) I posted on Stackoverflow, there is no direct support currently for non-public PostgreSQL schemas in the model definition.

I have a couple of ideas on how this could possibly be implemented, the first using an attribute, the second creating a second function with a 3rd parameter for selecting Postgres' schema (example below), though I think although this would look nicer, it would perhaps be a bit specific just to PostgreSQL.

    schema "nonpublicschema", "sometable" do
        field :somefield, :string
    end

You could even split the string at a fullstop, but this probably wouldn't be the best idea for the reason above, the extra overhead, and possibly even the fact someone *might* name their table in quotes *with* a fullstop :grinning:
Keep in mind, I haven't looked at the source, so my opinions are naive and only to give a headstart if needed. 

P.S. I would like to thank you guys for the effort you've put into elixir and it's libraries. Conditions that decide whether a language survives or not, seem to be if it has a presence of libraries, with documentation and a strong community, all check-boxes that seem to be ticked here. It is fun to learn, and highly productive. I can only hope I will be able to help more in the future.

**Comment by Tica2** [comment]
Do you check?
```elixir
schema "schema1.sometable" do
    field :somefield, :string
end
```

**Comment by avitex** [comment]
@Tica2 Thanks for the suggestion, but if you follow my question on Stackoverflow, that's exactly what I tried :smile:

**Comment by Tica2** [comment]
Message was:
> relation "nonpublicschema.sometable" does not exist

After some check problem is in Ecto **("schema1.tbl" vs "schema1"."tbl")**:



```bash
psql (9.4.0)
Type "help" for help.

hubbit_db_test=> create schema schema1;
CREATE SCHEMA
hubbit_db_test=> create table schema1.tbl (id integer not null, name varchar(20));
CREATE TABLE
hubbit_db_test=> insert into schema1.tbl values (1, 'a');
INSERT 0 1
hubbit_db_test=> select * from schema1.tbl;
 id | name
----+------
  1 | a
(1 row)   
```

> mix phoenix.gen.model Tbl tbl name:string
* creating priv/repo/migrations/20150923085804_create_tbl.exs
* creating web/models/tbl.ex
* creating test/models/tbl_test.exs

Remeber to update your repository by running migrations:

    $ mix ecto.migrate

Edit Tbl.ex insert schema1. and delete timestamps

```elixir
defmodule MyApp.Tbl do
  use MyApp.Web, :model

  schema "schema1.tbl" do
    field :name, :string
  end
end
```

```bash
iex -S mix
iex(1)> MyApp.Repo.get MyApp.Tbl, 1
12:27:21.788 [debug] SELECT s0."id", s0."name" FROM "schema1.tbl" AS s0 WHERE (s0."id" = $1) [1] ERROR query=153.6ms queue=4.5ms
** (Postgrex.Error) ERROR (undefined_table): relation "schema1.tbl" does not exist
```

Problem is on table name: "schema1.tbl" 
Corect is: schema1.tbl or "schema1"."tbl" 

This is good if schema will be supported with new field.

I think best way is to be on Query level and table to remain without attached schema.

**Comment by josevalim** [comment]
Thank you @avitex for opening the report an the nice words. We will support this either as:

```
schema "table", prefix: "nonpublicschema" do
```

Or:

```
schema {"nonpublicschema", "table"} do
```

It is mostly a API change because Ecto already supports those internally.

**Comment by Tica2** [comment]
Also Migrations need to support schema.

App.Repo.Migrations.CreateTbl do
  use Ecto.Migration

  def change do
    create table(:tbl) do
      add :name, :string
    end

  end
end

I am interested in good solution here to easy support 
Multitenancy https://en.wikipedia.org/wiki/Multitenancy
and
schema-sharding  https://en.wikipedia.org/wiki/Shard_%28database_architecture%29

**Comment by josevalim** [comment]
@Tica2 that's a good point about migrations.

**Comment by Tica2** [comment]
@josevalim 
Can I come with analyze about schema support in Ecto before start to implement this? (1 week)
In past I did java solution for Multitenancy with schema support:

client1.* schema tables    (database 1) (server 1)
client2.* schema tables    (database 1) (server 1)

clientX.* schema tables    (database X) (server 2)
clientY.* schema tables    (database X) (server 2)


and same java web app (war) working for more clients on same or diffrent domains.

I really want to have support for Multitenancy in Ecto by default.
I meen to have good implementation for schema in Ecto to implement easy Multitenancy 
 
 
This is also good selling point.

Thanks!

**Comment by josevalim** [comment]
Yes, please go ahead. There are some folks using Ecto in a multitenancy fashion in production. That's why queries and models already support the prefix option. To query a particular schema, you just need to run:

    query = from p in Post, ...
    set_schema(query, schema)

Where set_schema:

    def set_schema(query, schema) do
      %{query | prefix: schema}
    end

The only big question is migrations really. So ideas are welcome.

**Comment by Dania02525** [comment]
Jose, I've been fiddling with Ecto.Migrator to build my apartmentex library for multitenancy.  I'll probably borrow from migrator and migration, and schema_migration, and add a parameter to accept a prefix for the commands sent to execute.  I should have something working this week that could be cleaned up and supported by migrator directly.

**Comment by josevalim** [comment]
Great, let us know if you have any ideas about how to improve migrations.

**Comment by Dania02525** [comment]
Having now played with this a bit, I think the easiest approach will be allowing :prefix as an option in Ecto.Migrator, and passing it with the other options to Ecto.Runner agent.  The commands can then use the prefix if available.  

I'll need to change the arity for the schema migration functions as well, but I'm not sure how to add the prefix when creating the migration table with execute_ddl since its adapter specific.  Thoughts?

**Comment by Tica2** [comment]
In multitenancy environment schema is good to be on top level (migration parameter)

Example:
client1 use schema1 
client2 use schema2
...
app can automate tasks (unix bash/cron) to generate new schemas for new clients.

mix ecto.migrate -r Custom.Repo -schema schema1

**schema in migration**
If in migration we introduce schema passed as new parameter, list [: schema, : table] or
tuple {: schema, : table} (The final form is not so important)

What is **important** is to have replace schema option on ecto.migrate task:

```
# Replace named schema in migration
mix ecto.migrate -r Custom.RepoX -replace-schema public:schema1
```
or
```
# Use schema in migration where schema is not set in migration.exs
mix ecto.migrate -r Custom.RepoY -schema schema_123
```

## Example:

```elixir
defmodule TheApp.Migrations.TableCompanies do
  use Ecto.Migration
  @docs "Table companies"
  def up do
    create table({:public , :companies}) do
      add :name,                :string,  null: false, size: 120
      add :status,              :integer, null: false, default: 1
      add :country_id,          references(:countries), null: false
      timestamps
    end
  end
  def down do
    drop_if_exists table :companies
  end
end
```

```elixir
# For client1
mix ecto.migrate -r Custom.RepoX -replace-schema public:schema1
# For client2
mix ecto.migrate -r Custom.RepoX -replace-schema public:schema2
```

If we agree on specifications I can help with implementation.

Thanks,
@Tica2

**Comment by Dania02525** [comment]
@Tica
I'm approaching it thinking that tenant schema migrations should take place from the controller when a new tenant is created rather than as a mix task.  
Migrations can be run from within modules with Ecto.Migrator.run, and this also allows you to specify a source folder for them.

**Comment by Tica2** [comment]
Each client need full separate database.
Each client use same schema/objects (tables, indexes)

Second source folder do not help.
If we add schema parameter for migration, is fine, but in that moment I can run migration only against this schema.

Just see my point of view related to  multitenancy environment.

**Comment by josevalim** [comment]
Thank you @Dania02525. Instead of passing the schema for every command, I am wondering if it is easier to just change the schema in the connection. Your migration would look something like this:

```elixir
defmodule TheApp.Migrations.TableCompanies do
  use Ecto.Migration

  def up do
    put_prefix "foo" # This performs SET SCHEMA ...

    create table({:public , :companies}) do
      add :name,                :string,  null: false, size: 120
      add :status,              :integer, null: false, default: 1
      add :country_id,          references(:countries), null: false
      timestamps
    end
  end
end
```

We could also support it being given as a module attribute: `@prefix "foo"` so we don't need to change both `up` and `down` and also support the commands that @Tica2 mentioned. The question is: if we change the prefix/schema in the connection, is that enough? If so, it is much easier than changing all commands. :)

Thanks everyone!

**Comment by Dania02525** [comment]
@josevalim
That can also be useful, but I think we need some way to pass target prefix into the migrator function itself, since we can generate prefixes dynamically (schemas for postgres, databases for mysql).  Is there a way to dynamically define the schema when migration parses the model?

We'd still need a way to either create the schema (or database for mysql), but I've just been doing that with a raw query

**Comment by Dania02525** [comment]
Also, changing the schema on the connection affects our non prefixed repo calls too, right? I think I still want the default to be in public schema for non prefixed repo calls.

**Comment by Dania02525** [comment]
@Tika2
I'm sorry, I keep saying schema, but what I mean is prefix.  That ends up being a separate database for MySQL, or a separate schema in postgres.  The idea of having a separate folder is because you might not want to migrate the same tables as for your public schema.  

Example:, my tenants don't each need tenant tables, so I would keep that in the main migrations folder and not put it in my tenant_migrations folder.

**Comment by Tica2** [comment]
We agree to call `prefix` that mean:

prefix.table or prefix.object  (after dot)

* `schema` for postgresql
* `database` for mysql
* `user` for oracle
* `schema` for db2
* `user` for mssql (`schema` from MSSQL 2014)

By default `db_user` when is connected to `name_database` use default schema, also connection session can alter default schema. 

* `public` for postgresql
* `name_database` for mysql
* `db_user` for oracle
* `db_user` for db2
* `dbo` for mssql

To create schema is hard. Is database independent.

From this point of view is good that database setup and connection to set all settings 
and migration scripts to be prefix free.
   
In this case solutions is to put migrations in diffrent folders 
priv/repo/migrations/public
priv/repo/migrations/hr
priv/repo/migrations/webstore
 
This come with 3 Repo (Repo1, Repo2, Repo3) and :priv option
 
How we migrate now?
In config/env.exs 
We have all info to connect to database.
Where to alter schema?
```elixir
mix ecto.migrate -r Repo1 
mix ecto.migrate -r Repo2 
mix ecto.migrate -r Repo3
``` 
Still I need to run migration against more schemas.

```elixir
priv/repo/migrations/general       
priv/repo/migrations/meta_data
priv/repo/migrations/tenant_client

RepoGeneral
RepoMetaData
RepoTenantClient

mix ecto.migrate -r RepoGeneral
mix ecto.migrate -r RepoMetaData
mix ecto.migrate -r RepoTenantClient -schema cli0001
mix ecto.migrate -r RepoTenantClient -schema cli0002
mix ecto.migrate -r RepoTenantClient -schema cli0112
```
If we add prefix in migrations, that help to avoid 3 folders (just one), but we need  -replace-schema option
```elixir
mix ecto.migrate -replace-schema public:schema1
``` 
I think is best:
1) Do not introduce prefix in migration (simple by default)
2) Case with more repo and multitenancy is solved with more folders and more Repo.
3) `-schema cli0112` option for `mix ecto.migrate`

**Comment by Dania02525** [comment]
@Tica2 
I think we are talking about two different things.  In the current mix task, you have to pass it the repo and it pulls the migrations from one single folder.  However, if you use the Ecto.Migrator.run function directly, you can run migrations out of any other folder you want to, using the same repo.  

Once the function supports prefixing, the mix task could be modified so it could be passed a folder as the source of the migrations, and a prefix to migrate them to.  Something like:
```elixir
mix ecto.create --prefix "tenant_1"
mix ecto.migrate --source "priv/repo/tenant_migrations" --prefix "tenant_1"
```
if you left the prefix off, the above commands would target the default schema/database, so it won't be required to change existing migration code.  if you needed to run a migration against all your tenants, the best way to do that I think would be a mix run with a module that Enums each of the tenants and runs it.  Each migration is its own operation in the database- Are you looking for a single mix command to run the migrations against all the tenants?

**Comment by Tica2** [comment]
I meen `mix ecto.migrate`

Ecto.Migrator.run is runned by  `mix ecto.migrate`
> Are you looking for a single mix command to run the migrations against all the tenants?
No, separate mix ecto.migrate commands, with  `--prefix` option

Question remain: 
Do we alter prefix/schema on current connection session? and DDL is the same:
```sql
create table users (...)
```
Or we create objects with prefix (This is what you want, I think ...)
```sql
create table prefix.users (...)
``` 

We do not have `--source` for `mix ecto.migrate` 
We need to create.

Now location is rigid: 
https://github.com/elixir-lang/ecto/blob/master/lib/mix/ecto.ex#L89-L102

**Comment by josevalim** [comment]
> That can also be useful, but I think we need some way to pass target prefix into the migrator function itself, since we can generate prefixes dynamically (schemas for postgres, databases for mysql). Is there a way to dynamically define the schema when migration parses the model?

This is hard because we need to know the prefix before we run the migration, as we need to know if that particular migration was already executed for that particular prefix.

**Comment by Tica2** [comment]
Corect! To query ```prefix.schema_migrations``` table

**Comment by Dania02525** [comment]
@josevalim 
I pushed a commit to my Ecto fork with the prefix feature working.  here's how it works:
```elixir
Ecto.Migrator.run(Repo, 'priv/repo/tenant_migrations', :up, [all: true, prefix: "foo"]

Ecto.Migrator.run(Repo, 'priv/repo/tenant_migrations', :up, [all: true]
#defaults to public schema or main db depending on adapter

mix ecto.migrate --prefix "foo"
#migrates from folder priv/repo/migrations and targets prefix foo

mix ecto.migrate
#defaults to public schema or main db depending on adapter

```
This migrates the schema migrations table also to the specified prefix.  There seems to be some intermittent compiling problem in schema_migrations file- I'm getting an error about interpolation of the version in the query for down function. Please take a look at the diff:
https://github.com/elixir-lang/ecto/compare/master...Dania02525:master

**Comment by josevalim** [comment]
@Dania02525 that's great! I am wondering though if there is a way we can be less intrusive. Here is one idea but other suggestions are welcome: what if we introduce a `migrate` function to the adapter. We could call it here:

    https://github.com/elixir-lang/ecto/blob/master/lib/ecto/migrator.ex#L104

Something like:

    repo.__adapter__.migrate(opts, fun)

Then the adapter would check if there is a prefix in option and, if there is one, we change the schema while for the duration of the given function.

Another approach is to introduce two functions to the adapter: put_prefix and reset_prefix. The former we call before the migration, in the same are as that code, and the latter after.

Thoughts? :)

**Comment by Dania02525** [comment]
@josevalim

Agreed that the changes are pretty intrusive.  My only concern with changing the state of the adapter  is the case of a migration happening at the same time as some other process using the adapter.  

My use case for it is actually running the migration from my controller when a new tenant is created, which means that users could be using the adapter at the same time the migration is running. Would your solution above lock the db to prevent misrouted queries while the prefix was set?

**Comment by josevalim** [comment]
@Dania02525 if you set it inside a transaction, then any state we set in the transaction won't leave the transaction. We can also guarantee that the connection you check out to run a migration won't be used by anybody until the migration is done (this is a bit more complicated though and I can work on that once we get some initial version in). :)

**Comment by Dania02525** [comment]
@josevalim 
looking through this, I think i'll need to pass in the prefix here from opts:
https://github.com/Dania02525/ecto/blob/master/lib/ecto/adapters/sql.ex#L112

Then change the execute_ddl functions in connection to accept prefix parameter in addition to command.   It would be less intrusive, and the opts should only be for that particular transaction, correct?

**Comment by Dania02525** [comment]
are the execute_ddl functions called from anywhere else that will break if we change their arity?

**Comment by Tica2** [comment]
After some research I think is best to put explicit prefix when we migrate and query (at runtime)

What I find:
* Postgresql work nice with search_path and is workining transactional.
* MySql do not restore from transaction  
* MSSQL **DO NOT HAVE** a way to change schema on connection session.
  MSSQL provide ALTER USER, but that affect all database conection. 

## Postgresql 

```sql
db_dev=> SET search_path TO my_schema;
SET
db_dev=> SHOW search_path;
 search_path
-------------
 my_schema
(1 row)

db_dev=> begin;
BEGIN
db_dev=> SHOW search_path;
 search_path
-------------
 my_schema
(1 row)

db_dev=> SET search_path TO tr_schema;
SET
db_dev=> SHOW search_path;
 search_path
-------------
 tr_schema
(1 row)

db_dev=> ROLLBACK;
ROLLBACK
db_dev=> SHOW search_path;
 search_path
-------------
 my_schema
(1 row)
```
 
## MSQL

```sql
mysql> use a_db;
Database changed
mysql> SELECT DATABASE();
+------------+
| DATABASE() |
+------------+
| a_db       |
+------------+
1 row in set (0.00 sec)

mysql> BEGIN;
Query OK, 0 rows affected (0.00 sec)

mysql> use b_db;
Database changed
mysql> SELECT DATABASE();
+------------+
| DATABASE() |
+------------+
| b_db       |
+------------+
1 row in set (0.00 sec)

mysql> ROLLBACK;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT DATABASE();
+------------+
| DATABASE() |
+------------+
| b_db       |
+------------+
1 row in set (0.00 sec)

mysql>
```

**Comment by Tica2** [comment]
Solution is near @Dania02525 code.

**Comment by Tica2** [comment]
@josevalim What problem we have if all migrations DDL work with explicit prefix:

```sql
create table prefix.user (...)
```
and at runtime 
```sql
select * from prefix.user
```

**Comment by Dania02525** [comment]
@Tica2
That's a good point about MySQL, anything we store in the transaction state will go away as soon as the first CREATE TABLE is issued, if I understand correctly.

We could store the prefix in the migration runner agent, and get the prefix from it within the adapter as commands are flushed.  The bigger issue though is that the schema migration table is created outside the runner and outside the transaction, meaning wed still have to pass the prefix to its execute_ddl call.  

Perhaps the best solution is to give an optional prefix param to execute_ddl in the adapter to make it like the other functions

**Comment by Tica2** [comment]
Is not viable to query current prefix and to put back after transaction. 
Any DDL or SQL query it will clearly efective set.

What about to add :prefix in %Ecto.Migration.Table
https://github.com/elixir-lang/ecto/blob/master/lib/ecto/migration.ex#L115-L121

```elixir
  defmodule Table do
    @moduledoc """
    Defines a table struct used in migrations.
    """
    defstruct prefix: nil, name: nil, primary_key: true, engine: nil, options: nil
    @type t :: %__MODULE__{prefix: String.t, name: atom, primary_key: boolean, engine: atom}
  end
```  	
Same for %Ecto.Migration.Index and Reference

**Comment by josevalim** [comment]
Alright, you are both correct. :) I like the prefix idea on the Index, Reference and Table structs. What about you @Dania02525?

**Comment by Dania02525** [comment]
@josevalim 
I also like that idea, since we can then quite easily allow for setting the default prefix from within models.  Are we still keeping the ability to set prefix in opts for Ecto,Migrator.run? If we are, I think we still need something like this:
```elixir
def apply_prefix(commands) do  
    prefix =  Agent.get(__MODULE__, & &1.prefix)
    commands
    |> Enum.map(fn({action, table, opts})->
      case prefix do
        nil -> {action, table,  opts}
        string -> {action, %{table | prefix: [string, table.name]}, opts}
      end
    end)
  end
```
in Ecto.Migration.Runner to put the optional prefix in the commands.  That, the changes in schema migration, and some minor changes in the mysql and postgres connection I think would work.  @josevalim if you have any suggestions for improving my version of Ecto.Migration.SchemaMigration, I'd be happy to implement :-)

**Comment by josevalim** [comment]
@Dania02525 let's not support it for now. My concern is that if we support some "magical" prefix option, people will expect all migration commands to automatically apply to that prefix. So let's figure out a way to make it work locally (per table/index), which is what the prefix option is about, then we will figure out how to make it work for the whole migration.

Also, do we need a prefix for references? I think we can probably skip it. I am assuming many databases won't support cross-database references.

**Comment by Dania02525** [comment]
@josevalim 

I couldn't figure out a good way to target dropping indexes inside of schemas in postgres, so I left index prefix support off for now until we can finalize something for that.  You can add schemas like this to migrations:
```elixir
def up do
    create table(:widgets, prefix: :tenant_999) do
      add :name, :string

      timestamps
    end

  end
```
and they will be handled normally by MySql and postgres.  I also wrote a couple of tests and documented the feature.  Here's the diff, let me know what you think :-)
https://github.com/elixir-lang/ecto/compare/master...Dania02525:master

**Comment by josevalim** [comment]
@Dania02525 that patch is *perfect*, thank you! Is there anything we could do to help with the prefix support for indexes? Once we have indexes working, we are ready to get this first part merged!

**Comment by Dania02525** [comment]
Great!  For Index support, I just really need a postgres ninja to guide me on how to delete an index within a schema.  MySQL is easy since its just residing in the database.  Creating the prefixes is also easy since they are schema.table specific.

**Comment by Tica2** [comment]
> Also, do we need a prefix for references? I think we can probably skip it. I am assuming many databases won't support cross-database references.

For postgresql make sens, is in same database.
But is not about cross-database references!

If I have simple reference:
table pr1.comments (post_id reference to pr1.posts.id)
 
Is not about prefix table where reference is defined, is about prefix of table that refer.
 
Good work @Dania02525 !

**Comment by Tica2** [comment]
Delete index in postgresql schema with prefix:
```sql
create schema a;
create table a.test (id integer, name varchar(10));
create index test_name_index ON a.test (name);
DROP index a.test_name_index;
```

**Comment by parkerl** [comment]
This is going to be fantastic! :+1: Thanks for all your hard work on this @Tica2 and @Dania02525

**Comment by Tica2** [comment]
@parkerl It is just the beginning :)

**Comment by Tica2** [comment]
Now FK reference can be created only in table context.
We can simplify and accept FKs in same prefix, 
that mean reference/fk in next example need to refer `tenant_999.persons` table

```elixir
def up do
    create table(:car, prefix: :tenant_999) do
        add :name, :string
        add :person_id, references(:persons)
      timestamps
    end
end
```

If we accept this idea, in this case,  %Ecto.Migration.Reference do not need prefix,
but is require to use table.prefix.

This is good because we avoid to have cross-database references (see mysql)

This came from idea to have full migrations objects(tenant schema) in same prefix.

If `tenant_999.car` table has `tenant_999` prefix 
then `tenant_999.car.person_id` **is require** to refer `tenant_999.persons` table.

What do you think?

**Comment by Dania02525** [comment]
@Tica2
That makes sense to me, I don't think I've ever needed to have cross schema references before, but I suppose someone might need them, like if a tenant.order_items table referenced a products table in the main schema.  

What if we made it default to the same prefix as the table, but allow it to be overridden with and option in references()? We could just put in the docs that referencing a table outside current db is not supported

**Comment by Tica2** [comment]
> but I suppose someone might need them, like if a tenant.order_items table referenced a products table in the main schema. 
In this case we need also prefix for  %Ecto.Migration.Reference

**But** also in case we introduce  prefix in  %Ecto.Migration.Reference and this prefix is not set (is nil)
we still need to refer table in same prefix. Above logic remain.

We can add  `prefix` in  `%Ecto.Migration.Reference` in step 2.

**Comment by Dania02525** [comment]
@josevalim @Tica2 
I pushed the commit for prefixing the indexes from the migrations like this:
```elixir
create index(:weather, [:city], prefix: :north_america)
```
Created tests for it and documented it.  I have not added prefix to references yet, as they will require a closer look and some testing with the sql.

Ideally, the index and references should inherit the prefix of the table by default, but I couldn't see an elegant way of doing that in just glancing at the code.  I'm tempted to use Process.get(:last_command), but that assumes the relevant table command was the last run.  We may just need to hold off on prefix inheritance for indexes and references until the magical prefix option happens, but I'm open to ideas!

**Comment by Dania02525** [comment]
Added reference prefixes and documented use of prefixes for MySQL requiring same prefix for references as specified in table.  This should close the original issue created by @avitex , maybe we can open a new issue for defaulting a whole migration to a particular prefix for those who might need this feature.  Thanks all!

**Comment by Dania02525** [comment]
Is anyone tackling the main issue by @avitex ? I see that he wanted the model to be prefix qualified.  now that we've got migration support for it, maybe we can take a look at model support for it?

**Comment by josevalim** [comment]
Yes, we can split it in two issues: 1. prefixes in models and 2. prefixes in the migration runner :)

**Comment by hamiltop** [comment]
What's the current plan for creating prefixes (be it schemas or dbs)? Unless I'm missing something, it looks like there's no way for to create schemas/databases other than via `storage_up` which only works for the main database.

**Comment by josevalim** [comment]
We likely won't support an automated way of creating schemas because they change drastically between each storage. For example, for mysql, it is a new storage, so you don't need to have a previous storage running. For Postgres, it is the opposite, you need a storage and create a schema inside it.

**Comment by josevalim** [comment]
Thoughts?

**Comment by hamiltop** [comment]
I'd say it just splits into those two camps though. Either completely
independent storage (MySQL, SQLite) or a shared storage (PostgreSQL,
MongoDB). Though the two behaviors are indeed different, we should be able
to handle those two cases.

**Comment by josevalim** [comment]
That's a very good point. We could likely improve on this area but I can't personally focus on it. If you would like to write a proposal, please go ahead. A couple things:

1. we have typically called schema a "prefix". we can't call it schema because we already have Ecto.Schema too
2. we already added the ability to migrate a specific prefix but we haven't exposed it through the command line. Although, when we discussed the feature, we thought about `mix ecto.migrate --prefix foo`
3. I am not sure how we should expose this functionality. It could be an option to storage_up and storage_down callbacks, for example `mix ecto.create --prefix foo` but it could also be its own task. we would need to investigate which one makes more sense

**Comment by Dania02525** [comment]
@josevalim this would be really nice to expose at the command line.  As soon as I get some time in going to be writing a mix task to run a pool of migrations from a mix task in the apartments library, and ill see how something like this might look.

**Comment by josevalim** [comment]
Perfect, thank you. :)

**Comment by isaacsanders** [comment]
What is the status of this topic?

**Comment by josevalim** [comment]
It is supported on Ecto 2.0 under the prefix module attribute: https://github.com/elixir-lang/ecto/blob/master/lib/ecto/schema.ex#L38
