### ISSUE TITLE
Issue creating DB with ecto.create

### ISSUE THREAD

**Issue by DeodorantMan** [elixir-lang/ecto#980]
I've been getting this issue on a fresh Digital Ocean box with Ecto 1.1 and Phoenix 1.0 running default `mix phoenix.new`.
When I put in a bad password into the Postgres connection, and run `mix ecto.create`, it will compile everything, then tell me that the password is wrong. 
That is fine, however the second time I run the `mix ecto.create` after changing password, it hangs up on that last line. `Consolidated protocols written to _build/prod/consolidated`

```
...
Compiled lib/phoenix_ecto/html.ex
Generated phoenix_ecto app
==> prodapp
Compiled lib/prodapp.ex
Compiled lib/prodapp/repo.ex
Compiled web/channels/user_socket.ex
Compiled web/web.ex
Compiled web/router.ex
Compiled web/controllers/page_controller.ex
Compiled web/views/error_view.ex
Compiled lib/prodapp/endpoint.ex
Compiled web/views/page_view.ex
Compiled web/views/layout_view.ex
Generated prodapp app
Consolidated Phoenix.Param
Consolidated Phoenix.HTML.FormData
Consolidated Phoenix.HTML.Safe
Consolidated Plug.Exception
Consolidated Ecto.Queryable
Consolidated Poison.Decoder
Consolidated Poison.Encoder
Consolidated String.Chars
Consolidated Access
Consolidated Range.Iterator
Consolidated Enumerable
Consolidated Collectable
Consolidated Inspect
Consolidated List.Chars
Consolidated protocols written to _build/prod/consolidated
``` 

and I don't know how to proceed from there. Are there compiled files that need to be removed before running the create command again?

I was able to get `mix ecto.create` to run fine and create DB only when I got the password right the first time. Sometimes I'm not so luck.

**Comment by josevalim** [comment]
Maybe `psql` is stalling waiting for a password? I will investigate and see if we can reproduce it.

**Comment by cazrin** [comment]
I had the same problem just today. I didn't set a password when creating the user in postgres, so I assumed it was blank. `ecto.create` would just hang and not provide any warnings etc. when I configured it to use an empty password.

My solution was to change the password for the postgres user using `ALTER USER myuser with password 'your-pass';` and then set that as the password in the config.

**Comment by josevalim** [comment]
Thank you , we will solve this when we solve #854.

**Comment by ra9hu** [comment]
I ran into this issue which I could resolve by altering the role with first login & then createdb permissions. Happy Coding!
