### ISSUE TITLE
Repo.preload is not recursive if one of the intermediary models is already loaded

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/ecto#986]
I'm not exactly sure, if this is a bug, or it was designed like this and I want too much.
But with nested preloads, if one of the models is already loaded, it's child models won't be preloaded.

Example:
I have `Post` that has many `Comments`, and each comment belongs to a `User`.
If I first load post with only comments and without users using:
```
posts = 
  from(p in Post, preload: :comments)
  |> Repo.all
```
And later try to load the authors for the comments:
```
posts = Repo.preload(posts, comments: :authors)
```
The authors won't be loaded.

**Comment by josevalim** [comment]
Yup, bug. :)

**Comment by olivermt** [comment]
Setting ecto sub model manually blocks preload path for that sub model as well.

I am guessing this is maybe what you are saying in: #1212 ?
