### ISSUE TITLE
Repo isn't properly resolved from config when using namespaces

### ISSUE THREAD

**Issue by solatis** [elixir-lang/ecto#993]
As far as I understand, I am supposed to provide the Repo endpoint in the config like this:

```elixir
config :myapp_model, Myapp.Model.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "ecto_simple",
  username: "postgres",
  password: "postgres"
```

Note my use of a *namespace* `Myapp.Model` rather than the default `MyappModel`. When using any of the mix ecto tasks, however, a different mechanism is used to determine the Repo module, as seen in https://github.com/elixir-lang/ecto/blob/master/lib/mix/ecto.ex#L19 

```elixir
    case Application.get_env(app, :app_namespace, app) do
      ^app -> app |> to_string |> Mix.Utils.camelize
      mod  -> mod |> inspect
    end |> Module.concat(Repo)
```
 
In other words, the *application id* is resolved, camlized and the submodule "Repo" is added to this -- a completely different mechanism.

This should be changed towards something that correctly grabs the Repo module from the provided config file parameter rather than automatically constructing it from the application id (and making mistakes in the process), something like this:

```elixir
  def parse_repo([]) do
    app = Mix.Project.config |> Keyword.fetch!(:app)

    case Application.get_all_env(app) do
      [{repo, _}] -> repo
    end
  end
```

Any comments / thoughts on this ? I assume this is a legacy issue ?

**Comment by josevalim** [comment]
We could support a new option called `:app_repo` that does exactly what you propose. Please send a  PR. :)

**Comment by solatis** [comment]
The problem I think that's going on is that the configuration format currently is a bit malformed. Consider this configuration:

```elixir
config :myapp_model, Myapp.Model.Repo,
  adapter: Ecto.Adapters.Postgres,
  app_namespace: Myapp.Model,
  database: "ecto_simple",
  username: "postgres",
  password: "postgres"
```

When the code then does a look up for the `:app_namespace` key in the configuration (which, in this case, we would set to Myapp.Model), this fails because *the application environment is incorrectly parsed*. Allow me to illustrate using a small debug statement in the parse_repo function:

```elixir
  def parse_repo([]) do
    app = Mix.Project.config |> Keyword.fetch!(:app)
    
    all_env = Application.get_all_env(app)
    IO.puts "all_env = #{inspect all_env}"
```
Which outputs:

```
all_env = [{Myapp.Model.Repo, [app_namespace: Myapp.Model, adapter: Ecto.Adapters.Postgres, database: "ecto_simple", username: "postgres", password: "postgres"]}, {:included_applications, []}]
```

As you can see, all the application's environment is a part of the `Myapp.Model.Repo` key, not the application!

This doesn't raise any issues in other code, such as repo/supervisor.eex, because the code that is being used is this:

```elixir
  def parse_config(repo, opts) do
    otp_app = Keyword.fetch!(opts, :otp_app)
    config  = Application.get_env(otp_app, repo, [])
```

`repo` equals __MODULE__ here, which is the Repo itself -- you can see that the config is retrieved from the Application's env by the repo key itself.

The way to work around this issue right now is adjusting the config file to this:

```elixir
config :myapp_model 
  [{:app_namespace, MyApp.Model},
   {MyApp.Model.Repo, [adapter: Ecto.Adapters.Postgres,
                       database: "ecto_simple",
                       username: "postgres",
                       password: "postgres"]}]
```

Which feels like a kludge, and it definitely appears that this is a bug. What would be the best approach to solve it, so I can make a PR?

**Comment by josevalim** [comment]
I am afraid you are confusing the configuration keys and files. We only need the app_namespace for generators and Mix tasks, it is not used anywhere else. So you should support this:

    config :myapp_model, app_repo: MyApp.Model.Repo

And change the tasks to first look for app_repo and then app_namespace as today. You don't need to change anything else.

**Comment by solatis** [comment]
Sorry I think I misunderstood. Will do a patch today, once we have that let's discuss from there.

**Comment by solatis** [comment]
Ok, I have to admit, I am confused. Consider this configuration as you provide it right now:

```elixir
config :myapp_model, Myapp.Model.Repo,
  adapter: Ecto.Adapters.Postgres,
  app_namespace: Myapp.Model,
  database: "ecto_simple",
  username: "postgres",
  password: "postgres"
```

This is transformed/parsed as:

```elixir
config :servergloom_model, 
  [{Myapp.Model.Repo, [adapter: Ecto.Adapters.Postgres,
                             database: "ecto_simple",
                             username: "postgres",
                             password: "postgres"]}]
```

and the repo's __MODULE__ (in this case, Myapp.Model.Repo) is used to look up the values in the configuration.

This appears somewhat weird to me -- what is the design choice behind this? So you can have multiple repo's with multiple configurations?

**Comment by josevalim** [comment]
> This appears somewhat weird to me -- what is the design choice behind this? So you can have multiple repo's with multiple configurations?

Yes.

**Comment by solatis** [comment]
Ok so the patch listed above does the minimal thing to allow configuring the default repo. As you can see, there are now three different if/then/else conditions that allow specifying a repo:

 * app_repo;
 * app_namespace;
 * derive it from application name.

While I'm at it, I could refactor this a bit to make it more generic, or leave it as it is.

**Comment by josevalim** [comment]
Thank you @solatis! I am closing this in favor of the PR but your patch is perfect, we just need to apply it to master instead of v1.0. :)
