### ISSUE TITLE
Confusing error when using :datetime, :date, :time and :uuid as field types in schema definition

### ISSUE THREAD

**Issue by paulcsmith** [elixir-lang/ecto#994]
I think adding a helpful error when the type is `:date` or `:datetime`, `:uuid`, `:time` would be nice. Something like:

`(ArgumentError) invalid or unknown type :datetime for field :created_at. Maybe you meant to set the type to Ecto.DateTime?`

Here was my problem:

```elixir
defmodule MyApp.Repo.Migrations.CreateArticles do
  use Ecto.Migration

  def change do
    create table(:articles) do
      add :published_at, :datetime
    end
  end
end
```

and a model

```elixir
defmodule MyApp.Article do
  use Ecto.Model

  schema "articles" do
    # Figured this would also be `:datetime` like in the migration
    field :published_at, :datetime
  end
end
```

It seemed to me that `:datetime` would just work since that's what I used in the migration. This threw an error: `(ArgumentError) invalid or unknown type :datetime for field :published_at`. I was pretty confused by this so I tried `date_time`. Eventually I realized I needed `Ecto.DateTime`. This isn't a big deal, but I believe it can be improved. 

I can work on a PR for this if it's something you want

**Comment by josevalim** [comment]
:+1: we can detect and fail early for those four types.

**Comment by josevalim** [comment]
We can fail when the schema is defined even.
