### ISSUE TITLE
Potential race condition using poolboy when running a non-transaction query after previous client exits mid-transaction

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/ecto#999]
Theoretically it is possible for the following to occur:

* Client A starts transaction
* Client A exits
* Poolboy gets Client A `:DOWN` and gives worker to Client B
* Client B calls worker to checkout connection with a `:run` mode.
* Client B sends requests to connection and gets a result
* Worker gets Client A `:DOWN` and terminates connection rolling back Client B's request

We handle this potential race condition when Client B checks out with a `:transaction`. We should get concuerror out to verify before fixing this.

**Comment by josevalim** [comment]
You are completely right. :( in any case, should we move to sbroker as
default?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by fishcakez** [comment]
It is nice to default to poolboy because it is simpler and better known but we can default to either.

**Comment by josevalim** [comment]
In any case, do you have any idea how we can fix this?

**Comment by fishcakez** [comment]
Yes the fix is only a couple of lines (see alive? check in :transaction checkout), need to think about a test though..
